"""
SFDR Principal Adverse Impact (PAI) Calculation Engine
=======================================================

Structured calculation engine for the EU Sustainable Finance Disclosure
Regulation (SFDR) — Regulation (EU) 2019/2088, as supplemented by the
Delegated Regulation (EU) 2022/1288 (SFDR RTS).

Principal Adverse Impacts (PAI) modelled:
- Table 1 (Annex I RTS): 18 mandatory PAI indicators
    -- PAI 1-14:  Investments in investee companies
    -- PAI 15-16: Investments in sovereigns and supranationals
    -- PAI 17-18: Investments in real estate assets
- Table 2 (Annex I RTS): Additional climate/environment-related indicators
- Table 3 (Annex I RTS): Additional social/governance-related indicators

Entity classification:
- Article 6:  No sustainability claims (vanilla disclosure)
- Article 8:  Products promoting environmental/social characteristics
              ("light green")
- Article 9:  Products with sustainable investment as objective
              ("dark green")

Disclosure requirements:
- Article 4(1)(a): Entity-level PAI statement (FMPs with >500 employees)
- Article 4(3)/(4): Product-level PAI consideration
- Annex I RTS:      Prescribed template for PAI statement
- Reference period:  1 January to 31 December, published by 30 June

Cross-framework linkage:
- CSRD ESRS E1-E5, S1-S2, G1 — data feeds PAI calculations
- EU Taxonomy (Art 9 alignment, DNSH criteria)
- GHG Protocol — Scope 1/2/3 methodology for PAI 1-3
- PCAF — financed emissions attribution for PAI 1-3
- UNGC / OECD Guidelines — PAI 10-11
"""
from __future__ import annotations

import math
from dataclasses import dataclass, field
from datetime import datetime
from typing import Optional


# ---------------------------------------------------------------------------
# Reference Data Constants — Mandatory PAI Indicators (Table 1 Annex I)
# ---------------------------------------------------------------------------

PAI_INDICATORS = {
    # ── Investments in investee companies ──────────────────────────────────
    "pai_1": {
        "id": "pai_1",
        "name": "GHG emissions",
        "metric": "Scope 1, Scope 2, Scope 3, and Total GHG emissions",
        "unit": "tCO2e",
        "description": (
            "Scope 1 GHG emissions generated by investee companies; "
            "Scope 2 GHG emissions generated by investee companies; "
            "Scope 3 GHG emissions generated by investee companies; "
            "Total GHG emissions generated by investee companies"
        ),
        "category": "environmental",
        "asset_class": "company",
        "mandatory": True,
        "calculation_methodology": (
            "Sum of (attribution factor x investee Scope 1/2/3 emissions). "
            "Attribution factor = current value of investment / enterprise "
            "value including cash (EVIC) of the investee company."
        ),
    },
    "pai_2": {
        "id": "pai_2",
        "name": "Carbon footprint",
        "metric": "Carbon footprint of the portfolio",
        "unit": "tCO2e / EUR million invested",
        "description": (
            "Carbon footprint: total GHG emissions of investee companies "
            "per million EUR invested, calculated as the sum of attributed "
            "emissions divided by the current value of all investments."
        ),
        "category": "environmental",
        "asset_class": "company",
        "mandatory": True,
        "calculation_methodology": (
            "Sum of (current value of investment_i / EVIC_i x emissions_i) "
            "divided by current value of all investments (EUR millions)."
        ),
    },
    "pai_3": {
        "id": "pai_3",
        "name": "GHG intensity of investee companies",
        "metric": "Weighted average GHG intensity",
        "unit": "tCO2e / EUR million revenue",
        "description": (
            "GHG intensity of investee companies: weighted average of "
            "investee GHG intensity measured as tCO2e per EUR million "
            "revenue."
        ),
        "category": "environmental",
        "asset_class": "company",
        "mandatory": True,
        "calculation_methodology": (
            "Sum over all investments of (current value of investment_i / "
            "current value of all investments) x (investee emissions_i / "
            "investee revenue_i)."
        ),
    },
    "pai_4": {
        "id": "pai_4",
        "name": "Exposure to companies active in the fossil fuel sector",
        "metric": "Share of investments in fossil fuel companies",
        "unit": "%",
        "description": (
            "Share of investments in companies active in the fossil fuel "
            "sector. Includes companies that derive any revenues from "
            "exploration, mining, extraction, production, processing, "
            "storage, refining, or distribution of fossil fuels."
        ),
        "category": "environmental",
        "asset_class": "company",
        "mandatory": True,
        "calculation_methodology": (
            "Sum of current value of investments in fossil fuel companies / "
            "current value of all investments x 100."
        ),
    },
    "pai_5": {
        "id": "pai_5",
        "name": "Share of non-renewable energy consumption and production",
        "metric": "Non-renewable energy share",
        "unit": "%",
        "description": (
            "Share of non-renewable energy consumption and non-renewable "
            "energy production of investee companies from non-renewable "
            "energy sources compared to renewable energy sources, expressed "
            "as a percentage of total energy sources."
        ),
        "category": "environmental",
        "asset_class": "company",
        "mandatory": True,
        "calculation_methodology": (
            "Weighted average of investee non-renewable energy share: "
            "sum of (weight_i x non_renewable_energy_i / total_energy_i)."
        ),
    },
    "pai_6": {
        "id": "pai_6",
        "name": "Energy consumption intensity per high impact climate sector",
        "metric": "Energy consumption in GWh per million EUR revenue per NACE sector",
        "unit": "GWh / EUR million revenue",
        "description": (
            "Energy consumption intensity per high impact climate sector "
            "(NACE Sections A, B, C, D, E, F, G, H, L). Weighted average "
            "of energy consumption per revenue for each sector."
        ),
        "category": "environmental",
        "asset_class": "company",
        "mandatory": True,
        "calculation_methodology": (
            "For each NACE sector: sum of (weight_i x energy_gwh_i / "
            "revenue_eur_m_i) for investees in that sector. Report per "
            "NACE section A through L."
        ),
    },
    "pai_7": {
        "id": "pai_7",
        "name": "Activities negatively affecting biodiversity-sensitive areas",
        "metric": "Share of investments in investee companies with activities in/near biodiversity-sensitive areas",
        "unit": "%",
        "description": (
            "Share of investments in investee companies with sites/operations "
            "located in or near biodiversity-sensitive areas where activities "
            "negatively affect those areas."
        ),
        "category": "environmental",
        "asset_class": "company",
        "mandatory": True,
        "calculation_methodology": (
            "Sum of current value of investments in companies negatively "
            "affecting biodiversity-sensitive areas / current value of all "
            "investments x 100."
        ),
    },
    "pai_8": {
        "id": "pai_8",
        "name": "Emissions to water",
        "metric": "Tonnes of emissions to water per million EUR invested",
        "unit": "tonnes / EUR million invested",
        "description": (
            "Tonnes of emissions to water generated by investee companies "
            "per million EUR invested, weighted average."
        ),
        "category": "environmental",
        "asset_class": "company",
        "mandatory": True,
        "calculation_methodology": (
            "Sum of (current value of investment_i / EVIC_i x "
            "water_emissions_tonnes_i) / current value of all investments "
            "(EUR millions)."
        ),
    },
    "pai_9": {
        "id": "pai_9",
        "name": "Hazardous waste and radioactive waste ratio",
        "metric": "Tonnes of hazardous and radioactive waste per million EUR invested",
        "unit": "tonnes / EUR million invested",
        "description": (
            "Tonnes of hazardous waste and radioactive waste generated by "
            "investee companies per million EUR invested, weighted average."
        ),
        "category": "environmental",
        "asset_class": "company",
        "mandatory": True,
        "calculation_methodology": (
            "Sum of (current value of investment_i / EVIC_i x "
            "hazardous_waste_tonnes_i) / current value of all investments "
            "(EUR millions)."
        ),
    },
    "pai_10": {
        "id": "pai_10",
        "name": "Violations of UN Global Compact principles and OECD Guidelines",
        "metric": "Share of investments in companies involved in violations",
        "unit": "%",
        "description": (
            "Share of investments in investee companies that have been "
            "involved in violations of the UNGC principles or OECD "
            "Guidelines for Multinational Enterprises."
        ),
        "category": "social",
        "asset_class": "company",
        "mandatory": True,
        "calculation_methodology": (
            "Sum of current value of investments in companies with "
            "UNGC/OECD violations / current value of all investments x 100."
        ),
    },
    "pai_11": {
        "id": "pai_11",
        "name": "Lack of processes and compliance mechanisms to monitor UNGC and OECD compliance",
        "metric": "Share of investments in companies without UNGC/OECD compliance policies",
        "unit": "%",
        "description": (
            "Share of investments in investee companies without policies to "
            "monitor compliance with the UNGC principles or OECD Guidelines "
            "or grievance/complaints handling mechanisms."
        ),
        "category": "social",
        "asset_class": "company",
        "mandatory": True,
        "calculation_methodology": (
            "Sum of current value of investments in companies without "
            "UNGC/OECD monitoring mechanisms / current value of all "
            "investments x 100."
        ),
    },
    "pai_12": {
        "id": "pai_12",
        "name": "Unadjusted gender pay gap",
        "metric": "Average unadjusted gender pay gap of investee companies",
        "unit": "%",
        "description": (
            "Average unadjusted gender pay gap of investee companies, "
            "defined as the difference between average gross hourly "
            "earnings of male and female employees as a percentage of "
            "male gross earnings."
        ),
        "category": "social",
        "asset_class": "company",
        "mandatory": True,
        "calculation_methodology": (
            "Weighted average of investee gender pay gaps: sum of "
            "(weight_i x gender_pay_gap_pct_i)."
        ),
    },
    "pai_13": {
        "id": "pai_13",
        "name": "Board gender diversity",
        "metric": "Average ratio of female to male board members",
        "unit": "%",
        "description": (
            "Average ratio of female to male board members in investee "
            "companies, expressed as a percentage of all board members."
        ),
        "category": "social",
        "asset_class": "company",
        "mandatory": True,
        "calculation_methodology": (
            "Weighted average of investee female board ratios: sum of "
            "(weight_i x female_board_members_i / total_board_members_i)."
        ),
    },
    "pai_14": {
        "id": "pai_14",
        "name": "Exposure to controversial weapons",
        "metric": "Share of investments in companies involved in controversial weapons",
        "unit": "%",
        "description": (
            "Share of investments in investee companies involved in the "
            "manufacture or selling of controversial weapons "
            "(anti-personnel mines, cluster munitions, chemical weapons, "
            "biological weapons)."
        ),
        "category": "social",
        "asset_class": "company",
        "mandatory": True,
        "calculation_methodology": (
            "Sum of current value of investments in controversial weapons "
            "companies / current value of all investments x 100."
        ),
    },
    # ── Investments in sovereigns and supranationals ───────────────────────
    "pai_15": {
        "id": "pai_15",
        "name": "GHG intensity of investee countries",
        "metric": "GHG intensity of investee countries",
        "unit": "tCO2e / EUR million GDP",
        "description": (
            "GHG intensity of investee countries, measured as the "
            "country's total GHG emissions divided by GDP."
        ),
        "category": "environmental",
        "asset_class": "sovereign",
        "mandatory": True,
        "calculation_methodology": (
            "Weighted average of sovereign GHG intensity: sum of "
            "(weight_i x country_ghg_emissions_i / country_gdp_eur_m_i)."
        ),
    },
    "pai_16": {
        "id": "pai_16",
        "name": "Investee countries subject to social violations",
        "metric": "Number of investee countries subject to social violations",
        "unit": "count / share %",
        "description": (
            "Number of investee countries subject to social violations "
            "(as referred to in international treaties and conventions, "
            "UN principles, and, where applicable, national law) and "
            "the share of sovereign exposure to such countries."
        ),
        "category": "social",
        "asset_class": "sovereign",
        "mandatory": True,
        "calculation_methodology": (
            "Count of unique investee countries with social violations; "
            "share = sum of exposure to violated countries / total "
            "sovereign exposure x 100."
        ),
    },
    # ── Investments in real estate assets ──────────────────────────────────
    "pai_17": {
        "id": "pai_17",
        "name": "Exposure to fossil fuels through real estate assets",
        "metric": "Share of investments in real estate assets involved in extraction, storage, transport, or manufacture of fossil fuels",
        "unit": "%",
        "description": (
            "Share of investments in real estate assets involved in the "
            "extraction, storage, transport, or manufacture of fossil fuels."
        ),
        "category": "environmental",
        "asset_class": "real_estate",
        "mandatory": True,
        "calculation_methodology": (
            "Sum of current value of real estate investments involved with "
            "fossil fuels / current value of all real estate investments "
            "x 100."
        ),
    },
    "pai_18": {
        "id": "pai_18",
        "name": "Exposure to energy-inefficient real estate assets",
        "metric": "Share of investments in energy-inefficient real estate assets",
        "unit": "%",
        "description": (
            "Share of investments in energy-inefficient real estate assets. "
            "Energy-inefficient means EPC rating below C (i.e. D, E, F, G) "
            "or built before 31 December 2020 without at least EPC C or "
            "top 15% of national building stock by primary energy demand."
        ),
        "category": "environmental",
        "asset_class": "real_estate",
        "mandatory": True,
        "calculation_methodology": (
            "Sum of current value of energy-inefficient real estate assets "
            "/ current value of all real estate investments x 100. "
            "Energy-inefficient: EPC below C or pre-2021 without top 15% "
            "energy performance."
        ),
    },
}

# ---------------------------------------------------------------------------
# Additional PAI Indicators (Tables 2 and 3 Annex I)
# ---------------------------------------------------------------------------

ADDITIONAL_PAI_INDICATORS = {
    # ── Table 2: Additional environmental indicators ──────────────────────
    "add_env_1": {
        "id": "add_env_1", "table": 2,
        "name": "Emissions of inorganic pollutants",
        "metric": "Tonnes of inorganic pollutant equivalents per million EUR invested",
        "unit": "tonnes / EUR million invested",
        "category": "environmental", "sub_category": "emissions",
    },
    "add_env_2": {
        "id": "add_env_2", "table": 2,
        "name": "Emissions of air pollutants",
        "metric": "Tonnes of air pollutant equivalents per million EUR invested",
        "unit": "tonnes / EUR million invested",
        "category": "environmental", "sub_category": "emissions",
    },
    "add_env_3": {
        "id": "add_env_3", "table": 2,
        "name": "Emissions of ozone depletion substances",
        "metric": "Tonnes of ODS equivalents per million EUR invested",
        "unit": "tonnes / EUR million invested",
        "category": "environmental", "sub_category": "emissions",
    },
    "add_env_4": {
        "id": "add_env_4", "table": 2,
        "name": "Investments in companies without carbon emission reduction initiatives",
        "metric": "Share of investments in companies without carbon reduction initiatives targeting Paris alignment",
        "unit": "%",
        "category": "environmental", "sub_category": "climate",
    },
    "add_env_5": {
        "id": "add_env_5", "table": 2,
        "name": "Breakdown of energy consumption by type of non-renewable source",
        "metric": "Share of energy from non-renewable sources broken down by source",
        "unit": "%",
        "category": "environmental", "sub_category": "energy",
    },
    "add_env_6": {
        "id": "add_env_6", "table": 2,
        "name": "Water usage and recycling",
        "metric": "Average amount of water consumed and recycled by investee companies (m3) per million EUR revenue",
        "unit": "m3 / EUR million revenue",
        "category": "environmental", "sub_category": "water",
    },
    "add_env_7": {
        "id": "add_env_7", "table": 2,
        "name": "Investments in companies without water management policies",
        "metric": "Share of investments in companies without water management policies",
        "unit": "%",
        "category": "environmental", "sub_category": "water",
    },
    "add_env_8": {
        "id": "add_env_8", "table": 2,
        "name": "Exposure to areas of high water stress",
        "metric": "Share of investments in companies with sites in high water stress areas without adequate water management",
        "unit": "%",
        "category": "environmental", "sub_category": "water",
    },
    "add_env_9": {
        "id": "add_env_9", "table": 2,
        "name": "Investments in companies producing chemicals",
        "metric": "Share of investments in companies whose activities fall under Division 20.2 of Annex I to REACH",
        "unit": "%",
        "category": "environmental", "sub_category": "waste",
    },
    "add_env_10": {
        "id": "add_env_10", "table": 2,
        "name": "Land degradation, desertification, soil sealing",
        "metric": "Share of investments in companies causing or contributing to land degradation",
        "unit": "%",
        "category": "environmental", "sub_category": "biodiversity",
    },
    "add_env_11": {
        "id": "add_env_11", "table": 2,
        "name": "Investments in companies without sustainable land/agriculture practices",
        "metric": "Share of investments in companies without sustainable land use policies",
        "unit": "%",
        "category": "environmental", "sub_category": "biodiversity",
    },
    "add_env_12": {
        "id": "add_env_12", "table": 2,
        "name": "Investments in companies without sustainable ocean/sea practices",
        "metric": "Share of investments in companies without sustainable ocean practices",
        "unit": "%",
        "category": "environmental", "sub_category": "biodiversity",
    },
    "add_env_13": {
        "id": "add_env_13", "table": 2,
        "name": "Non-recycled waste ratio",
        "metric": "Tonnes of non-recycled waste per million EUR invested",
        "unit": "tonnes / EUR million invested",
        "category": "environmental", "sub_category": "waste",
    },
    "add_env_14": {
        "id": "add_env_14", "table": 2,
        "name": "Natural species and protected areas",
        "metric": "Share of investments negatively affecting threatened species",
        "unit": "%",
        "category": "environmental", "sub_category": "biodiversity",
    },
    "add_env_15": {
        "id": "add_env_15", "table": 2,
        "name": "Deforestation",
        "metric": "Share of investments in companies linked to deforestation",
        "unit": "%",
        "category": "environmental", "sub_category": "biodiversity",
    },
    # Additional sovereign/RE environmental
    "add_env_re_1": {
        "id": "add_env_re_1", "table": 2,
        "name": "GHG emissions of real estate assets",
        "metric": "Scope 1 and 2 GHG emissions from real estate assets",
        "unit": "tCO2e",
        "category": "environmental", "sub_category": "real_estate",
    },
    "add_env_re_2": {
        "id": "add_env_re_2", "table": 2,
        "name": "Energy consumption intensity of real estate assets",
        "metric": "Energy consumption per square metre of real estate assets",
        "unit": "kWh/m2",
        "category": "environmental", "sub_category": "real_estate",
    },
    "add_env_re_3": {
        "id": "add_env_re_3", "table": 2,
        "name": "Waste generation in real estate assets",
        "metric": "Tonnes of waste generated by real estate assets per million EUR invested",
        "unit": "tonnes / EUR million",
        "category": "environmental", "sub_category": "real_estate",
    },
    "add_env_re_4": {
        "id": "add_env_re_4", "table": 2,
        "name": "Raw material consumption for new construction and renovation",
        "metric": "Share of raw materials used for new construction and renovation",
        "unit": "%",
        "category": "environmental", "sub_category": "real_estate",
    },
    "add_env_re_5": {
        "id": "add_env_re_5", "table": 2,
        "name": "Land artificialisation of real estate assets",
        "metric": "Share of non-vegetated surface area (new construction/renovation)",
        "unit": "%",
        "category": "environmental", "sub_category": "real_estate",
    },
    # ── Table 3: Additional social indicators ─────────────────────────────
    "add_soc_1": {
        "id": "add_soc_1", "table": 3,
        "name": "Investments in companies without workplace accident prevention",
        "metric": "Share of investments in companies without workplace accident prevention policies",
        "unit": "%",
        "category": "social", "sub_category": "human_rights",
    },
    "add_soc_2": {
        "id": "add_soc_2", "table": 3,
        "name": "Rate of accidents",
        "metric": "Rate of workplace accidents in investee companies per million hours worked",
        "unit": "per million hours",
        "category": "social", "sub_category": "human_rights",
    },
    "add_soc_3": {
        "id": "add_soc_3", "table": 3,
        "name": "Number of days lost to injuries, accidents, fatalities, illness",
        "metric": "Weighted average of days lost per investee company",
        "unit": "days",
        "category": "social", "sub_category": "human_rights",
    },
    "add_soc_4": {
        "id": "add_soc_4", "table": 3,
        "name": "Lack of a supplier code of conduct",
        "metric": "Share of investments in companies without supplier codes of conduct",
        "unit": "%",
        "category": "social", "sub_category": "human_rights",
    },
    "add_soc_5": {
        "id": "add_soc_5", "table": 3,
        "name": "Lack of grievance/complaints handling mechanism",
        "metric": "Share of investments in companies without grievance mechanism",
        "unit": "%",
        "category": "social", "sub_category": "human_rights",
    },
    "add_soc_6": {
        "id": "add_soc_6", "table": 3,
        "name": "Insufficient whistleblower protection",
        "metric": "Share of investments in companies without whistleblower protections",
        "unit": "%",
        "category": "social", "sub_category": "human_rights",
    },
    "add_soc_7": {
        "id": "add_soc_7", "table": 3,
        "name": "Incidents of discrimination",
        "metric": "Weighted average number of discrimination incidents per investee company",
        "unit": "count",
        "category": "social", "sub_category": "human_rights",
    },
    "add_soc_8": {
        "id": "add_soc_8", "table": 3,
        "name": "Excessive CEO pay ratio",
        "metric": "Average ratio of CEO total compensation to median employee compensation",
        "unit": "ratio",
        "category": "social", "sub_category": "governance",
    },
    "add_soc_9": {
        "id": "add_soc_9", "table": 3,
        "name": "Lack of human rights policy",
        "metric": "Share of investments in companies without a human rights policy",
        "unit": "%",
        "category": "social", "sub_category": "human_rights",
    },
    "add_soc_10": {
        "id": "add_soc_10", "table": 3,
        "name": "Lack of due diligence",
        "metric": "Share of investments in companies without due diligence processes on human rights issues",
        "unit": "%",
        "category": "social", "sub_category": "human_rights",
    },
    "add_soc_11": {
        "id": "add_soc_11", "table": 3,
        "name": "Lack of anti-corruption and anti-bribery policies",
        "metric": "Share of investments in companies without anti-corruption/bribery policies",
        "unit": "%",
        "category": "social", "sub_category": "anti_corruption",
    },
    "add_soc_12": {
        "id": "add_soc_12", "table": 3,
        "name": "Cases of insufficient action against bribery and corruption",
        "metric": "Share of investments in companies with deficiencies in enforcement of anti-corruption measures",
        "unit": "%",
        "category": "social", "sub_category": "anti_corruption",
    },
    "add_soc_13": {
        "id": "add_soc_13", "table": 3,
        "name": "Number of convictions and amount of fines for violation of anti-corruption and anti-bribery laws",
        "metric": "Weighted average of fines EUR per investee company",
        "unit": "EUR",
        "category": "social", "sub_category": "anti_corruption",
    },
    "add_soc_sov_1": {
        "id": "add_soc_sov_1", "table": 3,
        "name": "Average income inequality score (sovereign)",
        "metric": "Income distribution inequality measured by the Palma ratio or GINI coefficient",
        "unit": "score",
        "category": "social", "sub_category": "sovereign",
    },
    "add_soc_sov_2": {
        "id": "add_soc_sov_2", "table": 3,
        "name": "Average freedom of expression score (sovereign)",
        "metric": "Press freedom / civil liberties index score of investee countries",
        "unit": "score",
        "category": "social", "sub_category": "sovereign",
    },
    "add_soc_sov_3": {
        "id": "add_soc_sov_3", "table": 3,
        "name": "Average human rights performance (sovereign)",
        "metric": "Human rights performance score of investee countries",
        "unit": "score",
        "category": "social", "sub_category": "sovereign",
    },
    "add_soc_sov_4": {
        "id": "add_soc_sov_4", "table": 3,
        "name": "Average rule of law score (sovereign)",
        "metric": "World Bank Governance Indicators rule of law score",
        "unit": "score",
        "category": "social", "sub_category": "sovereign",
    },
}

# ---------------------------------------------------------------------------
# PAI Calculation Methods
# ---------------------------------------------------------------------------

PAI_CALCULATION_METHODS = {
    "pai_1": {
        "formula": "attributed_emissions_i = (investment_value_i / evic_i) x scope_k_emissions_i; total = SUM(attributed_i)",
        "required_data_fields": [
            "investment_value_eur", "evic_eur", "scope_1_tco2e",
            "scope_2_tco2e", "scope_3_tco2e",
        ],
        "aggregation_method": "sum",
        "data_quality_requirements": "Scope 1/2 must be reported or estimated; Scope 3 may use PCAF estimation if no reported data.",
    },
    "pai_2": {
        "formula": "carbon_footprint = SUM((investment_value_i / evic_i) x total_emissions_i) / total_portfolio_value_eur_m",
        "required_data_fields": [
            "investment_value_eur", "evic_eur", "total_ghg_tco2e",
            "total_portfolio_value_eur",
        ],
        "aggregation_method": "ratio",
        "data_quality_requirements": "GHG data sourced from investee reports or PCAF-compliant estimates.",
    },
    "pai_3": {
        "formula": "ghg_intensity = SUM(weight_i x (investee_emissions_i / investee_revenue_eur_m_i))",
        "required_data_fields": [
            "investment_value_eur", "total_portfolio_value_eur",
            "total_ghg_tco2e", "revenue_eur",
        ],
        "aggregation_method": "weighted_average",
        "data_quality_requirements": "Revenue data from audited financials. GHG data from company reports or estimates.",
    },
    "pai_4": {
        "formula": "exposure_pct = SUM(investment_value_i for fossil_fuel companies) / total_portfolio_value x 100",
        "required_data_fields": [
            "investment_value_eur", "total_portfolio_value_eur",
            "is_fossil_fuel_company",
        ],
        "aggregation_method": "exposure_share",
        "data_quality_requirements": "Fossil fuel classification using NACE codes or revenue breakdown.",
    },
    "pai_5": {
        "formula": "nre_share = SUM(weight_i x non_renewable_energy_i / total_energy_i) x 100",
        "required_data_fields": [
            "investment_value_eur", "total_portfolio_value_eur",
            "non_renewable_energy_gwh", "total_energy_gwh",
        ],
        "aggregation_method": "weighted_average",
        "data_quality_requirements": "Energy data from CDP, annual reports, or estimated from sector averages.",
    },
    "pai_6": {
        "formula": "per NACE sector: intensity = SUM(weight_i x energy_gwh_i / revenue_eur_m_i)",
        "required_data_fields": [
            "investment_value_eur", "total_portfolio_value_eur",
            "energy_gwh", "revenue_eur", "nace_section",
        ],
        "aggregation_method": "weighted_average",
        "data_quality_requirements": "NACE classification required. Energy data from company reports or CDP.",
    },
    "pai_7": {
        "formula": "share_pct = SUM(investment_value_i for affected companies) / total_portfolio_value x 100",
        "required_data_fields": [
            "investment_value_eur", "total_portfolio_value_eur",
            "affects_biodiversity_sensitive_area",
        ],
        "aggregation_method": "exposure_share",
        "data_quality_requirements": "Biodiversity assessment using IBAT, Natura 2000, or equivalent screening.",
    },
    "pai_8": {
        "formula": "emissions_water = SUM((investment_value_i / evic_i) x water_emissions_tonnes_i) / total_value_eur_m",
        "required_data_fields": [
            "investment_value_eur", "evic_eur",
            "water_emissions_tonnes", "total_portfolio_value_eur",
        ],
        "aggregation_method": "ratio",
        "data_quality_requirements": "Water emissions from E-PRTR, CDP Water, or company sustainability reports.",
    },
    "pai_9": {
        "formula": "waste_ratio = SUM((investment_value_i / evic_i) x hazardous_waste_tonnes_i) / total_value_eur_m",
        "required_data_fields": [
            "investment_value_eur", "evic_eur",
            "hazardous_waste_tonnes", "total_portfolio_value_eur",
        ],
        "aggregation_method": "ratio",
        "data_quality_requirements": "Waste data from company reports, GRI 306 disclosures, or E-PRTR.",
    },
    "pai_10": {
        "formula": "share_pct = SUM(investment_value_i for violating companies) / total_portfolio_value x 100",
        "required_data_fields": [
            "investment_value_eur", "total_portfolio_value_eur",
            "has_ungc_oecd_violation",
        ],
        "aggregation_method": "exposure_share",
        "data_quality_requirements": "Violation screening from UNGC participant database, OECD NCP complaints, third-party ESG providers.",
    },
    "pai_11": {
        "formula": "share_pct = SUM(investment_value_i for non-compliant companies) / total_portfolio_value x 100",
        "required_data_fields": [
            "investment_value_eur", "total_portfolio_value_eur",
            "has_ungc_oecd_policy",
        ],
        "aggregation_method": "exposure_share",
        "data_quality_requirements": "Policy assessment from company disclosures or ESG data providers.",
    },
    "pai_12": {
        "formula": "avg_gap = SUM(weight_i x gender_pay_gap_pct_i)",
        "required_data_fields": [
            "investment_value_eur", "total_portfolio_value_eur",
            "gender_pay_gap_pct",
        ],
        "aggregation_method": "weighted_average",
        "data_quality_requirements": "Gender pay gap from company HR disclosures or mandatory national filings.",
    },
    "pai_13": {
        "formula": "avg_diversity = SUM(weight_i x female_board_pct_i)",
        "required_data_fields": [
            "investment_value_eur", "total_portfolio_value_eur",
            "female_board_members", "total_board_members",
        ],
        "aggregation_method": "weighted_average",
        "data_quality_requirements": "Board composition from annual reports or governance databases.",
    },
    "pai_14": {
        "formula": "share_pct = SUM(investment_value_i for controversial weapons companies) / total_portfolio_value x 100",
        "required_data_fields": [
            "investment_value_eur", "total_portfolio_value_eur",
            "involved_in_controversial_weapons",
        ],
        "aggregation_method": "exposure_share",
        "data_quality_requirements": "Controversial weapons screening from third-party providers (MSCI, ISS, Sustainalytics).",
    },
    "pai_15": {
        "formula": "ghg_intensity_sov = SUM(weight_i x country_ghg_tco2e_i / country_gdp_eur_m_i)",
        "required_data_fields": [
            "investment_value_eur", "total_sovereign_value_eur",
            "country_code", "country_ghg_tco2e", "country_gdp_eur_m",
        ],
        "aggregation_method": "weighted_average",
        "data_quality_requirements": "GHG from UNFCCC national inventories; GDP from World Bank/IMF.",
    },
    "pai_16": {
        "formula": "count = distinct countries with violations; share_pct = exposure_to_violated / total_sovereign x 100",
        "required_data_fields": [
            "investment_value_eur", "total_sovereign_value_eur",
            "country_code", "has_social_violation",
        ],
        "aggregation_method": "exposure_share",
        "data_quality_requirements": "Social violations from UN treaty body reports, OHCHR, or Freedom House.",
    },
    "pai_17": {
        "formula": "share_pct = SUM(value of RE assets involved with fossil fuels) / total_re_value x 100",
        "required_data_fields": [
            "asset_value_eur", "total_re_value_eur",
            "involved_with_fossil_fuels",
        ],
        "aggregation_method": "exposure_share",
        "data_quality_requirements": "Asset-level fossil fuel involvement from property records and tenant screening.",
    },
    "pai_18": {
        "formula": "share_pct = SUM(value of energy-inefficient RE assets) / total_re_value x 100",
        "required_data_fields": [
            "asset_value_eur", "total_re_value_eur",
            "epc_rating", "build_year",
        ],
        "aggregation_method": "exposure_share",
        "data_quality_requirements": "EPC rating from national EPC registries; build year from property records.",
    },
}

# ---------------------------------------------------------------------------
# SFDR Entity Classification (Art 6 / Art 8 / Art 9)
# ---------------------------------------------------------------------------

SFDR_ENTITY_CLASSIFICATION = {
    "article_6": {
        "label": "Article 6 — No sustainability claims",
        "description": (
            "Financial products that do not promote environmental or social "
            "characteristics and do not have sustainable investment as an "
            "objective. Must disclose how sustainability risks are integrated "
            "into investment decisions and the likely impact on returns."
        ),
        "disclosure_requirements": [
            "Pre-contractual: integration of sustainability risks (Art 6(1))",
            "Website: sustainability risk policy (if applicable)",
            "Periodic: no PAI statement required (but recommended)",
        ],
        "pai_statement_required": False,
        "taxonomy_alignment_required": False,
    },
    "article_8": {
        "label": "Article 8 — Promotes E/S characteristics (light green)",
        "description": (
            "Financial products that promote environmental or social "
            "characteristics, provided the companies invested in follow "
            "good governance practices. May include a proportion of "
            "sustainable investments."
        ),
        "disclosure_requirements": [
            "Pre-contractual: Annex II template (E/S characteristics, strategy, proportion)",
            "Website: Article 10 summary (methodology, data sources, limitations)",
            "Periodic: Annex IV template (extent to which E/S characteristics met)",
            "PAI statement at entity level (if > 500 employees or opt-in)",
        ],
        "pai_statement_required": True,
        "taxonomy_alignment_required": False,
        "minimum_sustainable_pct": 0.0,
    },
    "article_9": {
        "label": "Article 9 — Sustainable investment objective (dark green)",
        "description": (
            "Financial products that have sustainable investment as their "
            "objective. Must demonstrate that investments contribute to an "
            "environmental or social objective and do no significant harm "
            "(DNSH) to any other objective, and investees follow good "
            "governance practices."
        ),
        "disclosure_requirements": [
            "Pre-contractual: Annex III template (sustainable objective, DNSH, good governance)",
            "Website: Article 10 summary (sustainability objective, strategy, DNSH approach)",
            "Periodic: Annex V template (achievement of sustainable objective, DNSH)",
            "PAI statement mandatory at entity and product level",
            "DNSH assessment per PAI indicator required",
        ],
        "pai_statement_required": True,
        "taxonomy_alignment_required": True,
        "minimum_sustainable_pct": 100.0,
    },
}

# ---------------------------------------------------------------------------
# DNSH Taxonomy Objectives
# ---------------------------------------------------------------------------

_TAXONOMY_OBJECTIVES = [
    "climate_change_mitigation",
    "climate_change_adaptation",
    "sustainable_use_water",
    "transition_circular_economy",
    "pollution_prevention",
    "biodiversity_ecosystems",
]

# Mapping PAI indicators to taxonomy objectives for DNSH assessment
_PAI_DNSH_MAP = {
    "climate_change_mitigation": ["pai_1", "pai_2", "pai_3", "pai_4", "pai_5", "pai_6"],
    "climate_change_adaptation": ["pai_1", "pai_2", "pai_3"],
    "sustainable_use_water": ["pai_8"],
    "transition_circular_economy": ["pai_9"],
    "pollution_prevention": ["pai_8", "pai_9"],
    "biodiversity_ecosystems": ["pai_7"],
}

# ---------------------------------------------------------------------------
# Sector Benchmarks (illustrative average PAI values)
# ---------------------------------------------------------------------------

_SECTOR_BENCHMARKS = {
    "financials": {
        "pai_1_total_tco2e_per_m": 28.5,
        "pai_2_carbon_footprint": 35.2,
        "pai_3_ghg_intensity": 42.1,
        "pai_4_fossil_fuel_pct": 5.8,
        "pai_13_female_board_pct": 34.2,
        "pai_14_controversial_weapons_pct": 0.1,
    },
    "energy": {
        "pai_1_total_tco2e_per_m": 312.0,
        "pai_2_carbon_footprint": 428.5,
        "pai_3_ghg_intensity": 580.0,
        "pai_4_fossil_fuel_pct": 62.5,
        "pai_13_female_board_pct": 22.1,
        "pai_14_controversial_weapons_pct": 0.0,
    },
    "industrials": {
        "pai_1_total_tco2e_per_m": 145.0,
        "pai_2_carbon_footprint": 178.3,
        "pai_3_ghg_intensity": 210.0,
        "pai_4_fossil_fuel_pct": 12.4,
        "pai_13_female_board_pct": 28.7,
        "pai_14_controversial_weapons_pct": 1.2,
    },
    "technology": {
        "pai_1_total_tco2e_per_m": 12.3,
        "pai_2_carbon_footprint": 15.8,
        "pai_3_ghg_intensity": 18.5,
        "pai_4_fossil_fuel_pct": 0.5,
        "pai_13_female_board_pct": 30.5,
        "pai_14_controversial_weapons_pct": 0.0,
    },
    "utilities": {
        "pai_1_total_tco2e_per_m": 520.0,
        "pai_2_carbon_footprint": 610.0,
        "pai_3_ghg_intensity": 740.0,
        "pai_4_fossil_fuel_pct": 48.0,
        "pai_13_female_board_pct": 26.3,
        "pai_14_controversial_weapons_pct": 0.0,
    },
    "real_estate": {
        "pai_1_total_tco2e_per_m": 55.0,
        "pai_2_carbon_footprint": 68.0,
        "pai_3_ghg_intensity": 82.0,
        "pai_4_fossil_fuel_pct": 2.1,
        "pai_13_female_board_pct": 31.0,
        "pai_17_fossil_fuel_re_pct": 3.5,
        "pai_18_energy_inefficient_re_pct": 28.0,
    },
    "healthcare": {
        "pai_1_total_tco2e_per_m": 22.0,
        "pai_2_carbon_footprint": 30.0,
        "pai_3_ghg_intensity": 38.0,
        "pai_4_fossil_fuel_pct": 1.0,
        "pai_13_female_board_pct": 32.5,
        "pai_14_controversial_weapons_pct": 0.0,
    },
    "consumer_staples": {
        "pai_1_total_tco2e_per_m": 65.0,
        "pai_2_carbon_footprint": 80.0,
        "pai_3_ghg_intensity": 95.0,
        "pai_4_fossil_fuel_pct": 3.2,
        "pai_13_female_board_pct": 35.0,
        "pai_14_controversial_weapons_pct": 0.0,
    },
}

# ---------------------------------------------------------------------------
# RTS Disclosure Template Sections
# ---------------------------------------------------------------------------

_DISCLOSURE_TEMPLATE_SECTIONS = [
    {
        "section": "summary",
        "title": "Summary",
        "description": "Overview of PAI consideration and entity classification.",
    },
    {
        "section": "pai_description",
        "title": "Description of principal adverse impacts on sustainability factors",
        "description": "Narrative description of how PAIs are identified, prioritised, and addressed.",
    },
    {
        "section": "pai_table",
        "title": "Statement on principal adverse impacts (Table 1)",
        "description": "All 18 mandatory PAI indicators with values, explanations, and actions taken.",
    },
    {
        "section": "additional_indicators",
        "title": "Additional PAI indicators (Tables 2 and 3)",
        "description": "At least one additional environmental and one additional social indicator.",
    },
    {
        "section": "engagement_policies",
        "title": "Description of policies to identify and prioritise PAIs",
        "description": "Engagement policies, voting, escalation mechanisms.",
    },
    {
        "section": "international_standards",
        "title": "Adherence to international standards",
        "description": "Reference to UNGC, OECD, Paris Agreement, other international standards.",
    },
    {
        "section": "historical_comparison",
        "title": "Historical comparison",
        "description": "Comparison with previous reference periods (required from second reporting period).",
    },
]

# ---------------------------------------------------------------------------
# Cross-Framework Mapping
# ---------------------------------------------------------------------------

_CROSS_FRAMEWORK_MAP = [
    {"pai": "PAI 1-3 (GHG)", "csrd_esrs": "ESRS E1-6 (GHG emissions)", "eu_taxonomy": "Climate mitigation TSC", "ghg_protocol": "Scope 1/2/3"},
    {"pai": "PAI 4 (Fossil fuels)", "csrd_esrs": "ESRS E1 SBM-3", "eu_taxonomy": "Art 12(1)(f) exclusion", "ghg_protocol": "N/A"},
    {"pai": "PAI 5-6 (Energy)", "csrd_esrs": "ESRS E1-5 (Energy)", "eu_taxonomy": "Climate mitigation DNSH", "ghg_protocol": "N/A"},
    {"pai": "PAI 7 (Biodiversity)", "csrd_esrs": "ESRS E4 (Biodiversity)", "eu_taxonomy": "Biodiversity DNSH", "ghg_protocol": "N/A"},
    {"pai": "PAI 8 (Water)", "csrd_esrs": "ESRS E3 (Water)", "eu_taxonomy": "Water DNSH", "ghg_protocol": "N/A"},
    {"pai": "PAI 9 (Waste)", "csrd_esrs": "ESRS E5 (Circular economy)", "eu_taxonomy": "Circular economy DNSH", "ghg_protocol": "N/A"},
    {"pai": "PAI 10-11 (UNGC/OECD)", "csrd_esrs": "ESRS S1/S2, G1", "eu_taxonomy": "Minimum safeguards Art 18", "ghg_protocol": "N/A"},
    {"pai": "PAI 12-13 (Gender)", "csrd_esrs": "ESRS S1-9 / S1-16", "eu_taxonomy": "Minimum safeguards", "ghg_protocol": "N/A"},
    {"pai": "PAI 14 (Weapons)", "csrd_esrs": "ESRS G1-4", "eu_taxonomy": "Minimum safeguards Art 18", "ghg_protocol": "N/A"},
    {"pai": "PAI 15 (Sovereign GHG)", "csrd_esrs": "N/A (sovereign)", "eu_taxonomy": "N/A", "ghg_protocol": "National inventories"},
    {"pai": "PAI 17-18 (Real estate)", "csrd_esrs": "ESRS E1 (property)", "eu_taxonomy": "Buildings TSC", "ghg_protocol": "Scope 1/2"},
]


# ---------------------------------------------------------------------------
# Result Dataclasses
# ---------------------------------------------------------------------------

@dataclass
class PAICalculationResult:
    """Result of a single PAI indicator calculation."""
    indicator_id: str
    indicator_name: str
    value: float
    unit: str
    category: str
    asset_class: str
    data_quality_score: float = 0.0
    coverage_ratio: float = 0.0
    holdings_covered: int = 0
    holdings_total: int = 0
    estimation_method: str = ""
    notes: list = field(default_factory=list)


@dataclass
class PAIStatementResult:
    """Full PAI statement for Article 4 RTS disclosure."""
    entity_name: str
    lei: str
    reporting_period: str
    reference_date: str
    total_aum_eur: float
    mandatory_pais: dict = field(default_factory=dict)
    additional_pais: dict = field(default_factory=dict)
    average_data_quality: float = 0.0
    average_coverage: float = 0.0
    entity_classification: str = ""
    disclosure_sections: list = field(default_factory=list)
    cross_framework_mapping: list = field(default_factory=list)
    notes: list = field(default_factory=list)


@dataclass
class DNSHAssessmentResult:
    """Do No Significant Harm assessment for a single holding."""
    holding_id: str
    holding_name: str
    taxonomy_objective: str
    relevant_pais: list = field(default_factory=list)
    pai_assessments: list = field(default_factory=list)
    overall_pass: bool = False
    dnsh_score: float = 0.0
    notes: list = field(default_factory=list)


@dataclass
class EntityClassificationResult:
    """SFDR Article 6 / 8 / 9 classification."""
    entity_name: str
    classification: str
    label: str
    rationale: list = field(default_factory=list)
    disclosure_requirements: list = field(default_factory=list)
    pai_statement_required: bool = False
    taxonomy_alignment_required: bool = False
    sustainable_investment_pct: float = 0.0
    minimum_safeguards_met: bool = False
    notes: list = field(default_factory=list)


# ---------------------------------------------------------------------------
# Engine
# ---------------------------------------------------------------------------

class SFDRPAIEngine:
    """SFDR Principal Adverse Impact calculation and disclosure engine.

    Implements the full PAI framework from the SFDR Delegated Regulation
    (EU) 2022/1288, including all 18 mandatory indicators from Table 1,
    additional indicators from Tables 2 and 3, DNSH assessment, entity
    classification (Art 6/8/9), and structured disclosure generation.
    """

    # ── Single PAI Calculation ────────────────────────────────────────────

    def calculate_pai(
        self,
        portfolio_holdings: list[dict],
        pai_indicator_id: str,
    ) -> PAICalculationResult:
        """Calculate a single PAI indicator across a portfolio.

        Args:
            portfolio_holdings: List of holding dicts, each containing
                at minimum ``investment_value_eur`` and indicator-specific
                data fields as defined in ``PAI_CALCULATION_METHODS``.
            pai_indicator_id: Identifier such as ``"pai_1"`` through
                ``"pai_18"``.

        Returns:
            PAICalculationResult with the computed value, data quality
            score, and coverage ratio.
        """
        indicator = PAI_INDICATORS.get(pai_indicator_id)
        if indicator is None:
            return PAICalculationResult(
                indicator_id=pai_indicator_id,
                indicator_name="Unknown",
                value=0.0, unit="", category="", asset_class="",
                notes=[f"Unknown PAI indicator: {pai_indicator_id}"],
            )

        method = PAI_CALCULATION_METHODS.get(pai_indicator_id, {})
        agg = method.get("aggregation_method", "weighted_average")

        total_value = sum(
            h.get("investment_value_eur", 0.0) for h in portfolio_holdings
        )
        if total_value <= 0:
            return PAICalculationResult(
                indicator_id=pai_indicator_id,
                indicator_name=indicator["name"],
                value=0.0,
                unit=indicator["unit"],
                category=indicator["category"],
                asset_class=indicator["asset_class"],
                notes=["Portfolio total value is zero or negative."],
            )

        value = 0.0
        covered = 0
        total_h = len(portfolio_holdings)
        estimation_notes: list[str] = []

        if agg == "sum":
            value = self._calc_sum(portfolio_holdings, pai_indicator_id, total_value)
            covered = self._count_covered(portfolio_holdings, pai_indicator_id)
        elif agg == "ratio":
            value = self._calc_ratio(portfolio_holdings, pai_indicator_id, total_value)
            covered = self._count_covered(portfolio_holdings, pai_indicator_id)
        elif agg == "exposure_share":
            value = self._calc_exposure_share(portfolio_holdings, pai_indicator_id, total_value)
            covered = self._count_covered(portfolio_holdings, pai_indicator_id)
        else:
            value = self._calc_weighted_average(portfolio_holdings, pai_indicator_id, total_value)
            covered = self._count_covered(portfolio_holdings, pai_indicator_id)

        coverage = covered / total_h if total_h > 0 else 0.0
        dq_score = self._assess_indicator_data_quality(
            portfolio_holdings, pai_indicator_id, coverage,
        )

        if coverage < 1.0:
            estimation_notes.append(
                f"Data available for {covered}/{total_h} holdings "
                f"({coverage * 100:.1f}% coverage). Gaps filled with "
                f"sector averages or zero where unavailable."
            )

        return PAICalculationResult(
            indicator_id=pai_indicator_id,
            indicator_name=indicator["name"],
            value=round(value, 4),
            unit=indicator["unit"],
            category=indicator["category"],
            asset_class=indicator["asset_class"],
            data_quality_score=round(dq_score, 2),
            coverage_ratio=round(coverage, 4),
            holdings_covered=covered,
            holdings_total=total_h,
            estimation_method="sector_average_gap_fill" if coverage < 1.0 else "reported",
            notes=estimation_notes,
        )

    # ── All 18 Mandatory PAIs ─────────────────────────────────────────────

    def calculate_all_mandatory_pais(
        self,
        portfolio_holdings: list[dict],
    ) -> dict[str, PAICalculationResult]:
        """Calculate all 18 mandatory PAI indicators.

        Returns:
            Dict keyed by PAI indicator ID with PAICalculationResult values.
        """
        results: dict[str, PAICalculationResult] = {}
        for pai_id in PAI_INDICATORS:
            results[pai_id] = self.calculate_pai(portfolio_holdings, pai_id)
        return results

    # ── Additional (Optional) PAIs ────────────────────────────────────────

    def calculate_additional_pais(
        self,
        portfolio_holdings: list[dict],
        selected_indicators: list[str],
    ) -> dict[str, PAICalculationResult]:
        """Calculate selected additional PAI indicators from Tables 2 and 3.

        Args:
            portfolio_holdings: Portfolio holdings list.
            selected_indicators: List of additional indicator IDs
                (e.g. ``["add_env_4", "add_soc_11"]``).

        Returns:
            Dict of PAICalculationResult for each requested indicator.
        """
        results: dict[str, PAICalculationResult] = {}
        total_value = sum(
            h.get("investment_value_eur", 0.0) for h in portfolio_holdings
        )
        total_h = len(portfolio_holdings)

        for ind_id in selected_indicators:
            ind = ADDITIONAL_PAI_INDICATORS.get(ind_id)
            if ind is None:
                results[ind_id] = PAICalculationResult(
                    indicator_id=ind_id, indicator_name="Unknown",
                    value=0.0, unit="", category="", asset_class="",
                    notes=[f"Unknown additional indicator: {ind_id}"],
                )
                continue

            # For additional indicators, use weighted-average of the
            # holding-level metric value keyed by indicator ID.
            value = 0.0
            covered = 0
            for h in portfolio_holdings:
                metric_val = h.get(ind_id)
                if metric_val is not None:
                    weight = h.get("investment_value_eur", 0.0) / total_value if total_value > 0 else 0.0
                    value += weight * float(metric_val)
                    covered += 1

            coverage = covered / total_h if total_h > 0 else 0.0
            results[ind_id] = PAICalculationResult(
                indicator_id=ind_id,
                indicator_name=ind["name"],
                value=round(value, 4),
                unit=ind.get("unit", ""),
                category=ind["category"],
                asset_class=ind.get("sub_category", "company"),
                data_quality_score=round(min(coverage * 100, 100.0), 2),
                coverage_ratio=round(coverage, 4),
                holdings_covered=covered,
                holdings_total=total_h,
            )

        return results

    # ── DNSH Assessment ───────────────────────────────────────────────────

    def assess_do_no_significant_harm(
        self,
        holding: dict,
        taxonomy_objective: str,
    ) -> DNSHAssessmentResult:
        """Assess Do No Significant Harm for a holding against a taxonomy objective.

        For Article 9 products, each sustainable investment must demonstrate
        that it does not significantly harm any of the other five taxonomy
        objectives. The SFDR RTS uses PAI indicators as DNSH criteria.

        Args:
            holding: Dict with holding-level data (metrics keyed by PAI fields).
            taxonomy_objective: One of the six EU Taxonomy environmental
                objectives.

        Returns:
            DNSHAssessmentResult with per-PAI pass/fail and overall score.
        """
        holding_id = holding.get("holding_id", "unknown")
        holding_name = holding.get("name", "Unknown Holding")

        relevant_pais = _PAI_DNSH_MAP.get(taxonomy_objective, [])
        if not relevant_pais:
            return DNSHAssessmentResult(
                holding_id=holding_id,
                holding_name=holding_name,
                taxonomy_objective=taxonomy_objective,
                overall_pass=True,
                dnsh_score=100.0,
                notes=[f"No PAI indicators mapped to objective '{taxonomy_objective}'."],
            )

        assessments = []
        passes = 0
        for pai_id in relevant_pais:
            indicator = PAI_INDICATORS.get(pai_id, {})
            # Determine threshold based on indicator type
            threshold = self._get_dnsh_threshold(pai_id)
            holding_value = self._extract_holding_pai_value(holding, pai_id)
            passed = holding_value <= threshold if threshold is not None else True

            assessments.append({
                "pai_id": pai_id,
                "pai_name": indicator.get("name", pai_id),
                "holding_value": holding_value,
                "threshold": threshold,
                "passed": passed,
                "note": "" if passed else f"Exceeds DNSH threshold ({holding_value} > {threshold})",
            })
            if passed:
                passes += 1

        total_assessed = len(assessments)
        score = (passes / total_assessed * 100) if total_assessed > 0 else 0.0
        overall = all(a["passed"] for a in assessments)

        return DNSHAssessmentResult(
            holding_id=holding_id,
            holding_name=holding_name,
            taxonomy_objective=taxonomy_objective,
            relevant_pais=relevant_pais,
            pai_assessments=assessments,
            overall_pass=overall,
            dnsh_score=round(score, 1),
        )

    # ── Full PAI Statement ────────────────────────────────────────────────

    def calculate_portfolio_pai_statement(
        self,
        portfolio_holdings: list[dict],
        reporting_period: str,
        entity_name: str = "",
        lei: str = "",
    ) -> PAIStatementResult:
        """Produce a full PAI statement structure per Article 4 RTS.

        Args:
            portfolio_holdings: Complete list of portfolio holdings.
            reporting_period: E.g. ``"2025-01-01 to 2025-12-31"``.
            entity_name: Legal name of the financial market participant.
            lei: Legal Entity Identifier.

        Returns:
            PAIStatementResult ready for disclosure formatting.
        """
        total_aum = sum(h.get("investment_value_eur", 0.0) for h in portfolio_holdings)
        reference_date = datetime.utcnow().strftime("%Y-%m-%d")

        mandatory = self.calculate_all_mandatory_pais(portfolio_holdings)

        # RTS requires at least one additional env and one additional social
        default_additional = ["add_env_4", "add_soc_11"]
        additional = self.calculate_additional_pais(portfolio_holdings, default_additional)

        # Aggregate quality metrics
        mandatory_results = list(mandatory.values())
        avg_dq = (
            sum(r.data_quality_score for r in mandatory_results) / len(mandatory_results)
            if mandatory_results else 0.0
        )
        avg_cov = (
            sum(r.coverage_ratio for r in mandatory_results) / len(mandatory_results)
            if mandatory_results else 0.0
        )

        return PAIStatementResult(
            entity_name=entity_name,
            lei=lei,
            reporting_period=reporting_period,
            reference_date=reference_date,
            total_aum_eur=total_aum,
            mandatory_pais={k: v.__dict__ for k, v in mandatory.items()},
            additional_pais={k: v.__dict__ for k, v in additional.items()},
            average_data_quality=round(avg_dq, 2),
            average_coverage=round(avg_cov, 4),
            entity_classification="",
            disclosure_sections=_DISCLOSURE_TEMPLATE_SECTIONS,
            cross_framework_mapping=_CROSS_FRAMEWORK_MAP,
        )

    # ── Reporting Period Comparison ───────────────────────────────────────

    def compare_reporting_periods(
        self,
        current_pais: dict[str, dict],
        previous_pais: dict[str, dict],
    ) -> dict:
        """Compare PAI values between two reporting periods.

        Args:
            current_pais: Dict of current-period PAI results (as dicts).
            previous_pais: Dict of prior-period PAI results (as dicts).

        Returns:
            Dict with per-indicator trend, delta, improvement/deterioration
            classification, and summary statistics.
        """
        comparisons = []
        improvements = 0
        deteriorations = 0
        unchanged = 0

        all_ids = set(list(current_pais.keys()) + list(previous_pais.keys()))
        for pai_id in sorted(all_ids):
            curr = current_pais.get(pai_id, {})
            prev = previous_pais.get(pai_id, {})
            curr_val = curr.get("value", 0.0)
            prev_val = prev.get("value", 0.0)

            delta = curr_val - prev_val
            pct_change = (delta / prev_val * 100) if prev_val != 0 else 0.0

            indicator = PAI_INDICATORS.get(pai_id, {})
            # For most PAIs, lower is better (except PAI 13 board diversity)
            lower_is_better = pai_id != "pai_13"
            if abs(delta) < 1e-6:
                trend = "unchanged"
                unchanged += 1
            elif (delta < 0 and lower_is_better) or (delta > 0 and not lower_is_better):
                trend = "improved"
                improvements += 1
            else:
                trend = "deteriorated"
                deteriorations += 1

            comparisons.append({
                "indicator_id": pai_id,
                "indicator_name": indicator.get("name", pai_id),
                "current_value": round(curr_val, 4),
                "previous_value": round(prev_val, 4),
                "delta": round(delta, 4),
                "pct_change": round(pct_change, 2),
                "trend": trend,
            })

        return {
            "comparisons": comparisons,
            "summary": {
                "total_indicators_compared": len(comparisons),
                "improvements": improvements,
                "deteriorations": deteriorations,
                "unchanged": unchanged,
            },
        }

    # ── Disclosure Document Generation ────────────────────────────────────

    def generate_pai_disclosure(
        self,
        pai_statement: dict,
    ) -> dict:
        """Generate structured PAI disclosure document per Article 4 RTS.

        Args:
            pai_statement: Output of ``calculate_portfolio_pai_statement``
                (as a dict or PAIStatementResult.__dict__).

        Returns:
            Structured disclosure document with all RTS-required sections.
        """
        entity_name = pai_statement.get("entity_name", "")
        lei = pai_statement.get("lei", "")
        period = pai_statement.get("reporting_period", "")
        aum = pai_statement.get("total_aum_eur", 0.0)
        mandatory = pai_statement.get("mandatory_pais", {})
        additional = pai_statement.get("additional_pais", {})

        # Build indicator rows for the mandatory table
        mandatory_rows = []
        for pai_id in sorted(mandatory.keys()):
            data = mandatory[pai_id]
            indicator = PAI_INDICATORS.get(pai_id, {})
            mandatory_rows.append({
                "indicator_id": pai_id,
                "name": indicator.get("name", ""),
                "metric": indicator.get("metric", ""),
                "unit": indicator.get("unit", ""),
                "value": data.get("value", 0.0),
                "coverage_pct": round(data.get("coverage_ratio", 0.0) * 100, 1),
                "data_quality_score": data.get("data_quality_score", 0.0),
                "actions_taken": "",
                "actions_planned": "",
            })

        additional_rows = []
        for ind_id in sorted(additional.keys()):
            data = additional[ind_id]
            ind_ref = ADDITIONAL_PAI_INDICATORS.get(ind_id, {})
            additional_rows.append({
                "indicator_id": ind_id,
                "name": ind_ref.get("name", ""),
                "metric": ind_ref.get("metric", ""),
                "unit": ind_ref.get("unit", ""),
                "table": ind_ref.get("table", 0),
                "value": data.get("value", 0.0),
                "coverage_pct": round(data.get("coverage_ratio", 0.0) * 100, 1),
            })

        return {
            "document_type": "SFDR PAI Statement — Article 4 RTS",
            "entity_name": entity_name,
            "lei": lei,
            "reporting_period": period,
            "total_aum_eur": aum,
            "sections": [
                {
                    "section_id": "summary",
                    "title": "Summary",
                    "content": (
                        f"{entity_name} (LEI: {lei}) considers principal "
                        f"adverse impacts of its investment decisions on "
                        f"sustainability factors. The present statement "
                        f"covers the reference period {period} with total "
                        f"AUM of EUR {aum:,.0f}."
                    ),
                },
                {
                    "section_id": "mandatory_table",
                    "title": "Table 1 — Mandatory PAI Indicators",
                    "indicators": mandatory_rows,
                },
                {
                    "section_id": "additional_table",
                    "title": "Tables 2/3 — Additional PAI Indicators",
                    "indicators": additional_rows,
                },
                {
                    "section_id": "engagement",
                    "title": "Engagement Policies",
                    "content": "Description of engagement policies to be completed by the entity.",
                },
                {
                    "section_id": "international_standards",
                    "title": "International Standards Adherence",
                    "content": "UNGC, OECD Guidelines, Paris Agreement adherence to be completed.",
                },
                {
                    "section_id": "historical",
                    "title": "Historical Comparison",
                    "content": "Year-on-year comparison to be populated from second reporting period.",
                },
            ],
            "cross_framework": _CROSS_FRAMEWORK_MAP,
            "metadata": {
                "generated_at": datetime.utcnow().isoformat(),
                "average_data_quality": pai_statement.get("average_data_quality", 0.0),
                "average_coverage": pai_statement.get("average_coverage", 0.0),
            },
        }

    # ── Data Coverage Assessment ──────────────────────────────────────────

    def assess_data_coverage(
        self,
        portfolio_holdings: list[dict],
    ) -> dict:
        """Assess data availability and gaps across all mandatory PAI indicators.

        Returns:
            Per-indicator coverage report with gap analysis and
            estimation requirements.
        """
        total_h = len(portfolio_holdings)
        results = {}

        for pai_id, method in PAI_CALCULATION_METHODS.items():
            required_fields = method.get("required_data_fields", [])
            indicator = PAI_INDICATORS.get(pai_id, {})

            field_coverage = {}
            for fld in required_fields:
                count = sum(1 for h in portfolio_holdings if h.get(fld) is not None)
                field_coverage[fld] = {
                    "holdings_with_data": count,
                    "total_holdings": total_h,
                    "coverage_pct": round(count / total_h * 100, 1) if total_h > 0 else 0.0,
                }

            overall_cov = 0.0
            if field_coverage:
                overall_cov = sum(
                    fc["coverage_pct"] for fc in field_coverage.values()
                ) / len(field_coverage)

            estimation_needed = overall_cov < 100.0
            estimation_approach = ""
            if estimation_needed:
                if overall_cov >= 70:
                    estimation_approach = "Gap fill with sector averages (low estimation risk)"
                elif overall_cov >= 40:
                    estimation_approach = "Sector proxy + revenue-based estimation (moderate risk)"
                else:
                    estimation_approach = "Heavy estimation required — consider PCAF DQS 4-5 proxies"

            results[pai_id] = {
                "indicator_id": pai_id,
                "indicator_name": indicator.get("name", ""),
                "required_fields": required_fields,
                "field_coverage": field_coverage,
                "overall_coverage_pct": round(overall_cov, 1),
                "estimation_needed": estimation_needed,
                "estimation_approach": estimation_approach,
                "data_quality_tier": (
                    "high" if overall_cov >= 80 else
                    "medium" if overall_cov >= 50 else
                    "low"
                ),
            }

        return results

    # ── Entity Classification ─────────────────────────────────────────────

    def classify_entity(
        self,
        entity_config: dict,
    ) -> EntityClassificationResult:
        """Classify a financial product under SFDR Article 6, 8, or 9.

        Args:
            entity_config: Dict with keys:
                - ``entity_name`` (str)
                - ``promotes_es_characteristics`` (bool)
                - ``has_sustainable_objective`` (bool)
                - ``sustainable_investment_pct`` (float, 0-100)
                - ``taxonomy_aligned_pct`` (float, 0-100)
                - ``considers_pai`` (bool)
                - ``minimum_safeguards_met`` (bool)
                - ``good_governance_assessed`` (bool)
                - ``employees`` (int, for entity-level PAI obligation)

        Returns:
            EntityClassificationResult with classification and rationale.
        """
        name = entity_config.get("entity_name", "")
        promotes = entity_config.get("promotes_es_characteristics", False)
        sustainable_obj = entity_config.get("has_sustainable_objective", False)
        sustainable_pct = entity_config.get("sustainable_investment_pct", 0.0)
        taxonomy_pct = entity_config.get("taxonomy_aligned_pct", 0.0)
        considers_pai = entity_config.get("considers_pai", False)
        min_safeguards = entity_config.get("minimum_safeguards_met", False)
        good_gov = entity_config.get("good_governance_assessed", False)
        employees = entity_config.get("employees", 0)

        rationale: list[str] = []
        notes: list[str] = []

        # Article 9 check
        if sustainable_obj and min_safeguards and good_gov:
            classification = "article_9"
            rationale.append("Product has sustainable investment as its objective.")
            rationale.append("Minimum safeguards (UNGC, OECD, ILO) assessed as met.")
            rationale.append("Good governance practices verified.")
            if taxonomy_pct < 100:
                notes.append(
                    f"Taxonomy-aligned share is {taxonomy_pct:.1f}%. Art 9 products "
                    f"must disclose what proportion qualifies as environmentally "
                    f"sustainable under EU Taxonomy."
                )
        # Article 8 check
        elif promotes and good_gov:
            classification = "article_8"
            rationale.append("Product promotes environmental or social characteristics.")
            rationale.append("Good governance practices verified for investees.")
            if sustainable_pct > 0:
                rationale.append(
                    f"Product makes {sustainable_pct:.1f}% sustainable investments."
                )
            if not considers_pai:
                notes.append(
                    "PAI consideration is recommended for Art 8 products. "
                    "Consider opting into PAI reporting."
                )
        # Article 6 fallback
        else:
            classification = "article_6"
            rationale.append("Product does not promote E/S characteristics and has no sustainable objective.")
            if not promotes:
                rationale.append("No E/S characteristics promoted.")
            if not good_gov:
                rationale.append("Good governance assessment not confirmed.")

        cls_data = SFDR_ENTITY_CLASSIFICATION[classification]

        # Entity-level PAI obligation (>500 employees)
        pai_required = cls_data["pai_statement_required"]
        if employees > 500:
            pai_required = True
            notes.append(
                f"Entity has {employees} employees (>500): entity-level PAI "
                f"statement required under Art 4(1)(a) regardless of product classification."
            )

        return EntityClassificationResult(
            entity_name=name,
            classification=classification,
            label=cls_data["label"],
            rationale=rationale,
            disclosure_requirements=cls_data["disclosure_requirements"],
            pai_statement_required=pai_required,
            taxonomy_alignment_required=cls_data["taxonomy_alignment_required"],
            sustainable_investment_pct=sustainable_pct,
            minimum_safeguards_met=min_safeguards,
            notes=notes,
        )

    # ── Peer Benchmarking ─────────────────────────────────────────────────

    def benchmark_against_peers(
        self,
        pai_values: dict[str, float],
        peer_group: str,
    ) -> dict:
        """Benchmark PAI values against sector peer averages.

        Args:
            pai_values: Dict mapping benchmark keys (e.g.
                ``"pai_2_carbon_footprint"``) to portfolio values.
            peer_group: Sector key from the benchmark table (e.g.
                ``"financials"``, ``"energy"``).

        Returns:
            Dict with per-metric percentile ranking and relative
            performance classification.
        """
        benchmarks = _SECTOR_BENCHMARKS.get(peer_group, {})
        if not benchmarks:
            return {
                "peer_group": peer_group,
                "benchmarks_available": False,
                "note": f"No benchmarks available for peer group '{peer_group}'.",
                "results": [],
            }

        results = []
        for metric_key, portfolio_val in pai_values.items():
            bench_val = benchmarks.get(metric_key)
            if bench_val is None:
                continue

            # For most PAI metrics, lower is better
            lower_is_better = "female_board" not in metric_key
            if lower_is_better:
                if bench_val > 0:
                    ratio = portfolio_val / bench_val
                else:
                    ratio = 0.0
                # Percentile: lower ratio = better ranking
                if ratio <= 0.5:
                    percentile = 90
                elif ratio <= 0.75:
                    percentile = 75
                elif ratio <= 1.0:
                    percentile = 50
                elif ratio <= 1.25:
                    percentile = 25
                else:
                    percentile = 10
            else:
                if bench_val > 0:
                    ratio = portfolio_val / bench_val
                else:
                    ratio = 0.0
                if ratio >= 1.5:
                    percentile = 90
                elif ratio >= 1.25:
                    percentile = 75
                elif ratio >= 1.0:
                    percentile = 50
                elif ratio >= 0.75:
                    percentile = 25
                else:
                    percentile = 10

            performance = (
                "significantly_better" if percentile >= 90 else
                "better" if percentile >= 75 else
                "in_line" if percentile >= 50 else
                "worse" if percentile >= 25 else
                "significantly_worse"
            )

            results.append({
                "metric": metric_key,
                "portfolio_value": round(portfolio_val, 4),
                "peer_average": bench_val,
                "ratio_to_peer": round(ratio, 3),
                "percentile": percentile,
                "performance": performance,
            })

        return {
            "peer_group": peer_group,
            "benchmarks_available": True,
            "results": results,
        }

    # ── Internal Calculation Helpers ──────────────────────────────────────

    def _calc_sum(self, holdings: list[dict], pai_id: str, total_value: float) -> float:
        """Attribution-factor-based summation (PAI 1)."""
        total = 0.0
        scope_keys = {
            "pai_1": ["scope_1_tco2e", "scope_2_tco2e", "scope_3_tco2e"],
        }
        keys = scope_keys.get(pai_id, [])
        if not keys:
            return 0.0
        for h in holdings:
            evic = h.get("evic_eur", 0.0)
            inv_val = h.get("investment_value_eur", 0.0)
            if evic <= 0:
                continue
            af = inv_val / evic
            for k in keys:
                total += af * h.get(k, 0.0)
        return total

    def _calc_ratio(self, holdings: list[dict], pai_id: str, total_value: float) -> float:
        """Per-million-invested ratio (PAI 2, 8, 9)."""
        numerator = 0.0
        metric_key_map = {
            "pai_2": "total_ghg_tco2e",
            "pai_8": "water_emissions_tonnes",
            "pai_9": "hazardous_waste_tonnes",
        }
        metric_key = metric_key_map.get(pai_id)
        if not metric_key:
            return 0.0

        for h in holdings:
            evic = h.get("evic_eur", 0.0)
            inv_val = h.get("investment_value_eur", 0.0)
            if evic <= 0:
                continue
            af = inv_val / evic
            numerator += af * h.get(metric_key, 0.0)

        total_m = total_value / 1_000_000.0
        return numerator / total_m if total_m > 0 else 0.0

    def _calc_exposure_share(self, holdings: list[dict], pai_id: str, total_value: float) -> float:
        """Exposure-share percentage (PAI 4, 7, 10, 11, 14, 16, 17, 18)."""
        flag_key_map = {
            "pai_4": "is_fossil_fuel_company",
            "pai_7": "affects_biodiversity_sensitive_area",
            "pai_10": "has_ungc_oecd_violation",
            "pai_11": "lacks_ungc_oecd_policy",
            "pai_14": "involved_in_controversial_weapons",
            "pai_16": "has_social_violation",
            "pai_17": "involved_with_fossil_fuels",
            "pai_18": "is_energy_inefficient",
        }
        flag_key = flag_key_map.get(pai_id)
        if not flag_key:
            return 0.0

        flagged_value = sum(
            h.get("investment_value_eur", 0.0)
            for h in holdings if h.get(flag_key, False)
        )
        return (flagged_value / total_value * 100) if total_value > 0 else 0.0

    def _calc_weighted_average(self, holdings: list[dict], pai_id: str, total_value: float) -> float:
        """Weighted-average calculation (PAI 3, 5, 6, 12, 13, 15)."""
        metric_key_map = {
            "pai_3": ("total_ghg_tco2e", "revenue_eur"),
            "pai_5": ("non_renewable_energy_gwh", "total_energy_gwh"),
            "pai_6": ("energy_gwh", "revenue_eur"),
            "pai_12": ("gender_pay_gap_pct", None),
            "pai_13": ("female_board_pct", None),
            "pai_15": ("country_ghg_tco2e", "country_gdp_eur_m"),
        }
        mapping = metric_key_map.get(pai_id)
        if not mapping:
            return 0.0

        numerator_key, denominator_key = mapping
        result = 0.0

        for h in holdings:
            weight = h.get("investment_value_eur", 0.0) / total_value if total_value > 0 else 0.0
            num = h.get(numerator_key, 0.0)
            if denominator_key:
                denom = h.get(denominator_key, 0.0)
                intensity = (num / denom) if denom > 0 else 0.0
                result += weight * intensity
            else:
                result += weight * num

        # PAI 5: multiply by 100 to get percentage
        if pai_id == "pai_5":
            result *= 100.0

        return result

    def _count_covered(self, holdings: list[dict], pai_id: str) -> int:
        """Count holdings with at least one data point for the given PAI."""
        method = PAI_CALCULATION_METHODS.get(pai_id, {})
        required = method.get("required_data_fields", [])
        # A holding is "covered" if it has at least one non-null required field
        # beyond the portfolio-level fields.
        portfolio_fields = {"total_portfolio_value_eur", "total_sovereign_value_eur", "total_re_value_eur"}
        holding_fields = [f for f in required if f not in portfolio_fields]
        if not holding_fields:
            return len(holdings)
        covered = 0
        for h in holdings:
            if any(h.get(f) is not None for f in holding_fields):
                covered += 1
        return covered

    def _assess_indicator_data_quality(
        self, holdings: list[dict], pai_id: str, coverage: float,
    ) -> float:
        """Score data quality 0-100 based on coverage, source type, and recency."""
        score = coverage * 60  # 60% weight on coverage

        # Source quality bonus: reported > estimated
        reported_count = sum(
            1 for h in holdings
            if h.get("data_source") in ("reported", "audited", "verified")
        )
        if len(holdings) > 0:
            reported_ratio = reported_count / len(holdings)
            score += reported_ratio * 25  # 25% weight on source quality

        # Recency bonus: data from current or prior year
        recent_count = sum(
            1 for h in holdings
            if h.get("data_year") and h["data_year"] >= datetime.utcnow().year - 1
        )
        if len(holdings) > 0:
            recent_ratio = recent_count / len(holdings)
            score += recent_ratio * 15  # 15% weight on recency

        return min(score, 100.0)

    def _get_dnsh_threshold(self, pai_id: str) -> float | None:
        """Return a DNSH threshold for the given PAI indicator.

        Thresholds are illustrative screening values aligned with
        common market practice for Article 9 DNSH assessment.
        """
        thresholds = {
            "pai_1": 100_000.0,       # tCO2e absolute (varies by fund size)
            "pai_2": 100.0,           # tCO2e per EUR m invested
            "pai_3": 200.0,           # tCO2e per EUR m revenue
            "pai_4": 5.0,             # % exposure to fossil fuels
            "pai_5": 50.0,            # % non-renewable energy
            "pai_6": 0.5,             # GWh per EUR m revenue
            "pai_7": 0.0,             # 0% — any negative biodiversity impact fails
            "pai_8": 1.0,             # tonnes per EUR m invested
            "pai_9": 1.0,             # tonnes per EUR m invested
        }
        return thresholds.get(pai_id)

    def _extract_holding_pai_value(self, holding: dict, pai_id: str) -> float:
        """Extract the relevant metric value from a holding for a PAI check."""
        key_map = {
            "pai_1": "total_ghg_tco2e",
            "pai_2": "carbon_footprint",
            "pai_3": "ghg_intensity",
            "pai_4": "fossil_fuel_revenue_pct",
            "pai_5": "non_renewable_pct",
            "pai_6": "energy_intensity_gwh_per_m",
            "pai_7": "biodiversity_negative_impact",
            "pai_8": "water_emissions_intensity",
            "pai_9": "hazardous_waste_intensity",
        }
        key = key_map.get(pai_id)
        if key is None:
            return 0.0
        val = holding.get(key, 0.0)
        return float(val) if val is not None else 0.0

    # ── Static Reference Data ─────────────────────────────────────────────

    @staticmethod
    def get_mandatory_indicators() -> dict:
        """Return all 18 mandatory PAI indicators with full details."""
        return PAI_INDICATORS

    @staticmethod
    def get_additional_indicators() -> dict:
        """Return optional PAI indicators catalog (Tables 2 and 3)."""
        return ADDITIONAL_PAI_INDICATORS

    @staticmethod
    def get_calculation_methods() -> dict:
        """Return PAI calculation methodology reference."""
        return PAI_CALCULATION_METHODS

    @staticmethod
    def get_entity_classifications() -> dict:
        """Return Article 6/8/9 classification criteria."""
        return SFDR_ENTITY_CLASSIFICATION

    @staticmethod
    def get_disclosure_requirements() -> list[dict]:
        """Return RTS disclosure template sections."""
        return _DISCLOSURE_TEMPLATE_SECTIONS

    @staticmethod
    def get_sector_benchmarks() -> dict:
        """Return average PAI values by sector for benchmarking."""
        return _SECTOR_BENCHMARKS
