import React,{useState,useMemo,useCallback} from 'react';
import {BarChart,Bar,LineChart,Line,AreaChart,Area,PieChart,Pie,Cell,ScatterChart,Scatter,XAxis,YAxis,CartesianGrid,Tooltip,ResponsiveContainer,Legend,RadarChart,Radar,PolarGrid,PolarAngleAxis,PolarRadiusAxis} from 'recharts';
const T={bg:'#f6f4f0',surface:'#ffffff',surfaceH:'#f0ede7',border:'#e5e0d8',borderL:'#d5cfc5',navy:'#1b3a5c',navyL:'#2c5a8c',gold:'#c5a96a',goldL:'#d4be8a',sage:'#5a8a6a',sageL:'#7ba67d',teal:'#5a8a6a',text:'#1b3a5c',textSec:'#5c6b7e',textMut:'#9aa3ae',red:'#dc2626',green:'#16a34a',amber:'#d97706',font:"'DM Sans','SF Pro Display',system-ui,-apple-system,sans-serif",mono:"'JetBrains Mono','SF Mono','Fira Code',monospace"};
const sr=(s)=>{let x=Math.sin(s+1)*10000;return x-Math.floor(x);};
const ACCENT='#059669';const tip={contentStyle:{background:T.surface,border:`1px solid ${T.border}`,borderRadius:8,fontSize:11,fontFamily:T.font},labelStyle:{color:T.textSec,fontFamily:T.mono,fontSize:10}};const COLORS=[T.navy,T.gold,T.sage,T.red,T.amber,T.green,T.navyL,T.goldL,'#8b5cf6','#ec4899','#06b6d4'];
const fmt=v=>typeof v==='number'?v>=1e9?(v/1e9).toFixed(1)+'B':v>=1e6?(v/1e6).toFixed(1)+'M':v>=1e3?(v/1e3).toFixed(1)+'K':v.toFixed(1):v;
const TABS=['Portfolio Builder','Efficient Frontier','Constraint Analysis','Rebalancing'];const SECTORS=['All','Technology','Financials','Healthcare','Energy','Consumer','Industrials','Materials','Utilities'];const PAGE=12;
const HOLDINGS=Array.from({length:80},(_,i)=>{
  const names=['Apple','Microsoft','Alphabet','Amazon','NVIDIA','Meta','Tesla','JPMorgan','Visa','UnitedHealth','J&J','Walmart','P&G','Mastercard','Chevron','Home Depot','Coca-Cola','Pfizer','Abbott','Eli Lilly','PepsiCo','Costco','Broadcom','Cisco','Merck','Accenture','McDonalds','Adobe','Salesforce','AMD','Qualcomm','Intel','Goldman Sachs','Caterpillar','Amgen','Honeywell','Lockheed','Deere','IBM','GE','Medtronic','Shell','BP','TotalEnergies','Nestle','Roche','Novartis','SAP','Siemens','LVMH','Unilever','HSBC','BHP','Rio Tinto','Toyota','Samsung','TSMC','Novo Nordisk','AbbVie','Netflix','Starbucks','Booking','Intuit','Uber','Airbnb','PayPal','ServiceNow','CrowdStrike','Snowflake','Datadog','NextEra','Enel','Iberdrola','Orsted','Duke Energy','Southern Co','Xcel Energy','AES Corp','Dominion','Brookfield'];
  const secs=['Technology','Technology','Technology','Technology','Technology','Technology','Technology','Financials','Financials','Healthcare','Healthcare','Consumer','Consumer','Financials','Energy','Consumer','Consumer','Healthcare','Healthcare','Healthcare','Consumer','Consumer','Technology','Technology','Healthcare','Technology','Consumer','Technology','Technology','Technology','Technology','Technology','Financials','Industrials','Healthcare','Industrials','Industrials','Industrials','Technology','Industrials','Healthcare','Energy','Energy','Energy','Consumer','Healthcare','Healthcare','Technology','Industrials','Consumer','Consumer','Financials','Materials','Materials','Industrials','Technology','Technology','Healthcare','Healthcare','Technology','Consumer','Consumer','Technology','Technology','Technology','Financials','Technology','Technology','Technology','Technology','Utilities','Utilities','Utilities','Utilities','Utilities','Utilities','Utilities','Utilities','Utilities','Utilities'];
  const wt=+(sr(i*7)*3+0.2).toFixed(2);const itr=+(sr(i*11)*3+0.8).toFixed(1);const ci=Math.round(sr(i*13)*300+10);const ret=+((sr(i*17)-0.3)*20).toFixed(1);const vol=+(sr(i*19)*15+5).toFixed(1);
  return{id:i+1,name:names[i],sector:secs[i],weightPct:wt,itr,carbonIntensity:ci,greenRevPct:Math.round(sr(i*23)*50),sbti:sr(i*29)<0.4?'Approved':sr(i*29)<0.7?'Committed':'None',expectedReturn:ret,volatility:vol,sharpe:+(ret/(vol||1)).toFixed(2),esgScore:Math.round(sr(i*31)*40+50),trackingError:+(sr(i*37)*3+0.5).toFixed(1),beta:+(sr(i*41)*0.5+0.7).toFixed(2),divYield:+(sr(i*43)*4).toFixed(1)};
});
const FRONTIER=Array.from({length:20},(_,i)=>({risk:+(3+i*0.8).toFixed(1),returnNZ:+(2+i*0.55+sr(i*7)*0.5).toFixed(1),returnBM:+(1.5+i*0.6+sr(i*11)*0.4).toFixed(1)}));
export default function NetZeroPortfolioBuilderPage(){
  const[tab,setTab]=useState(0);const[search,setSearch]=useState('');const[sectorF,setSectorF]=useState('All');const[sortCol,setSortCol]=useState('weightPct');const[sortDir,setSortDir]=useState('desc');const[page,setPage]=useState(1);const[selected,setSelected]=useState(null);
  const[maxCarbon,setMaxCarbon]=useState(150);const[minGreen,setMinGreen]=useState(10);const[maxITR,setMaxITR]=useState(2.0);
  const filtered=useMemo(()=>{let d=[...HOLDINGS];if(search)d=d.filter(r=>r.name.toLowerCase().includes(search.toLowerCase()));if(sectorF!=='All')d=d.filter(r=>r.sector===sectorF);d.sort((a,b)=>sortDir==='asc'?(a[sortCol]>b[sortCol]?1:-1):(a[sortCol]<b[sortCol]?1:-1));return d;},[search,sectorF,sortCol,sortDir]);
  const constrained=useMemo(()=>filtered.filter(h=>h.carbonIntensity<=maxCarbon&&h.greenRevPct>=minGreen&&h.itr<=maxITR),[filtered,maxCarbon,minGreen,maxITR]);
  const paged=useMemo(()=>constrained.slice((page-1)*PAGE,page*PAGE),[constrained,page]);const totalPages=Math.ceil(constrained.length/PAGE);
  const doSort=col=>{if(sortCol===col)setSortDir(d=>d==='asc'?'desc':'asc');else{setSortCol(col);setSortDir('desc');}setPage(1);};
  const stats=useMemo(()=>{const d=constrained;return{count:d.length,avgITR:(d.reduce((s,r)=>s+r.itr,0)/d.length||0).toFixed(1),avgCI:Math.round(d.reduce((s,r)=>s+r.carbonIntensity,0)/d.length||0),avgGreen:Math.round(d.reduce((s,r)=>s+r.greenRevPct,0)/d.length||0),avgRet:(d.reduce((s,r)=>s+r.expectedReturn,0)/d.length||0).toFixed(1),avgVol:(d.reduce((s,r)=>s+r.volatility,0)/d.length||0).toFixed(1),sbtiApproved:d.filter(r=>r.sbti==='Approved').length};},[constrained]);
  const sectorAlloc=useMemo(()=>{const m={};constrained.forEach(h=>{m[h.sector]=(m[h.sector]||0)+h.weightPct;});return Object.entries(m).map(([k,v])=>({sector:k,weight:+v.toFixed(1)})).sort((a,b)=>b.weight-a.weight);},[constrained]);
  const exportCSV=useCallback((data,fn)=>{if(!data.length)return;const keys=Object.keys(data[0]);const csv=[keys.join(','),...data.map(r=>keys.map(k=>`"${r[k]}"`).join(','))].join('\n');const b=new Blob([csv],{type:'text/csv'});const u=URL.createObjectURL(b);const a=document.createElement('a');a.href=u;a.download=fn;a.click();URL.revokeObjectURL(u);},[]);
  const si=(col,cur,dir)=>cur===col?(dir==='asc'?' \u25B2':' \u25BC'):' \u25CB';
  const thS={padding:'8px 10px',fontSize:11,fontFamily:T.mono,color:T.textSec,cursor:'pointer',borderBottom:`1px solid ${T.border}`,whiteSpace:'nowrap',userSelect:'none',textAlign:'left',background:T.surfaceH};const tdS={padding:'7px 10px',fontSize:12,fontFamily:T.font,borderBottom:`1px solid ${T.border}`,color:T.text};const inpS={padding:'6px 12px',border:`1px solid ${T.border}`,borderRadius:6,fontSize:12,fontFamily:T.font,background:T.surface,color:T.text,outline:'none',width:180};const selS={padding:'6px 10px',border:`1px solid ${T.border}`,borderRadius:6,fontSize:11,fontFamily:T.font,background:T.surface,color:T.text};
  const btnS=a=>({padding:'6px 16px',border:`1px solid ${a?ACCENT:T.border}`,borderRadius:6,fontSize:12,fontFamily:T.font,background:a?ACCENT:T.surface,color:a?'#fff':T.text,cursor:'pointer',fontWeight:a?600:400});const pgB={padding:'4px 10px',border:`1px solid ${T.border}`,borderRadius:4,fontSize:11,cursor:'pointer',background:T.surface,color:T.text};const cS={background:T.surface,border:`1px solid ${T.border}`,borderRadius:10,padding:16};
  const kpi=(l,v,c)=>(<div style={{background:T.surface,border:`1px solid ${T.border}`,borderRadius:10,padding:'14px 18px',flex:1,minWidth:130}}><div style={{fontSize:10,color:T.textMut,fontFamily:T.mono,textTransform:'uppercase',letterSpacing:1}}>{l}</div><div style={{fontSize:22,fontWeight:700,color:c||T.navy,marginTop:4}}>{v}</div></div>);
  const Panel=({item,onClose})=>{if(!item)return null;return(<div style={{position:'fixed',top:0,right:0,width:440,height:'100vh',background:T.surface,borderLeft:`2px solid ${ACCENT}`,zIndex:1000,overflowY:'auto',boxShadow:'-4px 0 24px rgba(0,0,0,0.10)'}}><div style={{padding:'20px 24px',borderBottom:`1px solid ${T.border}`,display:'flex',justifyContent:'space-between',alignItems:'center'}}><div><div style={{fontSize:16,fontWeight:700,color:T.navy}}>{item.name}</div><div style={{fontSize:12,color:T.textSec}}>{item.sector}</div></div><button onClick={onClose} style={{background:'none',border:'none',fontSize:20,cursor:'pointer',color:T.textMut}}>{'\u2715'}</button></div>
    <div style={{padding:'16px 24px'}}><div style={{display:'grid',gridTemplateColumns:'1fr 1fr 1fr',gap:8}}>{[['Weight',item.weightPct+'%'],['ITR',item.itr+'\u00B0C'],['Carbon',item.carbonIntensity],['Green Rev',item.greenRevPct+'%'],['SBTi',item.sbti],['E[Return]',item.expectedReturn+'%'],['Volatility',item.volatility+'%'],['Sharpe',item.sharpe],['ESG',item.esgScore+'/100'],['TE',item.trackingError+'%'],['Beta',item.beta],['Div Yield',item.divYield+'%']].map(([k,v],j)=>(<div key={j} style={{background:T.surfaceH,borderRadius:6,padding:'8px 10px'}}><div style={{fontSize:9,color:T.textMut,fontFamily:T.mono}}>{k}</div><div style={{fontSize:13,fontWeight:600,color:T.navy,marginTop:2}}>{v}</div></div>))}</div></div></div>);};
  const sliderS={width:'100%',accentColor:ACCENT};
  const renderBuilder=()=>(<div>
    <div style={{display:'flex',gap:12,marginBottom:20,flexWrap:'wrap'}}>{kpi('Holdings',stats.count)}{kpi('Avg ITR',stats.avgITR+'\u00B0C')}{kpi('Avg Carbon',stats.avgCI)}{kpi('Avg Green Rev',stats.avgGreen+'%')}{kpi('E[Return]',stats.avgRet+'%')}{kpi('Avg Vol',stats.avgVol+'%')}{kpi('SBTi Approved',stats.sbtiApproved,T.green)}</div>
    <div style={{...cS,marginBottom:16}}><div style={{fontSize:13,fontWeight:600,color:T.navy,marginBottom:12}}>Constraint Sliders</div>
      <div style={{display:'grid',gridTemplateColumns:'1fr 1fr 1fr',gap:16}}>
        <div><div style={{fontSize:11,color:T.textSec}}>Max Carbon Intensity: <strong>{maxCarbon}</strong></div><input type="range" min={50} max={500} value={maxCarbon} onChange={e=>{setMaxCarbon(+e.target.value);setPage(1);}} style={sliderS}/></div>
        <div><div style={{fontSize:11,color:T.textSec}}>Min Green Revenue: <strong>{minGreen}%</strong></div><input type="range" min={0} max={50} value={minGreen} onChange={e=>{setMinGreen(+e.target.value);setPage(1);}} style={sliderS}/></div>
        <div><div style={{fontSize:11,color:T.textSec}}>Max ITR: <strong>{maxITR}\u00B0C</strong></div><input type="range" min={10} max={40} value={Math.round(maxITR*10)} onChange={e=>{setMaxITR(+(e.target.value/10).toFixed(1));setPage(1);}} style={sliderS}/></div>
      </div>
    </div>
    <div style={{display:'flex',gap:12,marginBottom:16,alignItems:'center',flexWrap:'wrap'}}><input value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}} placeholder="Search holdings..." style={inpS}/><select value={sectorF} onChange={e=>{setSectorF(e.target.value);setPage(1);}} style={selS}>{SECTORS.map(s=><option key={s}>{s}</option>)}</select><button onClick={()=>exportCSV(constrained,'nz_portfolio.csv')} style={btnS(false)}>Export CSV</button></div>
    <div style={{overflowX:'auto',...cS,padding:0}}><table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr>{[['name','Holding'],['sector','Sector'],['weightPct','Wt%'],['itr','ITR'],['carbonIntensity','Carbon'],['greenRevPct','Green%'],['expectedReturn','E[R]'],['esgScore','ESG']].map(([k,l])=><th key={k} onClick={()=>doSort(k)} style={thS}>{l}{si(k,sortCol,sortDir)}</th>)}</tr></thead>
      <tbody>{paged.map(r=><tr key={r.id} onClick={()=>setSelected(r)} style={{cursor:'pointer',background:selected?.id===r.id?T.surfaceH:'transparent'}}><td style={tdS}><span style={{fontWeight:600}}>{r.name}</span></td><td style={tdS}>{r.sector}</td><td style={tdS}>{r.weightPct}%</td><td style={tdS}><span style={{color:r.itr<1.5?T.green:r.itr<2?T.sage:r.itr<2.5?T.amber:T.red,fontWeight:600}}>{r.itr}\u00B0C</span></td><td style={tdS}>{r.carbonIntensity}</td><td style={tdS}>{r.greenRevPct}%</td><td style={tdS}>{r.expectedReturn}%</td><td style={tdS}>{r.esgScore}</td></tr>)}</tbody></table></div>
    {totalPages>1&&<div style={{display:'flex',gap:6,marginTop:12,alignItems:'center',justifyContent:'center'}}><button onClick={()=>setPage(p=>Math.max(1,p-1))} disabled={page===1} style={pgB}>&laquo;</button><span style={{fontSize:11,color:T.textSec,fontFamily:T.mono}}>Page {page}/{totalPages}</span><button onClick={()=>setPage(p=>Math.min(totalPages,p+1))} disabled={page===totalPages} style={pgB}>&raquo;</button></div>}
  </div>);
  const renderFrontier=()=>(<div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16}}>
    <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Efficient Frontier: Net Zero vs Benchmark</div><ResponsiveContainer width="100%" height={300}><LineChart data={FRONTIER}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="risk" tick={{fontSize:9,fill:T.textSec}} label={{value:'Risk (%)',position:'bottom',fontSize:10}}/><YAxis tick={{fontSize:9,fill:T.textSec}} label={{value:'Return (%)',angle:-90,position:'left',fontSize:10}}/><Tooltip {...tip}/><Line type="monotone" dataKey="returnNZ" stroke={ACCENT} strokeWidth={2} name="Net Zero" dot={{r:3}}/><Line type="monotone" dataKey="returnBM" stroke={T.textMut} strokeWidth={2} name="Benchmark" dot={{r:3}} strokeDasharray="5 5"/><Legend/></LineChart></ResponsiveContainer></div>
    <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Sector Allocation</div><ResponsiveContainer width="100%" height={300}><PieChart><Pie data={sectorAlloc} cx="50%" cy="50%" outerRadius={100} dataKey="weight" label={({sector,weight})=>`${sector}: ${weight}%`}>{sectorAlloc.map((_,i)=><Cell key={i} fill={COLORS[i%COLORS.length]}/>)}</Pie><Tooltip {...tip}/></PieChart></ResponsiveContainer></div>
    <div style={{...cS,gridColumn:'1/3'}}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Return vs Carbon Intensity</div><ResponsiveContainer width="100%" height={280}><ScatterChart><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="x" name="Carbon" tick={{fontSize:9,fill:T.textSec}}/><YAxis dataKey="y" name="E[R]" tick={{fontSize:9,fill:T.textSec}}/><Tooltip {...tip}/><Scatter data={constrained.map(h=>({name:h.name,x:h.carbonIntensity,y:h.expectedReturn}))} fill={ACCENT} fillOpacity={0.5}/></ScatterChart></ResponsiveContainer></div>
  </div></div>);
  const renderConstraint=()=>(<div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16}}>
    <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>ITR Distribution</div><ResponsiveContainer width="100%" height={280}><BarChart data={[{r:'<1.5',c:constrained.filter(h=>h.itr<1.5).length},{r:'1.5-2.0',c:constrained.filter(h=>h.itr>=1.5&&h.itr<2).length},{r:'2.0-2.5',c:constrained.filter(h=>h.itr>=2&&h.itr<2.5).length},{r:'2.5-3.0',c:constrained.filter(h=>h.itr>=2.5&&h.itr<3).length},{r:'>3.0',c:constrained.filter(h=>h.itr>=3).length}]}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="r" tick={{fontSize:9,fill:T.textSec}}/><YAxis tick={{fontSize:9,fill:T.textSec}}/><Tooltip {...tip}/><Bar dataKey="c" fill={ACCENT} radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></div>
    <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>SBTi Status</div><ResponsiveContainer width="100%" height={280}><PieChart><Pie data={[{n:'Approved',v:constrained.filter(h=>h.sbti==='Approved').length},{n:'Committed',v:constrained.filter(h=>h.sbti==='Committed').length},{n:'None',v:constrained.filter(h=>h.sbti==='None').length}]} cx="50%" cy="50%" outerRadius={90} dataKey="v" label={({n,v})=>`${n}: ${v}`}>{[T.green,T.amber,T.red].map((c,i)=><Cell key={i} fill={c}/>)}</Pie><Tooltip {...tip}/></PieChart></ResponsiveContainer></div>
  </div></div>);
  const renderRebal=()=>(<div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16}}>
    <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Top Overweight Positions</div><ResponsiveContainer width="100%" height={300}><BarChart data={[...constrained].sort((a,b)=>b.weightPct-a.weightPct).slice(0,15)} layout="vertical"><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis type="number" tick={{fontSize:9,fill:T.textSec}}/><YAxis type="category" dataKey="name" tick={{fontSize:8,fill:T.textSec}} width={80}/><Tooltip {...tip}/><Bar dataKey="weightPct" fill={T.navy} radius={[0,4,4,0]}/></BarChart></ResponsiveContainer></div>
    <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>ESG Score vs Weight</div><ResponsiveContainer width="100%" height={300}><ScatterChart><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="x" name="ESG" tick={{fontSize:9,fill:T.textSec}}/><YAxis dataKey="y" name="Weight%" tick={{fontSize:9,fill:T.textSec}}/><Tooltip {...tip}/><Scatter data={constrained.map(h=>({name:h.name,x:h.esgScore,y:h.weightPct}))} fill={T.gold} fillOpacity={0.5}/></ScatterChart></ResponsiveContainer></div>
  </div></div>);
  return(<div style={{padding:'24px 32px',fontFamily:T.font,background:T.bg,minHeight:'100vh'}}>
    <div style={{marginBottom:20}}><h1 style={{fontSize:22,fontWeight:700,color:T.navy,margin:0}}>Net Zero Portfolio Builder</h1><p style={{fontSize:12,color:T.textSec,margin:'4px 0 0'}}>80 holdings | Constraint optimization, efficient frontier, rebalancing</p></div>
    <div style={{display:'flex',gap:8,marginBottom:20}}>{TABS.map((t,i)=><button key={t} onClick={()=>setTab(i)} style={btnS(tab===i)}>{t}</button>)}</div>
    {tab===0&&renderBuilder()}{tab===1&&renderFrontier()}{tab===2&&renderConstraint()}{tab===3&&renderRebal()}
    <Panel item={selected} onClose={()=>setSelected(null)}/>
  </div>);
}