import React,{useState,useMemo,useCallback} from 'react';
import {BarChart,Bar,LineChart,Line,AreaChart,Area,PieChart,Pie,Cell,ScatterChart,Scatter,XAxis,YAxis,CartesianGrid,Tooltip,ResponsiveContainer,Legend,RadarChart,Radar,PolarGrid,PolarAngleAxis,PolarRadiusAxis} from 'recharts';

const T={bg:'#f6f4f0',surface:'#ffffff',surfaceH:'#f0ede7',border:'#e5e0d8',borderL:'#d5cfc5',navy:'#1b3a5c',navyL:'#2c5a8c',gold:'#c5a96a',goldL:'#d4be8a',sage:'#5a8a6a',sageL:'#7ba67d',teal:'#5a8a6a',text:'#1b3a5c',textSec:'#5c6b7e',textMut:'#9aa3ae',red:'#dc2626',green:'#16a34a',amber:'#d97706',font:"'DM Sans','SF Pro Display',system-ui,-apple-system,sans-serif",mono:"'JetBrains Mono','SF Mono','Fira Code',monospace"};
const sr=(s)=>{let x=Math.sin(s+1)*10000;return x-Math.floor(x);};
const ACCENT='#0e7490';const tip={contentStyle:{background:T.surface,border:`1px solid ${T.border}`,borderRadius:8,fontSize:11,fontFamily:T.font},labelStyle:{color:T.textSec,fontFamily:T.mono,fontSize:10}};
const COLORS=[T.navy,T.gold,T.sage,T.red,T.amber,T.green,T.navyL,T.goldL,T.sageL,'#8b5cf6','#ec4899','#06b6d4'];
const fmt=v=>typeof v==='number'?v>=1e9?(v/1e9).toFixed(1)+'B':v>=1e6?(v/1e6).toFixed(1)+'M':v>=1e3?(v/1e3).toFixed(1)+'K':v.toFixed(1):v;
const TABS=['Funding Overview','Fund Tracker','Regional Flows','Gap Analysis'];
const TYPES=['All','Mitigation','Adaptation','Cross-cutting','Loss & Damage'];const PAGE=12;
const FUNDS=['GCF','AF','GEF','CIF','LDCF','SCCF','CAFI','GCPF','NDC Partnership','IRENA Fund','GCA','AIIB Green','IFC Climate','ADB Climate','KfW Climate','EIB Green','EBRD Green','AfDB Climate','IsDB Green','NDB Green','GGGI','CTCN','TNC Blue','CI Fund','WWF Climate','UNDP Climate','UNEP Finance','WRI Climate','CDP Fund','Climate Works'];

const PROJECTS=Array.from({length:60},(_,i)=>{
  const regions=['Sub-Saharan Africa','South Asia','Southeast Asia','Latin America','East Asia','MENA','Pacific Islands','Central Asia','Eastern Europe','Caribbean'];
  const sectors=['Renewable Energy','Forest Conservation','Climate Resilience','Sustainable Transport','Water Management','Agriculture','Coastal Protection','Urban Adaptation','Energy Efficiency','Disaster Risk'];
  const fund=FUNDS[i%30];const region=regions[Math.floor(sr(i*7)*regions.length)];const sector=sectors[Math.floor(sr(i*11)*sectors.length)];
  const type=['Mitigation','Adaptation','Cross-cutting','Loss & Damage'][Math.floor(sr(i*13)*4)];const status=['Active','Completed','Pipeline','Disbursing'][Math.floor(sr(i*17)*4)];
  const approved=+(sr(i*19)*500+10).toFixed(1);const disbursed=+(approved*(sr(i*23)*0.6+0.2)).toFixed(1);const cofinance=+(approved*(sr(i*29)*2+0.5)).toFixed(1);
  const countries=Math.round(sr(i*31)*8+1);const beneficiaries=Math.round(sr(i*37)*5+0.1);const emissions=Math.round(sr(i*41)*50+5);const jobs=Math.round(sr(i*43)*20000+1000);
  const yearly=Array.from({length:5},(_,y)=>({year:2020+y,approved:+Math.max(0,approved/5+sr(i*100+y)*20-10).toFixed(1),disbursed:+Math.max(0,disbursed/5+sr(i*100+y*3)*10-5).toFixed(1)}));
  return{id:i+1,name:`${sector} - ${region.split(' ')[0]}`,fund,region,sector,type,status,approvedM:approved,disbursedM:disbursed,cofinanceM:cofinance,disbursementRate:approved>0?Math.round(disbursed/approved*100):0,countries,beneficiariesM:beneficiaries,emissionsReduced:emissions,jobsCreated:jobs,startYear:2019+Math.floor(sr(i*47)*4),endYear:2025+Math.floor(sr(i*49)*5),genderMarker:['G0','G1','G2'][Math.floor(sr(i*51)*3)],resultArea:['Energy','REDD+','Transport','Adaptation','Health','Food','Water','Cities'][Math.floor(sr(i*53)*8)],riskRating:['Low','Medium','High'][Math.floor(sr(i*57)*3)],yearly};
});

export default function ClimateFinanceHubPage(){
  const[tab,setTab]=useState(0);const[search,setSearch]=useState('');const[typeF,setTypeF]=useState('All');const[sortCol,setSortCol]=useState('approvedM');const[sortDir,setSortDir]=useState('desc');const[page,setPage]=useState(1);const[selected,setSelected]=useState(null);

  const filtered=useMemo(()=>{let d=[...PROJECTS];if(search)d=d.filter(r=>r.name.toLowerCase().includes(search.toLowerCase())||r.fund.toLowerCase().includes(search.toLowerCase()));if(typeF!=='All')d=d.filter(r=>r.type===typeF);d.sort((a,b)=>sortDir==='asc'?(a[sortCol]>b[sortCol]?1:-1):(a[sortCol]<b[sortCol]?1:-1));return d;},[search,typeF,sortCol,sortDir]);
  const paged=useMemo(()=>filtered.slice((page-1)*PAGE,page*PAGE),[filtered,page]);const totalPages=Math.ceil(filtered.length/PAGE);
  const doSort=col=>{if(sortCol===col)setSortDir(d=>d==='asc'?'desc':'asc');else{setSortCol(col);setSortDir('desc');}setPage(1);};

  const stats=useMemo(()=>({count:filtered.length,totalApproved:fmt(filtered.reduce((s,r)=>s+r.approvedM,0)*1e6),totalDisbursed:fmt(filtered.reduce((s,r)=>s+r.disbursedM,0)*1e6),avgDisbRate:filtered.length?Math.round(filtered.reduce((s,r)=>s+r.disbursementRate,0)/filtered.length):0,totalCofinance:fmt(filtered.reduce((s,r)=>s+r.cofinanceM,0)*1e6),totalEmissions:fmt(filtered.reduce((s,r)=>s+r.emissionsReduced,0)),active:filtered.filter(r=>r.status==='Active').length}),[filtered]);

  const typeDist=useMemo(()=>{const m={};PROJECTS.forEach(r=>{m[r.type]=(m[r.type]||0)+r.approvedM;});return Object.entries(m).map(([k,v])=>({name:k,value:Math.round(v)}));},[]);
  const regionFlow=useMemo(()=>{const m={};PROJECTS.forEach(r=>{if(!m[r.region])m[r.region]={region:r.region,approved:0,disbursed:0};m[r.region].approved+=r.approvedM;m[r.region].disbursed+=r.disbursedM;});return Object.values(m).sort((a,b)=>b.approved-a.approved);},[]);
  const fundRank=useMemo(()=>{const m={};PROJECTS.forEach(r=>{if(!m[r.fund])m[r.fund]={fund:r.fund,total:0,n:0};m[r.fund].total+=r.approvedM;m[r.fund].n++;});return Object.values(m).sort((a,b)=>b.total-a.total).slice(0,15);},[]);
  const yearlyTrend=useMemo(()=>{const m={};PROJECTS.forEach(p=>p.yearly.forEach(y=>{if(!m[y.year])m[y.year]={year:y.year,approved:0,disbursed:0};m[y.year].approved+=y.approved;m[y.year].disbursed+=y.disbursed;}));return Object.values(m).sort((a,b)=>a.year-b.year);},[]);

  const exportCSV=useCallback((data,fn)=>{if(!data.length)return;const keys=Object.keys(data[0]).filter(k=>k!=='yearly');const csv=[keys.join(','),...data.map(r=>keys.map(k=>`"${r[k]}"`).join(','))].join('\n');const b=new Blob([csv],{type:'text/csv'});const u=URL.createObjectURL(b);const a=document.createElement('a');a.href=u;a.download=fn;a.click();URL.revokeObjectURL(u);},[]);

  const si=(col,cur,dir)=>cur===col?(dir==='asc'?' \u25B2':' \u25BC'):' \u25CB';
  const thS={padding:'8px 10px',fontSize:11,fontFamily:T.mono,color:T.textSec,cursor:'pointer',borderBottom:`1px solid ${T.border}`,whiteSpace:'nowrap',userSelect:'none',textAlign:'left',background:T.surfaceH};
  const tdS={padding:'7px 10px',fontSize:12,fontFamily:T.font,borderBottom:`1px solid ${T.border}`,color:T.text};
  const inpS={padding:'6px 12px',border:`1px solid ${T.border}`,borderRadius:6,fontSize:12,fontFamily:T.font,background:T.surface,color:T.text,outline:'none',width:220};
  const selS={padding:'6px 10px',border:`1px solid ${T.border}`,borderRadius:6,fontSize:11,fontFamily:T.font,background:T.surface,color:T.text};
  const btnS=a=>({padding:'6px 16px',border:`1px solid ${a?ACCENT:T.border}`,borderRadius:6,fontSize:12,fontFamily:T.font,background:a?ACCENT:T.surface,color:a?'#fff':T.text,cursor:'pointer',fontWeight:a?600:400});
  const pgB={padding:'4px 10px',border:`1px solid ${T.border}`,borderRadius:4,fontSize:11,cursor:'pointer',background:T.surface,color:T.text};
  const cS={background:T.surface,border:`1px solid ${T.border}`,borderRadius:10,padding:16};
  const kpi=(l,v,c)=>(<div style={{background:T.surface,border:`1px solid ${T.border}`,borderRadius:10,padding:'14px 18px',flex:1,minWidth:140}}><div style={{fontSize:10,color:T.textMut,fontFamily:T.mono,textTransform:'uppercase',letterSpacing:1}}>{l}</div><div style={{fontSize:22,fontWeight:700,color:c||T.navy,marginTop:4}}>{v}</div></div>);

  const Panel=({item,onClose})=>{if(!item)return null;return(<div style={{position:'fixed',top:0,right:0,width:460,height:'100vh',background:T.surface,borderLeft:`2px solid ${ACCENT}`,zIndex:1000,overflowY:'auto',boxShadow:'-4px 0 24px rgba(0,0,0,0.10)'}}><div style={{padding:'20px 24px',borderBottom:`1px solid ${T.border}`,display:'flex',justifyContent:'space-between',alignItems:'center'}}><div><div style={{fontSize:16,fontWeight:700,color:T.navy}}>{item.name}</div><div style={{fontSize:12,color:T.textSec}}>{item.fund} | {item.type}</div></div><button onClick={onClose} style={{background:'none',border:'none',fontSize:20,cursor:'pointer',color:T.textMut}}>\u2715</button></div>
    <div style={{padding:'16px 24px'}}>
      <div style={{display:'grid',gridTemplateColumns:'1fr 1fr 1fr',gap:8,marginBottom:16}}>{[['Approved','$'+item.approvedM+'M'],['Disbursed','$'+item.disbursedM+'M'],['Co-finance','$'+item.cofinanceM+'M'],['Disb. Rate',item.disbursementRate+'%'],['Countries',item.countries],['Beneficiaries',item.beneficiariesM+'M'],['Emissions',item.emissionsReduced+' MtCO2'],['Jobs',fmt(item.jobsCreated)],['Status',item.status],['Region',item.region],['Sector',item.sector],['Risk',item.riskRating],['Gender',item.genderMarker],['Start',item.startYear],['End',item.endYear]].map(([k,v],j)=>(<div key={j} style={{background:T.surfaceH,borderRadius:6,padding:'8px 10px'}}><div style={{fontSize:9,color:T.textMut,fontFamily:T.mono}}>{k}</div><div style={{fontSize:13,fontWeight:600,color:T.navy,marginTop:2}}>{v}</div></div>))}</div>
      <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Yearly Funding Flow</div><ResponsiveContainer width="100%" height={200}><BarChart data={item.yearly}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="year" tick={{fontSize:9,fill:T.textSec}}/><YAxis tick={{fontSize:9,fill:T.textSec}}/><Tooltip {...tip}/><Bar dataKey="approved" fill={ACCENT} name="Approved $M"/><Bar dataKey="disbursed" fill={T.gold} name="Disbursed $M"/><Legend/></BarChart></ResponsiveContainer></div>
    </div></div>);};

  const renderOverview=()=>(<div>
    <div style={{display:'flex',gap:12,marginBottom:20,flexWrap:'wrap'}}>{kpi('Projects',stats.count)}{kpi('Total Approved',stats.totalApproved)}{kpi('Total Disbursed',stats.totalDisbursed)}{kpi('Avg Disb. Rate',stats.avgDisbRate+'%')}{kpi('Co-financing',stats.totalCofinance)}{kpi('Emissions Cut',stats.totalEmissions+' Mt')}{kpi('Active',stats.active,T.green)}</div>
    <div style={{display:'flex',gap:12,marginBottom:16,alignItems:'center',flexWrap:'wrap'}}><input value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}} placeholder="Search projects or funds..." style={inpS}/><select value={typeF} onChange={e=>{setTypeF(e.target.value);setPage(1);}} style={selS}>{TYPES.map(s=><option key={s}>{s}</option>)}</select><button onClick={()=>exportCSV(filtered,'climate_finance.csv')} style={btnS(false)}>Export CSV</button></div>
    <div style={{overflowX:'auto',...cS,padding:0}}><table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr>{[['name','Project'],['fund','Fund'],['type','Type'],['approvedM','Approved $M'],['disbursedM','Disbursed $M'],['disbursementRate','Disb %'],['region','Region'],['status','Status']].map(([k,l])=><th key={k} onClick={()=>doSort(k)} style={thS}>{l}{si(k,sortCol,sortDir)}</th>)}</tr></thead>
      <tbody>{paged.map(r=><tr key={r.id} onClick={()=>setSelected(r)} style={{cursor:'pointer',background:selected?.id===r.id?T.surfaceH:'transparent'}}><td style={tdS}><span style={{fontWeight:600}}>{r.name}</span></td><td style={{...tdS,fontSize:10,fontFamily:T.mono}}>{r.fund}</td><td style={tdS}>{r.type}</td><td style={tdS}>${r.approvedM}M</td><td style={tdS}>${r.disbursedM}M</td><td style={tdS}><span style={{color:r.disbursementRate>60?T.green:r.disbursementRate>30?T.amber:T.red,fontWeight:600}}>{r.disbursementRate}%</span></td><td style={tdS}>{r.region}</td><td style={tdS}>{r.status}</td></tr>)}</tbody></table></div>
    {totalPages>1&&<div style={{display:'flex',gap:6,marginTop:12,alignItems:'center',justifyContent:'center'}}><button onClick={()=>setPage(p=>Math.max(1,p-1))} disabled={page===1} style={pgB}>&laquo;</button><span style={{fontSize:11,color:T.textSec,fontFamily:T.mono}}>Page {page}/{totalPages}</span><button onClick={()=>setPage(p=>Math.min(totalPages,p+1))} disabled={page===totalPages} style={pgB}>&raquo;</button></div>}
    <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16,marginTop:20}}>
      <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Finance by Type</div><ResponsiveContainer width="100%" height={260}><PieChart><Pie data={typeDist} cx="50%" cy="50%" outerRadius={90} dataKey="value" label={({name,value})=>`${name}: $${value}M`}>{typeDist.map((_,i)=><Cell key={i} fill={COLORS[i]}/>)}</Pie><Tooltip {...tip}/></PieChart></ResponsiveContainer></div>
      <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Annual Trend</div><ResponsiveContainer width="100%" height={260}><AreaChart data={yearlyTrend}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="year" tick={{fontSize:9,fill:T.textSec}}/><YAxis tick={{fontSize:9,fill:T.textSec}}/><Tooltip {...tip}/><Area type="monotone" dataKey="approved" stroke={ACCENT} fill="rgba(14,116,144,0.15)" name="Approved"/><Area type="monotone" dataKey="disbursed" stroke={T.gold} fill="rgba(197,169,106,0.15)" name="Disbursed"/><Legend/></AreaChart></ResponsiveContainer></div>
    </div>
  </div>);

  const renderFunds=()=>(<div>
    <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16}}>
      <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Top 15 Funds by Volume</div><ResponsiveContainer width="100%" height={350}><BarChart data={fundRank} layout="vertical"><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis type="number" tick={{fontSize:9,fill:T.textSec}}/><YAxis type="category" dataKey="fund" tick={{fontSize:8,fill:T.textSec}} width={80}/><Tooltip {...tip}/><Bar dataKey="total" fill={ACCENT} radius={[0,4,4,0]}/></BarChart></ResponsiveContainer></div>
      <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Fund Project Count</div><ResponsiveContainer width="100%" height={350}><BarChart data={fundRank} layout="vertical"><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis type="number" tick={{fontSize:9,fill:T.textSec}}/><YAxis type="category" dataKey="fund" tick={{fontSize:8,fill:T.textSec}} width={80}/><Tooltip {...tip}/><Bar dataKey="n" fill={T.gold} radius={[0,4,4,0]}/></BarChart></ResponsiveContainer></div>
      <div style={{...cS,gridColumn:'1/3'}}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Approved vs Disbursed by Fund</div><ResponsiveContainer width="100%" height={280}><ScatterChart><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="x" name="Approved $M" tick={{fontSize:9,fill:T.textSec}}/><YAxis dataKey="y" name="Disbursed $M" tick={{fontSize:9,fill:T.textSec}}/><Tooltip {...tip}/><Scatter data={PROJECTS.map(p=>({name:p.fund,x:p.approvedM,y:p.disbursedM}))} fill={ACCENT} fillOpacity={0.5}/></ScatterChart></ResponsiveContainer></div>
    </div>
  </div>);

  const renderRegional=()=>(<div>
    <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16}}>
      <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Regional Funding Flows</div><ResponsiveContainer width="100%" height={300}><BarChart data={regionFlow}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="region" tick={{fontSize:8,fill:T.textSec}} angle={-25}/><YAxis tick={{fontSize:9,fill:T.textSec}}/><Tooltip {...tip}/><Bar dataKey="approved" fill={ACCENT} name="Approved $M"/><Bar dataKey="disbursed" fill={T.gold} name="Disbursed $M"/><Legend/></BarChart></ResponsiveContainer></div>
      <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Disbursement Efficiency by Region</div><ResponsiveContainer width="100%" height={300}><BarChart data={regionFlow.map(r=>({...r,rate:r.approved>0?Math.round(r.disbursed/r.approved*100):0}))}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="region" tick={{fontSize:8,fill:T.textSec}} angle={-25}/><YAxis tick={{fontSize:9,fill:T.textSec}} domain={[0,100]}/><Tooltip {...tip}/><Bar dataKey="rate" fill={T.sage} radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></div>
      <div style={{...cS,gridColumn:'1/3'}}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Regional Distribution</div><ResponsiveContainer width="100%" height={260}><PieChart><Pie data={regionFlow.map(r=>({name:r.region,value:Math.round(r.approved)}))} cx="50%" cy="50%" outerRadius={95} dataKey="value" label={({name,value})=>`${name}: $${value}M`}>{regionFlow.map((_,i)=><Cell key={i} fill={COLORS[i%COLORS.length]}/>)}</Pie><Tooltip {...tip}/></PieChart></ResponsiveContainer></div>
    </div>
  </div>);

  const renderGap=()=>{
    const needs=[{region:'Sub-Saharan Africa',need:80,current:25},{region:'South Asia',need:60,current:20},{region:'Southeast Asia',need:45,current:18},{region:'Latin America',need:35,current:15},{region:'Pacific Islands',need:25,current:5},{region:'MENA',need:30,current:12},{region:'Central Asia',need:20,current:7},{region:'Caribbean',need:15,current:4}];
    return(<div>
      <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16}}>
        <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Financing Gap by Region ($B)</div><ResponsiveContainer width="100%" height={300}><BarChart data={needs}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="region" tick={{fontSize:8,fill:T.textSec}} angle={-25}/><YAxis tick={{fontSize:9,fill:T.textSec}}/><Tooltip {...tip}/><Bar dataKey="need" fill={T.red} name="Need $B" opacity={0.3}/><Bar dataKey="current" fill={T.green} name="Current $B"/><Legend/></BarChart></ResponsiveContainer></div>
        <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Gap Closure Rate</div><ResponsiveContainer width="100%" height={300}><BarChart data={needs.map(n=>({...n,gap:Math.round(n.current/n.need*100)}))}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="region" tick={{fontSize:8,fill:T.textSec}} angle={-25}/><YAxis tick={{fontSize:9,fill:T.textSec}} domain={[0,100]}/><Tooltip {...tip}/><Bar dataKey="gap" fill={ACCENT} radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></div>
        <div style={{...cS,gridColumn:'1/3'}}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Mitigation vs Adaptation Split (% of approved)</div><ResponsiveContainer width="100%" height={260}><PieChart><Pie data={[{name:'Mitigation',value:Math.round(PROJECTS.filter(p=>p.type==='Mitigation').reduce((s,p)=>s+p.approvedM,0))},{name:'Adaptation',value:Math.round(PROJECTS.filter(p=>p.type==='Adaptation').reduce((s,p)=>s+p.approvedM,0))},{name:'Cross-cutting',value:Math.round(PROJECTS.filter(p=>p.type==='Cross-cutting').reduce((s,p)=>s+p.approvedM,0))},{name:'Loss & Damage',value:Math.round(PROJECTS.filter(p=>p.type==='Loss & Damage').reduce((s,p)=>s+p.approvedM,0))}]} cx="50%" cy="50%" outerRadius={90} dataKey="value" label={({name,value})=>`${name}: $${value}M`}>{[T.sage,ACCENT,T.gold,T.red].map((c,i)=><Cell key={i} fill={c}/>)}</Pie><Tooltip {...tip}/></PieChart></ResponsiveContainer></div>
      </div>
    </div>);
  };

  return(<div style={{padding:'24px 32px',fontFamily:T.font,background:T.bg,minHeight:'100vh'}}>
    <div style={{marginBottom:20}}><h1 style={{fontSize:22,fontWeight:700,color:T.navy,margin:0}}>Climate Finance Hub</h1><p style={{fontSize:12,color:T.textSec,margin:'4px 0 0'}}>$100B+ tracking | GCF, AF, GEF | 60 projects | Regional flows & gap analysis</p></div>
    <div style={{display:'flex',gap:8,marginBottom:20}}>{TABS.map((t,i)=><button key={t} onClick={()=>setTab(i)} style={btnS(tab===i)}>{t}</button>)}</div>
    {tab===0&&renderOverview()}{tab===1&&renderFunds()}{tab===2&&renderRegional()}{tab===3&&renderGap()}
    <Panel item={selected} onClose={()=>setSelected(null)}/>
  </div>);
}