import React,{useState,useMemo,useCallback} from 'react';
import {BarChart,Bar,LineChart,Line,AreaChart,Area,PieChart,Pie,Cell,ScatterChart,Scatter,XAxis,YAxis,CartesianGrid,Tooltip,ResponsiveContainer,Legend,RadarChart,Radar,PolarGrid,PolarAngleAxis,PolarRadiusAxis} from 'recharts';
import { useCarbonCredit } from '../../../context/CarbonCreditContext';
const T={bg:'#f6f4f0',surface:'#ffffff',surfaceH:'#f0ede7',border:'#e5e0d8',borderL:'#d5cfc5',navy:'#1b3a5c',navyL:'#2c5a8c',gold:'#c5a96a',goldL:'#d4be8a',sage:'#5a8a6a',sageL:'#7ba67d',teal:'#5a8a6a',text:'#1b3a5c',textSec:'#5c6b7e',textMut:'#9aa3ae',red:'#dc2626',green:'#16a34a',amber:'#d97706',font:"'DM Sans','SF Pro Display',system-ui,-apple-system,sans-serif",mono:"'JetBrains Mono','SF Mono','Fira Code',monospace"};
const sr=(s)=>{let x=Math.sin(s+1)*10000;return x-Math.floor(x);};
const ACCENT='#7c3aed';const tip={contentStyle:{background:T.surface,border:`1px solid ${T.border}`,borderRadius:8,fontSize:11,fontFamily:T.font},labelStyle:{color:T.textSec,fontFamily:T.mono,fontSize:10}};const COLORS=[T.navy,T.gold,T.sage,T.red,T.amber,T.green,T.navyL,T.goldL,'#8b5cf6','#ec4899'];
const fmt=v=>typeof v==='number'?v>=1e9?(v/1e9).toFixed(1)+'B':v>=1e6?(v/1e6).toFixed(1)+'M':v>=1e3?(v/1e3).toFixed(1)+'K':v.toFixed(1):v;
const TABS=['PAI Dashboard','Fund Screening','Pre-contractual','Periodic Reports'];const CLASSF=['All','Article 6','Article 8','Article 8+','Article 9'];const PAGE=12;
const PAI_INDICATORS=['GHG Emissions','Carbon Footprint','GHG Intensity','Fossil Fuel Exposure','Non-Renewable Energy','Energy Intensity','Biodiversity Impact','Water Emissions','Hazardous Waste','UNGC/OECD Violations','Gender Pay Gap','Board Gender Diversity','Controversial Weapons','Social Violations'];
const FUNDS=Array.from({length:60},(_,i)=>{
  const names=['Amundi ESG Leaders','BlackRock Sustainable','Vanguard ESG','PIMCO Climate Bond','Robeco Climate','Nordea Stars','Pictet Clean Energy','BNP Paribas Green','DWS ESG Strategy','UBS Sustainable','Fidelity Sustainable','Schroders Climate','AXA Climate Equity','Invesco ESG','Wellington Climate','HSBC ESG Equity','JPM Climate Aware','Goldman Climate','Morgan Stanley Impact','T Rowe Price ESG','Allianz Climate','Aviva Investors ESG','Legal & General ESG','M&G Positive Impact','Aberdeen Climate','Columbia ESG','Natixis Impact','Franklin ESG','Nuveen ESG','State Street ESG','iShares ESG Core','Xtrackers MSCI ESG','SPDR Climate','Lyxor Green Bond','Ossiam Climate','Mirova Global Sust','Candriam Sustainable','NN Green Bond','Comgest Positive','First Sentier Sust','Impax Environmental','Liontrust Sustainable','Janus Henderson Sust','Jupiter Climate','Stewart Investors','Baillie Gifford Pos','EdenTree Responsible','Sarasin Responsible','Rathbone Ethical','Triodos Impact','BMO Responsible','Royal London Sust','Aegon Sustainable','Standard Life ESG','Scottish Widows ESG','Aviva Pen Steward','NEST Ethical','People Pension Sust','Hargreaves ESG','AJ Bell Resp'];
  const cls=['Article 6','Article 8','Article 8','Article 8+','Article 9','Article 9','Article 8+','Article 8','Article 8','Article 8+','Article 8','Article 9','Article 8+','Article 8','Article 9','Article 8','Article 8','Article 8+','Article 9','Article 8','Article 8','Article 8','Article 8','Article 9','Article 8+','Article 8','Article 9','Article 8','Article 8','Article 6','Article 6','Article 8','Article 8','Article 8+','Article 8','Article 9','Article 8+','Article 8+','Article 9','Article 8','Article 9','Article 8+','Article 8','Article 8','Article 8','Article 9','Article 8+','Article 8','Article 8','Article 9','Article 8','Article 8','Article 6','Article 8','Article 6','Article 8','Article 6','Article 8','Article 6','Article 8'];
  const aumBn=+(sr(i*7)*50+0.5).toFixed(1);const paiScore=Math.round(sr(i*11)*40+50);const taxAligned=Math.round(sr(i*13)*60+10);const sustInvest=Math.round(sr(i*17)*50+10);const dnsh=Math.round(sr(i*19)*30+60);
  const paiValues=PAI_INDICATORS.map(p=>({indicator:p,value:+(sr(i*100+PAI_INDICATORS.indexOf(p)*7)*100).toFixed(1),coverage:Math.round(sr(i*100+PAI_INDICATORS.indexOf(p)*11)*40+50)}));
  return{id:i+1,name:names[i],classification:cls[i],aumBn,paiScore,taxonomyAligned:taxAligned,sustainableInvest:sustInvest,dnshCompliance:dnsh,carbonFootprint:Math.round(sr(i*23)*200+20),fossilExposure:+(sr(i*29)*20).toFixed(1),controversialWeapons:sr(i*31)>0.9?'Yes':'No',ungcViolations:Math.round(sr(i*37)*5),genderDiversity:Math.round(sr(i*41)*30+20),dataCompleteness:Math.round(sr(i*43)*30+60),reportStatus:sr(i*47)<0.3?'Draft':sr(i*47)<0.7?'Published':'Pending',paiValues};
});
export default function SfdrV2ReportingPage(){
  const ccData = useCarbonCredit(); const ccReg = ccData.adaptForRegulatory();
  const[tab,setTab]=useState(0);const[search,setSearch]=useState('');const[clsF,setClsF]=useState('All');const[sortCol,setSortCol]=useState('paiScore');const[sortDir,setSortDir]=useState('desc');const[page,setPage]=useState(1);const[selected,setSelected]=useState(null);
  const filtered=useMemo(()=>{let d=[...FUNDS];if(search)d=d.filter(r=>r.name.toLowerCase().includes(search.toLowerCase()));if(clsF!=='All')d=d.filter(r=>r.classification===clsF);d.sort((a,b)=>sortDir==='asc'?(a[sortCol]>b[sortCol]?1:-1):(a[sortCol]<b[sortCol]?1:-1));return d;},[search,clsF,sortCol,sortDir]);
  const paged=useMemo(()=>filtered.slice((page-1)*PAGE,page*PAGE),[filtered,page]);const totalPages=Math.ceil(filtered.length/PAGE);
  const doSort=col=>{if(sortCol===col)setSortDir(d=>d==='asc'?'desc':'asc');else{setSortCol(col);setSortDir('desc');}setPage(1);};
  const stats=useMemo(()=>({count:filtered.length,totalAUM:'€'+filtered.reduce((s,r)=>s+r.aumBn,0).toFixed(0)+'B',avgPAI:Math.round(filtered.reduce((s,r)=>s+r.paiScore,0)/filtered.length||0),avgTaxonomy:Math.round(filtered.reduce((s,r)=>s+r.taxonomyAligned,0)/filtered.length||0),art9:filtered.filter(r=>r.classification==='Article 9').length,published:filtered.filter(r=>r.reportStatus==='Published').length,avgData:Math.round(filtered.reduce((s,r)=>s+r.dataCompleteness,0)/filtered.length||0)}),[filtered]);
  const clsDist=useMemo(()=>CLASSF.slice(1).map(c=>({name:c,value:FUNDS.filter(f=>f.classification===c).length,aum:+FUNDS.filter(f=>f.classification===c).reduce((s,f)=>s+f.aumBn,0).toFixed(0)})),[]);
  const exportCSV=useCallback((data,fn)=>{if(!data.length)return;const keys=Object.keys(data[0]).filter(k=>k!=='paiValues');const csv=[keys.join(','),...data.map(r=>keys.map(k=>`"${r[k]}"`).join(','))].join('\n');const b=new Blob([csv],{type:'text/csv'});const u=URL.createObjectURL(b);const a=document.createElement('a');a.href=u;a.download=fn;a.click();URL.revokeObjectURL(u);},[]);
  const si=(col,cur,dir)=>cur===col?(dir==='asc'?' \u25B2':' \u25BC'):' \u25CB';
  const thS={padding:'8px 10px',fontSize:11,fontFamily:T.mono,color:T.textSec,cursor:'pointer',borderBottom:`1px solid ${T.border}`,whiteSpace:'nowrap',userSelect:'none',textAlign:'left',background:T.surfaceH};const tdS={padding:'7px 10px',fontSize:12,fontFamily:T.font,borderBottom:`1px solid ${T.border}`,color:T.text};const inpS={padding:'6px 12px',border:`1px solid ${T.border}`,borderRadius:6,fontSize:12,fontFamily:T.font,background:T.surface,color:T.text,outline:'none',width:220};const selS={padding:'6px 10px',border:`1px solid ${T.border}`,borderRadius:6,fontSize:11,fontFamily:T.font,background:T.surface,color:T.text};
  const btnS=a=>({padding:'6px 16px',border:`1px solid ${a?ACCENT:T.border}`,borderRadius:6,fontSize:12,fontFamily:T.font,background:a?ACCENT:T.surface,color:a?'#fff':T.text,cursor:'pointer',fontWeight:a?600:400});const pgB={padding:'4px 10px',border:`1px solid ${T.border}`,borderRadius:4,fontSize:11,cursor:'pointer',background:T.surface,color:T.text};const cS={background:T.surface,border:`1px solid ${T.border}`,borderRadius:10,padding:16};
  const kpi=(l,v,c)=>(<div style={{background:T.surface,border:`1px solid ${T.border}`,borderRadius:10,padding:'14px 18px',flex:1,minWidth:130}}><div style={{fontSize:10,color:T.textMut,fontFamily:T.mono,textTransform:'uppercase',letterSpacing:1}}>{l}</div><div style={{fontSize:22,fontWeight:700,color:c||T.navy,marginTop:4}}>{v}</div></div>);
  const Panel=({item,onClose})=>{if(!item)return null;return(<div style={{position:'fixed',top:0,right:0,width:480,height:'100vh',background:T.surface,borderLeft:`2px solid ${ACCENT}`,zIndex:1000,overflowY:'auto',boxShadow:'-4px 0 24px rgba(0,0,0,0.10)'}}><div style={{padding:'20px 24px',borderBottom:`1px solid ${T.border}`,display:'flex',justifyContent:'space-between',alignItems:'center'}}><div><div style={{fontSize:16,fontWeight:700,color:T.navy}}>{item.name}</div><div style={{fontSize:12,color:T.textSec}}>{item.classification} | AUM: ${item.aumBn}B</div></div><button onClick={onClose} style={{background:'none',border:'none',fontSize:20,cursor:'pointer',color:T.textMut}}>{'\u2715'}</button></div>
    <div style={{padding:'16px 24px'}}>
      <div style={{display:'grid',gridTemplateColumns:'1fr 1fr 1fr',gap:8,marginBottom:12}}>{[['PAI Score',item.paiScore+'/100'],['Taxonomy',item.taxonomyAligned+'%'],['Sust. Invest',item.sustainableInvest+'%'],['DNSH',item.dnshCompliance+'/100'],['Carbon',item.carbonFootprint],['Fossil',item.fossilExposure+'%'],['Controv. Wpns',item.controversialWeapons],['UNGC Viol.',item.ungcViolations],['Gender Div.',item.genderDiversity+'%'],['Data Quality',item.dataCompleteness+'%'],['Status',item.reportStatus]].map(([k,v],j)=>(<div key={j} style={{background:T.surfaceH,borderRadius:6,padding:'8px 10px'}}><div style={{fontSize:9,color:T.textMut,fontFamily:T.mono}}>{k}</div><div style={{fontSize:13,fontWeight:600,color:T.navy,marginTop:2}}>{v}</div></div>))}</div>
      <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>PAI Indicator Coverage</div><ResponsiveContainer width="100%" height={250}><BarChart data={item.paiValues.slice(0,8)} layout="vertical"><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis type="number" tick={{fontSize:9,fill:T.textSec}} domain={[0,100]}/><YAxis type="category" dataKey="indicator" tick={{fontSize:7,fill:T.textSec}} width={100}/><Tooltip {...tip}/><Bar dataKey="coverage" fill={ACCENT} radius={[0,4,4,0]} name="Coverage %"/></BarChart></ResponsiveContainer></div>
    </div></div>);};
  const renderDash=()=>(<div>
    <div style={{display:'flex',gap:12,marginBottom:20,flexWrap:'wrap'}}>{kpi('Funds',stats.count)}{kpi('Total AUM',stats.totalAUM)}{kpi('Avg PAI',stats.avgPAI+'/100')}{kpi('Avg Taxonomy',stats.avgTaxonomy+'%')}{kpi('Article 9',stats.art9,T.green)}{kpi('Published',stats.published)}{kpi('Data Quality',stats.avgData+'%')}{kpi('CC GHG Offset',ccReg.pai_1_ghg_offset?.toLocaleString()||'0','#059669')}{kpi('CC Tax Aligned',(ccReg.taxonomy_aligned_pct??0).toFixed(1)+'%','#059669')}</div>
    <div style={{display:'flex',gap:12,marginBottom:16,alignItems:'center',flexWrap:'wrap'}}><input value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}} placeholder="Search funds..." style={inpS}/><select value={clsF} onChange={e=>{setClsF(e.target.value);setPage(1);}} style={selS}>{CLASSF.map(s=><option key={s}>{s}</option>)}</select><button onClick={()=>exportCSV(filtered,'sfdr_reporting.csv')} style={btnS(false)}>Export CSV</button></div>
    <div style={{overflowX:'auto',...cS,padding:0}}><table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr>{[['name','Fund'],['classification','Class'],['aumBn','AUM $B'],['paiScore','PAI'],['taxonomyAligned','Tax%'],['sustainableInvest','SI%'],['carbonFootprint','Carbon'],['reportStatus','Status']].map(([k,l])=><th key={k} onClick={()=>doSort(k)} style={thS}>{l}{si(k,sortCol,sortDir)}</th>)}</tr></thead>
      <tbody>{paged.map(r=><tr key={r.id} onClick={()=>setSelected(r)} style={{cursor:'pointer',background:selected?.id===r.id?T.surfaceH:'transparent'}}><td style={tdS}><span style={{fontWeight:600}}>{r.name}</span></td><td style={{...tdS,fontFamily:T.mono,fontSize:10}}>{r.classification}</td><td style={tdS}>${r.aumBn}B</td><td style={tdS}>{r.paiScore}</td><td style={tdS}>{r.taxonomyAligned}%</td><td style={tdS}>{r.sustainableInvest}%</td><td style={tdS}>{r.carbonFootprint}</td><td style={tdS}><span style={{color:r.reportStatus==='Published'?T.green:r.reportStatus==='Draft'?T.amber:T.red,fontWeight:600,fontSize:10}}>{r.reportStatus}</span></td></tr>)}</tbody></table></div>
    {totalPages>1&&<div style={{display:'flex',gap:6,marginTop:12,alignItems:'center',justifyContent:'center'}}><button onClick={()=>setPage(p=>Math.max(1,p-1))} disabled={page===1} style={pgB}>&laquo;</button><span style={{fontSize:11,color:T.textSec,fontFamily:T.mono}}>Page {page}/{totalPages}</span><button onClick={()=>setPage(p=>Math.min(totalPages,p+1))} disabled={page===totalPages} style={pgB}>&raquo;</button></div>}
    <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16,marginTop:20}}>
      <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>SFDR Classification Split</div><ResponsiveContainer width="100%" height={260}><PieChart><Pie data={clsDist} cx="50%" cy="50%" outerRadius={90} dataKey="value" label={({name,value})=>`${name}: ${value}`}>{clsDist.map((_,i)=><Cell key={i} fill={COLORS[i]}/>)}</Pie><Tooltip {...tip}/></PieChart></ResponsiveContainer></div>
      <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>AUM by Classification</div><ResponsiveContainer width="100%" height={260}><BarChart data={clsDist}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="name" tick={{fontSize:9,fill:T.textSec}}/><YAxis tick={{fontSize:9,fill:T.textSec}}/><Tooltip {...tip}/><Bar dataKey="aum" fill={ACCENT} radius={[4,4,0,0]} name="AUM $B"/></BarChart></ResponsiveContainer></div>
    </div></div>);
  const renderFund=()=>(<div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16}}>
    <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Taxonomy Alignment by Classification</div><ResponsiveContainer width="100%" height={280}><BarChart data={CLASSF.slice(1).map(c=>{const fs=FUNDS.filter(f=>f.classification===c);return{cls:c,taxonomy:fs.length?Math.round(fs.reduce((s,f)=>s+f.taxonomyAligned,0)/fs.length):0,si:fs.length?Math.round(fs.reduce((s,f)=>s+f.sustainableInvest,0)/fs.length):0};})}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="cls" tick={{fontSize:9,fill:T.textSec}}/><YAxis tick={{fontSize:9,fill:T.textSec}} domain={[0,100]}/><Tooltip {...tip}/><Bar dataKey="taxonomy" fill={T.green} name="Taxonomy %"/><Bar dataKey="si" fill={ACCENT} name="Sust. Invest %"/><Legend/></BarChart></ResponsiveContainer></div>
    <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>PAI Score vs Carbon Footprint</div><ResponsiveContainer width="100%" height={280}><ScatterChart><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="x" name="PAI Score" tick={{fontSize:9,fill:T.textSec}}/><YAxis dataKey="y" name="Carbon" tick={{fontSize:9,fill:T.textSec}}/><Tooltip {...tip}/><Scatter data={filtered.map(f=>({name:f.name,x:f.paiScore,y:f.carbonFootprint}))} fill={ACCENT} fillOpacity={0.5}/></ScatterChart></ResponsiveContainer></div>
  </div></div>);
  const renderPre=()=>(<div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16}}>
    <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Sustainable Investment %</div><ResponsiveContainer width="100%" height={300}><BarChart data={[...filtered].sort((a,b)=>b.sustainableInvest-a.sustainableInvest).slice(0,15)} layout="vertical"><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis type="number" tick={{fontSize:9,fill:T.textSec}} domain={[0,100]}/><YAxis type="category" dataKey="name" tick={{fontSize:7,fill:T.textSec}} width={110}/><Tooltip {...tip}/><Bar dataKey="sustainableInvest" fill={T.sage} radius={[0,4,4,0]}/></BarChart></ResponsiveContainer></div>
    <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>DNSH Compliance</div><ResponsiveContainer width="100%" height={300}><BarChart data={[...filtered].sort((a,b)=>a.dnshCompliance-b.dnshCompliance).slice(0,15)} layout="vertical"><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis type="number" tick={{fontSize:9,fill:T.textSec}} domain={[0,100]}/><YAxis type="category" dataKey="name" tick={{fontSize:7,fill:T.textSec}} width={110}/><Tooltip {...tip}/><Bar dataKey="dnshCompliance" fill={T.navy} radius={[0,4,4,0]}/></BarChart></ResponsiveContainer></div>
  </div></div>);
  const renderPeriodic=()=>(<div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16}}>
    <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Report Status</div><ResponsiveContainer width="100%" height={260}><PieChart><Pie data={[{n:'Published',v:FUNDS.filter(f=>f.reportStatus==='Published').length},{n:'Draft',v:FUNDS.filter(f=>f.reportStatus==='Draft').length},{n:'Pending',v:FUNDS.filter(f=>f.reportStatus==='Pending').length}]} cx="50%" cy="50%" outerRadius={90} dataKey="v" label={({n,v})=>`${n}: ${v}`}>{[T.green,T.amber,T.red].map((c,i)=><Cell key={i} fill={c}/>)}</Pie><Tooltip {...tip}/></PieChart></ResponsiveContainer></div>
    <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Data Completeness</div><ResponsiveContainer width="100%" height={260}><BarChart data={[{r:'<60%',c:filtered.filter(f=>f.dataCompleteness<60).length},{r:'60-70%',c:filtered.filter(f=>f.dataCompleteness>=60&&f.dataCompleteness<70).length},{r:'70-80%',c:filtered.filter(f=>f.dataCompleteness>=70&&f.dataCompleteness<80).length},{r:'80-90%',c:filtered.filter(f=>f.dataCompleteness>=80&&f.dataCompleteness<90).length},{r:'>90%',c:filtered.filter(f=>f.dataCompleteness>=90).length}]}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="r" tick={{fontSize:9,fill:T.textSec}}/><YAxis tick={{fontSize:9,fill:T.textSec}}/><Tooltip {...tip}/><Bar dataKey="c" fill={ACCENT} radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></div>
  </div></div>);
  return(<div style={{padding:'24px 32px',fontFamily:T.font,background:T.bg,minHeight:'100vh'}}>
    <div style={{marginBottom:20}}><h1 style={{fontSize:22,fontWeight:700,color:T.navy,margin:0}}>SFDR V2 Reporting</h1><p style={{fontSize:12,color:T.textSec,margin:'4px 0 0'}}>60 funds | PAI indicators, pre-contractual disclosure, periodic reports</p></div>
    <div style={{display:'flex',gap:8,marginBottom:20}}>{TABS.map((t,i)=><button key={t} onClick={()=>setTab(i)} style={btnS(tab===i)}>{t}</button>)}</div>
    {tab===0&&renderDash()}{tab===1&&renderFund()}{tab===2&&renderPre()}{tab===3&&renderPeriodic()}
    <Panel item={selected} onClose={()=>setSelected(null)}/>
  </div>);
}