import React,{useState,useMemo,useCallback} from 'react';
import {BarChart,Bar,LineChart,Line,AreaChart,Area,PieChart,Pie,Cell,ScatterChart,Scatter,XAxis,YAxis,CartesianGrid,Tooltip,ResponsiveContainer,Legend,RadarChart,Radar,PolarGrid,PolarAngleAxis,PolarRadiusAxis} from 'recharts';
const T={bg:'#f6f4f0',surface:'#ffffff',surfaceH:'#f0ede7',border:'#e5e0d8',borderL:'#d5cfc5',navy:'#1b3a5c',navyL:'#2c5a8c',gold:'#c5a96a',goldL:'#d4be8a',sage:'#5a8a6a',sageL:'#7ba67d',teal:'#5a8a6a',text:'#1b3a5c',textSec:'#5c6b7e',textMut:'#9aa3ae',red:'#dc2626',green:'#16a34a',amber:'#d97706',font:"'DM Sans','SF Pro Display',system-ui,-apple-system,sans-serif",mono:"'JetBrains Mono','SF Mono','Fira Code',monospace"};
const sr=(s)=>{let x=Math.sin(s+1)*10000;return x-Math.floor(x);};
const ACCENT='#059669';const tip={contentStyle:{background:T.surface,border:`1px solid ${T.border}`,borderRadius:8,fontSize:11,fontFamily:T.font},labelStyle:{color:T.textSec,fontFamily:T.mono,fontSize:10}};const COLORS=[T.navy,T.gold,T.sage,T.red,T.amber,T.green,T.navyL,T.goldL,'#8b5cf6'];
const TABS=['ITR Dashboard','Company Alignment','Sector Pathways','Methodology'];const SECTORS=['All','Energy','Utilities','Materials','Industrials','Technology','Financials','Consumer','Healthcare'];const PAGE=15;
const COMPANIES=(()=>{const names=['Exxon Mobil','Shell plc','BP plc','TotalEnergies','Chevron','ConocoPhillips','Equinor','Eni SpA','Repsol','OMV AG','NextEra Energy','Enel SpA','Iberdrola','Orsted A/S','EDF Group','Duke Energy','Southern Co','Dominion Energy','Xcel Energy','AES Corp','BHP Group','Rio Tinto','ArcelorMittal','Glencore','Anglo American','BASF SE','Dow Inc','Linde plc','Air Liquide','HeidelbergCement','Siemens AG','GE','Honeywell','ABB Ltd','Schneider Electric','Caterpillar','Deere & Co','Atlas Copco','Komatsu','Mitsubishi Heavy','Apple','Microsoft','Alphabet','Amazon','Samsung','NVIDIA','TSMC','Intel','Broadcom','SAP','JPMorgan','Goldman Sachs','HSBC','BNP Paribas','Deutsche Bank','Nestle','Unilever','P&G','Coca-Cola','PepsiCo'];
  const secs=['Energy','Energy','Energy','Energy','Energy','Energy','Energy','Energy','Energy','Energy','Utilities','Utilities','Utilities','Utilities','Utilities','Utilities','Utilities','Utilities','Utilities','Utilities','Materials','Materials','Materials','Materials','Materials','Materials','Materials','Materials','Materials','Materials','Industrials','Industrials','Industrials','Industrials','Industrials','Industrials','Industrials','Industrials','Industrials','Industrials','Technology','Technology','Technology','Technology','Technology','Technology','Technology','Technology','Technology','Technology','Financials','Financials','Financials','Financials','Financials','Consumer','Consumer','Consumer','Consumer','Consumer'];
  return names.map((n,i)=>({id:i+1,name:n,sector:secs[i],itr:+(sr(i*7)*3+1).toFixed(1),scope1Intensity:Math.round(5+sr(i*11)*195),scope2Intensity:Math.round(2+sr(i*13)*80),scope3Intensity:Math.round(10+sr(i*17)*500),reductionTarget:Math.round(10+sr(i*19)*55),targetYear:sr(i*23)<0.3?2030:sr(i*23)<0.6?2040:2050,sbtiStatus:sr(i*29)<0.3?'Approved':sr(i*29)<0.55?'Committed':sr(i*29)<0.75?'Near-term':'None',alignment:sr(i*7)<0.15?'1.5C Aligned':sr(i*7)<0.35?'Below 2C':sr(i*7)<0.55?'2C':sr(i*7)<0.75?'Above 2C':'Not Aligned',budgetRemaining:Math.round(sr(i*31)*80),carbonBudget:Math.round(100+sr(i*37)*900),emissionsTrajectory:sr(i*41)<0.4?'Declining':sr(i*41)<0.7?'Flat':'Rising',netZeroCommit:sr(i*43)>0.3?'Yes':'No',greenRevPct:Math.round(sr(i*47)*50),transitionPlan:sr(i*53)<0.35?'Comprehensive':sr(i*53)<0.65?'Partial':'None',credibilityScore:Math.round(15+sr(i*59)*80)}));})();
const PATHWAY=Array.from({length:8},(_,i)=>({year:2023+i*4,portfolio:+(2.8-i*0.15+sr(i*7)*0.2).toFixed(1),benchmark:+(3.0-i*0.1+sr(i*11)*0.15).toFixed(1),target15:1.5,target2c:2.0}));
const ITR_DIST=[{range:'<1.5C',count:0},{range:'1.5-2.0C',count:0},{range:'2.0-2.5C',count:0},{range:'2.5-3.0C',count:0},{range:'3.0-3.5C',count:0},{range:'>3.5C',count:0}];
COMPANIES.forEach(c=>{if(c.itr<1.5)ITR_DIST[0].count++;else if(c.itr<2)ITR_DIST[1].count++;else if(c.itr<2.5)ITR_DIST[2].count++;else if(c.itr<3)ITR_DIST[3].count++;else if(c.itr<3.5)ITR_DIST[4].count++;else ITR_DIST[5].count++;});

export default function TemperatureAlignmentPage(){
  const[tab,setTab]=useState(0);const[search,setSearch]=useState('');const[sectorF,setSectorF]=useState('All');const[sortCol,setSortCol]=useState('itr');const[sortDir,setSortDir]=useState('asc');const[page,setPage]=useState(1);const[selected,setSelected]=useState(null);
  const filtered=useMemo(()=>{let d=[...COMPANIES];if(search)d=d.filter(r=>r.name.toLowerCase().includes(search.toLowerCase()));if(sectorF!=='All')d=d.filter(r=>r.sector===sectorF);d.sort((a,b)=>sortDir==='asc'?(a[sortCol]>b[sortCol]?1:-1):(a[sortCol]<b[sortCol]?1:-1));return d;},[search,sectorF,sortCol,sortDir]);
  const paged=useMemo(()=>filtered.slice((page-1)*PAGE,page*PAGE),[filtered,page]);const totalPages=Math.ceil(filtered.length/PAGE);
  const doSort=col=>{if(sortCol===col)setSortDir(d=>d==='asc'?'desc':'asc');else{setSortCol(col);setSortDir('desc');}setPage(1);};
  const stats=useMemo(()=>({count:filtered.length,avgITR:(filtered.reduce((s,r)=>s+r.itr,0)/filtered.length||0).toFixed(1),aligned:filtered.filter(r=>r.alignment==='1.5C Aligned'||r.alignment==='Below 2C').length,sbtiApproved:filtered.filter(r=>r.sbtiStatus==='Approved').length,avgCredibility:(filtered.reduce((s,r)=>s+r.credibilityScore,0)/filtered.length||0).toFixed(0)}),[filtered]);
  const sectorITR=useMemo(()=>{const m={};COMPANIES.forEach(r=>{if(!m[r.sector])m[r.sector]={s:r.sector,itr:0,n:0};m[r.sector].itr+=r.itr;m[r.sector].n++;});return Object.values(m).map(s=>({sector:s.s,itr:+(s.itr/s.n).toFixed(1)})).sort((a,b)=>b.itr-a.itr);},[]);
  const alignDist=useMemo(()=>{const order=['1.5C Aligned','Below 2C','2C','Above 2C','Not Aligned'];const m={};filtered.forEach(r=>{m[r.alignment]=(m[r.alignment]||0)+1;});return order.filter(k=>m[k]).map(k=>({name:k,value:m[k]}));},[filtered]);
  const exportCSV=useCallback((data,fn)=>{if(!data.length)return;const keys=Object.keys(data[0]);const csv=[keys.join(','),...data.map(r=>keys.map(k=>`"${r[k]}"`).join(','))].join('\n');const b=new Blob([csv],{type:'text/csv'});const u=URL.createObjectURL(b);const a=document.createElement('a');a.href=u;a.download=fn;a.click();URL.revokeObjectURL(u);},[]);
  const si=(col,cur,dir)=>cur===col?(dir==='asc'?' \u25B2':' \u25BC'):' \u25CB';
  const thS={padding:'8px 10px',fontSize:11,fontFamily:T.mono,color:T.textSec,cursor:'pointer',borderBottom:`1px solid ${T.border}`,whiteSpace:'nowrap',userSelect:'none',textAlign:'left',background:T.surfaceH};const tdS={padding:'7px 10px',fontSize:12,fontFamily:T.font,borderBottom:`1px solid ${T.border}`,color:T.text};const inpS={padding:'6px 12px',border:`1px solid ${T.border}`,borderRadius:6,fontSize:12,fontFamily:T.font,background:T.surface,color:T.text,outline:'none',width:220};const selS={padding:'6px 10px',border:`1px solid ${T.border}`,borderRadius:6,fontSize:11,fontFamily:T.font,background:T.surface,color:T.text};
  const btnS=a=>({padding:'6px 16px',border:`1px solid ${a?ACCENT:T.border}`,borderRadius:6,fontSize:12,fontFamily:T.font,background:a?ACCENT:T.surface,color:a?'#fff':T.text,cursor:'pointer',fontWeight:a?600:400});const pgB={padding:'4px 10px',border:`1px solid ${T.border}`,borderRadius:4,fontSize:11,cursor:'pointer',background:T.surface,color:T.text};const cS={background:T.surface,border:`1px solid ${T.border}`,borderRadius:10,padding:16};
  const kpi=(l,v,c)=>(<div style={{background:T.surface,border:`1px solid ${T.border}`,borderRadius:10,padding:'14px 18px',flex:1,minWidth:140}}><div style={{fontSize:10,color:T.textMut,fontFamily:T.mono,textTransform:'uppercase',letterSpacing:1}}>{l}</div><div style={{fontSize:22,fontWeight:700,color:c||T.navy,marginTop:4}}>{v}</div></div>);
  const itrBdg=v=>({background:v<1.5?'rgba(22,163,74,0.12)':v<2?'rgba(22,163,74,0.08)':v<2.5?'rgba(197,169,106,0.15)':v<3?'rgba(217,119,6,0.12)':'rgba(220,38,38,0.12)',color:v<1.5?T.green:v<2?'#15803d':v<2.5?T.gold:v<3?T.amber:T.red,padding:'2px 8px',borderRadius:4,fontSize:11,fontWeight:600,fontFamily:T.mono});
  const Panel=({item,onClose})=>{if(!item)return null;return(<div style={{position:'fixed',top:0,right:0,width:440,height:'100vh',background:T.surface,borderLeft:`2px solid ${ACCENT}`,zIndex:1000,overflowY:'auto',boxShadow:'-4px 0 24px rgba(0,0,0,0.10)'}}><div style={{padding:'20px 24px',borderBottom:`1px solid ${T.border}`,display:'flex',justifyContent:'space-between',alignItems:'center'}}><div style={{fontSize:16,fontWeight:700,color:T.navy}}>{item.name}</div><button onClick={onClose} style={{background:'none',border:'none',fontSize:20,cursor:'pointer',color:T.textMut}}>x</button></div><div style={{padding:'16px 24px'}}><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:10}}>{[['ITR',item.itr+'\u00B0C'],['Alignment',item.alignment],['Scope 1',item.scope1Intensity+' tCO2'],['Scope 2',item.scope2Intensity+' tCO2'],['Scope 3',item.scope3Intensity+' tCO2'],['Reduction Target',item.reductionTarget+'%'],['Target Year',item.targetYear],['SBTi Status',item.sbtiStatus],['Budget Remaining',item.budgetRemaining+'%'],['Carbon Budget',item.carbonBudget+' MtCO2'],['Trajectory',item.emissionsTrajectory],['Net Zero',item.netZeroCommit],['Green Rev.',item.greenRevPct+'%'],['Transition Plan',item.transitionPlan],['Credibility',item.credibilityScore+'/100']].map(([k,v],i)=>(<div key={i} style={{background:T.surfaceH,borderRadius:6,padding:'8px 12px'}}><div style={{fontSize:10,color:T.textMut,fontFamily:T.mono}}>{k}</div><div style={{fontSize:14,fontWeight:600,color:T.navy,marginTop:2}}>{v}</div></div>))}</div></div></div>);};
  const renderDash=()=>(<div>
    <div style={{display:'flex',gap:12,marginBottom:20,flexWrap:'wrap'}}>{kpi('Companies',stats.count)}{kpi('Portfolio ITR',stats.avgITR+'\u00B0C')}{kpi('Paris Aligned',stats.aligned+'/'+stats.count)}{kpi('SBTi Approved',stats.sbtiApproved)}{kpi('Avg Credibility',stats.avgCredibility+'/100')}</div>
    <div style={{display:'flex',gap:12,marginBottom:16,alignItems:'center'}}><input value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}} placeholder="Search companies..." style={inpS}/><select value={sectorF} onChange={e=>{setSectorF(e.target.value);setPage(1);}} style={selS}>{SECTORS.map(s=><option key={s}>{s}</option>)}</select><button onClick={()=>exportCSV(filtered,'temperature_alignment.csv')} style={btnS(false)}>Export CSV</button></div>
    <div style={{overflowX:'auto',...cS,padding:0}}><table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr>{[['name','Company'],['sector','Sector'],['itr','ITR'],['alignment','Alignment'],['scope1Intensity','S1'],['reductionTarget','Target%'],['sbtiStatus','SBTi'],['credibilityScore','Cred.']].map(([k,l])=><th key={k} onClick={()=>doSort(k)} style={thS}>{l}{si(k,sortCol,sortDir)}</th>)}</tr></thead>
      <tbody>{paged.map(r=><tr key={r.id} onClick={()=>setSelected(r)} style={{cursor:'pointer',background:selected?.id===r.id?T.surfaceH:'transparent'}}><td style={tdS}><span style={{fontWeight:600}}>{r.name}</span></td><td style={tdS}>{r.sector}</td><td style={tdS}><span style={itrBdg(r.itr)}>{r.itr}\u00B0C</span></td><td style={tdS}>{r.alignment}</td><td style={tdS}>{r.scope1Intensity}</td><td style={tdS}>{r.reductionTarget}%</td><td style={tdS}>{r.sbtiStatus}</td><td style={tdS}>{r.credibilityScore}</td></tr>)}</tbody></table></div>
    {totalPages>1&&<div style={{display:'flex',gap:6,marginTop:12,justifyContent:'center'}}><button onClick={()=>setPage(p=>Math.max(1,p-1))} disabled={page===1} style={pgB}>&laquo;</button><span style={{fontSize:11,color:T.textSec,fontFamily:T.mono}}>Page {page}/{totalPages}</span><button onClick={()=>setPage(p=>Math.min(totalPages,p+1))} disabled={page===totalPages} style={pgB}>&raquo;</button></div>}
    <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16,marginTop:20}}>
      <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>ITR Distribution</div><ResponsiveContainer width="100%" height={260}><BarChart data={ITR_DIST}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="range" tick={{fontSize:9,fill:T.textSec}}/><YAxis tick={{fontSize:9,fill:T.textSec}}/><Tooltip {...tip}/><Bar dataKey="count" radius={[4,4,0,0]}>{ITR_DIST.map((_,i)=><Cell key={i} fill={[T.green,'#15803d',T.gold,T.amber,T.red,'#991b1b'][i]}/>)}</Bar></BarChart></ResponsiveContainer></div>
      <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Alignment Breakdown</div><ResponsiveContainer width="100%" height={260}><PieChart><Pie data={alignDist} cx="50%" cy="50%" outerRadius={90} dataKey="value" label={({name,value})=>`${name}: ${value}`}>{alignDist.map((_,i)=><Cell key={i} fill={[T.green,'#15803d',T.gold,T.amber,T.red][i]}/>)}</Pie><Tooltip {...tip}/></PieChart></ResponsiveContainer></div>
    </div></div>);
  const renderCompany=()=>(<div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16}}>
    <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Companies by ITR (Worst 15)</div><ResponsiveContainer width="100%" height={350}><BarChart data={[...COMPANIES].sort((a,b)=>b.itr-a.itr).slice(0,15)} layout="vertical"><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis type="number" tick={{fontSize:9,fill:T.textSec}}/><YAxis type="category" dataKey="name" tick={{fontSize:8,fill:T.textSec}} width={90}/><Tooltip {...tip}/><Bar dataKey="itr" radius={[0,4,4,0]}>{[...COMPANIES].sort((a,b)=>b.itr-a.itr).slice(0,15).map((c,j)=><Cell key={j} fill={c.itr>2.5?T.red:c.itr>2?T.amber:T.gold}/>)}</Bar></BarChart></ResponsiveContainer></div>
    <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Credibility vs ITR</div><ResponsiveContainer width="100%" height={350}><ScatterChart><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="x" name="Credibility" tick={{fontSize:9,fill:T.textSec}}/><YAxis dataKey="y" name="ITR" tick={{fontSize:9,fill:T.textSec}}/><Tooltip {...tip}/><Scatter data={filtered.map(c=>({name:c.name,x:c.credibilityScore,y:c.itr}))} fill={ACCENT} fillOpacity={0.5}/></ScatterChart></ResponsiveContainer></div>
  </div></div>);
  const renderPathway=()=>(<div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16}}>
    <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Portfolio Temperature Pathway</div><ResponsiveContainer width="100%" height={300}><LineChart data={PATHWAY}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="year" tick={{fontSize:9,fill:T.textSec}}/><YAxis tick={{fontSize:9,fill:T.textSec}} domain={[1,3.5]}/><Tooltip {...tip}/><Line type="monotone" dataKey="portfolio" stroke={ACCENT} strokeWidth={2} name="Portfolio"/><Line type="monotone" dataKey="benchmark" stroke={T.textMut} strokeWidth={2} name="Benchmark" strokeDasharray="5 5"/><Line type="monotone" dataKey="target15" stroke={T.green} strokeWidth={1} name="1.5\u00B0C" strokeDasharray="3 3"/><Line type="monotone" dataKey="target2c" stroke={T.amber} strokeWidth={1} name="2\u00B0C" strokeDasharray="3 3"/><Legend/></LineChart></ResponsiveContainer></div>
    <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>ITR by Sector</div><ResponsiveContainer width="100%" height={300}><BarChart data={sectorITR}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="sector" tick={{fontSize:8,fill:T.textSec}} angle={-25}/><YAxis tick={{fontSize:9,fill:T.textSec}} domain={[0,4]}/><Tooltip {...tip}/><Bar dataKey="itr" radius={[4,4,0,0]}>{sectorITR.map((s,j)=><Cell key={j} fill={s.itr>2.5?T.red:s.itr>2?T.amber:s.itr>1.5?T.gold:T.green}/>)}</Bar></BarChart></ResponsiveContainer></div>
  </div></div>);
  const renderMethod=()=>(<div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16}}>
    <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>SBTi Status Distribution</div><ResponsiveContainer width="100%" height={260}><PieChart><Pie data={['Approved','Committed','Near-term','None'].map(s=>({name:s,value:COMPANIES.filter(c=>c.sbtiStatus===s).length}))} cx="50%" cy="50%" outerRadius={90} dataKey="value" label={({name,value})=>`${name}: ${value}`}>{[T.green,ACCENT,T.amber,T.red].map((c,i)=><Cell key={i} fill={c}/>)}</Pie><Tooltip {...tip}/></PieChart></ResponsiveContainer></div>
    <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Emissions Trajectory</div><ResponsiveContainer width="100%" height={260}><PieChart><Pie data={['Declining','Flat','Rising'].map(s=>({name:s,value:COMPANIES.filter(c=>c.emissionsTrajectory===s).length}))} cx="50%" cy="50%" outerRadius={90} dataKey="value" label={({name,value})=>`${name}: ${value}`}>{[T.green,T.amber,T.red].map((c,i)=><Cell key={i} fill={c}/>)}</Pie><Tooltip {...tip}/></PieChart></ResponsiveContainer></div>
    <div style={{...cS,gridColumn:'1/3'}}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Transition Plan Quality vs Credibility</div><ResponsiveContainer width="100%" height={260}><BarChart data={['Comprehensive','Partial','None'].map(p=>({plan:p,count:COMPANIES.filter(c=>c.transitionPlan===p).length,avgCred:Math.round(COMPANIES.filter(c=>c.transitionPlan===p).reduce((s,c)=>s+c.credibilityScore,0)/(COMPANIES.filter(c=>c.transitionPlan===p).length||1))}))}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="plan" tick={{fontSize:9,fill:T.textSec}}/><YAxis tick={{fontSize:9,fill:T.textSec}}/><Tooltip {...tip}/><Bar dataKey="count" fill={T.navy} name="Count"/><Bar dataKey="avgCred" fill={T.gold} name="Avg Credibility"/><Legend/></BarChart></ResponsiveContainer></div>
  </div></div>);
  return(<div style={{padding:'24px 32px',fontFamily:T.font,background:T.bg,minHeight:'100vh'}}>
    <div style={{marginBottom:20}}><h1 style={{fontSize:22,fontWeight:700,color:T.navy,margin:0}}>Temperature Alignment</h1><p style={{fontSize:12,color:T.textSec,margin:'4px 0 0'}}>60 companies | ITR methodology, 1.5/2/3\u00B0C pathways, sector analysis</p></div>
    <div style={{display:'flex',gap:8,marginBottom:20}}>{TABS.map((t,i)=><button key={t} onClick={()=>setTab(i)} style={btnS(tab===i)}>{t}</button>)}</div>
    {tab===0&&renderDash()}{tab===1&&renderCompany()}{tab===2&&renderPathway()}{tab===3&&renderMethod()}
    <Panel item={selected} onClose={()=>setSelected(null)}/>
  </div>);
}