"""
Seed script — BRSR Core reference data for India's Top 1000 listed companies.

Inserts 25 Nifty/BSE500 companies (FY2024) with:
  - Section A/B/C status
  - P1–P9 principle scores
  - 15 BRSR Core KPIs (environmental, social, governance)
  - Overall readiness %
  - Assurance / CIN / exchange details

Run:
    cd backend
    python scripts/seed_brsr_data.py
"""

import os
import sys
from pathlib import Path

# ── path setup ────────────────────────────────────────────────────────────────
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

import psycopg2
import json
from datetime import datetime

DATABASE_URL = os.environ.get(
    "DATABASE_URL",
    "postgresql://postgres:postgres@localhost:5432/risk_analytics"
)

# ─────────────────────────────────────────────────────────────────────────────
# Reference data: India Top-25 listed companies — FY2024 BRSR
# Columns order:
#   entity_name, cin, bse_scrip_code, nse_symbol, listed_exchange,
#   is_mandatory, brsr_core_applicable, brsr_core_assured, assurance_provider, assurance_standard,
#   section_a_status, section_c_status,
#   p1,p2,p3,p4,p5,p6,p7,p8,p9  (scores 0-10 each)
#   employee_permanent, employee_contract, turnover_inr_cr, net_worth_inr_cr,
#   scope1, scope2, scope3, energy_gj, renewable_pct,
#   water_intensity, waste_intensity,
#   csr_spend, women_mgmt_pct, attrition_pct, median_wage_ratio, training_hours,
#   ind_directors_pct, board_meetings, cybersecurity_incidents,
#   overall_readiness_pct, total_principles_disclosed, status
# ─────────────────────────────────────────────────────────────────────────────

COMPANIES = [
    # ── Conglomerates / Energy ─────────────────────────────────────────────────
    {
        "entity_name": "Reliance Industries Limited",
        "cin": "L17110MH1973PLC019786",
        "bse_scrip_code": "500325",
        "nse_symbol": "RELIANCE",
        "listed_exchange": "BOTH",
        "is_mandatory": True, "brsr_core_applicable": True, "brsr_core_assured": True,
        "assurance_provider": "Deloitte Haskins & Sells", "assurance_standard": "ISAE3000",
        "section_a_status": "published", "section_c_status": "published",
        "p1": 9, "p2": 9, "p3": 8, "p4": 8, "p5": 8, "p6": 8, "p7": 7, "p8": 9, "p9": 9,
        "emp_perm": 236334, "emp_contract": 32000,
        "turnover_inr_cr": 900000.0, "net_worth_inr_cr": 742000.0,
        "scope1": 44200.0, "scope2": 3800.0, "scope3": 210000.0,
        "energy_gj": 1950000.0, "renewable_pct": 8.2,
        "water_int": 1.84, "waste_int": 12.3,
        "csr_spend": 1591.0, "women_mgmt": 14.2, "attrition": 11.8, "wage_ratio": 0.61, "training_hrs": 42.0,
        "ind_dir_pct": 52.0, "board_meetings": 8, "cyber_incidents": 0,
        "overall_readiness": 89.0, "principles_disclosed": 9, "status": "published",
    },
    {
        "entity_name": "Tata Consultancy Services Limited",
        "cin": "L22210MH1995PLC084781",
        "bse_scrip_code": "532540",
        "nse_symbol": "TCS",
        "listed_exchange": "BOTH",
        "is_mandatory": True, "brsr_core_applicable": True, "brsr_core_assured": True,
        "assurance_provider": "EY India", "assurance_standard": "AA1000AS",
        "section_a_status": "published", "section_c_status": "published",
        "p1": 10, "p2": 9, "p3": 9, "p4": 9, "p5": 9, "p6": 9, "p7": 8, "p8": 9, "p9": 9,
        "emp_perm": 601546, "emp_contract": 4200,
        "turnover_inr_cr": 240893.0, "net_worth_inr_cr": 99000.0,
        "scope1": 230.0, "scope2": 1850.0, "scope3": 48000.0,
        "energy_gj": 98000.0, "renewable_pct": 62.4,
        "water_int": 0.38, "waste_int": 0.9,
        "csr_spend": 706.0, "women_mgmt": 35.7, "attrition": 12.5, "wage_ratio": 0.72, "training_hrs": 57.0,
        "ind_dir_pct": 58.0, "board_meetings": 7, "cyber_incidents": 0,
        "overall_readiness": 96.0, "principles_disclosed": 9, "status": "published",
    },
    {
        "entity_name": "Infosys Limited",
        "cin": "L85110KA1981PLC013115",
        "bse_scrip_code": "500209",
        "nse_symbol": "INFY",
        "listed_exchange": "BOTH",
        "is_mandatory": True, "brsr_core_applicable": True, "brsr_core_assured": True,
        "assurance_provider": "KPMG India", "assurance_standard": "ISAE3000",
        "section_a_status": "published", "section_c_status": "published",
        "p1": 10, "p2": 9, "p3": 9, "p4": 9, "p5": 9, "p6": 9, "p7": 8, "p8": 9, "p9": 9,
        "emp_perm": 317240, "emp_contract": 2800,
        "turnover_inr_cr": 153670.0, "net_worth_inr_cr": 69000.0,
        "scope1": 134.0, "scope2": 690.0, "scope3": 35000.0,
        "energy_gj": 42000.0, "renewable_pct": 85.0,
        "water_int": 0.32, "waste_int": 0.7,
        "csr_spend": 397.0, "women_mgmt": 39.4, "attrition": 12.9, "wage_ratio": 0.75, "training_hrs": 53.0,
        "ind_dir_pct": 60.0, "board_meetings": 7, "cyber_incidents": 0,
        "overall_readiness": 95.0, "principles_disclosed": 9, "status": "published",
    },
    {
        "entity_name": "HDFC Bank Limited",
        "cin": "L65920MH1994PLC080618",
        "bse_scrip_code": "500180",
        "nse_symbol": "HDFCBANK",
        "listed_exchange": "BOTH",
        "is_mandatory": True, "brsr_core_applicable": True, "brsr_core_assured": True,
        "assurance_provider": "PwC India", "assurance_standard": "ISAE3000",
        "section_a_status": "published", "section_c_status": "published",
        "p1": 9, "p2": 8, "p3": 8, "p4": 8, "p5": 8, "p6": 7, "p7": 7, "p8": 9, "p9": 8,
        "emp_perm": 177000, "emp_contract": 5000,
        "turnover_inr_cr": 231200.0, "net_worth_inr_cr": 270000.0,
        "scope1": 42.0, "scope2": 580.0, "scope3": 28000.0,
        "energy_gj": 18000.0, "renewable_pct": 18.0,
        "water_int": 0.12, "waste_int": 0.5,
        "csr_spend": 945.0, "women_mgmt": 22.1, "attrition": 19.3, "wage_ratio": 0.58, "training_hrs": 38.0,
        "ind_dir_pct": 63.0, "board_meetings": 9, "cyber_incidents": 1,
        "overall_readiness": 84.0, "principles_disclosed": 9, "status": "published",
    },
    {
        "entity_name": "ICICI Bank Limited",
        "cin": "L65190GJ1994PLC021012",
        "bse_scrip_code": "532174",
        "nse_symbol": "ICICIBANK",
        "listed_exchange": "BOTH",
        "is_mandatory": True, "brsr_core_applicable": True, "brsr_core_assured": True,
        "assurance_provider": "Deloitte Haskins & Sells", "assurance_standard": "ISAE3000",
        "section_a_status": "published", "section_c_status": "published",
        "p1": 9, "p2": 8, "p3": 8, "p4": 8, "p5": 8, "p6": 7, "p7": 7, "p8": 9, "p9": 8,
        "emp_perm": 131902, "emp_contract": 3800,
        "turnover_inr_cr": 162700.0, "net_worth_inr_cr": 195000.0,
        "scope1": 38.0, "scope2": 490.0, "scope3": 24000.0,
        "energy_gj": 15000.0, "renewable_pct": 22.0,
        "water_int": 0.09, "waste_int": 0.4,
        "csr_spend": 810.0, "women_mgmt": 25.8, "attrition": 16.7, "wage_ratio": 0.60, "training_hrs": 36.0,
        "ind_dir_pct": 67.0, "board_meetings": 8, "cyber_incidents": 0,
        "overall_readiness": 83.0, "principles_disclosed": 9, "status": "published",
    },
    {
        "entity_name": "Wipro Limited",
        "cin": "L32102KA1945PLC020800",
        "bse_scrip_code": "507685",
        "nse_symbol": "WIPRO",
        "listed_exchange": "BOTH",
        "is_mandatory": True, "brsr_core_applicable": True, "brsr_core_assured": True,
        "assurance_provider": "EY India", "assurance_standard": "AA1000AS",
        "section_a_status": "published", "section_c_status": "published",
        "p1": 9, "p2": 9, "p3": 9, "p4": 9, "p5": 9, "p6": 9, "p7": 7, "p8": 8, "p9": 8,
        "emp_perm": 234054, "emp_contract": 3200,
        "turnover_inr_cr": 90487.0, "net_worth_inr_cr": 71000.0,
        "scope1": 98.0, "scope2": 480.0, "scope3": 22000.0,
        "energy_gj": 21000.0, "renewable_pct": 70.0,
        "water_int": 0.28, "waste_int": 0.8,
        "csr_spend": 296.0, "women_mgmt": 36.2, "attrition": 14.1, "wage_ratio": 0.70, "training_hrs": 48.0,
        "ind_dir_pct": 55.0, "board_meetings": 7, "cyber_incidents": 0,
        "overall_readiness": 91.0, "principles_disclosed": 9, "status": "published",
    },
    {
        "entity_name": "HCL Technologies Limited",
        "cin": "L74140DL1991PLC046369",
        "bse_scrip_code": "532281",
        "nse_symbol": "HCLTECH",
        "listed_exchange": "BOTH",
        "is_mandatory": True, "brsr_core_applicable": True, "brsr_core_assured": True,
        "assurance_provider": "Bureau Veritas India", "assurance_standard": "ISAE3000",
        "section_a_status": "published", "section_c_status": "published",
        "p1": 9, "p2": 8, "p3": 8, "p4": 8, "p5": 8, "p6": 8, "p7": 7, "p8": 8, "p9": 8,
        "emp_perm": 225944, "emp_contract": 4100,
        "turnover_inr_cr": 104638.0, "net_worth_inr_cr": 68000.0,
        "scope1": 76.0, "scope2": 390.0, "scope3": 19800.0,
        "energy_gj": 17500.0, "renewable_pct": 58.0,
        "water_int": 0.25, "waste_int": 0.6,
        "csr_spend": 229.0, "women_mgmt": 30.4, "attrition": 13.0, "wage_ratio": 0.68, "training_hrs": 44.0,
        "ind_dir_pct": 50.0, "board_meetings": 6, "cyber_incidents": 0,
        "overall_readiness": 87.0, "principles_disclosed": 9, "status": "published",
    },
    # ── Industrials / Auto ────────────────────────────────────────────────────
    {
        "entity_name": "Larsen & Toubro Limited",
        "cin": "L99999MH1946PLC004768",
        "bse_scrip_code": "500510",
        "nse_symbol": "LT",
        "listed_exchange": "BOTH",
        "is_mandatory": True, "brsr_core_applicable": True, "brsr_core_assured": True,
        "assurance_provider": "DNV India", "assurance_standard": "ISAE3000",
        "section_a_status": "published", "section_c_status": "published",
        "p1": 9, "p2": 8, "p3": 8, "p4": 7, "p5": 8, "p6": 8, "p7": 7, "p8": 9, "p9": 8,
        "emp_perm": 56274, "emp_contract": 125000,
        "turnover_inr_cr": 221550.0, "net_worth_inr_cr": 95000.0,
        "scope1": 1840.0, "scope2": 620.0, "scope3": 48000.0,
        "energy_gj": 31000.0, "renewable_pct": 12.0,
        "water_int": 0.95, "waste_int": 8.2,
        "csr_spend": 374.0, "women_mgmt": 12.1, "attrition": 8.2, "wage_ratio": 0.48, "training_hrs": 52.0,
        "ind_dir_pct": 50.0, "board_meetings": 7, "cyber_incidents": 0,
        "overall_readiness": 82.0, "principles_disclosed": 9, "status": "published",
    },
    {
        "entity_name": "Mahindra & Mahindra Limited",
        "cin": "L65990MH1945PLC004558",
        "bse_scrip_code": "500520",
        "nse_symbol": "M&M",
        "listed_exchange": "BOTH",
        "is_mandatory": True, "brsr_core_applicable": True, "brsr_core_assured": True,
        "assurance_provider": "EY India", "assurance_standard": "ISAE3000",
        "section_a_status": "published", "section_c_status": "published",
        "p1": 9, "p2": 9, "p3": 8, "p4": 8, "p5": 8, "p6": 9, "p7": 7, "p8": 9, "p9": 8,
        "emp_perm": 40000, "emp_contract": 22000,
        "turnover_inr_cr": 135270.0, "net_worth_inr_cr": 60000.0,
        "scope1": 740.0, "scope2": 410.0, "scope3": 65000.0,
        "energy_gj": 22000.0, "renewable_pct": 35.0,
        "water_int": 1.10, "waste_int": 6.8,
        "csr_spend": 272.0, "women_mgmt": 18.6, "attrition": 9.8, "wage_ratio": 0.52, "training_hrs": 40.0,
        "ind_dir_pct": 55.0, "board_meetings": 7, "cyber_incidents": 0,
        "overall_readiness": 84.0, "principles_disclosed": 9, "status": "published",
    },
    {
        "entity_name": "Maruti Suzuki India Limited",
        "cin": "L34103DL1981PLC011375",
        "bse_scrip_code": "532500",
        "nse_symbol": "MARUTI",
        "listed_exchange": "BOTH",
        "is_mandatory": True, "brsr_core_applicable": True, "brsr_core_assured": False,
        "assurance_provider": None, "assurance_standard": None,
        "section_a_status": "published", "section_c_status": "submitted",
        "p1": 8, "p2": 8, "p3": 8, "p4": 7, "p5": 7, "p6": 8, "p7": 6, "p8": 8, "p9": 7,
        "emp_perm": 22500, "emp_contract": 18000,
        "turnover_inr_cr": 139055.0, "net_worth_inr_cr": 52000.0,
        "scope1": 1120.0, "scope2": 520.0, "scope3": 82000.0,
        "energy_gj": 28000.0, "renewable_pct": 24.0,
        "water_int": 1.42, "waste_int": 10.4,
        "csr_spend": 181.0, "women_mgmt": 10.4, "attrition": 7.2, "wage_ratio": 0.49, "training_hrs": 38.0,
        "ind_dir_pct": 50.0, "board_meetings": 6, "cyber_incidents": 0,
        "overall_readiness": 76.0, "principles_disclosed": 9, "status": "submitted",
    },
    {
        "entity_name": "Tata Motors Limited",
        "cin": "L28920MH1945PLC004520",
        "bse_scrip_code": "500570",
        "nse_symbol": "TATAMOTORS",
        "listed_exchange": "BOTH",
        "is_mandatory": True, "brsr_core_applicable": True, "brsr_core_assured": True,
        "assurance_provider": "KPMG India", "assurance_standard": "ISAE3000",
        "section_a_status": "published", "section_c_status": "published",
        "p1": 8, "p2": 8, "p3": 8, "p4": 8, "p5": 8, "p6": 8, "p7": 7, "p8": 8, "p9": 8,
        "emp_perm": 84000, "emp_contract": 36000,
        "turnover_inr_cr": 438487.0, "net_worth_inr_cr": 55000.0,
        "scope1": 1680.0, "scope2": 640.0, "scope3": 95000.0,
        "energy_gj": 40000.0, "renewable_pct": 18.0,
        "water_int": 1.22, "waste_int": 9.1,
        "csr_spend": 211.0, "women_mgmt": 14.8, "attrition": 10.6, "wage_ratio": 0.50, "training_hrs": 36.0,
        "ind_dir_pct": 60.0, "board_meetings": 8, "cyber_incidents": 0,
        "overall_readiness": 80.0, "principles_disclosed": 9, "status": "published",
    },
    # ── Energy / Utilities ─────────────────────────────────────────────────────
    {
        "entity_name": "NTPC Limited",
        "cin": "L40101DL1975GOI007966",
        "bse_scrip_code": "532555",
        "nse_symbol": "NTPC",
        "listed_exchange": "BOTH",
        "is_mandatory": True, "brsr_core_applicable": True, "brsr_core_assured": True,
        "assurance_provider": "Bureau Veritas India", "assurance_standard": "ISAE3000",
        "section_a_status": "published", "section_c_status": "published",
        "p1": 8, "p2": 8, "p3": 8, "p4": 8, "p5": 7, "p6": 7, "p7": 8, "p8": 9, "p9": 7,
        "emp_perm": 23000, "emp_contract": 14000,
        "turnover_inr_cr": 177090.0, "net_worth_inr_cr": 148000.0,
        "scope1": 248000.0, "scope2": 1200.0, "scope3": 18000.0,
        "energy_gj": 1280000.0, "renewable_pct": 16.0,
        "water_int": 32.0, "waste_int": 45.0,
        "csr_spend": 540.0, "women_mgmt": 9.8, "attrition": 3.2, "wage_ratio": 0.54, "training_hrs": 62.0,
        "ind_dir_pct": 50.0, "board_meetings": 8, "cyber_incidents": 0,
        "overall_readiness": 78.0, "principles_disclosed": 9, "status": "published",
    },
    {
        "entity_name": "Power Grid Corporation of India Limited",
        "cin": "L40101DL1989GOI038121",
        "bse_scrip_code": "532898",
        "nse_symbol": "POWERGRID",
        "listed_exchange": "BOTH",
        "is_mandatory": True, "brsr_core_applicable": True, "brsr_core_assured": False,
        "assurance_provider": None, "assurance_standard": None,
        "section_a_status": "published", "section_c_status": "submitted",
        "p1": 8, "p2": 7, "p3": 7, "p4": 7, "p5": 7, "p6": 7, "p7": 8, "p8": 8, "p9": 7,
        "emp_perm": 10200, "emp_contract": 5800,
        "turnover_inr_cr": 48418.0, "net_worth_inr_cr": 80000.0,
        "scope1": 1400.0, "scope2": 980.0, "scope3": 8200.0,
        "energy_gj": 58000.0, "renewable_pct": 8.0,
        "water_int": 0.48, "waste_int": 3.2,
        "csr_spend": 242.0, "women_mgmt": 10.2, "attrition": 2.1, "wage_ratio": 0.55, "training_hrs": 55.0,
        "ind_dir_pct": 50.0, "board_meetings": 7, "cyber_incidents": 0,
        "overall_readiness": 72.0, "principles_disclosed": 8, "status": "submitted",
    },
    {
        "entity_name": "Coal India Limited",
        "cin": "L10101WB1973GOI028844",
        "bse_scrip_code": "533278",
        "nse_symbol": "COALINDIA",
        "listed_exchange": "BOTH",
        "is_mandatory": True, "brsr_core_applicable": True, "brsr_core_assured": False,
        "assurance_provider": None, "assurance_standard": None,
        "section_a_status": "published", "section_c_status": "submitted",
        "p1": 7, "p2": 6, "p3": 7, "p4": 7, "p5": 6, "p6": 5, "p7": 8, "p8": 8, "p9": 6,
        "emp_perm": 248922, "emp_contract": 48000,
        "turnover_inr_cr": 141779.0, "net_worth_inr_cr": 48000.0,
        "scope1": 38400.0, "scope2": 2800.0, "scope3": 180000.0,
        "energy_gj": 142000.0, "renewable_pct": 4.0,
        "water_int": 8.60, "waste_int": 280.0,
        "csr_spend": 612.0, "women_mgmt": 8.4, "attrition": 4.1, "wage_ratio": 0.62, "training_hrs": 48.0,
        "ind_dir_pct": 50.0, "board_meetings": 8, "cyber_incidents": 0,
        "overall_readiness": 62.0, "principles_disclosed": 9, "status": "submitted",
    },
    # ── FMCG / Consumer ───────────────────────────────────────────────────────
    {
        "entity_name": "Hindustan Unilever Limited",
        "cin": "L15140MH1933PLC002030",
        "bse_scrip_code": "500696",
        "nse_symbol": "HINDUNILVR",
        "listed_exchange": "BOTH",
        "is_mandatory": True, "brsr_core_applicable": True, "brsr_core_assured": True,
        "assurance_provider": "PwC India", "assurance_standard": "AA1000AS",
        "section_a_status": "published", "section_c_status": "published",
        "p1": 10, "p2": 10, "p3": 9, "p4": 9, "p5": 9, "p6": 10, "p7": 8, "p8": 10, "p9": 10,
        "emp_perm": 21000, "emp_contract": 5400,
        "turnover_inr_cr": 60580.0, "net_worth_inr_cr": 10800.0,
        "scope1": 420.0, "scope2": 280.0, "scope3": 18000.0,
        "energy_gj": 12800.0, "renewable_pct": 88.0,
        "water_int": 0.62, "waste_int": 1.2,
        "csr_spend": 133.0, "women_mgmt": 42.0, "attrition": 8.9, "wage_ratio": 0.82, "training_hrs": 40.0,
        "ind_dir_pct": 60.0, "board_meetings": 7, "cyber_incidents": 0,
        "overall_readiness": 97.0, "principles_disclosed": 9, "status": "published",
    },
    {
        "entity_name": "ITC Limited",
        "cin": "L16005WB1910PLC001985",
        "bse_scrip_code": "500875",
        "nse_symbol": "ITC",
        "listed_exchange": "BOTH",
        "is_mandatory": True, "brsr_core_applicable": True, "brsr_core_assured": True,
        "assurance_provider": "DNV India", "assurance_standard": "ISAE3000",
        "section_a_status": "published", "section_c_status": "published",
        "p1": 10, "p2": 9, "p3": 9, "p4": 9, "p5": 9, "p6": 10, "p7": 9, "p8": 10, "p9": 9,
        "emp_perm": 28980, "emp_contract": 18000,
        "turnover_inr_cr": 72500.0, "net_worth_inr_cr": 55000.0,
        "scope1": 320.0, "scope2": 0.0, "scope3": 12000.0,
        "energy_gj": 38000.0, "renewable_pct": 100.0,
        "water_int": 0.52, "waste_int": 0.8,
        "csr_spend": 418.0, "women_mgmt": 28.4, "attrition": 7.6, "wage_ratio": 0.80, "training_hrs": 56.0,
        "ind_dir_pct": 67.0, "board_meetings": 8, "cyber_incidents": 0,
        "overall_readiness": 98.0, "principles_disclosed": 9, "status": "published",
    },
    # ── Pharma / Healthcare ───────────────────────────────────────────────────
    {
        "entity_name": "Sun Pharmaceutical Industries Limited",
        "cin": "L24230GJ1993PLC019050",
        "bse_scrip_code": "524715",
        "nse_symbol": "SUNPHARMA",
        "listed_exchange": "BOTH",
        "is_mandatory": True, "brsr_core_applicable": True, "brsr_core_assured": True,
        "assurance_provider": "EY India", "assurance_standard": "ISAE3000",
        "section_a_status": "published", "section_c_status": "published",
        "p1": 8, "p2": 9, "p3": 8, "p4": 8, "p5": 8, "p6": 8, "p7": 7, "p8": 8, "p9": 8,
        "emp_perm": 43000, "emp_contract": 8000,
        "turnover_inr_cr": 48110.0, "net_worth_inr_cr": 62000.0,
        "scope1": 380.0, "scope2": 620.0, "scope3": 12000.0,
        "energy_gj": 22000.0, "renewable_pct": 28.0,
        "water_int": 4.80, "waste_int": 14.0,
        "csr_spend": 80.0, "women_mgmt": 22.0, "attrition": 11.2, "wage_ratio": 0.60, "training_hrs": 28.0,
        "ind_dir_pct": 55.0, "board_meetings": 6, "cyber_incidents": 0,
        "overall_readiness": 80.0, "principles_disclosed": 9, "status": "published",
    },
    {
        "entity_name": "Dr. Reddy's Laboratories Limited",
        "cin": "L85195TG1984PLC004507",
        "bse_scrip_code": "500124",
        "nse_symbol": "DRREDDY",
        "listed_exchange": "BOTH",
        "is_mandatory": True, "brsr_core_applicable": True, "brsr_core_assured": True,
        "assurance_provider": "DNV India", "assurance_standard": "AA1000AS",
        "section_a_status": "published", "section_c_status": "published",
        "p1": 9, "p2": 9, "p3": 8, "p4": 8, "p5": 8, "p6": 8, "p7": 7, "p8": 8, "p9": 9,
        "emp_perm": 27000, "emp_contract": 5000,
        "turnover_inr_cr": 28800.0, "net_worth_inr_cr": 24000.0,
        "scope1": 180.0, "scope2": 340.0, "scope3": 9800.0,
        "energy_gj": 14000.0, "renewable_pct": 38.0,
        "water_int": 3.20, "waste_int": 11.0,
        "csr_spend": 58.0, "women_mgmt": 24.0, "attrition": 10.8, "wage_ratio": 0.62, "training_hrs": 30.0,
        "ind_dir_pct": 60.0, "board_meetings": 6, "cyber_incidents": 0,
        "overall_readiness": 82.0, "principles_disclosed": 9, "status": "published",
    },
    # ── Telecoms / Media ──────────────────────────────────────────────────────
    {
        "entity_name": "Bharti Airtel Limited",
        "cin": "L74899DL1995PLC070609",
        "bse_scrip_code": "532454",
        "nse_symbol": "BHARTIARTL",
        "listed_exchange": "BOTH",
        "is_mandatory": True, "brsr_core_applicable": True, "brsr_core_assured": True,
        "assurance_provider": "KPMG India", "assurance_standard": "ISAE3000",
        "section_a_status": "published", "section_c_status": "published",
        "p1": 8, "p2": 8, "p3": 8, "p4": 8, "p5": 8, "p6": 7, "p7": 7, "p8": 8, "p9": 8,
        "emp_perm": 18654, "emp_contract": 12000,
        "turnover_inr_cr": 149982.0, "net_worth_inr_cr": 80000.0,
        "scope1": 480.0, "scope2": 2800.0, "scope3": 32000.0,
        "energy_gj": 78000.0, "renewable_pct": 18.0,
        "water_int": 0.14, "waste_int": 2.2,
        "csr_spend": 128.0, "women_mgmt": 14.8, "attrition": 22.0, "wage_ratio": 0.54, "training_hrs": 28.0,
        "ind_dir_pct": 50.0, "board_meetings": 7, "cyber_incidents": 2,
        "overall_readiness": 77.0, "principles_disclosed": 9, "status": "published",
    },
    # ── Metals / Mining ───────────────────────────────────────────────────────
    {
        "entity_name": "Tata Steel Limited",
        "cin": "L27100MH1907PLC000260",
        "bse_scrip_code": "500470",
        "nse_symbol": "TATASTEEL",
        "listed_exchange": "BOTH",
        "is_mandatory": True, "brsr_core_applicable": True, "brsr_core_assured": True,
        "assurance_provider": "DNV India", "assurance_standard": "ISAE3000",
        "section_a_status": "published", "section_c_status": "published",
        "p1": 8, "p2": 8, "p3": 8, "p4": 8, "p5": 7, "p6": 8, "p7": 7, "p8": 8, "p9": 7,
        "emp_perm": 78000, "emp_contract": 22000,
        "turnover_inr_cr": 234000.0, "net_worth_inr_cr": 72000.0,
        "scope1": 18200.0, "scope2": 2400.0, "scope3": 42000.0,
        "energy_gj": 520000.0, "renewable_pct": 10.0,
        "water_int": 6.40, "waste_int": 120.0,
        "csr_spend": 198.0, "women_mgmt": 12.2, "attrition": 6.4, "wage_ratio": 0.48, "training_hrs": 44.0,
        "ind_dir_pct": 60.0, "board_meetings": 7, "cyber_incidents": 0,
        "overall_readiness": 79.0, "principles_disclosed": 9, "status": "published",
    },
    {
        "entity_name": "JSW Steel Limited",
        "cin": "L27102MH1994PLC152925",
        "bse_scrip_code": "500228",
        "nse_symbol": "JSWSTEEL",
        "listed_exchange": "BOTH",
        "is_mandatory": True, "brsr_core_applicable": True, "brsr_core_assured": False,
        "assurance_provider": None, "assurance_standard": None,
        "section_a_status": "published", "section_c_status": "submitted",
        "p1": 7, "p2": 7, "p3": 7, "p4": 7, "p5": 7, "p6": 7, "p7": 6, "p8": 7, "p9": 7,
        "emp_perm": 42000, "emp_contract": 24000,
        "turnover_inr_cr": 164800.0, "net_worth_inr_cr": 48000.0,
        "scope1": 24000.0, "scope2": 3200.0, "scope3": 38000.0,
        "energy_gj": 480000.0, "renewable_pct": 8.0,
        "water_int": 5.80, "waste_int": 98.0,
        "csr_spend": 153.0, "women_mgmt": 10.4, "attrition": 7.8, "wage_ratio": 0.46, "training_hrs": 36.0,
        "ind_dir_pct": 50.0, "board_meetings": 7, "cyber_incidents": 0,
        "overall_readiness": 68.0, "principles_disclosed": 9, "status": "submitted",
    },
    # ── Real Estate / Infrastructure ──────────────────────────────────────────
    {
        "entity_name": "DLF Limited",
        "cin": "L70101HR1963PLC002484",
        "bse_scrip_code": "532868",
        "nse_symbol": "DLF",
        "listed_exchange": "BOTH",
        "is_mandatory": True, "brsr_core_applicable": True, "brsr_core_assured": False,
        "assurance_provider": None, "assurance_standard": None,
        "section_a_status": "published", "section_c_status": "draft",
        "p1": 7, "p2": 7, "p3": 7, "p4": 7, "p5": 6, "p6": 7, "p7": 6, "p8": 8, "p9": 7,
        "emp_perm": 4200, "emp_contract": 18000,
        "turnover_inr_cr": 6960.0, "net_worth_inr_cr": 28000.0,
        "scope1": 140.0, "scope2": 1800.0, "scope3": 22000.0,
        "energy_gj": 28000.0, "renewable_pct": 12.0,
        "water_int": 1.80, "waste_int": 4.2,
        "csr_spend": 42.0, "women_mgmt": 16.8, "attrition": 14.2, "wage_ratio": 0.45, "training_hrs": 24.0,
        "ind_dir_pct": 50.0, "board_meetings": 6, "cyber_incidents": 0,
        "overall_readiness": 64.0, "principles_disclosed": 9, "status": "draft",
    },
    # ── Banking / Finance ─────────────────────────────────────────────────────
    {
        "entity_name": "State Bank of India",
        "cin": "L64190MH1955GOI009513",
        "bse_scrip_code": "500112",
        "nse_symbol": "SBIN",
        "listed_exchange": "BOTH",
        "is_mandatory": True, "brsr_core_applicable": True, "brsr_core_assured": False,
        "assurance_provider": None, "assurance_standard": None,
        "section_a_status": "published", "section_c_status": "submitted",
        "p1": 8, "p2": 7, "p3": 7, "p4": 7, "p5": 7, "p6": 6, "p7": 8, "p8": 9, "p9": 7,
        "emp_perm": 232296, "emp_contract": 38000,
        "turnover_inr_cr": 368000.0, "net_worth_inr_cr": 310000.0,
        "scope1": 48.0, "scope2": 680.0, "scope3": 38000.0,
        "energy_gj": 22000.0, "renewable_pct": 10.0,
        "water_int": 0.08, "waste_int": 0.4,
        "csr_spend": 492.0, "women_mgmt": 21.4, "attrition": 3.8, "wage_ratio": 0.72, "training_hrs": 42.0,
        "ind_dir_pct": 50.0, "board_meetings": 8, "cyber_incidents": 1,
        "overall_readiness": 70.0, "principles_disclosed": 9, "status": "submitted",
    },
    {
        "entity_name": "Bajaj Finance Limited",
        "cin": "L65910MH1987PLC042961",
        "bse_scrip_code": "500034",
        "nse_symbol": "BAJFINANCE",
        "listed_exchange": "BOTH",
        "is_mandatory": True, "brsr_core_applicable": True, "brsr_core_assured": False,
        "assurance_provider": None, "assurance_standard": None,
        "section_a_status": "published", "section_c_status": "draft",
        "p1": 8, "p2": 7, "p3": 7, "p4": 7, "p5": 7, "p6": 6, "p7": 6, "p8": 7, "p9": 8,
        "emp_perm": 42000, "emp_contract": 8000,
        "turnover_inr_cr": 54400.0, "net_worth_inr_cr": 60000.0,
        "scope1": 12.0, "scope2": 180.0, "scope3": 8200.0,
        "energy_gj": 4800.0, "renewable_pct": 6.0,
        "water_int": 0.06, "waste_int": 0.2,
        "csr_spend": 132.0, "women_mgmt": 18.8, "attrition": 28.0, "wage_ratio": 0.50, "training_hrs": 32.0,
        "ind_dir_pct": 55.0, "board_meetings": 7, "cyber_incidents": 0,
        "overall_readiness": 64.0, "principles_disclosed": 9, "status": "draft",
    },
    # ── Insurance ─────────────────────────────────────────────────────────────
    {
        "entity_name": "Life Insurance Corporation of India",
        "cin": "L65110MH1956GOI010998",
        "bse_scrip_code": "543526",
        "nse_symbol": "LICI",
        "listed_exchange": "BOTH",
        "is_mandatory": True, "brsr_core_applicable": True, "brsr_core_assured": False,
        "assurance_provider": None, "assurance_standard": None,
        "section_a_status": "published", "section_c_status": "submitted",
        "p1": 7, "p2": 7, "p3": 7, "p4": 7, "p5": 7, "p6": 5, "p7": 8, "p8": 9, "p9": 7,
        "emp_perm": 114000, "emp_contract": 12000,
        "turnover_inr_cr": 798000.0, "net_worth_inr_cr": 42000.0,
        "scope1": 22.0, "scope2": 320.0, "scope3": 14000.0,
        "energy_gj": 9800.0, "renewable_pct": 5.0,
        "water_int": 0.04, "waste_int": 0.2,
        "csr_spend": 290.0, "women_mgmt": 18.8, "attrition": 5.2, "wage_ratio": 0.68, "training_hrs": 36.0,
        "ind_dir_pct": 50.0, "board_meetings": 8, "cyber_incidents": 0,
        "overall_readiness": 65.0, "principles_disclosed": 9, "status": "submitted",
    },
]

# ─────────────────────────────────────────────────────────────────────────────

def run():
    print(f"Connecting to {DATABASE_URL[:50]}...")
    conn = psycopg2.connect(DATABASE_URL)
    cur = conn.cursor()

    # Check if brsr_disclosures table exists
    cur.execute("""
        SELECT EXISTS (
            SELECT FROM information_schema.tables
            WHERE table_name = 'brsr_disclosures'
        )
    """)
    if not cur.fetchone()[0]:
        print("ERROR: brsr_disclosures table does not exist. Run alembic upgrade first.")
        conn.close()
        return

    # Clear existing seed data to avoid duplicates
    cur.execute("DELETE FROM brsr_disclosures WHERE reporting_year = 2024")
    print(f"Cleared existing FY2024 BRSR records.")

    insert_sql = """
        INSERT INTO brsr_disclosures (
            entity_name, cin, bse_scrip_code, nse_symbol, listed_exchange,
            is_mandatory, brsr_core_applicable, brsr_core_assured,
            assurance_provider, assurance_standard,
            section_a_status, section_c_status, reporting_year,
            p1_ethics_score, p2_products_score, p3_employee_score,
            p4_stakeholder_score, p5_human_rights_score, p6_environment_score,
            p7_policy_score, p8_inclusive_score, p9_consumer_score,
            p1_ethics_status, p2_products_services_status, p3_employee_wellbeing_status,
            p4_stakeholder_engagement_status, p5_human_rights_status, p6_environment_status,
            p7_policy_advocacy_status, p8_inclusive_growth_status, p9_consumer_engagement_status,
            employee_count_permanent, employee_count_contract,
            turnover_inr_cr, net_worth_inr_cr,
            core_e1_ghg_scope1_tco2e, core_e2_ghg_scope2_tco2e, core_e3_ghg_scope3_tco2e,
            core_e4_total_energy_gj, core_e5_renewable_energy_pct,
            core_e6_water_intensity_m3_cr_revenue, core_e7_waste_intensity_kg_cr_revenue,
            core_s1_csr_spend_inr_cr, core_s2_women_in_mgmt_pct,
            core_s3_attrition_rate_pct, core_s4_median_wage_ratio, core_s5_training_hours_avg,
            core_g1_independent_directors_pct, core_g2_board_meetings_count, core_g3_cybersecurity_incidents,
            overall_readiness_pct, total_principles_disclosed, status
        ) VALUES (
            %(entity_name)s, %(cin)s, %(bse)s, %(nse)s, %(exchange)s,
            %(is_mandatory)s, %(core_app)s, %(core_assured)s,
            %(assurance_provider)s, %(assurance_standard)s,
            %(sec_a)s, %(sec_c)s, 2024,
            %(p1)s, %(p2)s, %(p3)s, %(p4)s, %(p5)s, %(p6)s, %(p7)s, %(p8)s, %(p9)s,
            'published','published','published','published','published','published','published','published','published',
            %(emp_perm)s, %(emp_contract)s,
            %(turnover)s, %(net_worth)s,
            %(scope1)s, %(scope2)s, %(scope3)s, %(energy_gj)s, %(renewable_pct)s,
            %(water_int)s, %(waste_int)s,
            %(csr_spend)s, %(women_mgmt)s, %(attrition)s, %(wage_ratio)s, %(training_hrs)s,
            %(ind_dir_pct)s, %(board_meetings)s, %(cyber_incidents)s,
            %(overall_readiness)s, %(principles_disclosed)s, %(status)s
        )
    """

    count = 0
    for c in COMPANIES:
        try:
            cur.execute(insert_sql, {
                "entity_name": c["entity_name"],
                "cin": c["cin"],
                "bse": c["bse_scrip_code"],
                "nse": c["nse_symbol"],
                "exchange": c["listed_exchange"],
                "is_mandatory": c["is_mandatory"],
                "core_app": c["brsr_core_applicable"],
                "core_assured": c["brsr_core_assured"],
                "assurance_provider": c["assurance_provider"],
                "assurance_standard": c["assurance_standard"],
                "sec_a": c["section_a_status"],
                "sec_c": c["section_c_status"],
                "p1": c["p1"], "p2": c["p2"], "p3": c["p3"],
                "p4": c["p4"], "p5": c["p5"], "p6": c["p6"],
                "p7": c["p7"], "p8": c["p8"], "p9": c["p9"],
                "emp_perm": c["emp_perm"], "emp_contract": c["emp_contract"],
                "turnover": c["turnover_inr_cr"], "net_worth": c["net_worth_inr_cr"],
                "scope1": c["scope1"], "scope2": c["scope2"], "scope3": c["scope3"],
                "energy_gj": c["energy_gj"], "renewable_pct": c["renewable_pct"],
                "water_int": c["water_int"], "waste_int": c["waste_int"],
                "csr_spend": c["csr_spend"], "women_mgmt": c["women_mgmt"],
                "attrition": c["attrition"], "wage_ratio": c["wage_ratio"],
                "training_hrs": c["training_hrs"], "ind_dir_pct": c["ind_dir_pct"],
                "board_meetings": c["board_meetings"], "cyber_incidents": c["cyber_incidents"],
                "overall_readiness": c["overall_readiness"],
                "principles_disclosed": c["principles_disclosed"],
                "status": c["status"],
            })
            count += 1
            print(f"  + {c['entity_name']}")
        except Exception as e:
            print(f"  ! FAILED {c['entity_name']}: {e}")
            conn.rollback()
            continue

    conn.commit()
    cur.close()
    conn.close()
    print(f"\nDone. Inserted {count}/{len(COMPANIES)} BRSR records for FY2024.")


if __name__ == "__main__":
    run()
