import React,{useState,useMemo} from 'react';
import {BarChart,Bar,LineChart,Line,AreaChart,Area,PieChart,Pie,Cell,XAxis,YAxis,CartesianGrid,Tooltip,ResponsiveContainer,Legend,RadarChart,Radar,PolarGrid,PolarAngleAxis,PolarRadiusAxis,ScatterChart,Scatter,ZAxis} from 'recharts';
const T={bg:'#f6f4f0',surface:'#ffffff',surfaceH:'#f0ede7',border:'#e5e0d8',borderL:'#d5cfc5',navy:'#1b3a5c',navyL:'#2c5a8c',gold:'#c5a96a',goldL:'#d4be8a',sage:'#5a8a6a',sageL:'#7ba67d',teal:'#5a8a6a',text:'#1b3a5c',textSec:'#5c6b7e',textMut:'#9aa3ae',red:'#dc2626',green:'#16a34a',amber:'#d97706',font:"'DM Sans','SF Pro Display',system-ui,-apple-system,sans-serif",mono:"'JetBrains Mono','SF Mono','Fira Code',monospace"};
const sr=(s)=>{let x=Math.sin(s+1)*10000;return x-Math.floor(x);};
const CC=[T.navy,T.gold,T.sage,T.red,T.amber,T.green,T.navyL,T.goldL,'#8b5cf6','#ec4899','#06b6d4'];
const fmt=v=>typeof v==='number'?v>=1e9?(v/1e9).toFixed(1)+'B':v>=1e6?(v/1e6).toFixed(1)+'M':v>=1e3?(v/1e3).toFixed(1)+'K':v.toFixed(1):v;
const tip={contentStyle:{background:T.surface,border:`1px solid ${T.border}`,borderRadius:8,fontFamily:T.font,fontSize:12},labelStyle:{color:T.navy,fontWeight:600}};
const PAGE=12;const TABS=['Portfolio Overview','Holdings Analysis','Risk Decomposition','Performance Attribution'];
const F1=['Active Equity','Passive Equity','Fixed Income','Multi-Asset','Alternatives','Quant','ESG Thematic','Impact'];
const F2=['Global','US','Europe','Asia-Pacific','Emerging Markets','UK','Japan','China'];
const ITEMS=Array.from({length:50},(_,i)=>({id:i+1,name:'Portfolio '+(i+1),strategy:F1[Math.floor(sr(i*3)*F1.length)],region:F2[Math.floor(sr(i*7)*F2.length)],aum:+(sr(i*11)*5000+100).toFixed(0),returnYtd:+(sr(i*13)*25-5).toFixed(2),return1y:+(sr(i*17)*30-8).toFixed(2),vol:+(sr(i*19)*18+4).toFixed(2),sharpe:+(sr(i*23)*2+0.1).toFixed(2),maxDD:+(sr(i*29)*25+3).toFixed(2),beta:+(sr(i*31)*1.2+0.3).toFixed(2),alpha:+(sr(i*37)*5-2).toFixed(2),te:+(sr(i*41)*4+0.5).toFixed(2),ir:+(sr(i*43)*1.5-0.3).toFixed(2),esgScore:+(sr(i*47)*30+55).toFixed(1),carbonInt:+(sr(i*53)*100+20).toFixed(1),holdings:Math.floor(sr(i*59)*300+30),turnover:+(sr(i*61)*40+5).toFixed(1),activeSh:+(sr(i*67)*50+20).toFixed(1)}));
const TS=Array.from({length:24},(_,i)=>{const d=new Date(2024,i%12,1);return{period:d.toLocaleString('default',{month:'short'})+' '+(2024+Math.floor(i/12)),v1:+(sr(i*71)*5-1).toFixed(2),v2:+(sr(i*73)*4-0.5).toFixed(2),v3:+(sr(i*79)*15+5).toFixed(2)};});
const exportCSV=(data,fn)=>{if(!data.length)return;const h=Object.keys(data[0]);const csv=[h.join(','),...data.map(r=>h.map(k=>JSON.stringify(r[k]??'')).join(','))].join('\n');const b=new Blob([csv],{type:'text/csv'});const u=URL.createObjectURL(b);const a=document.createElement('a');a.href=u;a.download=fn;a.click();URL.revokeObjectURL(u);};
export default function PortfolioSuitePage(){
  const [tab,setTab]=useState(0);const [search,setSearch]=useState('');const [sortCol,setSortCol]=useState('aum');const [sortDir,setSortDir]=useState('desc');const [page,setPage]=useState(0);const [expanded,setExpanded]=useState(null);const [f1,sf1]=useState('All');const [f2,sf2]=useState('All');
  const filtered=useMemo(()=>{let d=[...ITEMS];if(search)d=d.filter(x=>x.name.toLowerCase().includes(search.toLowerCase()));if(f1!=='All')d=d.filter(x=>x.strategy===f1);if(f2!=='All')d=d.filter(x=>x.region===f2);d.sort((a,b)=>sortDir==='asc'?((a[sortCol]>b[sortCol])?1:-1):((a[sortCol]<b[sortCol])?1:-1));return d;},[search,sortCol,sortDir,f1,f2]);
  const paged=filtered.slice(page*PAGE,page*PAGE+PAGE);const totalPages=Math.ceil(filtered.length/PAGE);
  const doSort=col=>{if(sortCol===col)setSortDir(d=>d==='asc'?'desc':'asc');else{setSortCol(col);setSortDir('desc');}setPage(0);};
  const SH=({col,label,w})=><th onClick={()=>doSort(col)} style={{cursor:'pointer',padding:'10px 8px',textAlign:'left',borderBottom:`2px solid ${T.border}`,fontSize:11,fontWeight:700,color:T.textSec,fontFamily:T.mono,width:w,userSelect:'none',whiteSpace:'nowrap'}}>{label}{sortCol===col?(sortDir==='asc'?' \u25B2':' \u25BC'):''}</th>;
  const Pg=()=><div style={{display:'flex',justifyContent:'center',gap:6,marginTop:14}}><button onClick={()=>setPage(p=>Math.max(0,p-1))} disabled={page===0} style={{padding:'6px 14px',border:`1px solid ${T.border}`,borderRadius:6,background:T.surface,cursor:page===0?'default':'pointer',opacity:page===0?0.4:1,fontSize:12}}>Prev</button>{Array.from({length:Math.min(totalPages,7)},(_,i)=>{const p=totalPages<=7?i:page<3?i:page>totalPages-4?totalPages-7+i:page-3+i;return <button key={p} onClick={()=>setPage(p)} style={{padding:'6px 12px',border:`1px solid ${page===p?T.gold:T.border}`,borderRadius:6,background:page===p?T.gold:'transparent',color:page===p?'#fff':T.text,cursor:'pointer',fontWeight:page===p?700:400,fontSize:12}}>{p+1}</button>;})}<button onClick={()=>setPage(p=>Math.min(totalPages-1,p+1))} disabled={page>=totalPages-1} style={{padding:'6px 14px',border:`1px solid ${T.border}`,borderRadius:6,background:T.surface,cursor:page>=totalPages-1?'default':'pointer',opacity:page>=totalPages-1?0.4:1,fontSize:12}}>Next</button></div>;
  const kpis=useMemo(()=>{const n=filtered.length||1;return[{l:'Portfolios',v:filtered.length},{l:'Total AUM',v:'$'+fmt(filtered.reduce((s,x)=>s+x.aum,0))+'M'},{l:'Avg Return',v:(filtered.reduce((s,x)=>s+parseFloat(x.returnYtd),0)/n).toFixed(2)+'%'},{l:'Avg Sharpe',v:(filtered.reduce((s,x)=>s+parseFloat(x.sharpe),0)/n).toFixed(2)},{l:'Avg ESG',v:(filtered.reduce((s,x)=>s+parseFloat(x.esgScore),0)/n).toFixed(1)}];},[filtered]);
  const d1=useMemo(()=>{const m={};F1.forEach(s=>m[s]=0);filtered.forEach(x=>m[x.strategy]++);return Object.entries(m).filter(([,v])=>v>0).map(([name,value])=>({name:name.length>14?name.slice(0,14)+'..':name,value}));},[filtered]);
  const d2=useMemo(()=>{const m={};F2.forEach(r=>m[r]=0);filtered.forEach(x=>m[x.region]++);return Object.entries(m).filter(([,v])=>v>0).map(([name,value])=>({name,value}));},[filtered]);
  const renderDash=()=>(<div>
    <div style={{display:'grid',gridTemplateColumns:'repeat(5,1fr)',gap:12,marginBottom:20}}>{kpis.map((k,i)=><div key={i} style={{background:T.surface,border:`1px solid ${T.border}`,borderRadius:10,padding:'16px 18px'}}><div style={{fontSize:11,color:T.textMut,fontFamily:T.mono,textTransform:'uppercase',letterSpacing:0.5}}>{k.l}</div><div style={{fontSize:24,fontWeight:700,color:T.navy,marginTop:4}}>{k.v}</div></div>)}</div>
    <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16,marginBottom:20}}>
      <div style={{background:T.surface,border:`1px solid ${T.border}`,borderRadius:10,padding:20}}><div style={{fontSize:14,fontWeight:700,color:T.navy,marginBottom:12}}>Return & Benchmark Trend</div><ResponsiveContainer width="100%" height={280}><AreaChart data={TS}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="period" tick={{fontSize:9,fill:T.textMut}} interval={3}/><YAxis tick={{fontSize:10,fill:T.textMut}}/><Tooltip {...tip}/><Legend/><Area type="monotone" dataKey="v1" stroke={T.navy} fill={T.navy} fillOpacity={0.15} name="Portfolio Return %"/><Area type="monotone" dataKey="v2" stroke={T.gold} fill={T.gold} fillOpacity={0.15} name="Benchmark %"/></AreaChart></ResponsiveContainer></div>
      <div style={{background:T.surface,border:`1px solid ${T.border}`,borderRadius:10,padding:20}}><div style={{fontSize:14,fontWeight:700,color:T.navy,marginBottom:12}}>Strategy Distribution</div><ResponsiveContainer width="100%" height={280}><PieChart><Pie data={d1} dataKey="value" nameKey="name" cx="50%" cy="50%" outerRadius={100} label={({name,percent})=>`${name} ${(percent*100).toFixed(0)}%`}>{d1.map((_,i)=><Cell key={i} fill={CC[i%CC.length]}/>)}</Pie><Tooltip {...tip}/></PieChart></ResponsiveContainer></div>
    </div>
    <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16,marginBottom:20}}>
      <div style={{background:T.surface,border:`1px solid ${T.border}`,borderRadius:10,padding:20}}><div style={{fontSize:14,fontWeight:700,color:T.navy,marginBottom:12}}>Regional Allocation</div><ResponsiveContainer width="100%" height={260}><BarChart data={d2} layout="vertical"><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis type="number" tick={{fontSize:10,fill:T.textMut}}/><YAxis dataKey="name" type="category" width={100} tick={{fontSize:10,fill:T.textMut}}/><Tooltip {...tip}/><Bar dataKey="value" fill={T.sage} radius={[0,6,6,0]}/></BarChart></ResponsiveContainer></div>
      <div style={{background:T.surface,border:`1px solid ${T.border}`,borderRadius:10,padding:20}}><div style={{fontSize:14,fontWeight:700,color:T.navy,marginBottom:12}}>Volatility Trend</div><ResponsiveContainer width="100%" height={260}><LineChart data={TS}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="period" tick={{fontSize:9,fill:T.textMut}} interval={3}/><YAxis tick={{fontSize:10,fill:T.textMut}}/><Tooltip {...tip}/><Line type="monotone" dataKey="v3" stroke={T.red} strokeWidth={2} name="Volatility %"/></LineChart></ResponsiveContainer></div>
    </div>
    <div style={{background:T.surface,border:`1px solid ${T.border}`,borderRadius:10,padding:20}}><div style={{fontSize:14,fontWeight:700,color:T.navy,marginBottom:12}}>Risk-Return Scatter</div><ResponsiveContainer width="100%" height={260}><ScatterChart><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="x" name="Volatility" tick={{fontSize:10,fill:T.textMut}}/><YAxis dataKey="y" name="Return %" tick={{fontSize:10,fill:T.textMut}}/><ZAxis dataKey="z" range={[40,400]}/><Tooltip {...tip}/><Scatter data={filtered.map(x=>({name:x.name,x:parseFloat(x.vol),y:parseFloat(x.returnYtd),z:x.aum/10}))} fill={T.navy} fillOpacity={0.5}/></ScatterChart></ResponsiveContainer></div>
  </div>);
  const renderTable=()=>(<div>
    <div style={{display:'flex',gap:12,marginBottom:16,flexWrap:'wrap',alignItems:'center'}}>
      <input value={search} onChange={e=>{setSearch(e.target.value);setPage(0);}} placeholder="Search portfolios..." style={{flex:1,minWidth:200,padding:'8px 14px',border:`1px solid ${T.border}`,borderRadius:8,fontSize:13,background:T.surface}}/>
      <select value={f1} onChange={e=>{sf1(e.target.value);setPage(0);}} style={{padding:'8px 12px',border:`1px solid ${T.border}`,borderRadius:8,fontSize:13,background:T.surface}}><option value="All">All Strategies</option>{F1.map(s=><option key={s} value={s}>{s}</option>)}</select>
      <select value={f2} onChange={e=>{sf2(e.target.value);setPage(0);}} style={{padding:'8px 12px',border:`1px solid ${T.border}`,borderRadius:8,fontSize:13,background:T.surface}}><option value="All">All Regions</option>{F2.map(r=><option key={r} value={r}>{r}</option>)}</select>
      <button onClick={()=>exportCSV(filtered,'portfolio_suite.csv')} style={{padding:'8px 16px',border:'none',borderRadius:8,background:T.gold,color:'#fff',fontWeight:600,fontSize:13,cursor:'pointer'}}>Export CSV</button>
    </div>
    <div style={{fontSize:12,color:T.textMut,marginBottom:8,fontFamily:T.mono}}>{filtered.length} portfolios | Page {page+1}/{totalPages}</div>
    <div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse',fontSize:12}}>
      <thead><tr style={{background:T.surfaceH}}><SH col="name" label="Portfolio" w="130px"/><SH col="strategy" label="Strategy"/><SH col="aum" label="AUM ($M)"/><SH col="returnYtd" label="YTD %"/><SH col="vol" label="Vol %"/><SH col="sharpe" label="Sharpe"/><SH col="esgScore" label="ESG"/><SH col="carbonInt" label="Carbon"/><SH col="holdings" label="Holdings"/></tr></thead>
      <tbody>{paged.map(item=>(<React.Fragment key={item.id}>
        <tr onClick={()=>setExpanded(expanded===item.id?null:item.id)} style={{cursor:'pointer',background:expanded===item.id?T.surfaceH:'transparent',borderBottom:`1px solid ${T.border}`}}>
          <td style={{padding:'10px 8px',fontWeight:600,color:T.navy}}>{expanded===item.id?'\u25BC':'\u25B6'} {item.name}</td>
          <td style={{padding:'10px 8px'}}><span style={{padding:'2px 8px',borderRadius:10,fontSize:10,fontWeight:600,background:T.surfaceH,color:T.navy}}>{item.strategy}</span></td>
          <td style={{padding:'10px 8px',fontFamily:T.mono}}>{fmt(item.aum)}</td>
          <td style={{padding:'10px 8px',fontFamily:T.mono,color:parseFloat(item.returnYtd)>0?T.green:T.red}}>{item.returnYtd}%</td>
          <td style={{padding:'10px 8px',fontFamily:T.mono}}>{item.vol}%</td>
          <td style={{padding:'10px 8px',fontFamily:T.mono}}>{item.sharpe}</td>
          <td style={{padding:'10px 8px',fontFamily:T.mono,color:parseFloat(item.esgScore)>70?T.green:T.navy}}>{item.esgScore}</td>
          <td style={{padding:'10px 8px',fontFamily:T.mono}}>{item.carbonInt}</td>
          <td style={{padding:'10px 8px',fontFamily:T.mono}}>{item.holdings}</td>
        </tr>
        {expanded===item.id&&(<tr><td colSpan={9} style={{padding:20,background:T.surfaceH,borderBottom:`2px solid ${T.gold}`}}>
          <div style={{display:'grid',gridTemplateColumns:'1fr 1fr 1fr',gap:16}}>
            <div><div style={{fontSize:13,fontWeight:700,color:T.navy,marginBottom:8}}>Performance</div>
              {[['Region',item.region],['1Y Return',item.return1y+'%'],['Max Drawdown',item.maxDD+'%'],['Beta',item.beta],['Alpha',item.alpha+'%'],['Tracking Error',item.te+'%'],['Info Ratio',item.ir]].map(([l,v])=><div key={l} style={{display:'flex',justifyContent:'space-between',padding:'4px 0',fontSize:12,borderBottom:`1px solid ${T.border}`}}><span style={{color:T.textMut}}>{l}</span><span style={{fontWeight:600,color:T.navy,fontFamily:T.mono}}>{v}</span></div>)}</div>
            <div><div style={{fontSize:13,fontWeight:700,color:T.navy,marginBottom:8}}>Characteristics</div>
              {[['Turnover',item.turnover+'%'],['Active Share',item.activeSh+'%']].map(([l,v])=><div key={l} style={{display:'flex',justifyContent:'space-between',padding:'4px 0',fontSize:12,borderBottom:`1px solid ${T.border}`}}><span style={{color:T.textMut}}>{l}</span><span style={{fontWeight:600,color:T.navy,fontFamily:T.mono}}>{v}</span></div>)}
              <div style={{fontSize:12,color:T.textSec,lineHeight:1.6,marginTop:8}}><p>Portfolio managed under {item.strategy} strategy with {item.holdings} holdings across {item.region} markets.</p></div></div>
            <div><div style={{fontSize:13,fontWeight:700,color:T.navy,marginBottom:8}}>Profile</div><ResponsiveContainer width="100%" height={200}><RadarChart data={[{m:'Return',v:(parseFloat(item.returnYtd)+10)*3},{m:'Sharpe',v:parseFloat(item.sharpe)*30},{m:'ESG',v:parseFloat(item.esgScore)},{m:'Low Carbon',v:100-parseFloat(item.carbonInt)/1.5},{m:'Alpha',v:(parseFloat(item.alpha)+3)*15},{m:'Active',v:parseFloat(item.activeSh)}]}><PolarGrid stroke={T.border}/><PolarAngleAxis dataKey="m" tick={{fontSize:9}}/><PolarRadiusAxis domain={[0,100]} tick={{fontSize:8}}/><Radar dataKey="v" stroke={T.navy} fill={T.navy} fillOpacity={0.2}/></RadarChart></ResponsiveContainer></div>
          </div>
        </td></tr>)}
      </React.Fragment>))}</tbody>
    </table></div><Pg/>
  </div>);
  const renderRisk=()=>(<div>
    <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16,marginBottom:20}}>
      <div style={{background:T.surface,border:`1px solid ${T.border}`,borderRadius:10,padding:20}}><div style={{fontSize:14,fontWeight:700,color:T.navy,marginBottom:12}}>Risk by Strategy</div><ResponsiveContainer width="100%" height={280}><BarChart data={F1.map(s=>{const ps=filtered.filter(x=>x.strategy===s);return{name:s.slice(0,12),vol:ps.length?(ps.reduce((sum,x)=>sum+parseFloat(x.vol),0)/ps.length).toFixed(1):0,dd:ps.length?(ps.reduce((sum,x)=>sum+parseFloat(x.maxDD),0)/ps.length).toFixed(1):0};}).filter(d=>d.vol>0)}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="name" tick={{fontSize:8,fill:T.textMut}} angle={-30} textAnchor="end" height={50}/><YAxis tick={{fontSize:10,fill:T.textMut}}/><Tooltip {...tip}/><Legend/><Bar dataKey="vol" fill={T.navy} name="Avg Vol %" radius={[4,4,0,0]}/><Bar dataKey="dd" fill={T.red} name="Avg Max DD %" radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></div>
      <div style={{background:T.surface,border:`1px solid ${T.border}`,borderRadius:10,padding:20}}><div style={{fontSize:14,fontWeight:700,color:T.navy,marginBottom:12}}>ESG vs Carbon</div><ResponsiveContainer width="100%" height={280}><ScatterChart><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="x" name="ESG Score" tick={{fontSize:10,fill:T.textMut}}/><YAxis dataKey="y" name="Carbon Intensity" tick={{fontSize:10,fill:T.textMut}}/><Tooltip {...tip}/><Scatter data={filtered.map(x=>({name:x.name,x:parseFloat(x.esgScore),y:parseFloat(x.carbonInt)}))} fill={T.gold} fillOpacity={0.6}/></ScatterChart></ResponsiveContainer></div>
    </div>
    <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16}}>
      <div style={{background:T.surface,border:`1px solid ${T.border}`,borderRadius:10,padding:20}}><div style={{fontSize:14,fontWeight:700,color:T.navy,marginBottom:12}}>Beta Distribution</div><ResponsiveContainer width="100%" height={260}><BarChart data={filtered.slice(0,15).map(x=>({name:x.name.slice(0,8),beta:parseFloat(x.beta)}))}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="name" tick={{fontSize:8,fill:T.textMut}}/><YAxis tick={{fontSize:10,fill:T.textMut}}/><Tooltip {...tip}/><Bar dataKey="beta" fill={T.sage} radius={[6,6,0,0]} name="Beta"/></BarChart></ResponsiveContainer></div>
      <div style={{background:T.surface,border:`1px solid ${T.border}`,borderRadius:10,padding:20}}><div style={{fontSize:14,fontWeight:700,color:T.navy,marginBottom:12}}>Tracking Error</div><ResponsiveContainer width="100%" height={260}><AreaChart data={filtered.sort((a,b)=>parseFloat(a.te)-parseFloat(b.te)).slice(0,20).map(x=>({name:x.name.slice(0,6),te:parseFloat(x.te)}))}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="name" tick={{fontSize:7,fill:T.textMut}} interval={2}/><YAxis tick={{fontSize:10,fill:T.textMut}}/><Tooltip {...tip}/><Area type="monotone" dataKey="te" stroke={T.navy} fill={T.navy} fillOpacity={0.15} name="TE %"/></AreaChart></ResponsiveContainer></div>
    </div>
  </div>);
  const renderAttrib=()=>(<div>
    <div style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:12,marginBottom:20}}>
      {[{l:'Avg Alpha',v:(filtered.reduce((s,x)=>s+parseFloat(x.alpha),0)/filtered.length).toFixed(2)+'%'},{l:'Avg Info Ratio',v:(filtered.reduce((s,x)=>s+parseFloat(x.ir),0)/filtered.length).toFixed(2)},{l:'Avg Active Share',v:(filtered.reduce((s,x)=>s+parseFloat(x.activeSh),0)/filtered.length).toFixed(1)+'%'},{l:'Avg Turnover',v:(filtered.reduce((s,x)=>s+parseFloat(x.turnover),0)/filtered.length).toFixed(1)+'%'}].map((k,i)=><div key={i} style={{background:T.surface,border:`1px solid ${T.border}`,borderRadius:10,padding:'16px 18px'}}><div style={{fontSize:11,color:T.textMut,fontFamily:T.mono,textTransform:'uppercase'}}>{k.l}</div><div style={{fontSize:22,fontWeight:700,color:T.navy,marginTop:4}}>{k.v}</div></div>)}
    </div>
    <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16,marginBottom:20}}>
      <div style={{background:T.surface,border:`1px solid ${T.border}`,borderRadius:10,padding:20}}><div style={{fontSize:14,fontWeight:700,color:T.navy,marginBottom:12}}>Alpha by Strategy</div><ResponsiveContainer width="100%" height={280}><BarChart data={F1.map(s=>{const ps=filtered.filter(x=>x.strategy===s);return{name:s.slice(0,12),alpha:ps.length?(ps.reduce((sum,x)=>sum+parseFloat(x.alpha),0)/ps.length).toFixed(2):0};}).filter(d=>d.alpha!==0)}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="name" tick={{fontSize:8,fill:T.textMut}} angle={-30} textAnchor="end" height={50}/><YAxis tick={{fontSize:10,fill:T.textMut}}/><Tooltip {...tip}/><Bar dataKey="alpha" fill={T.navy} radius={[6,6,0,0]} name="Avg Alpha %"/></BarChart></ResponsiveContainer></div>
      <div style={{background:T.surface,border:`1px solid ${T.border}`,borderRadius:10,padding:20}}><div style={{fontSize:14,fontWeight:700,color:T.navy,marginBottom:12}}>Cumulative Performance</div><ResponsiveContainer width="100%" height={280}><LineChart data={TS}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="period" tick={{fontSize:9,fill:T.textMut}} interval={3}/><YAxis yAxisId="l" tick={{fontSize:10,fill:T.textMut}}/><YAxis yAxisId="r" orientation="right" tick={{fontSize:10,fill:T.textMut}}/><Tooltip {...tip}/><Legend/><Line yAxisId="l" type="monotone" dataKey="v1" stroke={T.navy} strokeWidth={2} name="Portfolio"/><Line yAxisId="r" type="monotone" dataKey="v2" stroke={T.gold} strokeWidth={2} name="Benchmark"/></LineChart></ResponsiveContainer></div>
    </div>
  </div>);
  return(<div style={{fontFamily:T.font,background:T.bg,minHeight:'100vh',padding:'24px 32px'}}>
    <div style={{marginBottom:24}}><div style={{fontSize:11,fontFamily:T.mono,color:T.textMut,textTransform:'uppercase',letterSpacing:1}}>Portfolio Intelligence</div><h1 style={{fontSize:28,fontWeight:800,color:T.navy,margin:'4px 0 0'}}>Portfolio Analytics Suite</h1><div style={{width:40,height:3,background:T.gold,borderRadius:2,marginTop:6}}/></div>
    <div style={{display:'flex',gap:0,marginBottom:24,borderBottom:`2px solid ${T.border}`}}>{TABS.map((t,i)=><button key={t} onClick={()=>setTab(i)} style={{padding:'10px 20px',border:'none',borderBottom:tab===i?`3px solid ${T.gold}`:'3px solid transparent',background:'transparent',color:tab===i?T.navy:T.textMut,fontWeight:tab===i?700:500,fontSize:13,cursor:'pointer',fontFamily:T.font}}>{t}</button>)}</div>
    {tab===0&&renderDash()}{tab===1&&renderTable()}{tab===2&&renderRisk()}{tab===3&&renderAttrib()}
  </div>);
}