import React,{useState,useMemo,useCallback} from 'react';
import {BarChart,Bar,LineChart,Line,AreaChart,Area,PieChart,Pie,Cell,ScatterChart,Scatter,XAxis,YAxis,CartesianGrid,Tooltip,ResponsiveContainer,Legend,RadarChart,Radar,PolarGrid,PolarAngleAxis,PolarRadiusAxis} from 'recharts';
const T={bg:'#f6f4f0',surface:'#ffffff',surfaceH:'#f0ede7',border:'#e5e0d8',borderL:'#d5cfc5',navy:'#1b3a5c',navyL:'#2c5a8c',gold:'#c5a96a',goldL:'#d4be8a',sage:'#5a8a6a',sageL:'#7ba67d',teal:'#5a8a6a',text:'#1b3a5c',textSec:'#5c6b7e',textMut:'#9aa3ae',red:'#dc2626',green:'#16a34a',amber:'#d97706',font:"'DM Sans','SF Pro Display',system-ui,-apple-system,sans-serif",mono:"'JetBrains Mono','SF Mono','Fira Code',monospace"};
const sr=(s)=>{let x=Math.sin(s+1)*10000;return x-Math.floor(x);};
const ACCENT='#1b3a5c';const tip={contentStyle:{background:T.surface,border:`1px solid ${T.border}`,borderRadius:8,fontSize:11,fontFamily:T.font},labelStyle:{color:T.textSec,fontFamily:T.mono,fontSize:10}};const COLORS=[T.navy,T.gold,T.sage,T.red,T.amber,T.green,T.navyL,T.goldL,'#8b5cf6','#ec4899','#06b6d4'];
const fmt=v=>typeof v==='number'?v>=1e9?(v/1e9).toFixed(1)+'B':v>=1e6?(v/1e6).toFixed(1)+'M':v>=1e3?(v/1e3).toFixed(1)+'K':v.toFixed(1):v;
const TABS=['Portfolio Overview','Sector Drill-Down','Country Exposure','ESG Analytics'];const SECTORS=['All','Technology','Financials','Healthcare','Energy','Consumer','Industrials','Materials','Utilities','Real Estate'];const PAGE=15;
const COUNTRIES=['US','UK','Germany','Japan','China','France','Switzerland','Canada','Australia','Netherlands','South Korea','India','Sweden','Denmark','Brazil','Singapore','Taiwan','Ireland','Spain','Italy'];
const HOLDINGS=Array.from({length:100},(_,i)=>{
  const names=['Apple','Microsoft','Alphabet','Amazon','NVIDIA','Meta','Tesla','Berkshire','JPMorgan','Visa','UnitedHealth','J&J','Walmart','P&G','Mastercard','BofA','Chevron','Home Depot','Coca-Cola','Pfizer','Abbott','Eli Lilly','PepsiCo','Costco','Broadcom','Thermo Fisher','Cisco','Merck','Accenture','McDonalds','Danaher','Adobe','Linde','Salesforce','AMD','Qualcomm','Intel','Goldman Sachs','Caterpillar','Amgen','Morgan Stanley','Honeywell','Lockheed','Deere','IBM','GE','RTX','Medtronic','AstraZeneca','Shell','BP','TotalEnergies','Nestle','Roche','Novartis','SAP','Siemens','LVMH','Unilever','HSBC','BHP','Rio Tinto','Sony','Toyota','Samsung','Infosys','Reliance','TSMC','Novo Nordisk','Diageo','AbbVie','Starbucks','Netflix','Booking','Intuit','Uber','Airbnb','PayPal','ServiceNow','CrowdStrike','NextEra','Enel','Iberdrola','Orsted','Duke Energy','Prologis','American Tower','Crown Castle','Digital Realty','Equinix','Snowflake','Datadog','Crowdstrike','MongoDB','Fortinet','Zscaler','Cloudflare','Palantir','SentinelOne','Elastic'];
  const secs=['Technology','Technology','Technology','Technology','Technology','Technology','Technology','Financials','Financials','Financials','Healthcare','Healthcare','Consumer','Consumer','Financials','Financials','Energy','Consumer','Consumer','Healthcare','Healthcare','Healthcare','Consumer','Consumer','Technology','Healthcare','Technology','Healthcare','Technology','Consumer','Healthcare','Technology','Materials','Technology','Technology','Technology','Technology','Financials','Industrials','Healthcare','Financials','Industrials','Industrials','Industrials','Technology','Industrials','Industrials','Healthcare','Healthcare','Energy','Energy','Energy','Consumer','Healthcare','Healthcare','Technology','Industrials','Consumer','Consumer','Financials','Materials','Materials','Technology','Industrials','Technology','Technology','Energy','Technology','Healthcare','Consumer','Healthcare','Consumer','Technology','Consumer','Technology','Technology','Technology','Financials','Technology','Technology','Utilities','Utilities','Utilities','Utilities','Utilities','Real Estate','Real Estate','Real Estate','Real Estate','Real Estate','Technology','Technology','Technology','Technology','Technology','Technology','Technology','Technology','Technology','Technology'];
  const country=COUNTRIES[Math.floor(sr(i*7)*COUNTRIES.length)];const wt=+(3-i*0.025+sr(i*11)*0.5).toFixed(2);const mktCap=+(sr(i*13)*2000+10).toFixed(0);
  const ret1d=+((sr(i*17)-0.48)*4).toFixed(2);const ret1m=+((sr(i*19)-0.45)*10).toFixed(1);const retYTD=+((sr(i*23)-0.4)*30).toFixed(1);const ret1y=+((sr(i*29)-0.35)*40).toFixed(1);
  const esgScore=Math.round(sr(i*31)*40+50);const carbonI=Math.round(sr(i*37)*300+10);const greenRev=Math.round(sr(i*41)*50);
  return{id:i+1,name:names[i%names.length],sector:secs[i%secs.length],country,weightPct:Math.max(0.1,wt),mktCapBn:+mktCap,return1D:ret1d,return1M:ret1m,returnYTD:retYTD,return1Y:ret1y,volatility:+(sr(i*43)*20+8).toFixed(1),beta:+(sr(i*47)*0.8+0.5).toFixed(2),pe:+(sr(i*49)*30+8).toFixed(1),divYield:+(sr(i*51)*4).toFixed(1),esgScore,carbonIntensity:carbonI,greenRevPct:greenRev,itr:+(sr(i*53)*2.5+1).toFixed(1)};
});
export default function PortfolioDashboardPage(){
  const[tab,setTab]=useState(0);const[search,setSearch]=useState('');const[sectorF,setSectorF]=useState('All');const[sortCol,setSortCol]=useState('weightPct');const[sortDir,setSortDir]=useState('desc');const[page,setPage]=useState(1);const[selected,setSelected]=useState(null);
  const filtered=useMemo(()=>{let d=[...HOLDINGS];if(search)d=d.filter(r=>r.name.toLowerCase().includes(search.toLowerCase()));if(sectorF!=='All')d=d.filter(r=>r.sector===sectorF);d.sort((a,b)=>sortDir==='asc'?(a[sortCol]>b[sortCol]?1:-1):(a[sortCol]<b[sortCol]?1:-1));return d;},[search,sectorF,sortCol,sortDir]);
  const paged=useMemo(()=>filtered.slice((page-1)*PAGE,page*PAGE),[filtered,page]);const totalPages=Math.ceil(filtered.length/PAGE);
  const doSort=col=>{if(sortCol===col)setSortDir(d=>d==='asc'?'desc':'asc');else{setSortCol(col);setSortDir('desc');}setPage(1);};
  const stats=useMemo(()=>({count:filtered.length,totalWeight:filtered.reduce((s,r)=>s+r.weightPct,0).toFixed(1),avgRet1D:(filtered.reduce((s,r)=>s+r.return1D,0)/filtered.length||0).toFixed(2),avgRetYTD:(filtered.reduce((s,r)=>s+r.returnYTD,0)/filtered.length||0).toFixed(1),avgESG:Math.round(filtered.reduce((s,r)=>s+r.esgScore,0)/filtered.length||0),avgCarbon:Math.round(filtered.reduce((s,r)=>s+r.carbonIntensity,0)/filtered.length||0),topHolding:filtered.length?[...filtered].sort((a,b)=>b.weightPct-a.weightPct)[0].name:'-'}),[filtered]);
  const sectorAlloc=useMemo(()=>{const m={};HOLDINGS.forEach(h=>{if(!m[h.sector])m[h.sector]={s:h.sector,wt:0,ret:0,esg:0,n:0};m[h.sector].wt+=h.weightPct;m[h.sector].ret+=h.returnYTD;m[h.sector].esg+=h.esgScore;m[h.sector].n++;});return Object.values(m).map(s=>({sector:s.s,weight:+s.wt.toFixed(1),avgReturn:+(s.ret/s.n).toFixed(1),avgESG:Math.round(s.esg/s.n)})).sort((a,b)=>b.weight-a.weight);},[]);
  const countryAlloc=useMemo(()=>{const m={};HOLDINGS.forEach(h=>{if(!m[h.country])m[h.country]={c:h.country,wt:0,n:0};m[h.country].wt+=h.weightPct;m[h.country].n++;});return Object.values(m).map(c=>({country:c.c,weight:+c.wt.toFixed(1),count:c.n})).sort((a,b)=>b.weight-a.weight);},[]);
  const perfHistory=Array.from({length:12},(_,m)=>({month:['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'][m],portfolio:+((m+1)*0.8+sr(m*7)*3-1.5).toFixed(1),benchmark:+((m+1)*0.6+sr(m*11)*2.5-1.2).toFixed(1)}));
  const exportCSV=useCallback((data,fn)=>{if(!data.length)return;const keys=Object.keys(data[0]);const csv=[keys.join(','),...data.map(r=>keys.map(k=>`"${r[k]}"`).join(','))].join('\n');const b=new Blob([csv],{type:'text/csv'});const u=URL.createObjectURL(b);const a=document.createElement('a');a.href=u;a.download=fn;a.click();URL.revokeObjectURL(u);},[]);
  const si=(col,cur,dir)=>cur===col?(dir==='asc'?' \u25B2':' \u25BC'):' \u25CB';
  const thS={padding:'8px 10px',fontSize:11,fontFamily:T.mono,color:T.textSec,cursor:'pointer',borderBottom:`1px solid ${T.border}`,whiteSpace:'nowrap',userSelect:'none',textAlign:'left',background:T.surfaceH};const tdS={padding:'7px 10px',fontSize:12,fontFamily:T.font,borderBottom:`1px solid ${T.border}`,color:T.text};const inpS={padding:'6px 12px',border:`1px solid ${T.border}`,borderRadius:6,fontSize:12,fontFamily:T.font,background:T.surface,color:T.text,outline:'none',width:220};const selS={padding:'6px 10px',border:`1px solid ${T.border}`,borderRadius:6,fontSize:11,fontFamily:T.font,background:T.surface,color:T.text};
  const btnS=a=>({padding:'6px 16px',border:`1px solid ${a?ACCENT:T.border}`,borderRadius:6,fontSize:12,fontFamily:T.font,background:a?ACCENT:T.surface,color:a?'#fff':T.text,cursor:'pointer',fontWeight:a?600:400});const pgB={padding:'4px 10px',border:`1px solid ${T.border}`,borderRadius:4,fontSize:11,cursor:'pointer',background:T.surface,color:T.text};const cS={background:T.surface,border:`1px solid ${T.border}`,borderRadius:10,padding:16};
  const kpi=(l,v,c)=>(<div style={{background:T.surface,border:`1px solid ${T.border}`,borderRadius:10,padding:'14px 18px',flex:1,minWidth:130}}><div style={{fontSize:10,color:T.textMut,fontFamily:T.mono,textTransform:'uppercase',letterSpacing:1}}>{l}</div><div style={{fontSize:22,fontWeight:700,color:c||T.navy,marginTop:4}}>{v}</div></div>);
  const retC=v=>v>0?T.green:v<0?T.red:T.textSec;
  const Panel=({item,onClose})=>{if(!item)return null;return(<div style={{position:'fixed',top:0,right:0,width:460,height:'100vh',background:T.surface,borderLeft:`2px solid ${ACCENT}`,zIndex:1000,overflowY:'auto',boxShadow:'-4px 0 24px rgba(0,0,0,0.10)'}}><div style={{padding:'20px 24px',borderBottom:`1px solid ${T.border}`,display:'flex',justifyContent:'space-between',alignItems:'center'}}><div><div style={{fontSize:16,fontWeight:700,color:T.navy}}>{item.name}</div><div style={{fontSize:12,color:T.textSec}}>{item.sector} | {item.country}</div></div><button onClick={onClose} style={{background:'none',border:'none',fontSize:20,cursor:'pointer',color:T.textMut}}>{'\u2715'}</button></div>
    <div style={{padding:'16px 24px'}}><div style={{display:'grid',gridTemplateColumns:'1fr 1fr 1fr',gap:8}}>{[['Weight',item.weightPct+'%'],['Mkt Cap','$'+item.mktCapBn+'B'],['1D',item.return1D+'%'],['1M',item.return1M+'%'],['YTD',item.returnYTD+'%'],['1Y',item.return1Y+'%'],['Volatility',item.volatility+'%'],['Beta',item.beta],['P/E',item.pe],['Div Yield',item.divYield+'%'],['ESG',item.esgScore+'/100'],['Carbon',item.carbonIntensity],['Green Rev',item.greenRevPct+'%'],['ITR',item.itr+'\u00B0C'],['Country',item.country]].map(([k,v],j)=>(<div key={j} style={{background:T.surfaceH,borderRadius:6,padding:'8px 10px'}}><div style={{fontSize:9,color:T.textMut,fontFamily:T.mono}}>{k}</div><div style={{fontSize:13,fontWeight:600,color:T.navy,marginTop:2}}>{v}</div></div>))}</div></div></div>);};
  const renderOverview=()=>(<div>
    <div style={{display:'flex',gap:12,marginBottom:20,flexWrap:'wrap'}}>{kpi('Holdings',stats.count)}{kpi('Total Weight',stats.totalWeight+'%')}{kpi('Avg 1D',stats.avgRet1D+'%',retC(+stats.avgRet1D))}{kpi('Avg YTD',stats.avgRetYTD+'%',retC(+stats.avgRetYTD))}{kpi('Avg ESG',stats.avgESG+'/100')}{kpi('Avg Carbon',stats.avgCarbon)}{kpi('Top Holding',stats.topHolding)}</div>
    <div style={{display:'flex',gap:12,marginBottom:16,alignItems:'center',flexWrap:'wrap'}}><input value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}} placeholder="Search holdings..." style={inpS}/><select value={sectorF} onChange={e=>{setSectorF(e.target.value);setPage(1);}} style={selS}>{SECTORS.map(s=><option key={s}>{s}</option>)}</select><button onClick={()=>exportCSV(filtered,'portfolio.csv')} style={btnS(false)}>Export CSV</button></div>
    <div style={{overflowX:'auto',...cS,padding:0}}><table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr>{[['name','Holding'],['sector','Sector'],['country','Country'],['weightPct','Wt%'],['returnYTD','YTD'],['return1Y','1Y'],['esgScore','ESG'],['carbonIntensity','Carbon']].map(([k,l])=><th key={k} onClick={()=>doSort(k)} style={thS}>{l}{si(k,sortCol,sortDir)}</th>)}</tr></thead>
      <tbody>{paged.map(r=><tr key={r.id} onClick={()=>setSelected(r)} style={{cursor:'pointer',background:selected?.id===r.id?T.surfaceH:'transparent'}}><td style={tdS}><span style={{fontWeight:600}}>{r.name}</span></td><td style={tdS}>{r.sector}</td><td style={tdS}>{r.country}</td><td style={tdS}>{r.weightPct}%</td><td style={tdS}><span style={{color:retC(r.returnYTD),fontWeight:600,fontFamily:T.mono,fontSize:11}}>{r.returnYTD>0?'+':''}{r.returnYTD}%</span></td><td style={tdS}><span style={{color:retC(r.return1Y),fontWeight:600,fontFamily:T.mono,fontSize:11}}>{r.return1Y>0?'+':''}{r.return1Y}%</span></td><td style={tdS}>{r.esgScore}</td><td style={tdS}>{r.carbonIntensity}</td></tr>)}</tbody></table></div>
    {totalPages>1&&<div style={{display:'flex',gap:6,marginTop:12,alignItems:'center',justifyContent:'center'}}><button onClick={()=>setPage(p=>Math.max(1,p-1))} disabled={page===1} style={pgB}>&laquo;</button><span style={{fontSize:11,color:T.textSec,fontFamily:T.mono}}>Page {page}/{totalPages}</span><button onClick={()=>setPage(p=>Math.min(totalPages,p+1))} disabled={page===totalPages} style={pgB}>&raquo;</button></div>}
    <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16,marginTop:20}}>
      <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Cumulative Performance</div><ResponsiveContainer width="100%" height={260}><LineChart data={perfHistory}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="month" tick={{fontSize:9,fill:T.textSec}}/><YAxis tick={{fontSize:9,fill:T.textSec}}/><Tooltip {...tip}/><Line type="monotone" dataKey="portfolio" stroke={T.navy} strokeWidth={2} name="Portfolio" dot={false}/><Line type="monotone" dataKey="benchmark" stroke={T.textMut} strokeWidth={2} name="Benchmark" dot={false} strokeDasharray="5 5"/><Legend/></LineChart></ResponsiveContainer></div>
      <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Sector Allocation</div><ResponsiveContainer width="100%" height={260}><PieChart><Pie data={sectorAlloc.slice(0,8)} cx="50%" cy="50%" outerRadius={90} dataKey="weight" label={({sector,weight})=>`${sector}: ${weight}%`}>{sectorAlloc.slice(0,8).map((_,i)=><Cell key={i} fill={COLORS[i%COLORS.length]}/>)}</Pie><Tooltip {...tip}/></PieChart></ResponsiveContainer></div>
    </div></div>);
  const renderSector=()=>(<div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16}}>
    <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Sector Weight & Return</div><ResponsiveContainer width="100%" height={300}><BarChart data={sectorAlloc}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="sector" tick={{fontSize:8,fill:T.textSec}} angle={-25}/><YAxis tick={{fontSize:9,fill:T.textSec}}/><Tooltip {...tip}/><Bar dataKey="weight" fill={T.navy} name="Weight %"/><Bar dataKey="avgReturn" fill={T.gold} name="Avg YTD %"/><Legend/></BarChart></ResponsiveContainer></div>
    <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Sector ESG Scores</div><ResponsiveContainer width="100%" height={300}><RadarChart data={sectorAlloc.slice(0,8).map(s=>({sector:s.sector,esg:s.avgESG}))}><PolarGrid stroke={T.border}/><PolarAngleAxis dataKey="sector" tick={{fontSize:8,fill:T.textSec}}/><PolarRadiusAxis domain={[0,100]} tick={{fontSize:8}}/><Radar dataKey="esg" stroke={ACCENT} fill="rgba(27,58,92,0.2)"/></RadarChart></ResponsiveContainer></div>
    <div style={{...cS,gridColumn:'1/3'}}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Return vs Volatility by Holding</div><ResponsiveContainer width="100%" height={280}><ScatterChart><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="x" name="Volatility" tick={{fontSize:9,fill:T.textSec}}/><YAxis dataKey="y" name="YTD Return" tick={{fontSize:9,fill:T.textSec}}/><Tooltip {...tip}/><Scatter data={filtered.map(h=>({name:h.name,x:h.volatility,y:h.returnYTD}))} fill={T.navy} fillOpacity={0.4}/></ScatterChart></ResponsiveContainer></div>
  </div></div>);
  const renderCountry=()=>(<div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16}}>
    <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Country Allocation</div><ResponsiveContainer width="100%" height={350}><BarChart data={countryAlloc.slice(0,15)} layout="vertical"><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis type="number" tick={{fontSize:9,fill:T.textSec}}/><YAxis type="category" dataKey="country" tick={{fontSize:9,fill:T.textSec}} width={50}/><Tooltip {...tip}/><Bar dataKey="weight" fill={ACCENT} radius={[0,4,4,0]}/></BarChart></ResponsiveContainer></div>
    <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Country Distribution</div><ResponsiveContainer width="100%" height={350}><PieChart><Pie data={countryAlloc.slice(0,10)} cx="50%" cy="50%" outerRadius={110} dataKey="weight" label={({country,weight})=>`${country}: ${weight}%`}>{countryAlloc.slice(0,10).map((_,i)=><Cell key={i} fill={COLORS[i%COLORS.length]}/>)}</Pie><Tooltip {...tip}/></PieChart></ResponsiveContainer></div>
  </div></div>);
  const renderESG=()=>(<div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16}}>
    <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>ESG Score Distribution</div><ResponsiveContainer width="100%" height={280}><BarChart data={[{r:'<50',c:filtered.filter(h=>h.esgScore<50).length},{r:'50-60',c:filtered.filter(h=>h.esgScore>=50&&h.esgScore<60).length},{r:'60-70',c:filtered.filter(h=>h.esgScore>=60&&h.esgScore<70).length},{r:'70-80',c:filtered.filter(h=>h.esgScore>=70&&h.esgScore<80).length},{r:'>80',c:filtered.filter(h=>h.esgScore>=80).length}]}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="r" tick={{fontSize:9,fill:T.textSec}}/><YAxis tick={{fontSize:9,fill:T.textSec}}/><Tooltip {...tip}/><Bar dataKey="c" fill={T.sage} radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></div>
    <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>ESG vs Return</div><ResponsiveContainer width="100%" height={280}><ScatterChart><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="x" name="ESG" tick={{fontSize:9,fill:T.textSec}}/><YAxis dataKey="y" name="YTD %" tick={{fontSize:9,fill:T.textSec}}/><Tooltip {...tip}/><Scatter data={filtered.map(h=>({name:h.name,x:h.esgScore,y:h.returnYTD}))} fill={T.sage} fillOpacity={0.5}/></ScatterChart></ResponsiveContainer></div>
    <div style={{...cS,gridColumn:'1/3'}}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Carbon Intensity by Sector</div><ResponsiveContainer width="100%" height={260}><BarChart data={sectorAlloc.map(s=>{const cos=HOLDINGS.filter(h=>h.sector===s.sector);return{sector:s.sector,carbon:Math.round(cos.reduce((sum,h)=>sum+h.carbonIntensity,0)/cos.length)};})}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="sector" tick={{fontSize:8,fill:T.textSec}} angle={-25}/><YAxis tick={{fontSize:9,fill:T.textSec}}/><Tooltip {...tip}/><Bar dataKey="carbon" fill={T.red} radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></div>
  </div></div>);
  return(<div style={{padding:'24px 32px',fontFamily:T.font,background:T.bg,minHeight:'100vh'}}>
    <div style={{marginBottom:20}}><h1 style={{fontSize:22,fontWeight:700,color:T.navy,margin:0}}>Portfolio Dashboard</h1><p style={{fontSize:12,color:T.textSec,margin:'4px 0 0'}}>100 holdings | Sector/country/ESG drill-down | Performance analytics</p></div>
    <div style={{display:'flex',gap:8,marginBottom:20}}>{TABS.map((t,i)=><button key={t} onClick={()=>setTab(i)} style={btnS(tab===i)}>{t}</button>)}</div>
    {tab===0&&renderOverview()}{tab===1&&renderSector()}{tab===2&&renderCountry()}{tab===3&&renderESG()}
    <Panel item={selected} onClose={()=>setSelected(null)}/>
  </div>);
}