import React,{useState,useMemo} from 'react';
import {BarChart,Bar,LineChart,Line,AreaChart,Area,PieChart,Pie,Cell,XAxis,YAxis,CartesianGrid,Tooltip,ResponsiveContainer,Legend,RadarChart,Radar,PolarGrid,PolarAngleAxis,PolarRadiusAxis,ScatterChart,Scatter,ZAxis} from 'recharts';
const T={bg:'#f6f4f0',surface:'#ffffff',surfaceH:'#f0ede7',border:'#e5e0d8',borderL:'#d5cfc5',navy:'#1b3a5c',navyL:'#2c5a8c',gold:'#c5a96a',goldL:'#d4be8a',sage:'#5a8a6a',sageL:'#7ba67d',teal:'#5a8a6a',text:'#1b3a5c',textSec:'#5c6b7e',textMut:'#9aa3ae',red:'#dc2626',green:'#16a34a',amber:'#d97706',font:"'DM Sans','SF Pro Display',system-ui,-apple-system,sans-serif",mono:"'JetBrains Mono','SF Mono','Fira Code',monospace"};
const sr=(s)=>{let x=Math.sin(s+1)*10000;return x-Math.floor(x);};
const CC=[T.navy,T.gold,T.sage,T.red,T.amber,T.green,T.navyL,T.goldL,'#8b5cf6','#ec4899','#06b6d4'];
const fmt=v=>typeof v==='number'?v>=1e9?(v/1e9).toFixed(1)+'B':v>=1e6?(v/1e6).toFixed(1)+'M':v>=1e3?(v/1e3).toFixed(1)+'K':v.toFixed(1):v;
const tip={contentStyle:{background:T.surface,border:`1px solid ${T.border}`,borderRadius:8,fontFamily:T.font,fontSize:12},labelStyle:{color:T.navy,fontWeight:600}};
const PAGE=12;const TABS=['Nature Overview','Species & Habitats','Dependency Analysis','Mitigation Tracker'];
const F1=['Agriculture','Mining','Forestry','Fisheries','Utilities','Chemicals','Food & Bev','Pharma','Tourism','Construction'];
const F2=['Amazon','Congo Basin','SE Asia','Coral Triangle','European Alps','Arctic','Cerrado','Borneo','Madagascar','Baltic'];
const ITEMS=Array.from({length:55},(_,i)=>{const names=['Cargill','ADM','Bunge','Wilmar','Syngenta','Bayer','BASF','BHP','Rio Tinto','Anglo American','Glencore','Vale','Nestle','Unilever','P&G','Coca-Cola','PepsiCo','Danone','JBS','Tyson','Marfrig','Weyerhaeuser','Suzano','APP','Mowi','SalMar','Thai Union','Shell','Total','BP','Exxon','Chevron','Duke Energy','NextEra','Enel','HeidelbergCement','LafargeHolcim','CRH','Accor','Marriott','Hilton','TUI','Carnival','Disney','Bayer','BASF','DuPont','Solvay','DSM','Evonik','Lanxess','Wacker','Clariant','Arkema','Solvay'];
  return{id:i+1,name:names[i%names.length],sector:F1[Math.floor(sr(i*3)*F1.length)],region:F2[Math.floor(sr(i*7)*F2.length)],biodivScore:+(sr(i*11)*60+20).toFixed(1),speciesImpact:Math.floor(sr(i*13)*50+5),habitatLoss:+(sr(i*17)*40+5).toFixed(1),dependency:+(sr(i*19)*80+10).toFixed(1),deforestRisk:+(sr(i*23)*60+5).toFixed(1),waterDep:+(sr(i*29)*70+15).toFixed(1),pollinDep:+(sr(i*31)*50+5).toFixed(1),soilDep:+(sr(i*37)*60+10).toFixed(1),tnfd:sr(i*41)>0.3,sbtn:sr(i*43)>0.35,disclosure:+(sr(i*47)*40+40).toFixed(1),revAtRisk:+(sr(i*59)*25+2).toFixed(1)};});
const TS=Array.from({length:12},(_,i)=>({period:''+(2014+i),v1:+(sr(i*61)*20+30).toFixed(1),v2:+(sr(i*67)*15+40).toFixed(1),v3:+(sr(i*71)*10+15).toFixed(1)}));
const exportCSV=(data,fn)=>{if(!data.length)return;const h=Object.keys(data[0]);const csv=[h.join(','),...data.map(r=>h.map(k=>JSON.stringify(r[k]??'')).join(','))].join('\n');const b=new Blob([csv],{type:'text/csv'});const u=URL.createObjectURL(b);const a=document.createElement('a');a.href=u;a.download=fn;a.click();URL.revokeObjectURL(u);};
export default function NatureHubPage(){
  const [tab,setTab]=useState(0);const [search,setSearch]=useState('');const [sortCol,setSortCol]=useState('biodivScore');const [sortDir,setSortDir]=useState('desc');const [page,setPage]=useState(0);const [expanded,setExpanded]=useState(null);const [f1,setF1v]=useState('All');const [f2,setF2v]=useState('All');
  const filtered=useMemo(()=>{let d=[...ITEMS];if(search)d=d.filter(x=>x.name.toLowerCase().includes(search.toLowerCase()));if(f1!=='All')d=d.filter(x=>x.sector===f1);if(f2!=='All')d=d.filter(x=>x.region===f2);d.sort((a,b)=>sortDir==='asc'?((a[sortCol]>b[sortCol])?1:-1):((a[sortCol]<b[sortCol])?1:-1));return d;},[search,sortCol,sortDir,f1,f2]);
  const paged=filtered.slice(page*PAGE,page*PAGE+PAGE);const totalPages=Math.ceil(filtered.length/PAGE);
  const doSort=col=>{if(sortCol===col)setSortDir(d=>d==='asc'?'desc':'asc');else{setSortCol(col);setSortDir('desc');}setPage(0);};
  const SH=({col,label,w})=><th onClick={()=>doSort(col)} style={{cursor:'pointer',padding:'10px 8px',textAlign:'left',borderBottom:`2px solid ${T.border}`,fontSize:11,fontWeight:700,color:T.textSec,fontFamily:T.mono,width:w,userSelect:'none',whiteSpace:'nowrap'}}>{label}{sortCol===col?(sortDir==='asc'?' \u25B2':' \u25BC'):''}</th>;
  const Pg=()=><div style={{display:'flex',justifyContent:'center',gap:6,marginTop:14}}><button onClick={()=>setPage(p=>Math.max(0,p-1))} disabled={page===0} style={{padding:'6px 14px',border:`1px solid ${T.border}`,borderRadius:6,background:T.surface,cursor:page===0?'default':'pointer',opacity:page===0?0.4:1,fontSize:12}}>Prev</button>{Array.from({length:Math.min(totalPages,7)},(_,i)=>{const p=totalPages<=7?i:page<3?i:page>totalPages-4?totalPages-7+i:page-3+i;return <button key={p} onClick={()=>setPage(p)} style={{padding:'6px 12px',border:`1px solid ${page===p?T.gold:T.border}`,borderRadius:6,background:page===p?T.gold:'transparent',color:page===p?'#fff':T.text,cursor:'pointer',fontWeight:page===p?700:400,fontSize:12}}>{p+1}</button>;})}<button onClick={()=>setPage(p=>Math.min(totalPages-1,p+1))} disabled={page>=totalPages-1} style={{padding:'6px 14px',border:`1px solid ${T.border}`,borderRadius:6,background:T.surface,cursor:page>=totalPages-1?'default':'pointer',opacity:page>=totalPages-1?0.4:1,fontSize:12}}>Next</button></div>;
  const kpis=useMemo(()=>[{l:'Entities',v:filtered.length},{l:'Avg Biodiv Score',v:(filtered.reduce((s,x)=>s+parseFloat(x.biodivScore),0)/filtered.length).toFixed(1)},{l:'TNFD Aligned',v:filtered.filter(x=>x.tnfd).length},{l:'Avg Habitat Loss',v:(filtered.reduce((s,x)=>s+parseFloat(x.habitatLoss),0)/filtered.length).toFixed(1)+'%'},{l:'SBTN Committed',v:filtered.filter(x=>x.sbtn).length}],[filtered]);
  const dist1=useMemo(()=>{const m={};F1.forEach(s=>m[s]=0);filtered.forEach(x=>m[x.sector]++);return Object.entries(m).filter(([,v])=>v>0).map(([name,value])=>({name:name.length>12?name.slice(0,12)+'..':name,value}));},[filtered]);
  const dist2=useMemo(()=>{const m={};F2.forEach(r=>m[r]=0);filtered.forEach(x=>m[x.region]++);return Object.entries(m).filter(([,v])=>v>0).map(([name,value])=>({name,value}));},[filtered]);
  const renderDash=()=>(<div>
    <div style={{display:'grid',gridTemplateColumns:`repeat(${kpis.length},1fr)`,gap:12,marginBottom:20}}>{kpis.map((k,i)=><div key={i} style={{background:T.surface,border:`1px solid ${T.border}`,borderRadius:10,padding:'16px 18px'}}><div style={{fontSize:11,color:T.textMut,fontFamily:T.mono,textTransform:'uppercase',letterSpacing:0.5}}>{k.l}</div><div style={{fontSize:24,fontWeight:700,color:T.navy,marginTop:4}}>{k.v}</div></div>)}</div>
    <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16,marginBottom:20}}>
      <div style={{background:T.surface,border:`1px solid ${T.border}`,borderRadius:10,padding:20}}><div style={{fontSize:14,fontWeight:700,color:T.navy,marginBottom:12}}>Biodiversity Trend</div><ResponsiveContainer width="100%" height={280}><AreaChart data={TS}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="period" tick={{fontSize:10,fill:T.textMut}}/><YAxis tick={{fontSize:10,fill:T.textMut}}/><Tooltip {...tip}/><Legend/><Area type="monotone" dataKey="v1" stroke={T.navy} fill={T.navy} fillOpacity={0.15} name="Biodiv Index"/><Area type="monotone" dataKey="v2" stroke={T.gold} fill={T.gold} fillOpacity={0.15} name="Habitat %"/></AreaChart></ResponsiveContainer></div>
      <div style={{background:T.surface,border:`1px solid ${T.border}`,borderRadius:10,padding:20}}><div style={{fontSize:14,fontWeight:700,color:T.navy,marginBottom:12}}>Sector Distribution</div><ResponsiveContainer width="100%" height={280}><PieChart><Pie data={dist1} dataKey="value" nameKey="name" cx="50%" cy="50%" outerRadius={100} label={({name,percent})=>`${name} ${(percent*100).toFixed(0)}%`}>{dist1.map((_,i)=><Cell key={i} fill={CC[i%CC.length]}/>)}</Pie><Tooltip {...tip}/></PieChart></ResponsiveContainer></div>
    </div>
    <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16,marginBottom:20}}>
      <div style={{background:T.surface,border:`1px solid ${T.border}`,borderRadius:10,padding:20}}><div style={{fontSize:14,fontWeight:700,color:T.navy,marginBottom:12}}>Regional Exposure</div><ResponsiveContainer width="100%" height={260}><BarChart data={dist2} layout="vertical"><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis type="number" tick={{fontSize:10,fill:T.textMut}}/><YAxis dataKey="name" type="category" width={100} tick={{fontSize:10,fill:T.textMut}}/><Tooltip {...tip}/><Bar dataKey="value" fill={T.sage} radius={[0,6,6,0]}/></BarChart></ResponsiveContainer></div>
      <div style={{background:T.surface,border:`1px solid ${T.border}`,borderRadius:10,padding:20}}><div style={{fontSize:14,fontWeight:700,color:T.navy,marginBottom:12}}>Species Impact Trend</div><ResponsiveContainer width="100%" height={260}><LineChart data={TS}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="period" tick={{fontSize:10,fill:T.textMut}}/><YAxis tick={{fontSize:10,fill:T.textMut}}/><Tooltip {...tip}/><Legend/><Line type="monotone" dataKey="v1" stroke={T.navy} strokeWidth={2} name="Biodiv Index"/><Line type="monotone" dataKey="v3" stroke={T.red} strokeWidth={2} name="Threat Level"/></LineChart></ResponsiveContainer></div>
    </div>
    <div style={{background:T.surface,border:`1px solid ${T.border}`,borderRadius:10,padding:20}}><div style={{fontSize:14,fontWeight:700,color:T.navy,marginBottom:12}}>Biodiversity vs Revenue at Risk</div><ResponsiveContainer width="100%" height={260}><ScatterChart><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="x" name="Biodiv Score" tick={{fontSize:10,fill:T.textMut}}/><YAxis dataKey="y" name="Rev at Risk %" tick={{fontSize:10,fill:T.textMut}}/><Tooltip {...tip}/><Scatter data={filtered.map(x=>({name:x.name,x:parseFloat(x.biodivScore),y:parseFloat(x.revAtRisk)}))} fill={T.navy} fillOpacity={0.5}/></ScatterChart></ResponsiveContainer></div>
  </div>);
  const renderTable=()=>(<div>
    <div style={{display:'flex',gap:12,marginBottom:16,flexWrap:'wrap',alignItems:'center'}}>
      <input value={search} onChange={e=>{setSearch(e.target.value);setPage(0);}} placeholder="Search entities..." style={{flex:1,minWidth:200,padding:'8px 14px',border:`1px solid ${T.border}`,borderRadius:8,fontSize:13,background:T.surface}}/>
      <select value={f1} onChange={e=>{setF1v(e.target.value);setPage(0);}} style={{padding:'8px 12px',border:`1px solid ${T.border}`,borderRadius:8,fontSize:13,background:T.surface}}><option value="All">All Sectors</option>{F1.map(s=><option key={s} value={s}>{s}</option>)}</select>
      <select value={f2} onChange={e=>{setF2v(e.target.value);setPage(0);}} style={{padding:'8px 12px',border:`1px solid ${T.border}`,borderRadius:8,fontSize:13,background:T.surface}}><option value="All">All Regions</option>{F2.map(r=><option key={r} value={r}>{r}</option>)}</select>
      <button onClick={()=>exportCSV(filtered,'nature_hub.csv')} style={{padding:'8px 16px',border:'none',borderRadius:8,background:T.gold,color:'#fff',fontWeight:600,fontSize:13,cursor:'pointer'}}>Export CSV</button>
    </div>
    <div style={{fontSize:12,color:T.textMut,marginBottom:8,fontFamily:T.mono}}>{filtered.length} entities | Page {page+1}/{totalPages}</div>
    <div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse',fontSize:12}}>
      <thead><tr style={{background:T.surfaceH}}><SH col="name" label="Entity" w="140px"/><SH col="sector" label="Sector"/><SH col="biodivScore" label="Biodiv Score"/><SH col="speciesImpact" label="Species"/><SH col="habitatLoss" label="Habitat Loss %"/><SH col="dependency" label="Dependency"/><SH col="deforestRisk" label="Deforest Risk"/><SH col="disclosure" label="Disclosure"/></tr></thead>
      <tbody>{paged.map(item=>(<React.Fragment key={item.id}>
        <tr onClick={()=>setExpanded(expanded===item.id?null:item.id)} style={{cursor:'pointer',background:expanded===item.id?T.surfaceH:'transparent',borderBottom:`1px solid ${T.border}`}}>
          <td style={{padding:'10px 8px',fontWeight:600,color:T.navy}}>{expanded===item.id?'\u25BC':'\u25B6'} {item.name}</td>
          <td style={{padding:'10px 8px'}}><span style={{padding:'2px 8px',borderRadius:10,fontSize:10,fontWeight:600,background:T.surfaceH,color:T.navy}}>{item.sector}</span></td>
          <td style={{padding:'10px 8px',fontFamily:T.mono}}>{item.biodivScore}</td>
          <td style={{padding:'10px 8px',fontFamily:T.mono}}>{item.speciesImpact}</td>
          <td style={{padding:'10px 8px',fontFamily:T.mono,color:parseFloat(item.habitatLoss)>25?T.red:T.green}}>{item.habitatLoss}%</td>
          <td style={{padding:'10px 8px',fontFamily:T.mono}}>{item.dependency}</td>
          <td style={{padding:'10px 8px',fontFamily:T.mono,color:parseFloat(item.deforestRisk)>30?T.red:T.green}}>{item.deforestRisk}</td>
          <td style={{padding:'10px 8px',fontFamily:T.mono}}>{item.disclosure}</td>
        </tr>
        {expanded===item.id&&(<tr><td colSpan={8} style={{padding:20,background:T.surfaceH,borderBottom:`2px solid ${T.gold}`}}>
          <div style={{display:'grid',gridTemplateColumns:'1fr 1fr 1fr',gap:16}}>
            <div><div style={{fontSize:13,fontWeight:700,color:T.navy,marginBottom:8}}>Nature Details</div>
              {[['Region',item.region],['TNFD Aligned',item.tnfd?'Yes':'No'],['SBTN Committed',item.sbtn?'Yes':'No'],['Water Dep',item.waterDep+'%'],['Pollination Dep',item.pollinDep+'%'],['Soil Dep',item.soilDep+'%'],['Rev at Risk',item.revAtRisk+'%']].map(([l,v])=><div key={l} style={{display:'flex',justifyContent:'space-between',padding:'4px 0',fontSize:12,borderBottom:`1px solid ${T.border}`}}><span style={{color:T.textMut}}>{l}</span><span style={{fontWeight:600,color:T.navy,fontFamily:T.mono}}>{v}</span></div>)}
            </div>
            <div><div style={{fontSize:13,fontWeight:700,color:T.navy,marginBottom:8}}>Assessment Notes</div><div style={{fontSize:12,color:T.textSec,lineHeight:1.6}}><p>Comprehensive nature dependency assessment for {item.name} across biodiversity, deforestation, and ecosystem service dimensions.</p><p>TNFD-aligned disclosure with {item.disclosure} disclosure score and {item.biodivScore} biodiversity rating.</p></div></div>
            <div><div style={{fontSize:13,fontWeight:700,color:T.navy,marginBottom:8}}>Nature Radar</div><ResponsiveContainer width="100%" height={200}><RadarChart data={[{m:'Biodiv',v:parseFloat(item.biodivScore)},{m:'Habitat',v:100-parseFloat(item.habitatLoss)},{m:'Dependency',v:parseFloat(item.dependency)},{m:'Deforest',v:parseFloat(item.deforestRisk)},{m:'Disclosure',v:parseFloat(item.disclosure)},{m:'Water',v:parseFloat(item.waterDep)}]}><PolarGrid stroke={T.border}/><PolarAngleAxis dataKey="m" tick={{fontSize:9}}/><PolarRadiusAxis domain={[0,100]} tick={{fontSize:8}}/><Radar dataKey="v" stroke={T.navy} fill={T.navy} fillOpacity={0.2}/></RadarChart></ResponsiveContainer></div>
          </div>
        </td></tr>)}
      </React.Fragment>))}</tbody>
    </table></div><Pg/>
  </div>);
  const renderAnalytics=()=>(<div>
    <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16,marginBottom:20}}>
      <div style={{background:T.surface,border:`1px solid ${T.border}`,borderRadius:10,padding:20}}><div style={{fontSize:14,fontWeight:700,color:T.navy,marginBottom:12}}>Dependency by Sector</div><ResponsiveContainer width="100%" height={280}><BarChart data={F1.map(s=>{const cs=filtered.filter(x=>x.sector===s);return{name:s.slice(0,10),dep:cs.length?(cs.reduce((sum,x)=>sum+parseFloat(x.dependency),0)/cs.length).toFixed(1):0};}).filter(d=>d.dep>0)}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="name" tick={{fontSize:8,fill:T.textMut}} angle={-45} textAnchor="end" height={60}/><YAxis tick={{fontSize:10,fill:T.textMut}}/><Tooltip {...tip}/><Bar dataKey="dep" fill={T.navy} radius={[6,6,0,0]} name="Avg Dependency"/></BarChart></ResponsiveContainer></div>
      <div style={{background:T.surface,border:`1px solid ${T.border}`,borderRadius:10,padding:20}}><div style={{fontSize:14,fontWeight:700,color:T.navy,marginBottom:12}}>Ecosystem Service Dependencies</div><ResponsiveContainer width="100%" height={280}><BarChart data={[{name:'Water',val:(filtered.reduce((s,x)=>s+parseFloat(x.waterDep),0)/filtered.length).toFixed(1)},{name:'Pollination',val:(filtered.reduce((s,x)=>s+parseFloat(x.pollinDep),0)/filtered.length).toFixed(1)},{name:'Soil',val:(filtered.reduce((s,x)=>s+parseFloat(x.soilDep),0)/filtered.length).toFixed(1)}]}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="name" tick={{fontSize:10,fill:T.textMut}}/><YAxis tick={{fontSize:10,fill:T.textMut}}/><Tooltip {...tip}/><Bar dataKey="val" fill={T.sage} radius={[6,6,0,0]} name="Avg Dependency %"/></BarChart></ResponsiveContainer></div>
    </div>
    <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16}}>
      <div style={{background:T.surface,border:`1px solid ${T.border}`,borderRadius:10,padding:20}}><div style={{fontSize:14,fontWeight:700,color:T.navy,marginBottom:12}}>TNFD & SBTN Status</div><ResponsiveContainer width="100%" height={260}><PieChart><Pie data={[{name:'TNFD Aligned',value:filtered.filter(x=>x.tnfd).length},{name:'SBTN Only',value:filtered.filter(x=>x.sbtn&&!x.tnfd).length},{name:'Neither',value:filtered.filter(x=>!x.tnfd&&!x.sbtn).length}]} dataKey="value" cx="50%" cy="50%" outerRadius={90} label>{[T.green,T.gold,T.border].map((c,i)=><Cell key={i} fill={c}/>)}</Pie><Tooltip {...tip}/><Legend/></PieChart></ResponsiveContainer></div>
      <div style={{background:T.surface,border:`1px solid ${T.border}`,borderRadius:10,padding:20}}><div style={{fontSize:14,fontWeight:700,color:T.navy,marginBottom:12}}>Deforestation vs Habitat Loss</div><ResponsiveContainer width="100%" height={260}><ScatterChart><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="x" name="Deforest Risk" tick={{fontSize:10,fill:T.textMut}}/><YAxis dataKey="y" name="Habitat Loss %" tick={{fontSize:10,fill:T.textMut}}/><Tooltip {...tip}/><Scatter data={filtered.map(x=>({name:x.name,x:parseFloat(x.deforestRisk),y:parseFloat(x.habitatLoss)}))} fill={T.red} fillOpacity={0.5}/></ScatterChart></ResponsiveContainer></div>
    </div>
  </div>);
  const renderMitigation=()=>(<div>
    <div style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:12,marginBottom:20}}>
      {[{l:'TNFD Aligned',v:filtered.filter(x=>x.tnfd).length+'/'+filtered.length},{l:'SBTN Committed',v:filtered.filter(x=>x.sbtn).length},{l:'Avg Disclosure',v:(filtered.reduce((s,x)=>s+parseFloat(x.disclosure),0)/filtered.length).toFixed(1)},{l:'High Deforest Risk',v:filtered.filter(x=>parseFloat(x.deforestRisk)>30).length}].map((k,i)=><div key={i} style={{background:T.surface,border:`1px solid ${T.border}`,borderRadius:10,padding:'16px 18px'}}><div style={{fontSize:11,color:T.textMut,fontFamily:T.mono,textTransform:'uppercase'}}>{k.l}</div><div style={{fontSize:22,fontWeight:700,color:T.navy,marginTop:4}}>{k.v}</div></div>)}
    </div>
    <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16,marginBottom:20}}>
      <div style={{background:T.surface,border:`1px solid ${T.border}`,borderRadius:10,padding:20}}><div style={{fontSize:14,fontWeight:700,color:T.navy,marginBottom:12}}>Disclosure Scores</div><ResponsiveContainer width="100%" height={280}><BarChart data={filtered.slice(0,15).map(x=>({name:x.name.slice(0,10),score:parseFloat(x.disclosure),deforest:parseFloat(x.deforestRisk)}))}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="name" tick={{fontSize:8,fill:T.textMut}} angle={-45} textAnchor="end" height={50}/><YAxis tick={{fontSize:10,fill:T.textMut}}/><Tooltip {...tip}/><Legend/><Bar dataKey="score" fill={T.navy} name="Disclosure" radius={[4,4,0,0]}/><Bar dataKey="deforest" fill={T.red} name="Deforest Risk" radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></div>
      <div style={{background:T.surface,border:`1px solid ${T.border}`,borderRadius:10,padding:20}}><div style={{fontSize:14,fontWeight:700,color:T.navy,marginBottom:12}}>Time Trend</div><ResponsiveContainer width="100%" height={280}><LineChart data={TS}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="period" tick={{fontSize:10,fill:T.textMut}}/><YAxis yAxisId="l" tick={{fontSize:10,fill:T.textMut}}/><YAxis yAxisId="r" orientation="right" tick={{fontSize:10,fill:T.textMut}}/><Tooltip {...tip}/><Legend/><Line yAxisId="l" type="monotone" dataKey="v1" stroke={T.navy} strokeWidth={2} name="Biodiv Index"/><Line yAxisId="r" type="monotone" dataKey="v3" stroke={T.gold} strokeWidth={2} name="Threat Level"/></LineChart></ResponsiveContainer></div>
    </div>
  </div>);
  return(<div style={{fontFamily:T.font,background:T.bg,minHeight:'100vh',padding:'24px 32px'}}>
    <div style={{marginBottom:24}}><div style={{fontSize:11,fontFamily:T.mono,color:T.textMut,textTransform:'uppercase',letterSpacing:1}}>Nature Capital</div><h1 style={{fontSize:28,fontWeight:800,color:T.navy,margin:'4px 0 0'}}>Nature & Biodiversity Hub</h1><div style={{width:40,height:3,background:T.gold,borderRadius:2,marginTop:6}}/></div>
    <div style={{display:'flex',gap:0,marginBottom:24,borderBottom:`2px solid ${T.border}`}}>{TABS.map((t,i)=><button key={t} onClick={()=>setTab(i)} style={{padding:'10px 20px',border:'none',borderBottom:tab===i?`3px solid ${T.gold}`:'3px solid transparent',background:'transparent',color:tab===i?T.navy:T.textMut,fontWeight:tab===i?700:500,fontSize:13,cursor:'pointer',fontFamily:T.font}}>{t}</button>)}</div>
    {tab===0&&renderDash()}{tab===1&&renderTable()}{tab===2&&renderAnalytics()}{tab===3&&renderMitigation()}
  </div>);
}