import React,{useState,useMemo,useCallback} from 'react';
import {BarChart,Bar,LineChart,Line,AreaChart,Area,PieChart,Pie,Cell,ScatterChart,Scatter,XAxis,YAxis,CartesianGrid,Tooltip,ResponsiveContainer,Legend,RadarChart,Radar,PolarGrid,PolarAngleAxis,PolarRadiusAxis} from 'recharts';
const T={bg:'#f6f4f0',surface:'#ffffff',surfaceH:'#f0ede7',border:'#e5e0d8',borderL:'#d5cfc5',navy:'#1b3a5c',navyL:'#2c5a8c',gold:'#c5a96a',goldL:'#d4be8a',sage:'#5a8a6a',sageL:'#7ba67d',teal:'#5a8a6a',text:'#1b3a5c',textSec:'#5c6b7e',textMut:'#9aa3ae',red:'#dc2626',green:'#16a34a',amber:'#d97706',font:"'DM Sans','SF Pro Display',system-ui,-apple-system,sans-serif",mono:"'JetBrains Mono','SF Mono','Fira Code',monospace"};
const sr=(s)=>{let x=Math.sin(s+1)*10000;return x-Math.floor(x);};
const ACCENT='#6d28d9';const tip={contentStyle:{background:T.surface,border:`1px solid ${T.border}`,borderRadius:8,fontSize:11,fontFamily:T.font},labelStyle:{color:T.textSec,fontFamily:T.mono,fontSize:10}};const COLORS=[T.navy,T.gold,T.sage,T.red,T.amber,T.green,T.navyL,T.goldL,'#8b5cf6'];
const TABS=['Scenario Builder','Impact Analysis','Pathway Comparison','Custom Scenarios'];const PAGE=12;
const PRESETS=[{id:1,name:'NGFS Net Zero 2050',carbonPrice:250,renewPct:90,tempC:1.5,gdp:-2,coalPhase:2040,evShare:85,h2Scale:'High',ccusGt:7},{id:2,name:'NGFS Delayed',carbonPrice:350,renewPct:75,tempC:1.8,gdp:-4.5,coalPhase:2050,evShare:65,h2Scale:'Medium',ccusGt:5},{id:3,name:'Current Policies',carbonPrice:50,renewPct:40,tempC:3.0,gdp:-8,coalPhase:2070,evShare:30,h2Scale:'Low',ccusGt:1},{id:4,name:'IEA NZE',carbonPrice:280,renewPct:88,tempC:1.4,gdp:-1.5,coalPhase:2035,evShare:90,h2Scale:'High',ccusGt:8},{id:5,name:'Below 2C',carbonPrice:180,renewPct:70,tempC:1.7,gdp:-3,coalPhase:2045,evShare:55,h2Scale:'Medium',ccusGt:4},{id:6,name:'Divergent NZ',carbonPrice:400,renewPct:85,tempC:1.5,gdp:-5,coalPhase:2040,evShare:80,h2Scale:'High',ccusGt:6}];
const SECTORS=['Energy','Utilities','Materials','Industrials','Technology','Financials','Consumer','Healthcare','Real Estate','Transport'];
const SECTOR_IMPACTS=PRESETS.map(p=>({scenario:p.name,...Object.fromEntries(SECTORS.map((s,i)=>[s,+((sr(p.id*100+i*7)-0.5)*Math.abs(p.gdp)*3).toFixed(1)]))}));
const TIMELINE=Array.from({length:7},(_,y)=>({year:2025+y*5,nz:+(1.2+y*0.04).toFixed(1),delayed:+(1.2+y*0.1).toFixed(1),current:+(1.2+y*0.28).toFixed(1),carbon_nz:Math.round(250+y*0),carbon_del:Math.round(50+y*45),carbon_cur:Math.round(20+y*5)}));
export default function TransitionScenarioModellerPage(){
  const[tab,setTab]=useState(0);const[scenarioId,setScenarioId]=useState(1);const[search,setSearch]=useState('');const[sortCol,setSortCol]=useState('gdp');const[sortDir,setSortDir]=useState('asc');const[page,setPage]=useState(1);const[selected,setSelected]=useState(null);
  const[customCarbon,setCustomCarbon]=useState(200);const[customRenew,setCustomRenew]=useState(70);const[customTemp,setCustomTemp]=useState(2.0);
  const curPreset=PRESETS.find(p=>p.id===scenarioId)||PRESETS[0];
  const sectorImpact=useMemo(()=>{const si=SECTOR_IMPACTS.find(s=>s.scenario===curPreset.name);if(!si)return[];return SECTORS.map(s=>({sector:s,impact:si[s]||0})).sort((a,b)=>a.impact-b.impact);},[curPreset]);
  const filteredPresets=useMemo(()=>{let d=[...PRESETS];if(search)d=d.filter(r=>r.name.toLowerCase().includes(search.toLowerCase()));d.sort((a,b)=>sortDir==='asc'?(a[sortCol]>b[sortCol]?1:-1):(a[sortCol]<b[sortCol]?1:-1));return d;},[search,sortCol,sortDir]);
  const doSort=col=>{if(sortCol===col)setSortDir(d=>d==='asc'?'desc':'asc');else{setSortCol(col);setSortDir('asc');}};
  const exportCSV=useCallback((data,fn)=>{if(!data.length)return;const keys=Object.keys(data[0]);const csv=[keys.join(','),...data.map(r=>keys.map(k=>`"${r[k]}"`).join(','))].join('\n');const b=new Blob([csv],{type:'text/csv'});const u=URL.createObjectURL(b);const a=document.createElement('a');a.href=u;a.download=fn;a.click();URL.revokeObjectURL(u);},[]);
  const si=(col,cur,dir)=>cur===col?(dir==='asc'?' \u25B2':' \u25BC'):' \u25CB';
  const thS={padding:'8px 10px',fontSize:11,fontFamily:T.mono,color:T.textSec,cursor:'pointer',borderBottom:`1px solid ${T.border}`,whiteSpace:'nowrap',userSelect:'none',textAlign:'left',background:T.surfaceH};const tdS={padding:'7px 10px',fontSize:12,fontFamily:T.font,borderBottom:`1px solid ${T.border}`,color:T.text};const inpS={padding:'6px 12px',border:`1px solid ${T.border}`,borderRadius:6,fontSize:12,fontFamily:T.font,background:T.surface,color:T.text,outline:'none',width:180};const selS={padding:'6px 10px',border:`1px solid ${T.border}`,borderRadius:6,fontSize:11,fontFamily:T.font,background:T.surface,color:T.text};
  const btnS=a=>({padding:'6px 16px',border:`1px solid ${a?ACCENT:T.border}`,borderRadius:6,fontSize:12,fontFamily:T.font,background:a?ACCENT:T.surface,color:a?'#fff':T.text,cursor:'pointer',fontWeight:a?600:400});const cS={background:T.surface,border:`1px solid ${T.border}`,borderRadius:10,padding:16};
  const kpi=(l,v,c)=>(<div style={{background:T.surface,border:`1px solid ${T.border}`,borderRadius:10,padding:'14px 18px',flex:1,minWidth:130}}><div style={{fontSize:10,color:T.textMut,fontFamily:T.mono,textTransform:'uppercase',letterSpacing:1}}>{l}</div><div style={{fontSize:22,fontWeight:700,color:c||T.navy,marginTop:4}}>{v}</div></div>);
  const sliderS={width:'100%',accentColor:ACCENT};
  const Panel=({item,onClose})=>{if(!item)return null;return(<div style={{position:'fixed',top:0,right:0,width:420,height:'100vh',background:T.surface,borderLeft:`2px solid ${ACCENT}`,zIndex:1000,overflowY:'auto',boxShadow:'-4px 0 24px rgba(0,0,0,0.10)'}}><div style={{padding:'20px 24px',borderBottom:`1px solid ${T.border}`,display:'flex',justifyContent:'space-between',alignItems:'center'}}><div style={{fontSize:16,fontWeight:700,color:T.navy}}>{item.name}</div><button onClick={onClose} style={{background:'none',border:'none',fontSize:20,cursor:'pointer',color:T.textMut}}>{'\u2715'}</button></div>
    <div style={{padding:'16px 24px'}}><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:8}}>{[['Carbon Price','$'+item.carbonPrice+'/t'],['Renewable',item.renewPct+'%'],['Temperature',item.tempC+'\u00B0C'],['GDP Impact',item.gdp+'%'],['Coal Phase-out',item.coalPhase],['EV Share',item.evShare+'%'],['H2 Scale',item.h2Scale],['CCUS',item.ccusGt+' GtCO2']].map(([k,v],j)=>(<div key={j} style={{background:T.surfaceH,borderRadius:6,padding:'8px 10px'}}><div style={{fontSize:9,color:T.textMut,fontFamily:T.mono}}>{k}</div><div style={{fontSize:13,fontWeight:600,color:T.navy,marginTop:2}}>{v}</div></div>))}</div></div></div>);};
  const renderBuilder=()=>(<div>
    <div style={{display:'flex',gap:12,marginBottom:16}}><span style={{fontSize:12,color:T.textSec,alignSelf:'center'}}>Scenario:</span><select value={scenarioId} onChange={e=>setScenarioId(+e.target.value)} style={selS}>{PRESETS.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></div>
    <div style={{display:'flex',gap:12,marginBottom:20,flexWrap:'wrap'}}>{kpi('Temperature',curPreset.tempC+'\u00B0C',curPreset.tempC>2?T.red:T.green)}{kpi('Carbon Price','$'+curPreset.carbonPrice+'/t')}{kpi('GDP Impact',curPreset.gdp+'%',T.red)}{kpi('Renewable',curPreset.renewPct+'%',T.green)}{kpi('Coal Phase-out',curPreset.coalPhase)}{kpi('EV Share',curPreset.evShare+'%')}{kpi('CCUS',curPreset.ccusGt+' Gt')}</div>
    <div style={{overflowX:'auto',...cS,padding:0,marginBottom:16}}><table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr>{[['name','Scenario'],['carbonPrice','CO2 $/t'],['renewPct','Renew%'],['tempC','Temp'],['gdp','GDP%'],['coalPhase','Coal Out'],['evShare','EV%']].map(([k,l])=><th key={k} onClick={()=>doSort(k)} style={thS}>{l}{si(k,sortCol,sortDir)}</th>)}</tr></thead>
      <tbody>{filteredPresets.map(r=><tr key={r.id} onClick={()=>{setScenarioId(r.id);setSelected(r);}} style={{cursor:'pointer',background:r.id===scenarioId?T.surfaceH:'transparent'}}><td style={tdS}><span style={{fontWeight:600}}>{r.name}</span></td><td style={tdS}>${r.carbonPrice}</td><td style={tdS}>{r.renewPct}%</td><td style={tdS}><span style={{color:r.tempC>2?T.red:T.green,fontWeight:600}}>{r.tempC}\u00B0C</span></td><td style={tdS}><span style={{color:T.red}}>{r.gdp}%</span></td><td style={tdS}>{r.coalPhase}</td><td style={tdS}>{r.evShare}%</td></tr>)}</tbody></table></div>
    <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16}}>
      <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Sector Impact</div><ResponsiveContainer width="100%" height={280}><BarChart data={sectorImpact}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="sector" tick={{fontSize:8,fill:T.textSec}} angle={-25}/><YAxis tick={{fontSize:9,fill:T.textSec}}/><Tooltip {...tip}/><Bar dataKey="impact">{sectorImpact.map((e,j)=><Cell key={j} fill={e.impact>=0?T.green:T.red}/>)}</Bar></BarChart></ResponsiveContainer></div>
      <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Scenario Radar</div><ResponsiveContainer width="100%" height={280}><RadarChart data={[{m:'Renewable',v:curPreset.renewPct},{m:'EV',v:curPreset.evShare},{m:'CCUS',v:curPreset.ccusGt*12},{m:'Carbon$',v:curPreset.carbonPrice/4},{m:'GDP',v:100+curPreset.gdp*5}]}><PolarGrid stroke={T.border}/><PolarAngleAxis dataKey="m" tick={{fontSize:9,fill:T.textSec}}/><PolarRadiusAxis domain={[0,100]} tick={{fontSize:8}}/><Radar dataKey="v" stroke={ACCENT} fill="rgba(109,40,217,0.2)"/></RadarChart></ResponsiveContainer></div>
    </div></div>);
  const renderImpact=()=>(<div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16}}>
    <div style={{...cS,gridColumn:'1/3'}}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Sector Impact Across Scenarios</div><ResponsiveContainer width="100%" height={300}><BarChart data={SECTOR_IMPACTS}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="scenario" tick={{fontSize:7,fill:T.textSec}} angle={-20}/><YAxis tick={{fontSize:9,fill:T.textSec}}/><Tooltip {...tip}/>{SECTORS.slice(0,5).map((s,i)=><Bar key={s} dataKey={s} fill={COLORS[i]}/>)}<Legend/></BarChart></ResponsiveContainer></div>
    <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Carbon Price vs GDP</div><ResponsiveContainer width="100%" height={280}><ScatterChart><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="x" name="Carbon $/t" tick={{fontSize:9,fill:T.textSec}}/><YAxis dataKey="y" name="GDP %" tick={{fontSize:9,fill:T.textSec}}/><Tooltip {...tip}/><Scatter data={PRESETS.map(p=>({name:p.name,x:p.carbonPrice,y:p.gdp}))} fill={ACCENT} fillOpacity={0.6}/></ScatterChart></ResponsiveContainer></div>
    <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Temperature Outcomes</div><ResponsiveContainer width="100%" height={280}><BarChart data={PRESETS}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="name" tick={{fontSize:7,fill:T.textSec}} angle={-20}/><YAxis tick={{fontSize:9,fill:T.textSec}} domain={[0,4]}/><Tooltip {...tip}/><Bar dataKey="tempC" radius={[4,4,0,0]}>{PRESETS.map((p,j)=><Cell key={j} fill={p.tempC>2?T.red:p.tempC>1.5?T.amber:T.green}/>)}</Bar></BarChart></ResponsiveContainer></div>
  </div></div>);
  const renderPathway=()=>(<div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16}}>
    <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Temperature Pathways</div><ResponsiveContainer width="100%" height={300}><LineChart data={TIMELINE}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="year" tick={{fontSize:9,fill:T.textSec}}/><YAxis tick={{fontSize:9,fill:T.textSec}} domain={[1,4]}/><Tooltip {...tip}/><Line type="monotone" dataKey="nz" stroke={T.green} strokeWidth={2} name="Net Zero"/><Line type="monotone" dataKey="delayed" stroke={T.amber} strokeWidth={2} name="Delayed"/><Line type="monotone" dataKey="current" stroke={T.red} strokeWidth={2} name="Current"/><Legend/></LineChart></ResponsiveContainer></div>
    <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Carbon Price Pathways</div><ResponsiveContainer width="100%" height={300}><AreaChart data={TIMELINE}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="year" tick={{fontSize:9,fill:T.textSec}}/><YAxis tick={{fontSize:9,fill:T.textSec}}/><Tooltip {...tip}/><Area type="monotone" dataKey="carbon_nz" stroke={T.green} fill="rgba(22,163,74,0.1)" name="NZ $/t"/><Area type="monotone" dataKey="carbon_del" stroke={T.amber} fill="rgba(217,119,6,0.1)" name="Delayed $/t"/><Area type="monotone" dataKey="carbon_cur" stroke={T.red} fill="rgba(220,38,38,0.1)" name="Current $/t"/><Legend/></AreaChart></ResponsiveContainer></div>
  </div></div>);
  const renderCustom=()=>(<div>
    <div style={{...cS,marginBottom:16}}><div style={{fontSize:13,fontWeight:600,color:T.navy,marginBottom:12}}>Custom Scenario Builder</div>
      <div style={{display:'grid',gridTemplateColumns:'1fr 1fr 1fr',gap:16}}>
        <div><div style={{fontSize:11,color:T.textSec}}>Carbon Price: <strong>${customCarbon}/t</strong></div><input type="range" min={20} max={500} value={customCarbon} onChange={e=>setCustomCarbon(+e.target.value)} style={sliderS}/></div>
        <div><div style={{fontSize:11,color:T.textSec}}>Renewable: <strong>{customRenew}%</strong></div><input type="range" min={20} max={100} value={customRenew} onChange={e=>setCustomRenew(+e.target.value)} style={sliderS}/></div>
        <div><div style={{fontSize:11,color:T.textSec}}>Target Temp: <strong>{customTemp}\u00B0C</strong></div><input type="range" min={12} max={40} value={Math.round(customTemp*10)} onChange={e=>setCustomTemp(+(e.target.value/10).toFixed(1))} style={sliderS}/></div>
      </div>
    </div>
    <div style={{display:'flex',gap:12,marginBottom:16,flexWrap:'wrap'}}>{kpi('Carbon Price','$'+customCarbon+'/t')}{kpi('Renewable',customRenew+'%',T.green)}{kpi('Temperature',customTemp+'\u00B0C',customTemp>2?T.red:T.green)}{kpi('Est. GDP',(-customCarbon*0.01-customTemp*1.5).toFixed(1)+'%',T.red)}</div>
    <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16}}>
      <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Custom vs Presets</div><ResponsiveContainer width="100%" height={280}><ScatterChart><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="x" name="Carbon$/t" tick={{fontSize:9,fill:T.textSec}}/><YAxis dataKey="y" name="Temp\u00B0C" tick={{fontSize:9,fill:T.textSec}}/><Tooltip {...tip}/><Scatter data={[...PRESETS.map(p=>({name:p.name,x:p.carbonPrice,y:p.tempC})),{name:'Custom',x:customCarbon,y:customTemp}]} fill={ACCENT} fillOpacity={0.6}/></ScatterChart></ResponsiveContainer></div>
      <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Custom Sector Impact Estimate</div><ResponsiveContainer width="100%" height={280}><BarChart data={SECTORS.map((s,i)=>({sector:s,impact:+((sr(i*7)-0.5)*customCarbon*0.02).toFixed(1)}))}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="sector" tick={{fontSize:8,fill:T.textSec}} angle={-25}/><YAxis tick={{fontSize:9,fill:T.textSec}}/><Tooltip {...tip}/><Bar dataKey="impact">{SECTORS.map((_,j)=><Cell key={j} fill={sr(j*7)>0.5?T.green:T.red}/>)}</Bar></BarChart></ResponsiveContainer></div>
    </div>
    <div style={{marginTop:12}}><button onClick={()=>exportCSV(PRESETS,'scenarios.csv')} style={btnS(false)}>Export All Scenarios CSV</button></div>
  </div>);
  return(<div style={{padding:'24px 32px',fontFamily:T.font,background:T.bg,minHeight:'100vh'}}>
    <div style={{marginBottom:20}}><h1 style={{fontSize:22,fontWeight:700,color:T.navy,margin:0}}>Transition Scenario Modeller</h1><p style={{fontSize:12,color:T.textSec,margin:'4px 0 0'}}>6 NGFS/IEA presets | Custom scenario builder | Impact modelling</p></div>
    <div style={{display:'flex',gap:8,marginBottom:20}}>{TABS.map((t,i)=><button key={t} onClick={()=>setTab(i)} style={btnS(tab===i)}>{t}</button>)}</div>
    {tab===0&&renderBuilder()}{tab===1&&renderImpact()}{tab===2&&renderPathway()}{tab===3&&renderCustom()}
    <Panel item={selected} onClose={()=>setSelected(null)}/>
  </div>);
}