import React,{useState,useMemo,useCallback} from 'react';
import {BarChart,Bar,LineChart,Line,AreaChart,Area,PieChart,Pie,Cell,ScatterChart,Scatter,XAxis,YAxis,CartesianGrid,Tooltip,ResponsiveContainer,Legend,RadarChart,Radar,PolarGrid,PolarAngleAxis,PolarRadiusAxis} from 'recharts';
const T={bg:'#f6f4f0',surface:'#ffffff',surfaceH:'#f0ede7',border:'#e5e0d8',borderL:'#d5cfc5',navy:'#1b3a5c',navyL:'#2c5a8c',gold:'#c5a96a',goldL:'#d4be8a',sage:'#5a8a6a',sageL:'#7ba67d',teal:'#5a8a6a',text:'#1b3a5c',textSec:'#5c6b7e',textMut:'#9aa3ae',red:'#dc2626',green:'#16a34a',amber:'#d97706',font:"'DM Sans','SF Pro Display',system-ui,-apple-system,sans-serif",mono:"'JetBrains Mono','SF Mono','Fira Code',monospace"};
const sr=(s)=>{let x=Math.sin(s+1)*10000;return x-Math.floor(x);};
const ACCENT='#0284c7';const tip={contentStyle:{background:T.surface,border:`1px solid ${T.border}`,borderRadius:8,fontSize:11,fontFamily:T.font},labelStyle:{color:T.textSec,fontFamily:T.mono,fontSize:10}};const COLORS=[T.navy,T.gold,T.sage,T.red,T.amber,T.green,T.navyL,T.goldL,'#8b5cf6'];
const fmt=v=>typeof v==='number'?v>=1e9?(v/1e9).toFixed(1)+'B':v>=1e6?(v/1e6).toFixed(1)+'M':v>=1e3?(v/1e3).toFixed(1)+'K':v.toFixed(1):v;
const TABS=['Water Risk Dashboard','Regional Analysis','Corporate Exposure','Projections'];const RISKF=['All','Extremely High','High','Medium-High','Medium','Low'];const PAGE=12;
import { isIndiaMode, adaptForWaterRisk } from '../../../data/IndiaDataAdapter';
const _DEFAULT_REGIONS=Array.from({length:40},(_,i)=>{
  const names=['Ganges Basin','Indus Basin','Yellow River','Yangtze Delta','Mekong Delta','Nile Valley','Murray-Darling','Colorado Basin','California Central','Sao Francisco','Tigris-Euphrates','Lake Chad','Aral Sea','Jordan River','Orange-Senqu','Volta Basin','Zambezi','Congo Basin','Amazon Basin','Mississippi Delta','Rhine-Meuse','Danube Basin','Po Valley','Tagus Basin','Guadalquivir','North China Plain','Deccan Plateau','Rajasthan Desert','Middle East Gulf','Sahel Region','Horn of Africa','Central Asian Steppe','Australian Outback','Atacama Region','Western US','Great Plains','SE Australia','Southern Africa','NW India','Pakistan Punjab'];
  const basins=['Ganges','Indus','Yellow','Yangtze','Mekong','Nile','Murray','Colorado','Sacramento','Sao Francisco','Tigris','Lake Chad','Aral','Jordan','Orange','Volta','Zambezi','Congo','Amazon','Mississippi','Rhine','Danube','Po','Tagus','Guadalquivir','Hai','Godavari','Thar','Gulf','Niger','Juba','Amu Darya','Cooper','Loa','Columbia','Missouri','Yarra','Limpopo','Sabarmati','Chenab'];
  const stressLevel=+(sr(i*7)*4+1).toFixed(1);const riskCat=stressLevel>4?'Extremely High':stressLevel>3?'High':stressLevel>2.5?'Medium-High':stressLevel>1.5?'Medium':'Low';
  const supply=Math.round(sr(i*11)*500+10);const demand=Math.round(supply*(sr(i*13)*0.5+0.6));const deficit=stressLevel>3?Math.max(supply*0.1,demand-supply):Math.max(0,demand-supply);
  const floodRisk=Math.round(sr(i*17)*100);const droughtRisk=Math.round(sr(i*19)*100);const pollutionIdx=Math.round(sr(i*23)*100);const groundwater=Math.round(sr(i*29)*80+10);
  const yearly=Array.from({length:6},(_,y)=>({year:2020+y,stress:+(stressLevel+y*0.08+sr(i*100+y)*0.3).toFixed(1),supply:Math.round(supply-y*5+sr(i*100+y*3)*10),demand:Math.round(demand+y*8+sr(i*100+y*7)*5)}));
  return{id:i+1,name:names[i],basin:basins[i],waterStress:stressLevel,riskCategory:riskCat,supplyBCM:supply,demandBCM:demand,deficitBCM:deficit,aqueductScore:+Math.min(5,stressLevel*0.9+sr(i*31)*0.5).toFixed(1),floodRisk,droughtRisk,pollutionIndex:pollutionIdx,groundwaterDepletion:groundwater,popAffectedM:+(sr(i*37)*50+1).toFixed(1),agWaterPct:Math.round(sr(i*41)*70+10),industrialPct:Math.round(sr(i*43)*30+5),domesticPct:Math.round(100-Math.round(sr(i*41)*70+10)-Math.round(sr(i*43)*30+5)),waterPrice:+(sr(i*47)*3+0.2).toFixed(2),infraInvestBn:+(sr(i*49)*10+0.5).toFixed(1),desalCapacity:Math.round(sr(i*51)*500),recycleRate:Math.round(sr(i*53)*60+10),yearly};
});
// ── India Dataset Integration ──
const REGIONS = isIndiaMode() ? adaptForWaterRisk().map((c, i) => ({
  id: i + 1, name: c.name + ' (' + c.basin + ')', basin: c.basin, waterStress: +(c.stressScore / 20).toFixed(1),
  riskCategory: c.stressScore > 80 ? 'Extremely High' : c.stressScore > 60 ? 'High' : c.stressScore > 40 ? 'Medium-High' : c.stressScore > 20 ? 'Medium' : 'Low',
  supplyBCM: Math.round(sr(i * 11) * 500 + 10), demandBCM: Math.round(sr(i * 13) * 400 + 20),
  deficitBCM: Math.max(0, Math.round(c.waterWithdrawal_m3 / 1e6)), aqueductScore: +(c.stressScore / 20).toFixed(1),
  floodRisk: Math.round(sr(i * 17) * 100), droughtRisk: Math.round(sr(i * 19) * 100),
  pollutionIndex: Math.round(sr(i * 23) * 100), groundwaterDepletion: Math.round(sr(i * 29) * 80 + 10),
  popAffectedM: +(sr(i * 37) * 50 + 1).toFixed(1), agWaterPct: Math.round(sr(i * 41) * 70 + 10),
  industrialPct: Math.round(sr(i * 43) * 30 + 5), domesticPct: Math.round(100 - Math.round(sr(i * 41) * 70 + 10) - Math.round(sr(i * 43) * 30 + 5)),
  waterPrice: +(sr(i * 47) * 3 + 0.2).toFixed(2), infraInvestBn: +(sr(i * 49) * 10 + 0.5).toFixed(1),
  desalCapacity: Math.round(sr(i * 51) * 500), recycleRate: Math.round(sr(i * 53) * 60 + 10),
  yearly: Array.from({ length: 6 }, (_, y) => ({ year: 2020 + y, stress: +(c.stressScore / 20 + y * 0.08).toFixed(1), supply: Math.round(sr(i * 100 + y) * 300 + 50), demand: Math.round(sr(i * 100 + y * 3) * 350 + 60) })),
})) : _DEFAULT_REGIONS;
export default function WaterRiskAnalyticsPage(){
  const[tab,setTab]=useState(0);const[search,setSearch]=useState('');const[riskF,setRiskF]=useState('All');const[sortCol,setSortCol]=useState('waterStress');const[sortDir,setSortDir]=useState('desc');const[page,setPage]=useState(1);const[selected,setSelected]=useState(null);
  const filtered=useMemo(()=>{let d=[...REGIONS];if(search)d=d.filter(r=>r.name.toLowerCase().includes(search.toLowerCase())||r.basin.toLowerCase().includes(search.toLowerCase()));if(riskF!=='All')d=d.filter(r=>r.riskCategory===riskF);d.sort((a,b)=>sortDir==='asc'?(a[sortCol]>b[sortCol]?1:-1):(a[sortCol]<b[sortCol]?1:-1));return d;},[search,riskF,sortCol,sortDir]);
  const paged=useMemo(()=>filtered.slice((page-1)*PAGE,page*PAGE),[filtered,page]);const totalPages=Math.ceil(filtered.length/PAGE);
  const doSort=col=>{if(sortCol===col)setSortDir(d=>d==='asc'?'desc':'asc');else{setSortCol(col);setSortDir('desc');}setPage(1);};
  const stats=useMemo(()=>{const d=Math.max(1,filtered.length);return{count:filtered.length,avgStress:(filtered.reduce((s,r)=>s+r.waterStress,0)/d).toFixed(1),extreme:filtered.filter(r=>r.riskCategory==='Extremely High').length,totalDeficit:Math.round(filtered.reduce((s,r)=>s+r.deficitBCM,0)),popAffected:fmt(filtered.reduce((s,r)=>s+r.popAffectedM,0)*1e6),avgGroundwater:Math.round(filtered.reduce((s,r)=>s+r.groundwaterDepletion,0)/d),totalInfra:'$'+filtered.reduce((s,r)=>s+r.infraInvestBn,0).toFixed(0)+'B'};},[filtered]);
  const riskDist=useMemo(()=>['Extremely High','High','Medium-High','Medium','Low'].map(r=>({name:r,value:REGIONS.filter(reg=>reg.riskCategory===r).length})),[]);
  const exportCSV=useCallback((data,fn)=>{if(!data.length)return;const keys=Object.keys(data[0]).filter(k=>k!=='yearly');const csv=[keys.join(','),...data.map(r=>keys.map(k=>`"${r[k]}"`).join(','))].join('\n');const b=new Blob([csv],{type:'text/csv'});const u=URL.createObjectURL(b);const a=document.createElement('a');a.href=u;a.download=fn;a.click();URL.revokeObjectURL(u);},[]);
  const si=(col,cur,dir)=>cur===col?(dir==='asc'?' \u25B2':' \u25BC'):' \u25CB';
  const thS={padding:'8px 10px',fontSize:11,fontFamily:T.mono,color:T.textSec,cursor:'pointer',borderBottom:`1px solid ${T.border}`,whiteSpace:'nowrap',userSelect:'none',textAlign:'left',background:T.surfaceH};const tdS={padding:'7px 10px',fontSize:12,fontFamily:T.font,borderBottom:`1px solid ${T.border}`,color:T.text};const inpS={padding:'6px 12px',border:`1px solid ${T.border}`,borderRadius:6,fontSize:12,fontFamily:T.font,background:T.surface,color:T.text,outline:'none',width:220};const selS={padding:'6px 10px',border:`1px solid ${T.border}`,borderRadius:6,fontSize:11,fontFamily:T.font,background:T.surface,color:T.text};
  const btnS=a=>({padding:'6px 16px',border:`1px solid ${a?ACCENT:T.border}`,borderRadius:6,fontSize:12,fontFamily:T.font,background:a?ACCENT:T.surface,color:a?'#fff':T.text,cursor:'pointer',fontWeight:a?600:400});const pgB={padding:'4px 10px',border:`1px solid ${T.border}`,borderRadius:4,fontSize:11,cursor:'pointer',background:T.surface,color:T.text};const cS={background:T.surface,border:`1px solid ${T.border}`,borderRadius:10,padding:16};
  const kpi=(l,v,c)=>(<div style={{background:T.surface,border:`1px solid ${T.border}`,borderRadius:10,padding:'14px 18px',flex:1,minWidth:130}}><div style={{fontSize:10,color:T.textMut,fontFamily:T.mono,textTransform:'uppercase',letterSpacing:1}}>{l}</div><div style={{fontSize:22,fontWeight:700,color:c||T.navy,marginTop:4}}>{v}</div></div>);
  const rBdg=r=>({color:r==='Extremely High'?T.red:r==='High'?T.amber:r==='Medium-High'?T.gold:r==='Medium'?T.sage:T.green,fontWeight:600,fontSize:11});
  const Panel=({item,onClose})=>{if(!item)return null;return(<div style={{position:'fixed',top:0,right:0,width:460,height:'100vh',background:T.surface,borderLeft:`2px solid ${ACCENT}`,zIndex:1000,overflowY:'auto',boxShadow:'-4px 0 24px rgba(0,0,0,0.10)'}}><div style={{padding:'20px 24px',borderBottom:`1px solid ${T.border}`,display:'flex',justifyContent:'space-between',alignItems:'center'}}><div><div style={{fontSize:16,fontWeight:700,color:T.navy}}>{item.name}</div><div style={{fontSize:12,color:T.textSec}}>{item.basin} Basin | {item.riskCategory}</div></div><button onClick={onClose} style={{background:'none',border:'none',fontSize:20,cursor:'pointer',color:T.textMut}}>{'\u2715'}</button></div>
    <div style={{padding:'16px 24px'}}>
      <div style={{display:'grid',gridTemplateColumns:'1fr 1fr 1fr',gap:8,marginBottom:16}}>{[['Stress',item.waterStress+'/5'],['Supply',item.supplyBCM+' BCM'],['Demand',item.demandBCM+' BCM'],['Deficit',item.deficitBCM+' BCM'],['Flood Risk',item.floodRisk+'/100'],['Drought Risk',item.droughtRisk+'/100'],['Pollution',item.pollutionIndex+'/100'],['Groundwater',item.groundwaterDepletion+'%'],['Pop Affected',item.popAffectedM+'M'],['Ag Water',item.agWaterPct+'%'],['Industrial',item.industrialPct+'%'],['Price','$'+item.waterPrice+'/m3'],['Infra Invest','$'+item.infraInvestBn+'B'],['Desal',item.desalCapacity+' ML/d'],['Recycle',item.recycleRate+'%']].map(([k,v],j)=>(<div key={j} style={{background:T.surfaceH,borderRadius:6,padding:'8px 10px'}}><div style={{fontSize:9,color:T.textMut,fontFamily:T.mono}}>{k}</div><div style={{fontSize:13,fontWeight:600,color:T.navy,marginTop:2}}>{v}</div></div>))}</div>
      <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Supply vs Demand Trend</div><ResponsiveContainer width="100%" height={180}><LineChart data={item.yearly}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="year" tick={{fontSize:9,fill:T.textSec}}/><YAxis tick={{fontSize:9,fill:T.textSec}}/><Tooltip {...tip}/><Line type="monotone" dataKey="supply" stroke={ACCENT} name="Supply BCM" strokeWidth={2}/><Line type="monotone" dataKey="demand" stroke={T.red} name="Demand BCM" strokeWidth={2}/><Legend/></LineChart></ResponsiveContainer></div>
      <div style={{...cS,marginTop:12}}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Risk Radar</div><ResponsiveContainer width="100%" height={200}><RadarChart data={[{m:'Water Stress',v:item.waterStress*20},{m:'Flood',v:item.floodRisk},{m:'Drought',v:item.droughtRisk},{m:'Pollution',v:item.pollutionIndex},{m:'Groundwater',v:item.groundwaterDepletion}]}><PolarGrid stroke={T.border}/><PolarAngleAxis dataKey="m" tick={{fontSize:8,fill:T.textSec}}/><PolarRadiusAxis domain={[0,100]} tick={{fontSize:8}}/><Radar dataKey="v" stroke={ACCENT} fill="rgba(2,132,199,0.2)"/></RadarChart></ResponsiveContainer></div>
    </div></div>);};
  const renderDash=()=>(<div>
    <div style={{display:'flex',gap:12,marginBottom:20,flexWrap:'wrap'}}>{kpi('Regions',stats.count)}{kpi('Avg Stress',stats.avgStress+'/5',+stats.avgStress>3?T.red:T.amber)}{kpi('Extreme Risk',stats.extreme,T.red)}{kpi('Total Deficit',stats.totalDeficit+' BCM')}{kpi('Pop Affected',stats.popAffected)}{kpi('Groundwater',stats.avgGroundwater+'%')}{kpi('Infra Invest',stats.totalInfra)}</div>
    <div style={{display:'flex',gap:12,marginBottom:16,alignItems:'center',flexWrap:'wrap'}}><input value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}} placeholder="Search regions..." style={inpS}/><select value={riskF} onChange={e=>{setRiskF(e.target.value);setPage(1);}} style={selS}>{RISKF.map(s=><option key={s}>{s}</option>)}</select><button onClick={()=>exportCSV(filtered,'water_risk.csv')} style={btnS(false)}>Export CSV</button></div>
    <div style={{overflowX:'auto',...cS,padding:0}}><table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr>{[['name','Region'],['basin','Basin'],['waterStress','Stress'],['riskCategory','Risk'],['deficitBCM','Deficit'],['droughtRisk','Drought'],['groundwaterDepletion','GW%'],['popAffectedM','Pop M']].map(([k,l])=><th key={k} onClick={()=>doSort(k)} style={thS}>{l}{si(k,sortCol,sortDir)}</th>)}</tr></thead>
      <tbody>{paged.map(r=><tr key={r.id} onClick={()=>setSelected(r)} style={{cursor:'pointer',background:selected?.id===r.id?T.surfaceH:'transparent'}}><td style={tdS}><span style={{fontWeight:600}}>{r.name}</span></td><td style={tdS}>{r.basin}</td><td style={tdS}>{r.waterStress}</td><td style={tdS}><span style={rBdg(r.riskCategory)}>{r.riskCategory}</span></td><td style={tdS}>{r.deficitBCM}</td><td style={tdS}>{r.droughtRisk}</td><td style={tdS}>{r.groundwaterDepletion}%</td><td style={tdS}>{r.popAffectedM}M</td></tr>)}</tbody></table></div>
    {totalPages>1&&<div style={{display:'flex',gap:6,marginTop:12,justifyContent:'center'}}><button onClick={()=>setPage(p=>Math.max(1,p-1))} disabled={page===1} style={pgB}>&laquo;</button><span style={{fontSize:11,color:T.textSec,fontFamily:T.mono}}>Page {page}/{totalPages}</span><button onClick={()=>setPage(p=>Math.min(totalPages,p+1))} disabled={page===totalPages} style={pgB}>&raquo;</button></div>}
    <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16,marginTop:20}}>
      <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Water Risk Distribution</div><ResponsiveContainer width="100%" height={260}><PieChart><Pie data={riskDist} cx="50%" cy="50%" outerRadius={90} dataKey="value" label={({name,value})=>`${name}: ${value}`}>{[T.red,T.amber,T.gold,T.sage,T.green].map((c,i)=><Cell key={i} fill={c}/>)}</Pie><Tooltip {...tip}/></PieChart></ResponsiveContainer></div>
      <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Water Stress Ranking (Top 15)</div><ResponsiveContainer width="100%" height={260}><BarChart data={[...REGIONS].sort((a,b)=>b.waterStress-a.waterStress).slice(0,15)} layout="vertical"><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis type="number" tick={{fontSize:9,fill:T.textSec}} domain={[0,5]}/><YAxis type="category" dataKey="name" tick={{fontSize:7,fill:T.textSec}} width={90}/><Tooltip {...tip}/><Bar dataKey="waterStress" fill={ACCENT} radius={[0,4,4,0]}/></BarChart></ResponsiveContainer></div>
    </div></div>);
  const renderRegional=()=>(<div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16}}>
    <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Drought vs Flood Risk</div><ResponsiveContainer width="100%" height={300}><ScatterChart><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="x" name="Drought" tick={{fontSize:9,fill:T.textSec}}/><YAxis dataKey="y" name="Flood" tick={{fontSize:9,fill:T.textSec}}/><Tooltip {...tip}/><Scatter data={filtered.map(r=>({name:r.name,x:r.droughtRisk,y:r.floodRisk}))} fill={ACCENT} fillOpacity={0.5}/></ScatterChart></ResponsiveContainer></div>
    <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Groundwater Depletion</div><ResponsiveContainer width="100%" height={300}><BarChart data={[...filtered].sort((a,b)=>b.groundwaterDepletion-a.groundwaterDepletion).slice(0,15)} layout="vertical"><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis type="number" tick={{fontSize:9,fill:T.textSec}} domain={[0,100]}/><YAxis type="category" dataKey="name" tick={{fontSize:7,fill:T.textSec}} width={90}/><Tooltip {...tip}/><Bar dataKey="groundwaterDepletion" fill={T.red} radius={[0,4,4,0]}/></BarChart></ResponsiveContainer></div>
    <div style={{...cS,gridColumn:'1/3'}}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Water Use Breakdown</div><ResponsiveContainer width="100%" height={260}><BarChart data={filtered.slice(0,15)}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="name" tick={{fontSize:7,fill:T.textSec}} angle={-30}/><YAxis tick={{fontSize:9,fill:T.textSec}} domain={[0,100]}/><Tooltip {...tip}/><Bar dataKey="agWaterPct" fill={T.sage} stackId="a" name="Agriculture"/><Bar dataKey="industrialPct" fill={T.navy} stackId="a" name="Industrial"/><Bar dataKey="domesticPct" fill={ACCENT} stackId="a" name="Domestic"/><Legend/></BarChart></ResponsiveContainer></div>
  </div></div>);
  const renderCorporate=()=>(<div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16}}>
    <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Pollution Index</div><ResponsiveContainer width="100%" height={300}><BarChart data={[...filtered].sort((a,b)=>b.pollutionIndex-a.pollutionIndex).slice(0,15)} layout="vertical"><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis type="number" tick={{fontSize:9,fill:T.textSec}} domain={[0,100]}/><YAxis type="category" dataKey="name" tick={{fontSize:7,fill:T.textSec}} width={90}/><Tooltip {...tip}/><Bar dataKey="pollutionIndex" fill={T.amber} radius={[0,4,4,0]}/></BarChart></ResponsiveContainer></div>
    <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Infrastructure Investment</div><ResponsiveContainer width="100%" height={300}><BarChart data={[...filtered].sort((a,b)=>b.infraInvestBn-a.infraInvestBn).slice(0,15)} layout="vertical"><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis type="number" tick={{fontSize:9,fill:T.textSec}}/><YAxis type="category" dataKey="name" tick={{fontSize:7,fill:T.textSec}} width={90}/><Tooltip {...tip}/><Bar dataKey="infraInvestBn" fill={T.gold} radius={[0,4,4,0]}/></BarChart></ResponsiveContainer></div>
  </div></div>);
  const renderProjections=()=>(<div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16}}>
    <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Water Stress vs Population</div><ResponsiveContainer width="100%" height={280}><ScatterChart><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="x" name="Stress" tick={{fontSize:9,fill:T.textSec}}/><YAxis dataKey="y" name="Pop (M)" tick={{fontSize:9,fill:T.textSec}}/><Tooltip {...tip}/><Scatter data={filtered.map(r=>({name:r.name,x:r.waterStress,y:r.popAffectedM}))} fill={T.red} fillOpacity={0.5}/></ScatterChart></ResponsiveContainer></div>
    <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Recycling Rate vs Stress</div><ResponsiveContainer width="100%" height={280}><ScatterChart><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="x" name="Recycle %" tick={{fontSize:9,fill:T.textSec}}/><YAxis dataKey="y" name="Stress" tick={{fontSize:9,fill:T.textSec}}/><Tooltip {...tip}/><Scatter data={filtered.map(r=>({name:r.name,x:r.recycleRate,y:r.waterStress}))} fill={T.sage} fillOpacity={0.5}/></ScatterChart></ResponsiveContainer></div>
    <div style={{...cS,gridColumn:'1/3'}}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Desalination Capacity</div><ResponsiveContainer width="100%" height={260}><BarChart data={[...REGIONS].filter(r=>r.desalCapacity>50).sort((a,b)=>b.desalCapacity-a.desalCapacity).slice(0,15)}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="name" tick={{fontSize:7,fill:T.textSec}} angle={-30}/><YAxis tick={{fontSize:9,fill:T.textSec}}/><Tooltip {...tip}/><Bar dataKey="desalCapacity" fill={ACCENT} radius={[4,4,0,0]} name="ML/day"/></BarChart></ResponsiveContainer></div>
  </div></div>);
  return(<div style={{padding:'24px 32px',fontFamily:T.font,background:T.bg,minHeight:'100vh'}}>
    <div style={{marginBottom:20}}><h1 style={{fontSize:22,fontWeight:700,color:T.navy,margin:0}}>Water Risk Analytics</h1><p style={{fontSize:12,color:T.textSec,margin:'4px 0 0'}}>40 regions | Aqueduct water stress, basin analysis, projections</p></div>
    <div style={{display:'flex',gap:8,marginBottom:20}}>{TABS.map((t,i)=><button key={t} onClick={()=>setTab(i)} style={btnS(tab===i)}>{t}</button>)}</div>
    {tab===0&&renderDash()}{tab===1&&renderRegional()}{tab===2&&renderCorporate()}{tab===3&&renderProjections()}
    <Panel item={selected} onClose={()=>setSelected(null)}/>
  </div>);
}