import React,{useState,useMemo,useCallback} from 'react';
import {BarChart,Bar,LineChart,Line,AreaChart,Area,PieChart,Pie,Cell,ScatterChart,Scatter,XAxis,YAxis,CartesianGrid,Tooltip,ResponsiveContainer,Legend,RadarChart,Radar,PolarGrid,PolarAngleAxis,PolarRadiusAxis} from 'recharts';
const T={bg:'#f6f4f0',surface:'#ffffff',surfaceH:'#f0ede7',border:'#e5e0d8',borderL:'#d5cfc5',navy:'#1b3a5c',navyL:'#2c5a8c',gold:'#c5a96a',goldL:'#d4be8a',sage:'#5a8a6a',sageL:'#7ba67d',teal:'#5a8a6a',text:'#1b3a5c',textSec:'#5c6b7e',textMut:'#9aa3ae',red:'#dc2626',green:'#16a34a',amber:'#d97706',font:"'DM Sans','SF Pro Display',system-ui,-apple-system,sans-serif",mono:"'JetBrains Mono','SF Mono','Fira Code',monospace"};
const sr=(s)=>{let x=Math.sin(s+1)*10000;return x-Math.floor(x);};
const ACCENT='#0ea5e9';const tip={contentStyle:{background:T.surface,border:`1px solid ${T.border}`,borderRadius:8,fontSize:11,fontFamily:T.font},labelStyle:{color:T.textSec,fontFamily:T.mono,fontSize:10}};const COLORS=[T.navy,T.gold,T.sage,T.red,T.amber,T.green,T.navyL,T.goldL,'#8b5cf6','#ec4899'];
const fmt=v=>typeof v==='number'?v>=1e9?(v/1e9).toFixed(1)+'B':v>=1e6?(v/1e6).toFixed(1)+'M':v>=1e3?(v/1e3).toFixed(1)+'K':v.toFixed(0):v;
const TABS=['Campaign Dashboard','Active Campaigns','Activist Profiles','Outcome Analysis'];const SECTORS=['All','Technology','Energy','Financials','Healthcare','Consumer','Industrials','Materials'];const PAGE=12;
const ACTIVISTS=['Elliott Management','Carl Icahn','Third Point','ValueAct','Trian Partners','Starboard Value','JANA Partners','Pershing Square','Engaged Capital','Sachem Head','Cevian Capital','TCI Fund','Bluebell Capital','Follow This','Engine No.1','Inclusive Capital','Green Century','As You Sow','ShareAction','Impax Asset'];
const CAMPAIGNS=Array.from({length:60},(_,i)=>{
  const targets=['ExxonMobil','Shell','Chevron','Disney','Salesforce','PayPal','Alphabet','Meta','Amazon','Walmart','J&J','P&G','Unilever','Nestle','BHP','Rio Tinto','BP','TotalEnergies','Barclays','HSBC','Citigroup','Goldman Sachs','JPMorgan','McDonalds','Starbucks','Coca-Cola','PepsiCo','Nike','Toyota','Samsung','Microsoft','Apple','Intel','IBM','GE','Boeing','Lockheed','Caterpillar','3M','DuPont','Dow','BASF','Bayer','Siemens','Volkswagen','Daimler','BMW','ArcelorMittal','Glencore','Anglo American','Newmont','Barrick Gold','Vale','Freeport','Southern Co','Duke Energy','Dominion','AES','NextEra','Enel'];
  const secs=['Energy','Energy','Energy','Technology','Technology','Technology','Technology','Technology','Technology','Consumer','Healthcare','Consumer','Consumer','Consumer','Materials','Materials','Energy','Energy','Financials','Financials','Financials','Financials','Financials','Consumer','Consumer','Consumer','Consumer','Consumer','Industrials','Technology','Technology','Technology','Technology','Technology','Industrials','Industrials','Industrials','Industrials','Materials','Materials','Materials','Materials','Materials','Industrials','Industrials','Industrials','Industrials','Materials','Materials','Materials','Materials','Materials','Materials','Materials','Energy','Energy','Energy','Energy','Energy','Energy'];
  const activist=ACTIVISTS[Math.floor(sr(i*7)*ACTIVISTS.length)];const target=targets[i%targets.length];const sector=secs[i%secs.length];
  const type=['Board Seat','Strategic Review','ESG Proposal','M&A Opposition','Capital Return','Governance Reform','Climate Action','Compensation Reform'][Math.floor(sr(i*11)*8)];
  const status=['Active','Settled','Won','Lost','Withdrawn'][Math.floor(sr(i*13)*5)];const stakeM=Math.round(sr(i*17)*5000+100);const stakePct=+(sr(i*19)*8+0.5).toFixed(1);
  return{id:i+1,target,sector,activist,campaignType:type,status,stakeMktValM:stakeM,stakeOwnershipPct:stakePct,boardSeatsWon:type==='Board Seat'?Math.round(sr(i*23)*3+1):0,startDate:`${2022+Math.floor(sr(i*29)*3)}-${String(Math.floor(sr(i*31)*12)+1).padStart(2,'0')}`,durationMonths:Math.round(sr(i*37)*24+3),proxyFight:sr(i*41)>0.7?'Yes':'No',settlementAchieved:status==='Settled'?'Yes':'No',stockImpact:+((sr(i*43)-0.4)*30).toFixed(1),esgFocus:sr(i*47)>0.5?'Yes':'No',supportPct:Math.round(sr(i*49)*40+20),coFilers:Math.round(sr(i*51)*5),mediaAttention:['High','Medium','Low'][Math.floor(sr(i*53)*3)]};
});
export default function ShareholderActivismPage(){
  const[tab,setTab]=useState(0);const[search,setSearch]=useState('');const[sectorF,setSectorF]=useState('All');const[sortCol,setSortCol]=useState('stakeMktValM');const[sortDir,setSortDir]=useState('desc');const[page,setPage]=useState(1);const[selected,setSelected]=useState(null);
  const filtered=useMemo(()=>{let d=[...CAMPAIGNS];if(search)d=d.filter(r=>r.target.toLowerCase().includes(search.toLowerCase())||r.activist.toLowerCase().includes(search.toLowerCase()));if(sectorF!=='All')d=d.filter(r=>r.sector===sectorF);d.sort((a,b)=>sortDir==='asc'?(a[sortCol]>b[sortCol]?1:-1):(a[sortCol]<b[sortCol]?1:-1));return d;},[search,sectorF,sortCol,sortDir]);
  const paged=useMemo(()=>filtered.slice((page-1)*PAGE,page*PAGE),[filtered,page]);const totalPages=Math.ceil(filtered.length/PAGE);
  const doSort=col=>{if(sortCol===col)setSortDir(d=>d==='asc'?'desc':'asc');else{setSortCol(col);setSortDir('desc');}setPage(1);};
  const stats=useMemo(()=>({count:filtered.length,active:filtered.filter(r=>r.status==='Active').length,totalStake:'$'+fmt(filtered.reduce((s,r)=>s+r.stakeMktValM,0)*1e6),won:filtered.filter(r=>r.status==='Won').length,esgFocused:filtered.filter(r=>r.esgFocus==='Yes').length,avgSupport:Math.round(filtered.reduce((s,r)=>s+r.supportPct,0)/filtered.length||0),proxyFights:filtered.filter(r=>r.proxyFight==='Yes').length}),[filtered]);
  const typeDist=useMemo(()=>{const m={};CAMPAIGNS.forEach(c=>{m[c.campaignType]=(m[c.campaignType]||0)+1;});return Object.entries(m).map(([k,v])=>({type:k,count:v})).sort((a,b)=>b.count-a.count);},[]);
  const activistRank=useMemo(()=>{const m={};CAMPAIGNS.forEach(c=>{if(!m[c.activist])m[c.activist]={name:c.activist,campaigns:0,wins:0,stake:0};m[c.activist].campaigns++;if(c.status==='Won')m[c.activist].wins++;m[c.activist].stake+=c.stakeMktValM;});return Object.values(m).sort((a,b)=>b.campaigns-a.campaigns).slice(0,12);},[]);
  const exportCSV=useCallback((data,fn)=>{if(!data.length)return;const keys=Object.keys(data[0]);const csv=[keys.join(','),...data.map(r=>keys.map(k=>`"${r[k]}"`).join(','))].join('\n');const b=new Blob([csv],{type:'text/csv'});const u=URL.createObjectURL(b);const a=document.createElement('a');a.href=u;a.download=fn;a.click();URL.revokeObjectURL(u);},[]);
  const si=(col,cur,dir)=>cur===col?(dir==='asc'?' \u25B2':' \u25BC'):' \u25CB';
  const thS={padding:'8px 10px',fontSize:11,fontFamily:T.mono,color:T.textSec,cursor:'pointer',borderBottom:`1px solid ${T.border}`,whiteSpace:'nowrap',userSelect:'none',textAlign:'left',background:T.surfaceH};const tdS={padding:'7px 10px',fontSize:12,fontFamily:T.font,borderBottom:`1px solid ${T.border}`,color:T.text};const inpS={padding:'6px 12px',border:`1px solid ${T.border}`,borderRadius:6,fontSize:12,fontFamily:T.font,background:T.surface,color:T.text,outline:'none',width:220};const selS={padding:'6px 10px',border:`1px solid ${T.border}`,borderRadius:6,fontSize:11,fontFamily:T.font,background:T.surface,color:T.text};
  const btnS=a=>({padding:'6px 16px',border:`1px solid ${a?ACCENT:T.border}`,borderRadius:6,fontSize:12,fontFamily:T.font,background:a?ACCENT:T.surface,color:a?'#fff':T.text,cursor:'pointer',fontWeight:a?600:400});const pgB={padding:'4px 10px',border:`1px solid ${T.border}`,borderRadius:4,fontSize:11,cursor:'pointer',background:T.surface,color:T.text};const cS={background:T.surface,border:`1px solid ${T.border}`,borderRadius:10,padding:16};
  const kpi=(l,v,c)=>(<div style={{background:T.surface,border:`1px solid ${T.border}`,borderRadius:10,padding:'14px 18px',flex:1,minWidth:130}}><div style={{fontSize:10,color:T.textMut,fontFamily:T.mono,textTransform:'uppercase',letterSpacing:1}}>{l}</div><div style={{fontSize:22,fontWeight:700,color:c||T.navy,marginTop:4}}>{v}</div></div>);
  const stBdg=s=>({color:s==='Won'?T.green:s==='Active'?ACCENT:s==='Settled'?T.gold:s==='Lost'?T.red:T.textMut,fontWeight:600,fontSize:11});
  const Panel=({item,onClose})=>{if(!item)return null;return(<div style={{position:'fixed',top:0,right:0,width:440,height:'100vh',background:T.surface,borderLeft:`2px solid ${ACCENT}`,zIndex:1000,overflowY:'auto',boxShadow:'-4px 0 24px rgba(0,0,0,0.10)'}}><div style={{padding:'20px 24px',borderBottom:`1px solid ${T.border}`,display:'flex',justifyContent:'space-between',alignItems:'center'}}><div><div style={{fontSize:16,fontWeight:700,color:T.navy}}>{item.target}</div><div style={{fontSize:12,color:T.textSec}}>by {item.activist}</div></div><button onClick={onClose} style={{background:'none',border:'none',fontSize:20,cursor:'pointer',color:T.textMut}}>{'\u2715'}</button></div>
    <div style={{padding:'16px 24px'}}><div style={{display:'grid',gridTemplateColumns:'1fr 1fr 1fr',gap:8}}>{[['Type',item.campaignType],['Status',item.status],['Stake','$'+fmt(item.stakeMktValM*1e6)],['Ownership',item.stakeOwnershipPct+'%'],['Board Seats',item.boardSeatsWon],['Start',item.startDate],['Duration',item.durationMonths+'mo'],['Proxy Fight',item.proxyFight],['Settlement',item.settlementAchieved],['Stock Impact',item.stockImpact+'%'],['ESG Focus',item.esgFocus],['Support',item.supportPct+'%'],['Co-filers',item.coFilers],['Media',item.mediaAttention]].map(([k,v],j)=>(<div key={j} style={{background:T.surfaceH,borderRadius:6,padding:'8px 10px'}}><div style={{fontSize:9,color:T.textMut,fontFamily:T.mono}}>{k}</div><div style={{fontSize:13,fontWeight:600,color:T.navy,marginTop:2}}>{v}</div></div>))}</div></div></div>);};
  const renderDash=()=>(<div>
    <div style={{display:'flex',gap:12,marginBottom:20,flexWrap:'wrap'}}>{kpi('Campaigns',stats.count)}{kpi('Active',stats.active,ACCENT)}{kpi('Total Stake',stats.totalStake)}{kpi('Won',stats.won,T.green)}{kpi('ESG Focus',stats.esgFocused)}{kpi('Avg Support',stats.avgSupport+'%')}{kpi('Proxy Fights',stats.proxyFights)}</div>
    <div style={{display:'flex',gap:12,marginBottom:16,alignItems:'center',flexWrap:'wrap'}}><input value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}} placeholder="Search target or activist..." style={inpS}/><select value={sectorF} onChange={e=>{setSectorF(e.target.value);setPage(1);}} style={selS}>{SECTORS.map(s=><option key={s}>{s}</option>)}</select><button onClick={()=>exportCSV(filtered,'activism.csv')} style={btnS(false)}>Export CSV</button></div>
    <div style={{overflowX:'auto',...cS,padding:0}}><table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr>{[['target','Target'],['activist','Activist'],['campaignType','Type'],['stakeMktValM','Stake $M'],['stakeOwnershipPct','Own%'],['status','Status'],['supportPct','Support%'],['esgFocus','ESG']].map(([k,l])=><th key={k} onClick={()=>doSort(k)} style={thS}>{l}{si(k,sortCol,sortDir)}</th>)}</tr></thead>
      <tbody>{paged.map(r=><tr key={r.id} onClick={()=>setSelected(r)} style={{cursor:'pointer',background:selected?.id===r.id?T.surfaceH:'transparent'}}><td style={tdS}><span style={{fontWeight:600}}>{r.target}</span></td><td style={{...tdS,fontSize:11}}>{r.activist}</td><td style={tdS}>{r.campaignType}</td><td style={tdS}>${fmt(r.stakeMktValM*1e6)}</td><td style={tdS}>{r.stakeOwnershipPct}%</td><td style={tdS}><span style={stBdg(r.status)}>{r.status}</span></td><td style={tdS}>{r.supportPct}%</td><td style={tdS}>{r.esgFocus}</td></tr>)}</tbody></table></div>
    {totalPages>1&&<div style={{display:'flex',gap:6,marginTop:12,alignItems:'center',justifyContent:'center'}}><button onClick={()=>setPage(p=>Math.max(1,p-1))} disabled={page===1} style={pgB}>&laquo;</button><span style={{fontSize:11,color:T.textSec,fontFamily:T.mono}}>Page {page}/{totalPages}</span><button onClick={()=>setPage(p=>Math.min(totalPages,p+1))} disabled={page===totalPages} style={pgB}>&raquo;</button></div>}
    <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16,marginTop:20}}>
      <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Campaign Type Distribution</div><ResponsiveContainer width="100%" height={260}><PieChart><Pie data={typeDist} cx="50%" cy="50%" outerRadius={90} dataKey="count" label={({type,count})=>`${type}: ${count}`}>{typeDist.map((_,i)=><Cell key={i} fill={COLORS[i%COLORS.length]}/>)}</Pie><Tooltip {...tip}/></PieChart></ResponsiveContainer></div>
      <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Status Breakdown</div><ResponsiveContainer width="100%" height={260}><PieChart><Pie data={['Active','Settled','Won','Lost','Withdrawn'].map(s=>({name:s,value:CAMPAIGNS.filter(c=>c.status===s).length}))} cx="50%" cy="50%" outerRadius={90} dataKey="value" label={({name,value})=>`${name}: ${value}`}>{[ACCENT,T.gold,T.green,T.red,T.textMut].map((c,i)=><Cell key={i} fill={c}/>)}</Pie><Tooltip {...tip}/></PieChart></ResponsiveContainer></div>
    </div></div>);
  const renderActive=()=>(<div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16}}>
    <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Largest Active Stakes</div><ResponsiveContainer width="100%" height={350}><BarChart data={[...CAMPAIGNS].filter(c=>c.status==='Active').sort((a,b)=>b.stakeMktValM-a.stakeMktValM).slice(0,12)} layout="vertical"><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis type="number" tick={{fontSize:9,fill:T.textSec}}/><YAxis type="category" dataKey="target" tick={{fontSize:8,fill:T.textSec}} width={80}/><Tooltip {...tip}/><Bar dataKey="stakeMktValM" fill={ACCENT} radius={[0,4,4,0]}/></BarChart></ResponsiveContainer></div>
    <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Campaigns by Sector</div><ResponsiveContainer width="100%" height={350}><BarChart data={SECTORS.slice(1).map(s=>({sector:s,count:CAMPAIGNS.filter(c=>c.sector===s).length}))}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="sector" tick={{fontSize:8,fill:T.textSec}} angle={-20}/><YAxis tick={{fontSize:9,fill:T.textSec}}/><Tooltip {...tip}/><Bar dataKey="count" fill={T.navy} radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></div>
  </div></div>);
  const renderProfiles=()=>(<div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16}}>
    <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Most Active Investors</div><ResponsiveContainer width="100%" height={350}><BarChart data={activistRank} layout="vertical"><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis type="number" tick={{fontSize:9,fill:T.textSec}}/><YAxis type="category" dataKey="name" tick={{fontSize:8,fill:T.textSec}} width={100}/><Tooltip {...tip}/><Bar dataKey="campaigns" fill={ACCENT} name="Campaigns" radius={[0,4,4,0]}/></BarChart></ResponsiveContainer></div>
    <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Win Rate by Activist</div><ResponsiveContainer width="100%" height={350}><BarChart data={activistRank.map(a=>({...a,winRate:a.campaigns>0?Math.round(a.wins/a.campaigns*100):0}))}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="name" tick={{fontSize:7,fill:T.textSec}} angle={-35}/><YAxis tick={{fontSize:9,fill:T.textSec}} domain={[0,100]}/><Tooltip {...tip}/><Bar dataKey="winRate" fill={T.green} radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></div>
  </div></div>);
  const renderOutcome=()=>(<div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16}}>
    <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Stock Impact Distribution</div><ResponsiveContainer width="100%" height={280}><BarChart data={[{r:'<-10%',c:CAMPAIGNS.filter(c=>c.stockImpact<-10).length},{r:'-10 to 0',c:CAMPAIGNS.filter(c=>c.stockImpact>=-10&&c.stockImpact<0).length},{r:'0 to 10%',c:CAMPAIGNS.filter(c=>c.stockImpact>=0&&c.stockImpact<10).length},{r:'>10%',c:CAMPAIGNS.filter(c=>c.stockImpact>=10).length}]}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="r" tick={{fontSize:9,fill:T.textSec}}/><YAxis tick={{fontSize:9,fill:T.textSec}}/><Tooltip {...tip}/><Bar dataKey="c" fill={ACCENT} radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></div>
    <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Support % vs Stock Impact</div><ResponsiveContainer width="100%" height={280}><ScatterChart><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="x" name="Support %" tick={{fontSize:9,fill:T.textSec}}/><YAxis dataKey="y" name="Stock Impact %" tick={{fontSize:9,fill:T.textSec}}/><Tooltip {...tip}/><Scatter data={filtered.map(c=>({name:c.target,x:c.supportPct,y:c.stockImpact}))} fill={ACCENT} fillOpacity={0.5}/></ScatterChart></ResponsiveContainer></div>
  </div></div>);
  return(<div style={{padding:'24px 32px',fontFamily:T.font,background:T.bg,minHeight:'100vh'}}>
    <div style={{marginBottom:20}}><h1 style={{fontSize:22,fontWeight:700,color:T.navy,margin:0}}>Shareholder Activism Intelligence</h1><p style={{fontSize:12,color:T.textSec,margin:'4px 0 0'}}>60 campaigns | Activist investors, ESG proposals, outcome analysis</p></div>
    <div style={{display:'flex',gap:8,marginBottom:20}}>{TABS.map((t,i)=><button key={t} onClick={()=>setTab(i)} style={btnS(tab===i)}>{t}</button>)}</div>
    {tab===0&&renderDash()}{tab===1&&renderActive()}{tab===2&&renderProfiles()}{tab===3&&renderOutcome()}
    <Panel item={selected} onClose={()=>setSelected(null)}/>
  </div>);
}