import React,{useState,useMemo,useCallback} from 'react';
import {BarChart,Bar,LineChart,Line,AreaChart,Area,PieChart,Pie,Cell,ScatterChart,Scatter,XAxis,YAxis,CartesianGrid,Tooltip,ResponsiveContainer,Legend,RadarChart,Radar,PolarGrid,PolarAngleAxis,PolarRadiusAxis} from 'recharts';
const T={bg:'#f6f4f0',surface:'#ffffff',surfaceH:'#f0ede7',border:'#e5e0d8',borderL:'#d5cfc5',navy:'#1b3a5c',navyL:'#2c5a8c',gold:'#c5a96a',goldL:'#d4be8a',sage:'#5a8a6a',sageL:'#7ba67d',teal:'#5a8a6a',text:'#1b3a5c',textSec:'#5c6b7e',textMut:'#9aa3ae',red:'#dc2626',green:'#16a34a',amber:'#d97706',font:"'DM Sans','SF Pro Display',system-ui,-apple-system,sans-serif",mono:"'JetBrains Mono','SF Mono','Fira Code',monospace"};
const sr=(s)=>{let x=Math.sin(s+1)*10000;return x-Math.floor(x);};
const ACCENT='#991b1b';const tip={contentStyle:{background:T.surface,border:`1px solid ${T.border}`,borderRadius:8,fontSize:11,fontFamily:T.font},labelStyle:{color:T.textSec,fontFamily:T.mono,fontSize:10}};const COLORS=[T.navy,T.gold,T.sage,T.red,T.amber,T.green,T.navyL,T.goldL,'#8b5cf6','#ec4899'];
const fmt=v=>typeof v==='number'?v>=1e6?(v/1e6).toFixed(1)+'M':v>=1e3?(v/1e3).toFixed(1)+'K':v.toFixed(0):v;
const TABS=['MSA Dashboard','Statement Analysis','Forced Labour Indicators','Supply Chain Risk'];const SECTORS=['All','Apparel','Consumer','Technology','Agriculture','Mining','Construction','Hospitality'];const PAGE=12;
const INDICATORS=['Debt Bondage','Excessive Overtime','Document Retention','Wage Withholding','Deceptive Recruitment','Restricted Movement','Isolation','Threats/Violence','Underpayment','Child Labour','Forced Marriage','Trafficking'];
const COS=Array.from({length:60},(_,i)=>{
  const names=['Nike','H&M','Walmart','Amazon','Apple','Nestle','Unilever','Tesco','Marks & Spencer','Sainsbury','Primark','Next plc','BHP','Rio Tinto','Anglo American','Glencore','Shell','BP','Foxconn','Samsung','Gap Inc','Inditex','LVMH','Adidas','Fast Retailing','VF Corp','PVH','Hanesbrands','Levi Strauss','Under Armour','JBS','Tyson','Cargill','Starbucks','McDonalds','Coca-Cola','PepsiCo','Mondelez','Mars','Danone','Marriott','Hilton','Balfour Beatty','Skanska','Vinci','Bouygues','Taylor Wimpey','Persimmon','Accor','InterContinental','Associated British Foods','Compass Group','G4S','Serco','Mitie','ISS','Sodexo','Wesfarmers','Woolworths','Coles'];
  const secs=['Apparel','Apparel','Consumer','Technology','Technology','Consumer','Consumer','Consumer','Consumer','Consumer','Apparel','Apparel','Mining','Mining','Mining','Mining','Mining','Mining','Technology','Technology','Apparel','Apparel','Consumer','Apparel','Apparel','Apparel','Apparel','Apparel','Apparel','Apparel','Agriculture','Agriculture','Agriculture','Hospitality','Hospitality','Consumer','Consumer','Consumer','Consumer','Consumer','Hospitality','Hospitality','Construction','Construction','Construction','Construction','Construction','Construction','Hospitality','Hospitality','Consumer','Hospitality','Hospitality','Hospitality','Hospitality','Hospitality','Hospitality','Consumer','Consumer','Consumer'];
  const msaScore=Math.round(sr(i*7)*60+30);const ukMSA=sr(i*11)>0.3;const ausMSA=sr(i*13)>0.5;const indicators=INDICATORS.filter((_,j)=>sr(i*100+j*7)>0.6).slice(0,Math.round(sr(i*17)*4+1));
  const supplyTiers=Math.round(sr(i*19)*5+1);const audits=Math.round(sr(i*23)*50+5);const violations=Math.round(sr(i*29)*10);const remediated=Math.round(violations*(sr(i*31)*0.5+0.3));
  const yearly=Array.from({length:5},(_,y)=>({year:2020+y,score:Math.round(msaScore-5+y*3+sr(i*100+y)*5),audits:Math.round(audits/5+sr(i*100+y*3)*3),violations:Math.round(violations/5-y*0.3+sr(i*100+y*7)*2)}));
  return{id:i+1,name:names[i],sector:secs[i],msaScore,ukMSA:ukMSA?'Filed':'N/A',ausMSA:ausMSA?'Filed':'N/A',indicatorCount:indicators.length,indicators,supplyTiers,totalAudits:audits,violations,remediated,remediationRate:violations>0?Math.round(remediated/violations*100):100,workerVoice:sr(i*37)>0.4?'Yes':'No',grievanceMech:sr(i*41)>0.3?'Active':'None',trainingPct:Math.round(sr(i*43)*60+20),highRiskCountries:Math.round(sr(i*47)*15+2),supplierCount:Math.round(sr(i*49)*2000+100),mappedPct:Math.round(sr(i*51)*60+20),riskLevel:msaScore>70?'Low':msaScore>50?'Medium':msaScore>30?'High':'Critical',statementQuality:['Comprehensive','Adequate','Basic','Minimal'][Math.floor(sr(i*53)*4)],boardSignoff:sr(i*57)>0.3?'Yes':'No',yearly};
});
export default function ModernSlaveryIntelPage(){
  const[tab,setTab]=useState(0);const[search,setSearch]=useState('');const[sectorF,setSectorF]=useState('All');const[sortCol,setSortCol]=useState('msaScore');const[sortDir,setSortDir]=useState('asc');const[page,setPage]=useState(1);const[selected,setSelected]=useState(null);
  const filtered=useMemo(()=>{let d=[...COS];if(search)d=d.filter(r=>r.name.toLowerCase().includes(search.toLowerCase()));if(sectorF!=='All')d=d.filter(r=>r.sector===sectorF);d.sort((a,b)=>sortDir==='asc'?(a[sortCol]>b[sortCol]?1:-1):(a[sortCol]<b[sortCol]?1:-1));return d;},[search,sectorF,sortCol,sortDir]);
  const paged=useMemo(()=>filtered.slice((page-1)*PAGE,page*PAGE),[filtered,page]);const totalPages=Math.ceil(filtered.length/PAGE);
  const doSort=col=>{if(sortCol===col)setSortDir(d=>d==='asc'?'desc':'asc');else{setSortCol(col);setSortDir('desc');}setPage(1);};
  const stats=useMemo(()=>({count:filtered.length,avgScore:Math.round(filtered.reduce((s,r)=>s+r.msaScore,0)/filtered.length||0),critical:filtered.filter(r=>r.riskLevel==='Critical').length,ukFiled:filtered.filter(r=>r.ukMSA==='Filed').length,ausFiled:filtered.filter(r=>r.ausMSA==='Filed').length,totalViolations:filtered.reduce((s,r)=>s+r.violations,0),avgRemediation:Math.round(filtered.reduce((s,r)=>s+r.remediationRate,0)/filtered.length||0)}),[filtered]);
  const sectorRisk=useMemo(()=>{const m={};COS.forEach(c=>{if(!m[c.sector])m[c.sector]={s:c.sector,score:0,viol:0,n:0};m[c.sector].score+=c.msaScore;m[c.sector].viol+=c.violations;m[c.sector].n++;});return Object.values(m).map(s=>({sector:s.s,score:Math.round(s.score/s.n),violations:s.viol})).sort((a,b)=>a.score-b.score);},[]);
  const indDist=useMemo(()=>{const m={};COS.forEach(c=>c.indicators.forEach(i=>{m[i]=(m[i]||0)+1;}));return Object.entries(m).map(([k,v])=>({indicator:k,count:v})).sort((a,b)=>b.count-a.count);},[]);
  const exportCSV=useCallback((data,fn)=>{if(!data.length)return;const keys=Object.keys(data[0]).filter(k=>k!=='yearly'&&k!=='indicators');const csv=[keys.join(','),...data.map(r=>keys.map(k=>`"${r[k]}"`).join(','))].join('\n');const b=new Blob([csv],{type:'text/csv'});const u=URL.createObjectURL(b);const a=document.createElement('a');a.href=u;a.download=fn;a.click();URL.revokeObjectURL(u);},[]);
  const si=(col,cur,dir)=>cur===col?(dir==='asc'?' \u25B2':' \u25BC'):' \u25CB';
  const thS={padding:'8px 10px',fontSize:11,fontFamily:T.mono,color:T.textSec,cursor:'pointer',borderBottom:`1px solid ${T.border}`,whiteSpace:'nowrap',userSelect:'none',textAlign:'left',background:T.surfaceH};const tdS={padding:'7px 10px',fontSize:12,fontFamily:T.font,borderBottom:`1px solid ${T.border}`,color:T.text};const inpS={padding:'6px 12px',border:`1px solid ${T.border}`,borderRadius:6,fontSize:12,fontFamily:T.font,background:T.surface,color:T.text,outline:'none',width:220};const selS={padding:'6px 10px',border:`1px solid ${T.border}`,borderRadius:6,fontSize:11,fontFamily:T.font,background:T.surface,color:T.text};
  const btnS=a=>({padding:'6px 16px',border:`1px solid ${a?ACCENT:T.border}`,borderRadius:6,fontSize:12,fontFamily:T.font,background:a?ACCENT:T.surface,color:a?'#fff':T.text,cursor:'pointer',fontWeight:a?600:400});const pgB={padding:'4px 10px',border:`1px solid ${T.border}`,borderRadius:4,fontSize:11,cursor:'pointer',background:T.surface,color:T.text};const cS={background:T.surface,border:`1px solid ${T.border}`,borderRadius:10,padding:16};
  const kpi=(l,v,c)=>(<div style={{background:T.surface,border:`1px solid ${T.border}`,borderRadius:10,padding:'14px 18px',flex:1,minWidth:140}}><div style={{fontSize:10,color:T.textMut,fontFamily:T.mono,textTransform:'uppercase',letterSpacing:1}}>{l}</div><div style={{fontSize:22,fontWeight:700,color:c||T.navy,marginTop:4}}>{v}</div></div>);
  const Panel=({item,onClose})=>{if(!item)return null;return(<div style={{position:'fixed',top:0,right:0,width:460,height:'100vh',background:T.surface,borderLeft:`2px solid ${ACCENT}`,zIndex:1000,overflowY:'auto',boxShadow:'-4px 0 24px rgba(0,0,0,0.10)'}}><div style={{padding:'20px 24px',borderBottom:`1px solid ${T.border}`,display:'flex',justifyContent:'space-between',alignItems:'center'}}><div><div style={{fontSize:16,fontWeight:700,color:T.navy}}>{item.name}</div><div style={{fontSize:12,color:T.textSec}}>{item.sector} | {item.riskLevel} Risk</div></div><button onClick={onClose} style={{background:'none',border:'none',fontSize:20,cursor:'pointer',color:T.textMut}}>{'\u2715'}</button></div>
    <div style={{padding:'16px 24px'}}>
      <div style={{display:'grid',gridTemplateColumns:'1fr 1fr 1fr',gap:8,marginBottom:12}}>{[['MSA Score',item.msaScore+'/100'],['UK MSA',item.ukMSA],['Aus MSA',item.ausMSA],['Indicators',item.indicatorCount],['Supply Tiers',item.supplyTiers],['Audits',item.totalAudits],['Violations',item.violations],['Remediation',item.remediationRate+'%'],['Worker Voice',item.workerVoice],['Grievance',item.grievanceMech],['Training',item.trainingPct+'%'],['High Risk Ctry',item.highRiskCountries],['Suppliers',item.supplierCount],['Mapped',item.mappedPct+'%'],['Board Sign',item.boardSignoff]].map(([k,v],j)=>(<div key={j} style={{background:T.surfaceH,borderRadius:6,padding:'8px 10px'}}><div style={{fontSize:9,color:T.textMut,fontFamily:T.mono}}>{k}</div><div style={{fontSize:13,fontWeight:600,color:T.navy,marginTop:2}}>{v}</div></div>))}</div>
      <div style={{marginBottom:12}}><div style={{fontSize:11,color:T.textSec,marginBottom:4}}>Indicators:</div><div style={{display:'flex',flexWrap:'wrap',gap:4}}>{item.indicators.map(i=><span key={i} style={{background:'rgba(153,27,27,0.08)',color:ACCENT,padding:'2px 6px',borderRadius:4,fontSize:9}}>{i}</span>)}</div></div>
      <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>5-Year Trend</div><ResponsiveContainer width="100%" height={180}><LineChart data={item.yearly}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="year" tick={{fontSize:9,fill:T.textSec}}/><YAxis tick={{fontSize:9,fill:T.textSec}}/><Tooltip {...tip}/><Line type="monotone" dataKey="score" stroke={T.green} name="MSA Score" strokeWidth={2}/><Line type="monotone" dataKey="violations" stroke={T.red} name="Violations" strokeWidth={2}/><Legend/></LineChart></ResponsiveContainer></div>
    </div></div>);};
  const renderDash=()=>(<div>
    <div style={{display:'flex',gap:12,marginBottom:20,flexWrap:'wrap'}}>{kpi('Companies',stats.count)}{kpi('Avg MSA Score',stats.avgScore+'/100')}{kpi('Critical Risk',stats.critical,T.red)}{kpi('UK MSA Filed',stats.ukFiled)}{kpi('Aus MSA Filed',stats.ausFiled)}{kpi('Total Violations',stats.totalViolations,T.red)}{kpi('Avg Remediation',stats.avgRemediation+'%')}</div>
    <div style={{display:'flex',gap:12,marginBottom:16,alignItems:'center',flexWrap:'wrap'}}><input value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}} placeholder="Search companies..." style={inpS}/><select value={sectorF} onChange={e=>{setSectorF(e.target.value);setPage(1);}} style={selS}>{SECTORS.map(s=><option key={s}>{s}</option>)}</select><button onClick={()=>exportCSV(filtered,'modern_slavery.csv')} style={btnS(false)}>Export CSV</button></div>
    <div style={{overflowX:'auto',...cS,padding:0}}><table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr>{[['name','Company'],['sector','Sector'],['msaScore','MSA'],['ukMSA','UK'],['violations','Viol.'],['remediationRate','Remed%'],['riskLevel','Risk'],['statementQuality','Quality']].map(([k,l])=><th key={k} onClick={()=>doSort(k)} style={thS}>{l}{si(k,sortCol,sortDir)}</th>)}</tr></thead>
      <tbody>{paged.map(r=><tr key={r.id} onClick={()=>setSelected(r)} style={{cursor:'pointer',background:selected?.id===r.id?T.surfaceH:'transparent'}}><td style={tdS}><span style={{fontWeight:600}}>{r.name}</span></td><td style={tdS}>{r.sector}</td><td style={tdS}>{r.msaScore}</td><td style={tdS}>{r.ukMSA}</td><td style={tdS}>{r.violations}</td><td style={tdS}>{r.remediationRate}%</td><td style={tdS}><span style={{color:r.riskLevel==='Critical'?T.red:r.riskLevel==='High'?T.amber:r.riskLevel==='Medium'?T.gold:T.green,fontWeight:600,fontSize:11}}>{r.riskLevel}</span></td><td style={tdS}>{r.statementQuality}</td></tr>)}</tbody></table></div>
    {totalPages>1&&<div style={{display:'flex',gap:6,marginTop:12,alignItems:'center',justifyContent:'center'}}><button onClick={()=>setPage(p=>Math.max(1,p-1))} disabled={page===1} style={pgB}>&laquo;</button><span style={{fontSize:11,color:T.textSec,fontFamily:T.mono}}>Page {page}/{totalPages}</span><button onClick={()=>setPage(p=>Math.min(totalPages,p+1))} disabled={page===totalPages} style={pgB}>&raquo;</button></div>}
    <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16,marginTop:20}}>
      <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>MSA Score by Sector</div><ResponsiveContainer width="100%" height={260}><BarChart data={sectorRisk}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="sector" tick={{fontSize:8,fill:T.textSec}} angle={-25}/><YAxis tick={{fontSize:9,fill:T.textSec}} domain={[0,100]}/><Tooltip {...tip}/><Bar dataKey="score" fill={ACCENT} radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></div>
      <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Risk Level Distribution</div><ResponsiveContainer width="100%" height={260}><PieChart><Pie data={[{n:'Critical',v:COS.filter(c=>c.riskLevel==='Critical').length},{n:'High',v:COS.filter(c=>c.riskLevel==='High').length},{n:'Medium',v:COS.filter(c=>c.riskLevel==='Medium').length},{n:'Low',v:COS.filter(c=>c.riskLevel==='Low').length}]} cx="50%" cy="50%" outerRadius={90} dataKey="v" label={({n,v})=>`${n}: ${v}`}>{[T.red,T.amber,T.gold,T.green].map((c,i)=><Cell key={i} fill={c}/>)}</Pie><Tooltip {...tip}/></PieChart></ResponsiveContainer></div>
    </div></div>);
  const renderStatement=()=>(<div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16}}>
    <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Statement Quality Distribution</div><ResponsiveContainer width="100%" height={280}><PieChart><Pie data={['Comprehensive','Adequate','Basic','Minimal'].map(q=>({name:q,value:COS.filter(c=>c.statementQuality===q).length}))} cx="50%" cy="50%" outerRadius={90} dataKey="value" label={({name,value})=>`${name}: ${value}`}>{COLORS.slice(0,4).map((c,i)=><Cell key={i} fill={c}/>)}</Pie><Tooltip {...tip}/></PieChart></ResponsiveContainer></div>
    <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Board Signoff Rate by Sector</div><ResponsiveContainer width="100%" height={280}><BarChart data={SECTORS.slice(1).map(s=>{const cos=COS.filter(c=>c.sector===s);return{sector:s,pct:cos.length?Math.round(cos.filter(c=>c.boardSignoff==='Yes').length/cos.length*100):0};})}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="sector" tick={{fontSize:8,fill:T.textSec}} angle={-20}/><YAxis tick={{fontSize:9,fill:T.textSec}} domain={[0,100]}/><Tooltip {...tip}/><Bar dataKey="pct" fill={T.navy} radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></div>
  </div></div>);
  const renderFL=()=>(<div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16}}>
    <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Most Common Indicators</div><ResponsiveContainer width="100%" height={350}><BarChart data={indDist.slice(0,10)} layout="vertical"><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis type="number" tick={{fontSize:9,fill:T.textSec}}/><YAxis type="category" dataKey="indicator" tick={{fontSize:8,fill:T.textSec}} width={110}/><Tooltip {...tip}/><Bar dataKey="count" fill={ACCENT} radius={[0,4,4,0]}/></BarChart></ResponsiveContainer></div>
    <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Violations by Sector</div><ResponsiveContainer width="100%" height={350}><BarChart data={sectorRisk}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="sector" tick={{fontSize:8,fill:T.textSec}} angle={-25}/><YAxis tick={{fontSize:9,fill:T.textSec}}/><Tooltip {...tip}/><Bar dataKey="violations" fill={T.red} radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></div>
  </div></div>);
  const renderSupply=()=>(<div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16}}>
    <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Supply Chain Mapping %</div><ResponsiveContainer width="100%" height={280}><BarChart data={[...filtered].sort((a,b)=>b.mappedPct-a.mappedPct).slice(0,15)} layout="vertical"><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis type="number" tick={{fontSize:9,fill:T.textSec}} domain={[0,100]}/><YAxis type="category" dataKey="name" tick={{fontSize:8,fill:T.textSec}} width={80}/><Tooltip {...tip}/><Bar dataKey="mappedPct" fill={T.sage} radius={[0,4,4,0]}/></BarChart></ResponsiveContainer></div>
    <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Audits vs Violations</div><ResponsiveContainer width="100%" height={280}><ScatterChart><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="x" name="Audits" tick={{fontSize:9,fill:T.textSec}}/><YAxis dataKey="y" name="Violations" tick={{fontSize:9,fill:T.textSec}}/><Tooltip {...tip}/><Scatter data={filtered.map(c=>({name:c.name,x:c.totalAudits,y:c.violations}))} fill={T.red} fillOpacity={0.5}/></ScatterChart></ResponsiveContainer></div>
  </div></div>);
  return(<div style={{padding:'24px 32px',fontFamily:T.font,background:T.bg,minHeight:'100vh'}}>
    <div style={{marginBottom:20}}><h1 style={{fontSize:22,fontWeight:700,color:T.navy,margin:0}}>Modern Slavery Intelligence</h1><p style={{fontSize:12,color:T.textSec,margin:'4px 0 0'}}>60 companies | UK/Aus MSA, forced labour indicators, supply chain risk</p></div>
    <div style={{display:'flex',gap:8,marginBottom:20}}>{TABS.map((t,i)=><button key={t} onClick={()=>setTab(i)} style={btnS(tab===i)}>{t}</button>)}</div>
    {tab===0&&renderDash()}{tab===1&&renderStatement()}{tab===2&&renderFL()}{tab===3&&renderSupply()}
    <Panel item={selected} onClose={()=>setSelected(null)}/>
  </div>);
}