import React,{useState,useMemo,useCallback} from 'react';
import {BarChart,Bar,XAxis,YAxis,CartesianGrid,Tooltip,ResponsiveContainer,PieChart,Pie,Cell,AreaChart,Area,ScatterChart,Scatter,ZAxis,Legend,RadarChart,Radar,PolarGrid,PolarAngleAxis,PolarRadiusAxis,LineChart,Line} from 'recharts';
const T={bg:'#f6f4f0',surface:'#ffffff',surfaceH:'#f0ede7',border:'#e5e0d8',borderL:'#d5cfc5',navy:'#1b3a5c',navyL:'#2c5a8c',gold:'#c5a96a',goldL:'#d4be8a',sage:'#5a8a6a',sageL:'#7ba67d',teal:'#5a8a6a',text:'#1b3a5c',textSec:'#5c6b7e',textMut:'#9aa3ae',red:'#dc2626',green:'#16a34a',amber:'#d97706',font:"'DM Sans','SF Pro Display',system-ui,-apple-system,sans-serif",mono:"'JetBrains Mono','SF Mono','Fira Code',monospace"};
const sr=(s)=>{let x=Math.sin(s+1)*10000;return x-Math.floor(x);};const ACCENT='#059669';const tip={contentStyle:{background:T.surface,border:`1px solid ${T.border}`,borderRadius:8,fontSize:11,fontFamily:T.font},labelStyle:{color:T.textSec,fontFamily:T.mono,fontSize:10}};
const TABS=['Hub Overview','SBTi Tracker','Abatement Curves','Roadmap Progress'];const SECTORS=['All','Energy','Utilities','Materials','Industrials','Technology','Transport','Agriculture','Buildings','Waste'];const PAGE_SIZE=15;const PIECLRS=[T.navy,T.gold,T.sage,T.red,T.amber,T.green,T.navyL,T.goldL,'#8b5cf6','#ec4899'];
const COMPANIES=(()=>{const names=['Exxon Mobil','Shell plc','BP plc','TotalEnergies','Chevron','Equinor','Eni SpA','Repsol','NextEra Energy','Enel SpA','Iberdrola','Orsted','Duke Energy','Southern Co','AES Corp','BHP Group','Rio Tinto','ArcelorMittal','BASF SE','HeidelbergCement','Siemens AG','GE','ABB Ltd','Schneider Electric','Caterpillar','Volkswagen','Toyota','BMW','Daimler','Stellantis','Cargill','ADM','Bunge','Nestle','Danone','Apple','Microsoft','Amazon','Google','Samsung','LafargeHolcim','CRH plc','Saint-Gobain','Cemex','Holcim','Deutsche Post','Maersk','UPS','FedEx','Delta Airlines','Waste Management','Veolia','Republic Services','Suez','Covanta','Air Liquide','Linde','Dow Inc','DuPont','3M Company'];
  const secs=['Energy','Energy','Energy','Energy','Energy','Energy','Energy','Energy','Utilities','Utilities','Utilities','Utilities','Utilities','Utilities','Utilities','Materials','Materials','Materials','Materials','Materials','Industrials','Industrials','Industrials','Industrials','Industrials','Transport','Transport','Transport','Transport','Transport','Agriculture','Agriculture','Agriculture','Agriculture','Agriculture','Technology','Technology','Technology','Technology','Technology','Buildings','Buildings','Buildings','Buildings','Buildings','Transport','Transport','Transport','Transport','Transport','Waste','Waste','Waste','Waste','Waste','Materials','Materials','Materials','Materials','Industrials'];
  return names.map((n,i)=>({id:i+1,name:n,sector:secs[i],totalEmissions:Math.round(5+sr(i*7)*495),scope1:Math.round(2+sr(i*11)*200),scope2:Math.round(1+sr(i*13)*80),scope3:Math.round(5+sr(i*17)*400),reductionTarget:Math.round(15+sr(i*19)*55),targetYear:sr(i*23)<0.3?2030:sr(i*23)<0.6?2040:2050,sbtiStatus:sr(i*29)<0.25?'Approved':sr(i*29)<0.5?'Committed':sr(i*29)<0.7?'Near-term':'None',netZeroYear:sr(i*31)<0.4?2050:sr(i*31)<0.7?2040:sr(i*31)<0.85?2030:0,progressPct:Math.round(5+sr(i*37)*60),yoyReduction:+(sr(i*41)*12-2).toFixed(1),carbonIntensity:Math.round(5+sr(i*43)*195),abatementCost:Math.round(10+sr(i*47)*190),renewableShare:Math.round(sr(i*53)*80),energyEfficiency:Math.round(20+sr(i*59)*60),ccusCapacity:Math.round(sr(i*61)*50),offsetsPct:Math.round(sr(i*67)*30),credibilityScore:Math.round(15+sr(i*71)*80),roadmapStatus:sr(i*73)<0.3?'On Track':sr(i*73)<0.6?'Behind':sr(i*73)<0.85?'At Risk':'No Plan'}));})();
const PATHWAY=Array.from({length:7},(_,i)=>({year:2025+i*5,currentEmissions:Math.round(100-i*10+sr(i*7)*5),targetEmissions:Math.round(100-i*14),sbtiPath:Math.round(100-i*16),progressPct:Math.round(10+i*12+sr(i*11)*5)}));
const ABATEMENT=[{measure:'Energy Efficiency',cost:15,potential:18},{measure:'Renewable Electricity',cost:25,potential:22},{measure:'Electrification',cost:45,potential:15},{measure:'Green Hydrogen',cost:80,potential:12},{measure:'CCUS',cost:95,potential:10},{measure:'Nature-Based',cost:20,potential:8},{measure:'Circular Economy',cost:35,potential:7},{measure:'Fuel Switching',cost:55,potential:6},{measure:'Process Innovation',cost:70,potential:5},{measure:'Carbon Offsets',cost:30,potential:4}];

export default function DecarbonisationHubPage(){
  const[tab,setTab]=useState(0);const[search,setSearch]=useState('');const[sectorF,setSectorF]=useState('All');const[sortCol,setSortCol]=useState('totalEmissions');const[sortDir,setSortDir]=useState('desc');const[page,setPage]=useState(1);const[selected,setSelected]=useState(null);
  const filtered=useMemo(()=>{let d=[...COMPANIES];if(search)d=d.filter(r=>r.name.toLowerCase().includes(search.toLowerCase()));if(sectorF!=='All')d=d.filter(r=>r.sector===sectorF);d.sort((a,b)=>sortDir==='asc'?(a[sortCol]>b[sortCol]?1:-1):(a[sortCol]<b[sortCol]?1:-1));return d;},[search,sectorF,sortCol,sortDir]);
  const paged=useMemo(()=>filtered.slice((page-1)*PAGE_SIZE,page*PAGE_SIZE),[filtered,page]);const totalPages=Math.ceil(filtered.length/PAGE_SIZE);
  const doSort=(col)=>{if(sortCol===col)setSortDir(d=>d==='asc'?'desc':'asc');else{setSortCol(col);setSortDir('desc');}setPage(1);};
  const stats=useMemo(()=>({count:filtered.length,totalEmissions:filtered.reduce((s,r)=>s+r.totalEmissions,0),avgProgress:(filtered.reduce((s,r)=>s+r.progressPct,0)/filtered.length||0).toFixed(0),sbtiApproved:filtered.filter(r=>r.sbtiStatus==='Approved').length,avgCredibility:(filtered.reduce((s,r)=>s+r.credibilityScore,0)/filtered.length||0).toFixed(0),onTrack:filtered.filter(r=>r.roadmapStatus==='On Track').length}),[filtered]);
  const sectorEmissions=useMemo(()=>{const m={};COMPANIES.forEach(r=>{if(!m[r.sector])m[r.sector]={s:r.sector,e:0,p:0,n:0};m[r.sector].e+=r.totalEmissions;m[r.sector].p+=r.progressPct;m[r.sector].n++;});return Object.values(m).map(s=>({sector:s.s,emissions:Math.round(s.e),progress:Math.round(s.p/s.n)})).sort((a,b)=>b.emissions-a.emissions);},[]);
  const sbtiDist=useMemo(()=>{const m={};COMPANIES.forEach(r=>{m[r.sbtiStatus]=(m[r.sbtiStatus]||0)+1;});return Object.entries(m).map(([k,v])=>({name:k,value:v}));},[]);
  const roadmapDist=useMemo(()=>{const m={};COMPANIES.forEach(r=>{m[r.roadmapStatus]=(m[r.roadmapStatus]||0)+1;});return Object.entries(m).map(([k,v])=>({name:k,value:v}));},[]);
  const exportCSV=useCallback((data,fn)=>{if(!data.length)return;const keys=Object.keys(data[0]);const csv=[keys.join(','),...data.map(r=>keys.map(k=>`"${r[k]}"`).join(','))].join('\n');const blob=new Blob([csv],{type:'text/csv'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=fn;a.click();URL.revokeObjectURL(url);},[]);
  const si=(col,cur,dir)=>cur===col?(dir==='asc'?' \u25B2':' \u25BC'):' \u25CB';
  const thS={padding:'8px 10px',fontSize:11,fontFamily:T.mono,color:T.textSec,cursor:'pointer',borderBottom:`1px solid ${T.border}`,whiteSpace:'nowrap',userSelect:'none',textAlign:'left',background:T.surfaceH};const tdS={padding:'7px 10px',fontSize:12,fontFamily:T.font,borderBottom:`1px solid ${T.border}`,color:T.text};const inpS={padding:'6px 12px',border:`1px solid ${T.border}`,borderRadius:6,fontSize:12,fontFamily:T.font,background:T.surface,color:T.text,outline:'none',width:220};const selS={padding:'6px 10px',border:`1px solid ${T.border}`,borderRadius:6,fontSize:11,fontFamily:T.font,background:T.surface,color:T.text};const btnS=(a)=>({padding:'6px 16px',border:`1px solid ${a?ACCENT:T.border}`,borderRadius:6,fontSize:12,fontFamily:T.font,background:a?ACCENT:T.surface,color:a?'#fff':T.text,cursor:'pointer',fontWeight:a?600:400});const pgB={padding:'4px 10px',border:`1px solid ${T.border}`,borderRadius:4,fontSize:11,cursor:'pointer',background:T.surface,color:T.text};const cS={background:T.surface,border:`1px solid ${T.border}`,borderRadius:10,padding:16};
  const kpi=(l,v)=>(<div style={{background:T.surface,border:`1px solid ${T.border}`,borderRadius:10,padding:'14px 18px',flex:1,minWidth:150}}><div style={{fontSize:10,color:T.textMut,fontFamily:T.mono,textTransform:'uppercase',letterSpacing:1}}>{l}</div><div style={{fontSize:24,fontWeight:700,color:T.navy,marginTop:4}}>{v}</div></div>);
  const SidePanel=({item,onClose})=>{if(!item)return null;return(<div style={{position:'fixed',top:0,right:0,width:440,height:'100vh',background:T.surface,borderLeft:`2px solid ${ACCENT}`,zIndex:1000,overflowY:'auto',boxShadow:'-4px 0 24px rgba(0,0,0,0.10)'}}><div style={{padding:'20px 24px',borderBottom:`1px solid ${T.border}`,display:'flex',justifyContent:'space-between',alignItems:'center'}}><div style={{fontSize:16,fontWeight:700,color:T.navy}}>{item.name}</div><button onClick={onClose} style={{background:'none',border:'none',fontSize:20,cursor:'pointer',color:T.textMut}}>x</button></div><div style={{padding:'16px 24px'}}><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:10,marginBottom:16}}>{[['Emissions',item.totalEmissions+' MtCO2'],['Scope 1',item.scope1+' Mt'],['Scope 2',item.scope2+' Mt'],['Scope 3',item.scope3+' Mt'],['Target',item.reductionTarget+'%'],['Target Year',item.targetYear],['SBTi',item.sbtiStatus],['Net Zero',item.netZeroYear||'N/A'],['Progress',item.progressPct+'%'],['YoY',item.yoyReduction+'%'],['Abatement Cost','$'+item.abatementCost+'/t'],['Renewable',item.renewableShare+'%'],['Efficiency',item.energyEfficiency+'%'],['CCUS',item.ccusCapacity+'%'],['Offsets',item.offsetsPct+'%'],['Credibility',item.credibilityScore+'/100']].map(([k,v],i)=>(<div key={i} style={{background:T.surfaceH,borderRadius:6,padding:'8px 12px'}}><div style={{fontSize:10,color:T.textMut,fontFamily:T.mono}}>{k}</div><div style={{fontSize:14,fontWeight:600,color:T.navy,marginTop:2}}>{v}</div></div>))}</div><div style={{height:220}}><div style={{fontSize:11,fontFamily:T.mono,color:T.textSec,marginBottom:6}}>DECARB PROFILE</div><ResponsiveContainer width="100%" height={200}><RadarChart data={[{axis:'Progress',v:item.progressPct},{axis:'Renewable',v:item.renewableShare},{axis:'Efficiency',v:item.energyEfficiency},{axis:'Credibility',v:item.credibilityScore},{axis:'CCUS',v:item.ccusCapacity*2},{axis:'Target',v:item.reductionTarget}]}><PolarGrid stroke={T.border}/><PolarAngleAxis dataKey="axis" tick={{fontSize:9,fill:T.textSec}}/><PolarRadiusAxis angle={30} domain={[0,100]} tick={{fontSize:9}}/><Radar dataKey="v" stroke={ACCENT} fill={ACCENT} fillOpacity={0.15}/></RadarChart></ResponsiveContainer></div></div></div>);};

  const renderOverview=()=>(<div>
    <div style={{display:'flex',gap:12,marginBottom:20,flexWrap:'wrap'}}>{kpi('Companies',stats.count)}{kpi('Total Emissions',(stats.totalEmissions/1000).toFixed(1)+' GtCO2')}{kpi('Avg Progress',stats.avgProgress+'%')}{kpi('SBTi Approved',stats.sbtiApproved)}{kpi('Avg Credibility',stats.avgCredibility+'/100')}{kpi('On Track',stats.onTrack)}</div>
    <div style={{display:'flex',gap:12,marginBottom:16,flexWrap:'wrap',alignItems:'center'}}><input value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}} placeholder="Search companies..." style={inpS}/><select value={sectorF} onChange={e=>{setSectorF(e.target.value);setPage(1);}} style={selS}>{SECTORS.map(s=><option key={s}>{s}</option>)}</select><button onClick={()=>exportCSV(filtered,'decarbonisation_hub.csv')} style={btnS(false)}>Export CSV</button></div>
    <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16,marginBottom:20}}>
      <div style={cS}><div style={{fontSize:11,fontFamily:T.mono,color:T.textSec,marginBottom:8}}>SBTi STATUS</div><ResponsiveContainer width="100%" height={220}><PieChart><Pie data={sbtiDist} cx="50%" cy="50%" outerRadius={80} dataKey="value" label={({name,percent})=>`${name} ${(percent*100).toFixed(0)}%`}>{sbtiDist.map((_,i)=><Cell key={i} fill={[T.green,T.gold,T.amber,T.red][i%4]}/>)}</Pie><Tooltip {...tip}/></PieChart></ResponsiveContainer></div>
      <div style={cS}><div style={{fontSize:11,fontFamily:T.mono,color:T.textSec,marginBottom:8}}>ROADMAP STATUS</div><ResponsiveContainer width="100%" height={220}><PieChart><Pie data={roadmapDist} cx="50%" cy="50%" outerRadius={80} dataKey="value" label={({name,percent})=>`${name} ${(percent*100).toFixed(0)}%`}>{roadmapDist.map((_,i)=><Cell key={i} fill={[T.green,T.amber,T.red,'#b91c1c'][i%4]}/>)}</Pie><Tooltip {...tip}/></PieChart></ResponsiveContainer></div>
    </div>
    <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16,marginBottom:20}}>
      <div style={cS}><div style={{fontSize:11,fontFamily:T.mono,color:T.textSec,marginBottom:8}}>SECTOR EMISSIONS</div><ResponsiveContainer width="100%" height={240}><BarChart data={sectorEmissions}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="sector" tick={{fontSize:9}} angle={-15}/><YAxis tick={{fontSize:10}}/><Tooltip {...tip}/><Bar dataKey="emissions" fill={T.red} name="Total MtCO2" radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></div>
      <div style={cS}><div style={{fontSize:11,fontFamily:T.mono,color:T.textSec,marginBottom:8}}>DECARBONIZATION PATHWAY</div><ResponsiveContainer width="100%" height={240}><LineChart data={PATHWAY}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="year" tick={{fontSize:10}}/><YAxis tick={{fontSize:10}}/><Tooltip {...tip}/><Line type="monotone" dataKey="currentEmissions" stroke={T.red} strokeWidth={2} name="Current Path"/><Line type="monotone" dataKey="targetEmissions" stroke={T.green} strokeWidth={2} name="Target" strokeDasharray="5 5"/><Line type="monotone" dataKey="sbtiPath" stroke={ACCENT} strokeWidth={2} name="SBTi Path" strokeDasharray="5 5"/><Legend/></LineChart></ResponsiveContainer></div>
    </div>
    <div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr>{[['name','Company'],['sector','Sector'],['totalEmissions','Emissions'],['reductionTarget','Target %'],['progressPct','Progress'],['sbtiStatus','SBTi'],['credibilityScore','Credibility'],['yoyReduction','YoY %'],['roadmapStatus','Roadmap']].map(([col,label])=>(<th key={col} onClick={()=>doSort(col)} style={thS}>{label}{si(col,sortCol,sortDir)}</th>))}</tr></thead><tbody>{paged.map(r=>(<tr key={r.id} onClick={()=>setSelected(r)} style={{cursor:'pointer',background:selected?.id===r.id?T.surfaceH:'transparent'}}><td style={{...tdS,fontWeight:600}}>{r.name}</td><td style={tdS}>{r.sector}</td><td style={tdS}>{r.totalEmissions} Mt</td><td style={tdS}>{r.reductionTarget}%</td><td style={tdS}>{r.progressPct}%</td><td style={tdS}>{r.sbtiStatus}</td><td style={tdS}>{r.credibilityScore}</td><td style={{...tdS,color:r.yoyReduction>0?T.green:T.red}}>{r.yoyReduction>0?'+':''}{r.yoyReduction}%</td><td style={tdS}><span style={{background:r.roadmapStatus==='On Track'?'rgba(22,163,74,0.12)':r.roadmapStatus==='Behind'?'rgba(217,119,6,0.12)':r.roadmapStatus==='At Risk'?'rgba(220,38,38,0.12)':'rgba(154,163,174,0.12)',color:r.roadmapStatus==='On Track'?T.green:r.roadmapStatus==='Behind'?T.amber:r.roadmapStatus==='At Risk'?T.red:T.textMut,padding:'2px 8px',borderRadius:4,fontSize:11,fontWeight:600}}>{r.roadmapStatus}</span></td></tr>))}</tbody></table>
    <div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginTop:12}}><span style={{fontSize:11,color:T.textMut,fontFamily:T.mono}}>{filtered.length} companies | Page {page}/{totalPages}</span><div style={{display:'flex',gap:4}}><button disabled={page<=1} onClick={()=>setPage(p=>p-1)} style={pgB}>Prev</button><button disabled={page>=totalPages} onClick={()=>setPage(p=>p+1)} style={pgB}>Next</button></div></div></div>
  </div>);

  const renderSBTi=()=>(<div>
    <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16,marginBottom:20}}>
      <div style={cS}><div style={{fontSize:11,fontFamily:T.mono,color:T.textSec,marginBottom:8}}>SBTi STATUS BY SECTOR</div><ResponsiveContainer width="100%" height={260}><BarChart data={SECTORS.filter(s=>s!=='All').map(sec=>{const c=COMPANIES.filter(r=>r.sector===sec);return{sector:sec,approved:c.filter(r=>r.sbtiStatus==='Approved').length,committed:c.filter(r=>r.sbtiStatus==='Committed').length,none:c.filter(r=>r.sbtiStatus==='None').length};})}>
        <CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="sector" tick={{fontSize:8}} angle={-15}/><YAxis tick={{fontSize:10}}/><Tooltip {...tip}/><Bar dataKey="approved" fill={T.green} name="Approved" stackId="a"/><Bar dataKey="committed" fill={T.gold} name="Committed" stackId="a"/><Bar dataKey="none" fill={T.red} name="None" stackId="a"/><Legend/></BarChart></ResponsiveContainer></div>
      <div style={cS}><div style={{fontSize:11,fontFamily:T.mono,color:T.textSec,marginBottom:8}}>TARGET YEAR DISTRIBUTION</div><ResponsiveContainer width="100%" height={260}><PieChart><Pie data={[{name:'2030',value:COMPANIES.filter(r=>r.targetYear===2030).length},{name:'2040',value:COMPANIES.filter(r=>r.targetYear===2040).length},{name:'2050',value:COMPANIES.filter(r=>r.targetYear===2050).length}]} cx="50%" cy="50%" outerRadius={80} dataKey="value" label={({name,percent})=>`${name} ${(percent*100).toFixed(0)}%`}>{[0,1,2].map(i=><Cell key={i} fill={[T.green,T.gold,T.amber][i]}/>)}</Pie><Tooltip {...tip}/></PieChart></ResponsiveContainer></div>
    </div>
    <div style={cS}><div style={{fontSize:11,fontFamily:T.mono,color:T.textSec,marginBottom:8}}>CREDIBILITY vs PROGRESS</div><ResponsiveContainer width="100%" height={260}><ScatterChart><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="x" name="Progress %" tick={{fontSize:10}}/><YAxis dataKey="y" name="Credibility" tick={{fontSize:10}}/><Tooltip {...tip}/><Scatter data={COMPANIES.map(r=>({name:r.name,x:r.progressPct,y:r.credibilityScore}))} fill={ACCENT} fillOpacity={0.4}/></ScatterChart></ResponsiveContainer></div>
  </div>);

  const renderAbatement=()=>(<div>
    <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16,marginBottom:20}}>
      <div style={cS}><div style={{fontSize:11,fontFamily:T.mono,color:T.textSec,marginBottom:8}}>ABATEMENT COST CURVE ($/tCO2 vs POTENTIAL %)</div><ResponsiveContainer width="100%" height={280}><BarChart data={ABATEMENT}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="measure" tick={{fontSize:8}} angle={-15}/><YAxis tick={{fontSize:10}}/><Tooltip {...tip}/><Bar dataKey="cost" fill={T.red} name="Cost $/tCO2" radius={[2,2,0,0]}/><Bar dataKey="potential" fill={T.green} name="Potential %" radius={[2,2,0,0]}/><Legend/></BarChart></ResponsiveContainer></div>
      <div style={cS}><div style={{fontSize:11,fontFamily:T.mono,color:T.textSec,marginBottom:8}}>COST vs POTENTIAL</div><ResponsiveContainer width="100%" height={280}><ScatterChart><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="x" name="Cost $/t" tick={{fontSize:10}}/><YAxis dataKey="y" name="Potential %" tick={{fontSize:10}}/><Tooltip {...tip}/><Scatter data={ABATEMENT.map(r=>({name:r.measure,x:r.cost,y:r.potential}))} fill={T.gold} fillOpacity={0.7} r={8}/></ScatterChart></ResponsiveContainer></div>
    </div>
    <div style={cS}><div style={{fontSize:11,fontFamily:T.mono,color:T.textSec,marginBottom:8}}>ABATEMENT MEASURES TABLE</div><table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr>{['Measure','Cost ($/tCO2)','Potential (%)','Cumulative'].map(h=>(<th key={h} style={thS}>{h}</th>))}</tr></thead><tbody>{ABATEMENT.map((r,i)=>{const cum=ABATEMENT.slice(0,i+1).reduce((s,a)=>s+a.potential,0);return(<tr key={i}><td style={{...tdS,fontWeight:600}}>{r.measure}</td><td style={tdS}>${r.cost}</td><td style={tdS}>{r.potential}%</td><td style={tdS}>{cum}%</td></tr>);})}</tbody></table></div>
  </div>);

  const renderRoadmap=()=>(<div>
    <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16,marginBottom:20}}>
      <div style={cS}><div style={{fontSize:11,fontFamily:T.mono,color:T.textSec,marginBottom:8}}>PROGRESS PATHWAY</div><ResponsiveContainer width="100%" height={260}><AreaChart data={PATHWAY}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="year" tick={{fontSize:10}}/><YAxis tick={{fontSize:10}}/><Tooltip {...tip}/><Area type="monotone" dataKey="progressPct" stroke={ACCENT} fill={ACCENT} fillOpacity={0.1} name="Progress %"/><Legend/></AreaChart></ResponsiveContainer></div>
      <div style={cS}><div style={{fontSize:11,fontFamily:T.mono,color:T.textSec,marginBottom:8}}>SECTOR PROGRESS COMPARISON</div><ResponsiveContainer width="100%" height={260}><BarChart data={sectorEmissions}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="sector" tick={{fontSize:8}} angle={-15}/><YAxis tick={{fontSize:10}}/><Tooltip {...tip}/><Bar dataKey="progress" fill={ACCENT} name="Avg Progress %" radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></div>
    </div>
    <div style={cS}><div style={{fontSize:11,fontFamily:T.mono,color:T.textSec,marginBottom:8}}>RENEWABLE SHARE vs ENERGY EFFICIENCY</div><ResponsiveContainer width="100%" height={240}><ScatterChart><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="x" name="Renewable %" tick={{fontSize:10}}/><YAxis dataKey="y" name="Efficiency %" tick={{fontSize:10}}/><Tooltip {...tip}/><Scatter data={COMPANIES.map(r=>({name:r.name,x:r.renewableShare,y:r.energyEfficiency}))} fill={T.green} fillOpacity={0.4}/></ScatterChart></ResponsiveContainer></div>
  </div>);

  return(<div style={{fontFamily:T.font,background:T.bg,minHeight:'100vh',padding:'24px 32px',color:T.text}}>
    <div style={{marginBottom:20}}><div style={{fontSize:22,fontWeight:700,color:T.navy}}>Decarbonisation Hub</div><div style={{fontSize:12,color:T.textSec,marginTop:4,fontFamily:T.mono}}>SBTi tracking, abatement cost curves, decarbonization roadmaps across {COMPANIES.length} companies</div></div>
    <div style={{display:'flex',gap:4,marginBottom:20,borderBottom:`2px solid ${T.border}`}}>{TABS.map((t,i)=>(<button key={t} onClick={()=>setTab(i)} style={{...btnS(tab===i),borderRadius:'6px 6px 0 0',borderBottom:tab===i?`2px solid ${ACCENT}`:'2px solid transparent'}}>{t}</button>))}</div>
    {tab===0&&renderOverview()}{tab===1&&renderSBTi()}{tab===2&&renderAbatement()}{tab===3&&renderRoadmap()}
    <SidePanel item={selected} onClose={()=>setSelected(null)}/>
  </div>);
}
