import React,{useState,useMemo,useCallback} from 'react';
import {BarChart,Bar,LineChart,Line,AreaChart,Area,PieChart,Pie,Cell,ScatterChart,Scatter,XAxis,YAxis,CartesianGrid,Tooltip,ResponsiveContainer,Legend,RadarChart,Radar,PolarGrid,PolarAngleAxis,PolarRadiusAxis} from 'recharts';
const T={bg:'#f6f4f0',surface:'#ffffff',surfaceH:'#f0ede7',border:'#e5e0d8',borderL:'#d5cfc5',navy:'#1b3a5c',navyL:'#2c5a8c',gold:'#c5a96a',goldL:'#d4be8a',sage:'#5a8a6a',sageL:'#7ba67d',teal:'#5a8a6a',text:'#1b3a5c',textSec:'#5c6b7e',textMut:'#9aa3ae',red:'#dc2626',green:'#16a34a',amber:'#d97706',font:"'DM Sans','SF Pro Display',system-ui,-apple-system,sans-serif",mono:"'JetBrains Mono','SF Mono','Fira Code',monospace"};
const sr=(s)=>{let x=Math.sin(s+1)*10000;return x-Math.floor(x);};
const ACCENT='#dc2626';const tip={contentStyle:{background:T.surface,border:`1px solid ${T.border}`,borderRadius:8,fontSize:11,fontFamily:T.font},labelStyle:{color:T.textSec,fontFamily:T.mono,fontSize:10}};const COLORS=[T.navy,T.gold,T.sage,T.red,T.amber,T.green,T.navyL,T.goldL,'#8b5cf6'];
const fmt=v=>typeof v==='number'?v>=1e9?(v/1e9).toFixed(1)+'B':v>=1e6?(v/1e6).toFixed(1)+'M':v>=1e3?(v/1e3).toFixed(1)+'K':v.toFixed(1):v;
const TABS=['Scenario Dashboard','Portfolio Impact','Sector Stress','Historical Comparison'];const PAGE=12;
const SCENARIOS=[{id:1,name:'NGFS Net Zero 2050',type:'Orderly',source:'NGFS',horizon:'2050',carbonPrice:250,tempC:1.5,gdpImpact:-2.1,severity:'Medium'},{id:2,name:'NGFS Delayed Transition',type:'Disorderly',source:'NGFS',horizon:'2050',carbonPrice:350,tempC:1.8,gdpImpact:-4.5,severity:'High'},{id:3,name:'NGFS Current Policies',type:'Hot House',source:'NGFS',horizon:'2100',carbonPrice:50,tempC:3.5,gdpImpact:-8.2,severity:'Critical'},{id:4,name:'NGFS Below 2C',type:'Orderly',source:'NGFS',horizon:'2050',carbonPrice:200,tempC:1.7,gdpImpact:-1.8,severity:'Low'},{id:5,name:'IEA Net Zero',type:'Orderly',source:'IEA',horizon:'2050',carbonPrice:280,tempC:1.4,gdpImpact:-1.5,severity:'Medium'},{id:6,name:'IEA Stated Policies',type:'Hot House',source:'IEA',horizon:'2050',carbonPrice:80,tempC:2.7,gdpImpact:-5.8,severity:'High'},{id:7,name:'Sudden Carbon Tax',type:'Disorderly',source:'Custom',horizon:'2030',carbonPrice:500,tempC:2.0,gdpImpact:-6.5,severity:'Critical'},{id:8,name:'Physical Risk Extreme',type:'Physical',source:'Custom',horizon:'2050',carbonPrice:0,tempC:4.0,gdpImpact:-12.5,severity:'Critical'}];
const SECTORS_DATA=['Energy','Materials','Industrials','Technology','Financials','Healthcare','Consumer','Utilities','Real Estate','Telecom'];
const SECTOR_IMPACT=SCENARIOS.map(s=>({scenario:s.name,...Object.fromEntries(SECTORS_DATA.map(sec=>[sec,+((sr(s.id*100+SECTORS_DATA.indexOf(sec)*7)-0.5)*s.severity.length*4).toFixed(1)]))}));
const HOLDINGS=Array.from({length:40},(_,i)=>{
  const names=['Apple','Microsoft','Alphabet','Amazon','JPMorgan','Visa','Chevron','ExxonMobil','Shell','BP','BHP','Rio Tinto','Caterpillar','GE','NextEra','Duke Energy','Walmart','P&G','J&J','Pfizer','Goldman Sachs','HSBC','Toyota','Siemens','BASF','ArcelorMittal','TotalEnergies','Nestle','Unilever','LVMH','Tesla','NVIDIA','Meta','Intel','AMD','Broadcom','Qualcomm','Adobe','Salesforce','ServiceNow'];
  const secs=['Technology','Technology','Technology','Technology','Financials','Financials','Energy','Energy','Energy','Energy','Materials','Materials','Industrials','Industrials','Utilities','Utilities','Consumer','Consumer','Healthcare','Healthcare','Financials','Financials','Industrials','Industrials','Materials','Materials','Energy','Consumer','Consumer','Consumer','Technology','Technology','Technology','Technology','Technology','Technology','Technology','Technology','Technology','Technology'];
  const impacts=SCENARIOS.map(s=>{const sIdx=SECTORS_DATA.indexOf(secs[i]);const base=(sr(s.id*100+i*7)-0.5)*20;return{scenario:s.name,impact:+(base-s.severity.length*1.5).toFixed(1)};});
  return{id:i+1,name:names[i],sector:secs[i],weight:+(sr(i*7)*3+0.5).toFixed(1),currentVal:Math.round(sr(i*11)*500+50),impacts};
});
export default function StressTestOrchestratorPage(){
  const[tab,setTab]=useState(0);const[search,setSearch]=useState('');const[scenarioF,setScenarioF]=useState(SCENARIOS[0].name);const[sortCol,setSortCol]=useState('impact');const[sortDir,setSortDir]=useState('asc');const[page,setPage]=useState(1);const[selected,setSelected]=useState(null);
  const holdingsWithImpact=useMemo(()=>HOLDINGS.map(h=>{const imp=h.impacts.find(i=>i.scenario===scenarioF);return{...h,impact:imp?imp.impact:0};}),[scenarioF]);
  const filtered=useMemo(()=>{let d=[...holdingsWithImpact];if(search)d=d.filter(r=>r.name.toLowerCase().includes(search.toLowerCase()));d.sort((a,b)=>sortDir==='asc'?(a[sortCol]>b[sortCol]?1:-1):(a[sortCol]<b[sortCol]?1:-1));return d;},[holdingsWithImpact,search,sortCol,sortDir]);
  const paged=useMemo(()=>filtered.slice((page-1)*PAGE,page*PAGE),[filtered,page]);const totalPages=Math.ceil(filtered.length/PAGE);
  const doSort=col=>{if(sortCol===col)setSortDir(d=>d==='asc'?'desc':'asc');else{setSortCol(col);setSortDir('asc');}setPage(1);};
  const curScenario=SCENARIOS.find(s=>s.name===scenarioF)||SCENARIOS[0];
  const stats=useMemo(()=>({holdings:filtered.length,portfolioImpact:(filtered.reduce((s,r)=>s+r.impact*r.weight/100,0)).toFixed(1),worstHolding:filtered.length?[...filtered].sort((a,b)=>a.impact-b.impact)[0].name:'-',bestHolding:filtered.length?[...filtered].sort((a,b)=>b.impact-a.impact)[0].name:'-',avgImpact:(filtered.length?filtered.reduce((s,r)=>s+r.impact,0)/filtered.length:0).toFixed(1),atRisk:filtered.filter(r=>r.impact<-10).length,temp:curScenario.tempC+'\u00B0C'}),[filtered,curScenario]);
  const sectorImpact=useMemo(()=>{const si=SECTOR_IMPACT.find(s=>s.scenario===scenarioF);if(!si)return[];return SECTORS_DATA.map(s=>({sector:s,impact:si[s]||0})).sort((a,b)=>a.impact-b.impact);},[scenarioF]);
  const exportCSV=useCallback((data,fn)=>{if(!data.length)return;const keys=Object.keys(data[0]).filter(k=>k!=='impacts');const csv=[keys.join(','),...data.map(r=>keys.map(k=>`"${r[k]}"`).join(','))].join('\n');const b=new Blob([csv],{type:'text/csv'});const u=URL.createObjectURL(b);const a=document.createElement('a');a.href=u;a.download=fn;a.click();URL.revokeObjectURL(u);},[]);
  const si2=(col,cur,dir)=>cur===col?(dir==='asc'?' \u25B2':' \u25BC'):' \u25CB';
  const thS={padding:'8px 10px',fontSize:11,fontFamily:T.mono,color:T.textSec,cursor:'pointer',borderBottom:`1px solid ${T.border}`,whiteSpace:'nowrap',userSelect:'none',textAlign:'left',background:T.surfaceH};const tdS={padding:'7px 10px',fontSize:12,fontFamily:T.font,borderBottom:`1px solid ${T.border}`,color:T.text};const inpS={padding:'6px 12px',border:`1px solid ${T.border}`,borderRadius:6,fontSize:12,fontFamily:T.font,background:T.surface,color:T.text,outline:'none',width:180};const selS={padding:'6px 10px',border:`1px solid ${T.border}`,borderRadius:6,fontSize:11,fontFamily:T.font,background:T.surface,color:T.text};
  const btnS=a=>({padding:'6px 16px',border:`1px solid ${a?ACCENT:T.border}`,borderRadius:6,fontSize:12,fontFamily:T.font,background:a?ACCENT:T.surface,color:a?'#fff':T.text,cursor:'pointer',fontWeight:a?600:400});const pgB={padding:'4px 10px',border:`1px solid ${T.border}`,borderRadius:4,fontSize:11,cursor:'pointer',background:T.surface,color:T.text};const cS={background:T.surface,border:`1px solid ${T.border}`,borderRadius:10,padding:16};
  const kpi=(l,v,c)=>(<div style={{background:T.surface,border:`1px solid ${T.border}`,borderRadius:10,padding:'14px 18px',flex:1,minWidth:130}}><div style={{fontSize:10,color:T.textMut,fontFamily:T.mono,textTransform:'uppercase',letterSpacing:1}}>{l}</div><div style={{fontSize:22,fontWeight:700,color:c||T.navy,marginTop:4}}>{v}</div></div>);
  const Panel=({item,onClose})=>{if(!item)return null;return(<div style={{position:'fixed',top:0,right:0,width:440,height:'100vh',background:T.surface,borderLeft:`2px solid ${ACCENT}`,zIndex:1000,overflowY:'auto',boxShadow:'-4px 0 24px rgba(0,0,0,0.10)'}}><div style={{padding:'20px 24px',borderBottom:`1px solid ${T.border}`,display:'flex',justifyContent:'space-between',alignItems:'center'}}><div><div style={{fontSize:16,fontWeight:700,color:T.navy}}>{item.name}</div><div style={{fontSize:12,color:T.textSec}}>{item.sector}</div></div><button onClick={onClose} style={{background:'none',border:'none',fontSize:20,cursor:'pointer',color:T.textMut}}>{'\u2715'}</button></div>
    <div style={{padding:'16px 24px'}}>
      <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:8,marginBottom:12}}>{[['Weight',item.weight+'%'],['Current Value','$'+item.currentVal+'M'],['Impact ('+scenarioF.slice(0,15)+')',item.impact+'%']].map(([k,v],j)=>(<div key={j} style={{background:T.surfaceH,borderRadius:6,padding:'8px 10px'}}><div style={{fontSize:9,color:T.textMut,fontFamily:T.mono}}>{k}</div><div style={{fontSize:13,fontWeight:600,color:T.navy,marginTop:2}}>{v}</div></div>))}</div>
      <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Impact Across All Scenarios</div><ResponsiveContainer width="100%" height={220}><BarChart data={item.impacts}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="scenario" tick={{fontSize:7,fill:T.textSec}} angle={-30}/><YAxis tick={{fontSize:9,fill:T.textSec}}/><Tooltip {...tip}/><Bar dataKey="impact">{item.impacts.map((e,j)=><Cell key={j} fill={e.impact>=0?T.green:T.red}/>)}</Bar></BarChart></ResponsiveContainer></div>
    </div></div>);};
  const renderDash=()=>(<div>
    <div style={{display:'flex',gap:12,marginBottom:16}}><span style={{fontSize:12,color:T.textSec,alignSelf:'center'}}>Scenario:</span><select value={scenarioF} onChange={e=>setScenarioF(e.target.value)} style={selS}>{SCENARIOS.map(s=><option key={s.name} value={s.name}>{s.name}</option>)}</select></div>
    <div style={{display:'flex',gap:12,marginBottom:20,flexWrap:'wrap'}}>{kpi('Temperature',stats.temp,+curScenario.tempC>2?T.red:T.amber)}{kpi('Carbon Price','$'+curScenario.carbonPrice+'/t')}{kpi('GDP Impact',curScenario.gdpImpact+'%',T.red)}{kpi('Portfolio Impact',stats.portfolioImpact+'%',+stats.portfolioImpact<-5?T.red:T.amber)}{kpi('At Risk (>-10%)',stats.atRisk,T.red)}{kpi('Worst Holding',stats.worstHolding)}{kpi('Severity',curScenario.severity)}</div>
    <div style={{...cS,marginBottom:16,overflowX:'auto'}}><div style={{fontSize:13,fontWeight:600,color:T.navy,marginBottom:12}}>Scenario Comparison</div><table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr>{['Scenario','Type','Source','Horizon','Carbon $/t','Temp \u00B0C','GDP %','Severity'].map(h=><th key={h} style={thS}>{h}</th>)}</tr></thead><tbody>{SCENARIOS.map(s=><tr key={s.id} onClick={()=>setScenarioF(s.name)} style={{cursor:'pointer',background:s.name===scenarioF?T.surfaceH:'transparent'}}><td style={{...tdS,fontWeight:600}}>{s.name}</td><td style={tdS}>{s.type}</td><td style={tdS}>{s.source}</td><td style={tdS}>{s.horizon}</td><td style={tdS}>${s.carbonPrice}</td><td style={tdS}>{s.tempC}\u00B0C</td><td style={tdS}><span style={{color:T.red}}>{s.gdpImpact}%</span></td><td style={tdS}><span style={{color:s.severity==='Critical'?T.red:s.severity==='High'?T.amber:s.severity==='Medium'?T.gold:T.green,fontWeight:600,fontSize:11}}>{s.severity}</span></td></tr>)}</tbody></table></div>
    <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16}}>
      <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Sector Impact ({curScenario.name})</div><ResponsiveContainer width="100%" height={280}><BarChart data={sectorImpact}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="sector" tick={{fontSize:8,fill:T.textSec}} angle={-25}/><YAxis tick={{fontSize:9,fill:T.textSec}}/><Tooltip {...tip}/><Bar dataKey="impact">{sectorImpact.map((e,j)=><Cell key={j} fill={e.impact>=0?T.green:T.red}/>)}</Bar></BarChart></ResponsiveContainer></div>
      <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Scenario Type Distribution</div><ResponsiveContainer width="100%" height={280}><PieChart><Pie data={['Orderly','Disorderly','Hot House','Physical'].map(t=>({name:t,value:SCENARIOS.filter(s=>s.type===t).length}))} cx="50%" cy="50%" outerRadius={90} dataKey="value" label={({name,value})=>`${name}: ${value}`}>{[T.green,T.amber,T.red,'#8b5cf6'].map((c,i)=><Cell key={i} fill={c}/>)}</Pie><Tooltip {...tip}/></PieChart></ResponsiveContainer></div>
    </div></div>);
  const renderPortfolio=()=>(<div>
    <div style={{display:'flex',gap:12,marginBottom:16,alignItems:'center',flexWrap:'wrap'}}><input value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}} placeholder="Search holdings..." style={inpS}/><select value={scenarioF} onChange={e=>setScenarioF(e.target.value)} style={selS}>{SCENARIOS.map(s=><option key={s.name} value={s.name}>{s.name}</option>)}</select><button onClick={()=>exportCSV(filtered,'stress_test.csv')} style={btnS(false)}>Export CSV</button></div>
    <div style={{overflowX:'auto',...cS,padding:0}}><table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr>{[['name','Holding'],['sector','Sector'],['weight','Wt%'],['currentVal','Val $M'],['impact','Impact %']].map(([k,l])=><th key={k} onClick={()=>doSort(k)} style={thS}>{l}{si2(k,sortCol,sortDir)}</th>)}</tr></thead>
      <tbody>{paged.map(r=><tr key={r.id} onClick={()=>setSelected(r)} style={{cursor:'pointer',background:selected?.id===r.id?T.surfaceH:'transparent'}}><td style={tdS}><span style={{fontWeight:600}}>{r.name}</span></td><td style={tdS}>{r.sector}</td><td style={tdS}>{r.weight}%</td><td style={tdS}>${r.currentVal}M</td><td style={tdS}><span style={{color:r.impact>=0?T.green:r.impact>-10?T.amber:T.red,fontWeight:600,fontFamily:T.mono}}>{r.impact>0?'+':''}{r.impact}%</span></td></tr>)}</tbody></table></div>
    {totalPages>1&&<div style={{display:'flex',gap:6,marginTop:12,justifyContent:'center'}}><button onClick={()=>setPage(p=>Math.max(1,p-1))} disabled={page===1} style={pgB}>&laquo;</button><span style={{fontSize:11,color:T.textSec}}>{page}/{totalPages}</span><button onClick={()=>setPage(p=>Math.min(totalPages,p+1))} disabled={page===totalPages} style={pgB}>&raquo;</button></div>}
  </div>);
  const renderSector=()=>(<div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16}}>
    <div style={{...cS,gridColumn:'1/3'}}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Sector Impact Across Scenarios</div><ResponsiveContainer width="100%" height={300}><BarChart data={SECTOR_IMPACT}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="scenario" tick={{fontSize:7,fill:T.textSec}} angle={-25}/><YAxis tick={{fontSize:9,fill:T.textSec}}/><Tooltip {...tip}/>{SECTORS_DATA.slice(0,5).map((s,i)=><Bar key={s} dataKey={s} fill={COLORS[i]}/>)}<Legend/></BarChart></ResponsiveContainer></div>
    <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Most Vulnerable Sectors</div><ResponsiveContainer width="100%" height={280}><RadarChart data={sectorImpact.map(s=>({...s,impact:Math.abs(s.impact)}))}><PolarGrid stroke={T.border}/><PolarAngleAxis dataKey="sector" tick={{fontSize:8,fill:T.textSec}}/><PolarRadiusAxis tick={{fontSize:8}}/><Radar dataKey="impact" stroke={T.red} fill="rgba(220,38,38,0.15)"/></RadarChart></ResponsiveContainer></div>
    <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Carbon Price vs GDP Impact</div><ResponsiveContainer width="100%" height={280}><ScatterChart><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="x" name="Carbon $/t" tick={{fontSize:9,fill:T.textSec}}/><YAxis dataKey="y" name="GDP %" tick={{fontSize:9,fill:T.textSec}}/><Tooltip {...tip}/><Scatter data={SCENARIOS.map(s=>({name:s.name,x:s.carbonPrice,y:s.gdpImpact}))} fill={ACCENT} fillOpacity={0.6}/></ScatterChart></ResponsiveContainer></div>
  </div></div>);
  const renderHistorical=()=>(<div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16}}>
    <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Historical Crisis Comparison</div><ResponsiveContainer width="100%" height={300}><BarChart data={[{event:'GFC 2008',impact:-37},{event:'COVID 2020',impact:-34},{event:'Oil Crash 2014',impact:-28},{event:'Tech Bust 2000',impact:-45},{event:'EU Debt 2011',impact:-18},{event:'Climate Stress',impact:+curScenario.gdpImpact*5}]}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="event" tick={{fontSize:9,fill:T.textSec}}/><YAxis tick={{fontSize:9,fill:T.textSec}}/><Tooltip {...tip}/><Bar dataKey="impact">{[T.red,T.red,T.red,T.red,T.red,ACCENT].map((c,i)=><Cell key={i} fill={c}/>)}</Bar></BarChart></ResponsiveContainer></div>
    <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Temperature Pathway Scenarios</div><ResponsiveContainer width="100%" height={300}><LineChart data={Array.from({length:8},(_,y)=>({year:2025+y*5,nz:+(1.2+y*0.04).toFixed(1),delayed:+(1.2+y*0.08).toFixed(1),current:+(1.2+y*0.25).toFixed(1)}))}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="year" tick={{fontSize:9,fill:T.textSec}}/><YAxis tick={{fontSize:9,fill:T.textSec}} domain={[1,4.5]}/><Tooltip {...tip}/><Line type="monotone" dataKey="nz" stroke={T.green} name="Net Zero" strokeWidth={2}/><Line type="monotone" dataKey="delayed" stroke={T.amber} name="Delayed" strokeWidth={2}/><Line type="monotone" dataKey="current" stroke={T.red} name="Current Policies" strokeWidth={2}/><Legend/></LineChart></ResponsiveContainer></div>
  </div></div>);
  return(<div style={{padding:'24px 32px',fontFamily:T.font,background:T.bg,minHeight:'100vh'}}>
    <div style={{marginBottom:20}}><h1 style={{fontSize:22,fontWeight:700,color:T.navy,margin:0}}>Stress Test Orchestrator</h1><p style={{fontSize:12,color:T.textSec,margin:'4px 0 0'}}>8 NGFS/IEA scenarios | Multi-scenario stress testing | Portfolio impact</p></div>
    <div style={{display:'flex',gap:8,marginBottom:20}}>{TABS.map((t,i)=><button key={t} onClick={()=>setTab(i)} style={btnS(tab===i)}>{t}</button>)}</div>
    {tab===0&&renderDash()}{tab===1&&renderPortfolio()}{tab===2&&renderSector()}{tab===3&&renderHistorical()}
    <Panel item={selected} onClose={()=>setSelected(null)}/>
  </div>);
}