"""Add pcaf_time_series and platform_alerts tables

Revision ID: 018
Revises: 017
Create Date: 2026-03-03

Adds:
  - pcaf_time_series: multi-year glidepath tracking store (actual vs. target)
    Used by: NZBA Glidepath Tracker, Paris Alignment bars, PCAF trend analysis
  - platform_alerts: continuous monitoring alert feed
    Used by: Sustainability Pulse dashboard, alert engine, per-module notifications
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "018_time_series_tables"
down_revision = "017_enable_postgis"
branch_labels = None
depends_on = None


def upgrade():
    # ── pcaf_time_series ───────────────────────────────────────────────────────
    # Stores actual + target metric values per portfolio/sector/year.
    # Feeds the NZBA glidepath tracker and CRREM pathway comparisons.
    op.create_table(
        "pcaf_time_series",
        sa.Column("id", sa.Integer, primary_key=True, autoincrement=True),
        sa.Column(
            "portfolio_id",
            sa.String(36),
            sa.ForeignKey("portfolios_pg.id", ondelete="CASCADE"),
            nullable=True,
            comment="NULL = platform-level aggregate (benchmark store)",
        ),
        sa.Column(
            "entity_lei",
            sa.String(20),
            nullable=True,
            comment="GLEIF LEI — cross-module entity linkage key",
        ),
        sa.Column("sector", sa.String(100), nullable=True),
        sa.Column(
            "metric_type",
            sa.String(50),
            nullable=False,
            comment="absolute_tco2e | waci | itr | carbon_footprint | crrem_intensity",
        ),
        sa.Column("reporting_year", sa.Integer, nullable=False),
        sa.Column(
            "actual_value",
            sa.Numeric(18, 4),
            nullable=True,
            comment="Computed from PCAF engine or client upload",
        ),
        sa.Column(
            "glidepath_value",
            sa.Numeric(18, 4),
            nullable=True,
            comment="Reference target from Data Hub /glidepaths/nze/{sector}",
        ),
        sa.Column(
            "target_value",
            sa.Numeric(18, 4),
            nullable=True,
            comment="Entity-specific commitment target (if set)",
        ),
        sa.Column(
            "unit",
            sa.String(50),
            nullable=True,
            comment="tCO2e | tCO2e/MEUR | degC | kgCO2/m2",
        ),
        sa.Column(
            "dqs_score",
            sa.Numeric(4, 2),
            nullable=True,
            comment="Portfolio-weighted PCAF Data Quality Score 1.0–5.0",
        ),
        sa.Column("data_source", sa.String(200), nullable=True),
        sa.Column(
            "is_benchmark",
            sa.Boolean,
            server_default="false",
            nullable=False,
            comment="True = anonymised platform aggregate for benchmarking",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
        ),
    )
    op.create_index(
        "idx_pcaf_ts_portfolio_sector_year",
        "pcaf_time_series",
        ["portfolio_id", "sector", "reporting_year"],
    )
    op.create_index(
        "idx_pcaf_ts_lei",
        "pcaf_time_series",
        ["entity_lei"],
    )
    op.create_index(
        "idx_pcaf_ts_metric_year",
        "pcaf_time_series",
        ["metric_type", "reporting_year"],
    )
    op.create_index(
        "idx_pcaf_ts_benchmark",
        "pcaf_time_series",
        ["is_benchmark", "sector", "metric_type", "reporting_year"],
    )

    # ── platform_alerts ────────────────────────────────────────────────────────
    # Continuous monitoring alerts generated by the alert engine after each
    # computation run (PCAF, ECL, glidepath update, DSCR assessment).
    op.create_table(
        "platform_alerts",
        sa.Column(
            "id",
            sa.String(36),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()::text"),
        ),
        sa.Column(
            "portfolio_id",
            sa.String(36),
            sa.ForeignKey("portfolios_pg.id", ondelete="CASCADE"),
            nullable=True,
        ),
        sa.Column("entity_lei", sa.String(20), nullable=True),
        sa.Column(
            "alert_type",
            sa.String(100),
            nullable=False,
            comment=(
                "glidepath_deviation | sicr_trigger | dqs_degradation | "
                "dscr_breach | crrem_crossover | pcaf_coverage_low | "
                "transition_plan_missing | engagement_overdue"
            ),
        ),
        sa.Column(
            "severity",
            sa.String(20),
            nullable=False,
            server_default="info",
            comment="info | warning | critical",
        ),
        sa.Column("title", sa.String(300), nullable=False),
        sa.Column("message", sa.Text, nullable=False),
        sa.Column(
            "metric_value",
            sa.Numeric(18, 4),
            nullable=True,
            comment="Actual value that triggered the alert",
        ),
        sa.Column(
            "threshold",
            sa.Numeric(18, 4),
            nullable=True,
            comment="Threshold value that was breached",
        ),
        sa.Column(
            "module_link",
            sa.String(200),
            nullable=True,
            comment="Frontend route to navigate to from alert (e.g. /glidepath-tracker)",
        ),
        sa.Column("is_read", sa.Boolean, server_default="false", nullable=False),
        sa.Column("is_resolved", sa.Boolean, server_default="false", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
        ),
    )
    op.create_index(
        "idx_alerts_portfolio_unread",
        "platform_alerts",
        ["portfolio_id", "is_read", "created_at"],
        postgresql_ops={"created_at": "DESC"},
    )
    op.create_index(
        "idx_alerts_severity",
        "platform_alerts",
        ["severity", "is_resolved", "created_at"],
    )
    op.create_index(
        "idx_alerts_type",
        "platform_alerts",
        ["alert_type", "portfolio_id"],
    )


def downgrade():
    op.drop_index("idx_alerts_type", table_name="platform_alerts")
    op.drop_index("idx_alerts_severity", table_name="platform_alerts")
    op.drop_index("idx_alerts_portfolio_unread", table_name="platform_alerts")
    op.drop_table("platform_alerts")

    op.drop_index("idx_pcaf_ts_benchmark", table_name="pcaf_time_series")
    op.drop_index("idx_pcaf_ts_metric_year", table_name="pcaf_time_series")
    op.drop_index("idx_pcaf_ts_lei", table_name="pcaf_time_series")
    op.drop_index("idx_pcaf_ts_portfolio_sector_year", table_name="pcaf_time_series")
    op.drop_table("pcaf_time_series")
