"""Initial schema

Revision ID: 133e9046d191
Revises: 
Create Date: 2026-02-14 04:05:05.717337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '133e9046d191'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolios',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolios_name'), 'portfolios', ['name'], unique=False)
    op.create_table('scenario_series',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('scenario', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('variable', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('source_version', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_scenario_lookup', 'scenario_series', ['scenario', 'variable', 'region', 'year'], unique=False)
    op.create_index(op.f('ix_scenario_series_region'), 'scenario_series', ['region'], unique=False)
    op.create_index(op.f('ix_scenario_series_scenario'), 'scenario_series', ['scenario'], unique=False)
    op.create_index(op.f('ix_scenario_series_variable'), 'scenario_series', ['variable'], unique=False)
    op.create_index(op.f('ix_scenario_series_year'), 'scenario_series', ['year'], unique=False)
    op.create_index('ix_scenario_year', 'scenario_series', ['scenario', 'year'], unique=False)
    op.create_table('analysis_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('portfolio_id', sa.String(), nullable=False),
    sa.Column('portfolio_name', sa.String(), nullable=False),
    sa.Column('scenarios', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('horizons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_runs_created_at'), 'analysis_runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_analysis_runs_portfolio_id'), 'analysis_runs', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_analysis_runs_status'), 'analysis_runs', ['status'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('portfolio_id', sa.String(), nullable=False),
    sa.Column('asset_type', sa.Enum('BOND', 'LOAN', 'EQUITY', name='assettypeenum'), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('company_sector', sa.Enum('POWER_GENERATION', 'OIL_GAS', 'METALS_MINING', 'AUTOMOTIVE', 'AIRLINES', 'REAL_ESTATE', name='sectorenum'), nullable=False),
    sa.Column('company_subsector', sa.String(), nullable=True),
    sa.Column('exposure', sa.Float(), nullable=False),
    sa.Column('market_value', sa.Float(), nullable=False),
    sa.Column('base_pd', sa.Float(), nullable=False),
    sa.Column('base_lgd', sa.Float(), nullable=False),
    sa.Column('rating', sa.String(), nullable=False),
    sa.Column('maturity_years', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_company_sector'), 'assets', ['company_sector'], unique=False)
    op.create_index(op.f('ix_assets_portfolio_id'), 'assets', ['portfolio_id'], unique=False)
    op.create_index('ix_assets_portfolio_sector', 'assets', ['portfolio_id', 'company_sector'], unique=False)
    op.create_table('scenario_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('analysis_run_id', sa.String(), nullable=False),
    sa.Column('scenario', sa.String(), nullable=False),
    sa.Column('horizon', sa.Integer(), nullable=False),
    sa.Column('expected_loss', sa.Float(), nullable=False),
    sa.Column('expected_loss_pct', sa.Float(), nullable=False),
    sa.Column('risk_adjusted_return', sa.Float(), nullable=False),
    sa.Column('avg_pd_change_pct', sa.Float(), nullable=False),
    sa.Column('rating_migrations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('var_95', sa.Float(), nullable=False),
    sa.Column('concentration_hhi', sa.Float(), nullable=False),
    sa.Column('total_exposure', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_results_run_scenario', 'scenario_results', ['analysis_run_id', 'scenario', 'horizon'], unique=False)
    op.create_index(op.f('ix_scenario_results_analysis_run_id'), 'scenario_results', ['analysis_run_id'], unique=False)
    op.create_index(op.f('ix_scenario_results_horizon'), 'scenario_results', ['horizon'], unique=False)
    op.create_index(op.f('ix_scenario_results_scenario'), 'scenario_results', ['scenario'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scenario_results_scenario'), table_name='scenario_results')
    op.drop_index(op.f('ix_scenario_results_horizon'), table_name='scenario_results')
    op.drop_index(op.f('ix_scenario_results_analysis_run_id'), table_name='scenario_results')
    op.drop_index('ix_results_run_scenario', table_name='scenario_results')
    op.drop_table('scenario_results')
    op.drop_index('ix_assets_portfolio_sector', table_name='assets')
    op.drop_index(op.f('ix_assets_portfolio_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_company_sector'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_analysis_runs_status'), table_name='analysis_runs')
    op.drop_index(op.f('ix_analysis_runs_portfolio_id'), table_name='analysis_runs')
    op.drop_index(op.f('ix_analysis_runs_created_at'), table_name='analysis_runs')
    op.drop_table('analysis_runs')
    op.drop_index('ix_scenario_year', table_name='scenario_series')
    op.drop_index(op.f('ix_scenario_series_year'), table_name='scenario_series')
    op.drop_index(op.f('ix_scenario_series_variable'), table_name='scenario_series')
    op.drop_index(op.f('ix_scenario_series_scenario'), table_name='scenario_series')
    op.drop_index(op.f('ix_scenario_series_region'), table_name='scenario_series')
    op.drop_index('ix_scenario_lookup', table_name='scenario_series')
    op.drop_table('scenario_series')
    op.drop_index(op.f('ix_portfolios_name'), table_name='portfolios')
    op.drop_table('portfolios')
    # ### end Alembic commands ###
