import React,{useState,useMemo,useCallback} from 'react';
import {BarChart,Bar,LineChart,Line,AreaChart,Area,ScatterChart,Scatter,RadarChart,Radar,PolarGrid,PolarAngleAxis,PolarRadiusAxis,PieChart,Pie,Cell,XAxis,YAxis,CartesianGrid,Tooltip,ResponsiveContainer,Legend,ZAxis} from 'recharts';

const T={bg:'#f6f4f0',surface:'#ffffff',surfaceH:'#f0ede7',border:'#e5e0d8',borderL:'#d5cfc5',navy:'#1b3a5c',navyL:'#2c5a8c',gold:'#c5a96a',goldL:'#d4be8a',sage:'#5a8a6a',sageL:'#7ba67d',teal:'#5a8a6a',text:'#1b3a5c',textSec:'#5c6b7e',textMut:'#9aa3ae',red:'#dc2626',green:'#16a34a',amber:'#d97706',font:"'DM Sans','SF Pro Display',system-ui,-apple-system,sans-serif",mono:"'JetBrains Mono','SF Mono','Fira Code',monospace"};
const sr=(s)=>{let x=Math.sin(s+1)*10000;return x-Math.floor(x);};
const ACCENT='#dc2626';
const tip={contentStyle:{background:T.surface,border:`1px solid ${T.border}`,borderRadius:8,fontSize:11,fontFamily:T.font},labelStyle:{color:T.textSec,fontFamily:T.mono,fontSize:10}};
const COLORS=[T.navy,T.gold,T.sage,T.red,T.amber,T.green,T.navyL,T.goldL,T.sageL,'#8b5cf6','#ec4899','#06b6d4'];
const fmt=v=>typeof v==='number'?v>=1e9?(v/1e9).toFixed(1)+'B':v>=1e6?(v/1e6).toFixed(1)+'M':v>=1e3?(v/1e3).toFixed(1)+'K':v.toFixed(1):v;
const TABS=['City Dashboard','Pollutant Analysis','Health Economics','Regulatory Tracker'];
const REGIONS=['All','South Asia','East Asia','Southeast Asia','Middle East','Africa','Europe','Americas'];
const PAGE=12;

const CITIES=Array.from({length:50},(_,i)=>{
  const names=['Delhi','Lahore','Dhaka','Kolkata','Chengdu','Jakarta','Karachi','Mumbai','Beijing','Cairo','Lagos','Hanoi','Bangkok','Lima','Santiago','Bogota','Manila','Riyadh','Tehran','Kabul','Accra','Nairobi','Addis Ababa','Ulaanbaatar','Almaty','Tashkent','Kathmandu','Colombo','Yangon','Phnom Penh','Ho Chi Minh','Kuala Lumpur','Singapore','Tokyo','Seoul','Shanghai','Guangzhou','Shenzhen','Taipei','Hong Kong','London','Paris','Berlin','Madrid','Rome','Warsaw','Istanbul','Moscow','Mexico City','Sao Paulo'];
  const regions=['South Asia','South Asia','South Asia','South Asia','East Asia','Southeast Asia','South Asia','South Asia','East Asia','Middle East','Africa','Southeast Asia','Southeast Asia','Americas','Americas','Americas','Southeast Asia','Middle East','Middle East','South Asia','Africa','Africa','Africa','East Asia','East Asia','East Asia','South Asia','South Asia','Southeast Asia','Southeast Asia','Southeast Asia','Southeast Asia','Southeast Asia','East Asia','East Asia','East Asia','East Asia','East Asia','East Asia','East Asia','Europe','Europe','Europe','Europe','Europe','Europe','Middle East','Europe','Americas','Americas'];
  const countries=['India','Pakistan','Bangladesh','India','China','Indonesia','Pakistan','India','China','Egypt','Nigeria','Vietnam','Thailand','Peru','Chile','Colombia','Philippines','Saudi Arabia','Iran','Afghanistan','Ghana','Kenya','Ethiopia','Mongolia','Kazakhstan','Uzbekistan','Nepal','Sri Lanka','Myanmar','Cambodia','Vietnam','Malaysia','Singapore','Japan','South Korea','China','China','China','Taiwan','China','UK','France','Germany','Spain','Italy','Poland','Turkey','Russia','Mexico','Brazil'];
  const basePM=95-i*1.4+sr(i*7)*12;const baseNO2=48-i*0.6+sr(i*11)*10;const baseSO2=35-i*0.5+sr(i*13)*8;const baseO3=80+sr(i*17)*40;
  const monthly=Array.from({length:12},(_,m)=>({month:['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'][m],pm25:+(basePM+sr(i*100+m*7)*20-10).toFixed(1),no2:+(baseNO2+sr(i*100+m*11)*8-4).toFixed(1),aqi:Math.round((basePM+sr(i*100+m*7)*20)*3.2)}));
  const yearly=Array.from({length:5},(_,y)=>({year:2020+y,pm25:+(basePM-y*2+sr(i*200+y*13)*5).toFixed(1),deaths:Math.round(sr(i*23+y)*15000+500-y*200),cost:+(sr(i*19+y)*25+2-y*0.4).toFixed(1)}));
  return {id:i+1,city:names[i],country:countries[i],region:regions[i],pm25:+basePM.toFixed(1),no2:+baseNO2.toFixed(1),so2:+baseSO2.toFixed(1),o3:+baseO3.toFixed(1),co:+(sr(i*51)*3+0.5).toFixed(1),pb:+(sr(i*53)*0.5).toFixed(2),aqi:Math.round(basePM*3.5+sr(i*3)*40),whoCompliant:basePM<15?'Yes':'No',healthCostBn:+(sr(i*19)*25+2).toFixed(1),prematureDeaths:Math.round(sr(i*23)*15000+500),asthmaCases:Math.round(sr(i*29)*80000+5000),copdCases:Math.round(sr(i*31)*20000+1000),lungCancer:Math.round(sr(i*37)*5000+200),childAsthma:Math.round(sr(i*41)*30000+2000),pop:+(sr(i*37)*25+1).toFixed(1),trend:sr(i*41)>0.6?'Improving':sr(i*41)<0.3?'Worsening':'Stable',yoy:+((sr(i*43)-0.5)*12).toFixed(1),monitorStations:Math.round(sr(i*47)*40+5),regCompliance:Math.round(sr(i*49)*100),natStandard:+(sr(i*53)*60+25).toFixed(0),whoGuideline:5,enforcementScore:Math.round(sr(i*59)*100),policyCount:Math.round(sr(i*61)*15+2),greenSpacePct:+(sr(i*67)*30+5).toFixed(1),evAdoption:+(sr(i*71)*25).toFixed(1),industrialZones:Math.round(sr(i*73)*20+2),monthly,yearly};
});

const POLLUTANTS=[{key:'pm25',label:'PM2.5',who:5,unit:'ug/m3',color:T.red},{key:'no2',label:'NO2',who:10,unit:'ug/m3',color:T.amber},{key:'so2',label:'SO2',who:20,unit:'ug/m3',color:T.navy},{key:'o3',label:'Ozone',who:100,unit:'ug/m3',color:T.sage},{key:'co',label:'CO',who:4,unit:'mg/m3',color:T.gold},{key:'pb',label:'Lead',who:0.5,unit:'ug/m3',color:'#8b5cf6'}];

export default function AirQualityHealthRiskPage(){
  const[tab,setTab]=useState(0);const[search,setSearch]=useState('');const[regionF,setRegionF]=useState('All');const[sortCol,setSortCol]=useState('aqi');const[sortDir,setSortDir]=useState('desc');const[page,setPage]=useState(1);const[selected,setSelected]=useState(null);const[pollutant,setPollutant]=useState('pm25');const[trendF,setTrendF]=useState('All');

  const filtered=useMemo(()=>{let d=[...CITIES];if(search)d=d.filter(r=>r.city.toLowerCase().includes(search.toLowerCase())||r.country.toLowerCase().includes(search.toLowerCase()));if(regionF!=='All')d=d.filter(r=>r.region===regionF);if(trendF!=='All')d=d.filter(r=>r.trend===trendF);d.sort((a,b)=>sortDir==='asc'?(a[sortCol]>b[sortCol]?1:-1):(a[sortCol]<b[sortCol]?1:-1));return d;},[search,regionF,sortCol,sortDir,trendF]);
  const paged=useMemo(()=>filtered.slice((page-1)*PAGE,page*PAGE),[filtered,page]);
  const totalPages=Math.ceil(filtered.length/PAGE);
  const doSort=col=>{if(sortCol===col)setSortDir(d=>d==='asc'?'desc':'asc');else{setSortCol(col);setSortDir('desc');}setPage(1);};

  const stats=useMemo(()=>({count:filtered.length,avgAQI:Math.round(filtered.reduce((s,r)=>s+r.aqi,0)/filtered.length||0),avgPM25:(filtered.reduce((s,r)=>s+r.pm25,0)/filtered.length||0).toFixed(1),whoCompliant:filtered.filter(r=>r.whoCompliant==='Yes').length,totalDeaths:fmt(filtered.reduce((s,r)=>s+r.prematureDeaths,0)),totalCost:fmt(filtered.reduce((s,r)=>s+r.healthCostBn,0)*1e9),improving:filtered.filter(r=>r.trend==='Improving').length}),[filtered]);

  const regionAgg=useMemo(()=>{const m={};CITIES.forEach(r=>{if(!m[r.region])m[r.region]={region:r.region,pm25:0,aqi:0,deaths:0,cost:0,n:0};m[r.region].pm25+=r.pm25;m[r.region].aqi+=r.aqi;m[r.region].deaths+=r.prematureDeaths;m[r.region].cost+=r.healthCostBn;m[r.region].n++;});return Object.values(m).map(r=>({region:r.region,pm25:+(r.pm25/r.n).toFixed(1),aqi:Math.round(r.aqi/r.n),deaths:r.deaths,cost:+r.cost.toFixed(1)})).sort((a,b)=>b.pm25-a.pm25);},[]);

  const pollScatter=useMemo(()=>filtered.map(c=>({city:c.city,x:c[pollutant],y:c.prematureDeaths,pop:c.pop})),[filtered,pollutant]);
  const trendDist=useMemo(()=>{const m={Improving:0,Stable:0,Worsening:0};filtered.forEach(r=>m[r.trend]++);return Object.entries(m).map(([k,v])=>({name:k,value:v}));},[filtered]);
  const complianceByRegion=useMemo(()=>{const m={};CITIES.forEach(r=>{if(!m[r.region])m[r.region]={region:r.region,compliant:0,non:0};if(r.whoCompliant==='Yes')m[r.region].compliant++;else m[r.region].non++;});return Object.values(m);},[]);

  const exportCSV=useCallback((data,fn)=>{if(!data.length)return;const keys=Object.keys(data[0]).filter(k=>k!=='monthly'&&k!=='yearly');const csv=[keys.join(','),...data.map(r=>keys.map(k=>`"${r[k]}"`).join(','))].join('\n');const b=new Blob([csv],{type:'text/csv'});const u=URL.createObjectURL(b);const a=document.createElement('a');a.href=u;a.download=fn;a.click();URL.revokeObjectURL(u);},[]);

  const si=(col,cur,dir)=>cur===col?(dir==='asc'?' \u25B2':' \u25BC'):' \u25CB';
  const thS={padding:'8px 10px',fontSize:11,fontFamily:T.mono,color:T.textSec,cursor:'pointer',borderBottom:`1px solid ${T.border}`,whiteSpace:'nowrap',userSelect:'none',textAlign:'left',background:T.surfaceH};
  const tdS={padding:'7px 10px',fontSize:12,fontFamily:T.font,borderBottom:`1px solid ${T.border}`,color:T.text};
  const inpS={padding:'6px 12px',border:`1px solid ${T.border}`,borderRadius:6,fontSize:12,fontFamily:T.font,background:T.surface,color:T.text,outline:'none',width:220};
  const selS={padding:'6px 10px',border:`1px solid ${T.border}`,borderRadius:6,fontSize:11,fontFamily:T.font,background:T.surface,color:T.text};
  const btnS=a=>({padding:'6px 16px',border:`1px solid ${a?ACCENT:T.border}`,borderRadius:6,fontSize:12,fontFamily:T.font,background:a?ACCENT:T.surface,color:a?'#fff':T.text,cursor:'pointer',fontWeight:a?600:400});
  const pgB={padding:'4px 10px',border:`1px solid ${T.border}`,borderRadius:4,fontSize:11,cursor:'pointer',background:T.surface,color:T.text};
  const cS={background:T.surface,border:`1px solid ${T.border}`,borderRadius:10,padding:16};
  const aqiBdg=v=>({background:v>300?'rgba(220,38,38,0.15)':v>200?'rgba(220,38,38,0.10)':v>150?'rgba(217,119,6,0.12)':v>100?'rgba(197,169,106,0.15)':v>50?'rgba(22,163,74,0.10)':'rgba(22,163,74,0.15)',color:v>200?T.red:v>150?T.amber:v>100?T.gold:T.green,padding:'2px 8px',borderRadius:4,fontSize:11,fontWeight:600,fontFamily:T.mono});
  const kpi=(l,v,c)=>(<div style={{background:T.surface,border:`1px solid ${T.border}`,borderRadius:10,padding:'14px 18px',flex:1,minWidth:140}}><div style={{fontSize:10,color:T.textMut,fontFamily:T.mono,textTransform:'uppercase',letterSpacing:1}}>{l}</div><div style={{fontSize:22,fontWeight:700,color:c||T.navy,marginTop:4}}>{v}</div></div>);

  const SidePanel=({item,onClose})=>{if(!item)return null;return(<div style={{position:'fixed',top:0,right:0,width:480,height:'100vh',background:T.surface,borderLeft:`2px solid ${ACCENT}`,zIndex:1000,overflowY:'auto',boxShadow:'-4px 0 24px rgba(0,0,0,0.10)'}}><div style={{padding:'20px 24px',borderBottom:`1px solid ${T.border}`,display:'flex',justifyContent:'space-between',alignItems:'center'}}><div><div style={{fontSize:16,fontWeight:700,color:T.navy}}>{item.city}</div><div style={{fontSize:12,color:T.textSec}}>{item.country} | {item.region}</div></div><button onClick={onClose} style={{background:'none',border:'none',fontSize:20,cursor:'pointer',color:T.textMut}}>\u2715</button></div>
    <div style={{padding:'16px 24px'}}>
      <div style={{display:'grid',gridTemplateColumns:'1fr 1fr 1fr',gap:8,marginBottom:16}}>{[['AQI',item.aqi],['PM2.5',item.pm25+' ug/m3'],['NO2',item.no2],['SO2',item.so2],['Ozone',item.o3],['CO',item.co],['Deaths',fmt(item.prematureDeaths)],['Asthma',fmt(item.asthmaCases)],['COPD',fmt(item.copdCases)],['Lung Cancer',fmt(item.lungCancer)],['Child Asthma',fmt(item.childAsthma)],['Health Cost','$'+item.healthCostBn+'B'],['Pop',item.pop+'M'],['Stations',item.monitorStations],['WHO Compliant',item.whoCompliant],['Trend',item.trend],['YoY',item.yoy+'%'],['Enforcement',item.enforcementScore+'/100'],['Green Space',item.greenSpacePct+'%'],['EV Adoption',item.evAdoption+'%'],['Industrial Zones',item.industrialZones]].map(([k,v],j)=>(<div key={j} style={{background:T.surfaceH,borderRadius:6,padding:'8px 10px'}}><div style={{fontSize:9,color:T.textMut,fontFamily:T.mono}}>{k}</div><div style={{fontSize:13,fontWeight:600,color:T.navy,marginTop:2}}>{v}</div></div>))}</div>
      <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Monthly PM2.5 Trend</div><ResponsiveContainer width="100%" height={180}><AreaChart data={item.monthly}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="month" tick={{fontSize:9,fill:T.textSec}}/><YAxis tick={{fontSize:9,fill:T.textSec}}/><Tooltip {...tip}/><Area type="monotone" dataKey="pm25" stroke={T.red} fill="rgba(220,38,38,0.15)"/></AreaChart></ResponsiveContainer></div>
      <div style={{...cS,marginTop:12}}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>5-Year Deaths & Cost Trend</div><ResponsiveContainer width="100%" height={180}><LineChart data={item.yearly}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="year" tick={{fontSize:9,fill:T.textSec}}/><YAxis yAxisId="l" tick={{fontSize:9,fill:T.textSec}}/><YAxis yAxisId="r" orientation="right" tick={{fontSize:9,fill:T.textSec}}/><Tooltip {...tip}/><Line yAxisId="l" type="monotone" dataKey="deaths" stroke={T.red} strokeWidth={2} dot={{r:3}}/><Line yAxisId="r" type="monotone" dataKey="cost" stroke={T.gold} strokeWidth={2} dot={{r:3}}/><Legend/></LineChart></ResponsiveContainer></div>
      <div style={{...cS,marginTop:12}}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Pollutant Radar</div><ResponsiveContainer width="100%" height={220}><RadarChart data={POLLUTANTS.map(p=>({pollutant:p.label,value:item[p.key],who:p.who}))}><PolarGrid stroke={T.border}/><PolarAngleAxis dataKey="pollutant" tick={{fontSize:9,fill:T.textSec}}/><PolarRadiusAxis tick={{fontSize:8,fill:T.textMut}}/><Radar name="City" dataKey="value" stroke={T.red} fill="rgba(220,38,38,0.2)"/><Radar name="WHO" dataKey="who" stroke={T.green} fill="rgba(22,163,74,0.1)"/><Legend/></RadarChart></ResponsiveContainer></div>
    </div></div>);};

  const renderDash=()=>(<div>
    <div style={{display:'flex',gap:12,marginBottom:20,flexWrap:'wrap'}}>{kpi('Cities',stats.count)}{kpi('Avg AQI',stats.avgAQI,stats.avgAQI>150?T.red:T.amber)}{kpi('Avg PM2.5',stats.avgPM25+' ug/m3')}{kpi('WHO Compliant',stats.whoCompliant+'/'+stats.count,T.green)}{kpi('Premature Deaths',stats.totalDeaths,T.red)}{kpi('Health Cost',stats.totalCost)}{kpi('Improving',stats.improving)}</div>
    <div style={{display:'flex',gap:12,marginBottom:16,alignItems:'center',flexWrap:'wrap'}}><input value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}} placeholder="Search city or country..." style={inpS}/><select value={regionF} onChange={e=>{setRegionF(e.target.value);setPage(1);}} style={selS}>{REGIONS.map(r=><option key={r}>{r}</option>)}</select><select value={trendF} onChange={e=>{setTrendF(e.target.value);setPage(1);}} style={selS}><option>All</option><option>Improving</option><option>Stable</option><option>Worsening</option></select><button onClick={()=>exportCSV(filtered,'air_quality_data.csv')} style={btnS(false)}>Export CSV</button></div>
    <div style={{overflowX:'auto',...cS,padding:0}}>
      <table style={{width:'100%',borderCollapse:'collapse'}}>
        <thead><tr>{[['city','City'],['country','Country'],['aqi','AQI'],['pm25','PM2.5'],['no2','NO2'],['prematureDeaths','Deaths'],['healthCostBn','Cost $B'],['trend','Trend'],['whoCompliant','WHO']].map(([k,l])=><th key={k} onClick={()=>doSort(k)} style={thS}>{l}{si(k,sortCol,sortDir)}</th>)}</tr></thead>
        <tbody>{paged.map(r=><tr key={r.id} onClick={()=>setSelected(r)} style={{cursor:'pointer',background:selected?.id===r.id?T.surfaceH:'transparent'}}><td style={tdS}><span style={{fontWeight:600}}>{r.city}</span></td><td style={tdS}>{r.country}</td><td style={tdS}><span style={aqiBdg(r.aqi)}>{r.aqi}</span></td><td style={tdS}>{r.pm25}</td><td style={tdS}>{r.no2}</td><td style={tdS}>{fmt(r.prematureDeaths)}</td><td style={tdS}>${r.healthCostBn}B</td><td style={tdS}><span style={{color:r.trend==='Improving'?T.green:r.trend==='Worsening'?T.red:T.amber,fontWeight:600,fontSize:11}}>{r.trend}</span></td><td style={tdS}><span style={{color:r.whoCompliant==='Yes'?T.green:T.red}}>{r.whoCompliant}</span></td></tr>)}</tbody>
      </table>
    </div>
    {totalPages>1&&<div style={{display:'flex',gap:6,marginTop:12,alignItems:'center',justifyContent:'center'}}><button onClick={()=>setPage(p=>Math.max(1,p-1))} disabled={page===1} style={pgB}>&laquo;</button><span style={{fontSize:11,color:T.textSec,fontFamily:T.mono}}>Page {page}/{totalPages}</span><button onClick={()=>setPage(p=>Math.min(totalPages,p+1))} disabled={page===totalPages} style={pgB}>&raquo;</button></div>}
    <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16,marginTop:20}}>
      <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Average PM2.5 by Region</div><ResponsiveContainer width="100%" height={260}><BarChart data={regionAgg}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="region" tick={{fontSize:9,fill:T.textSec}} angle={-15}/><YAxis tick={{fontSize:9,fill:T.textSec}}/><Tooltip {...tip}/><Bar dataKey="pm25" fill={T.red} radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></div>
      <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>AQI Trend Distribution</div><ResponsiveContainer width="100%" height={260}><PieChart><Pie data={trendDist} cx="50%" cy="50%" outerRadius={90} dataKey="value" label={({name,value})=>`${name}: ${value}`}>{trendDist.map((_,i)=><Cell key={i} fill={[T.green,T.gold,T.red][i]}/>)}</Pie><Tooltip {...tip}/></PieChart></ResponsiveContainer></div>
    </div>
  </div>);

  const renderPollutant=()=>(<div>
    <div style={{display:'flex',gap:12,marginBottom:16,alignItems:'center'}}><span style={{fontSize:12,color:T.textSec}}>Pollutant:</span><select value={pollutant} onChange={e=>setPollutant(e.target.value)} style={selS}>{POLLUTANTS.map(p=><option key={p.key} value={p.key}>{p.label}</option>)}</select></div>
    <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16}}>
      <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>{POLLUTANTS.find(p=>p.key===pollutant)?.label} vs Deaths (Scatter)</div><ResponsiveContainer width="100%" height={300}><ScatterChart><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="x" name={pollutant} tick={{fontSize:9,fill:T.textSec}}/><YAxis dataKey="y" name="Deaths" tick={{fontSize:9,fill:T.textSec}}/><ZAxis dataKey="pop" range={[20,400]} name="Pop (M)"/><Tooltip {...tip} cursor={{strokeDasharray:'3 3'}}/><Scatter data={pollScatter} fill={T.red} fillOpacity={0.6}/></ScatterChart></ResponsiveContainer></div>
      <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Top 15 Cities by {POLLUTANTS.find(p=>p.key===pollutant)?.label}</div><ResponsiveContainer width="100%" height={300}><BarChart data={[...filtered].sort((a,b)=>b[pollutant]-a[pollutant]).slice(0,15)} layout="vertical"><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis type="number" tick={{fontSize:9,fill:T.textSec}}/><YAxis type="category" dataKey="city" tick={{fontSize:9,fill:T.textSec}} width={90}/><Tooltip {...tip}/><Bar dataKey={pollutant} fill={POLLUTANTS.find(p=>p.key===pollutant)?.color} radius={[0,4,4,0]}/></BarChart></ResponsiveContainer></div>
      <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Pollutant Comparison (Top 10 Cities)</div><ResponsiveContainer width="100%" height={300}><BarChart data={[...CITIES].sort((a,b)=>b.aqi-a.aqi).slice(0,10)}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="city" tick={{fontSize:9,fill:T.textSec}} angle={-20}/><YAxis tick={{fontSize:9,fill:T.textSec}}/><Tooltip {...tip}/><Bar dataKey="pm25" fill={T.red} stackId="a"/><Bar dataKey="no2" fill={T.amber} stackId="a"/><Bar dataKey="so2" fill={T.navy} stackId="a"/><Legend/></BarChart></ResponsiveContainer></div>
      <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>WHO Compliance by Region</div><ResponsiveContainer width="100%" height={300}><BarChart data={complianceByRegion}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="region" tick={{fontSize:9,fill:T.textSec}} angle={-15}/><YAxis tick={{fontSize:9,fill:T.textSec}}/><Tooltip {...tip}/><Bar dataKey="compliant" fill={T.green} stackId="a" name="Compliant"/><Bar dataKey="non" fill={T.red} stackId="a" name="Non-Compliant"/><Legend/></BarChart></ResponsiveContainer></div>
    </div>
  </div>);

  const renderHealth=()=>{
    const topDeaths=[...filtered].sort((a,b)=>b.prematureDeaths-a.prematureDeaths).slice(0,15);
    const costByRegion=regionAgg.map(r=>({region:r.region,cost:r.cost})).sort((a,b)=>b.cost-a.cost);
    const healthBreak=filtered.slice(0,20).map(c=>({city:c.city,asthma:c.asthmaCases,copd:c.copdCases,lung:c.lungCancer,child:c.childAsthma}));
    return(<div>
      <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16}}>
        <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Premature Deaths - Top 15 Cities</div><ResponsiveContainer width="100%" height={300}><BarChart data={topDeaths}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="city" tick={{fontSize:9,fill:T.textSec}} angle={-25}/><YAxis tick={{fontSize:9,fill:T.textSec}}/><Tooltip {...tip}/><Bar dataKey="prematureDeaths" fill={T.red} radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></div>
        <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Health Cost by Region ($B)</div><ResponsiveContainer width="100%" height={300}><BarChart data={costByRegion}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="region" tick={{fontSize:9,fill:T.textSec}}/><YAxis tick={{fontSize:9,fill:T.textSec}}/><Tooltip {...tip}/><Bar dataKey="cost" fill={T.gold} radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></div>
        <div style={{...cS,gridColumn:'1/3'}}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Disease Burden Breakdown (Top 20 cities)</div><ResponsiveContainer width="100%" height={300}><BarChart data={healthBreak}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="city" tick={{fontSize:8,fill:T.textSec}} angle={-30}/><YAxis tick={{fontSize:9,fill:T.textSec}}/><Tooltip {...tip}/><Bar dataKey="asthma" fill={T.amber} stackId="a" name="Asthma"/><Bar dataKey="copd" fill={T.navy} stackId="a" name="COPD"/><Bar dataKey="lung" fill={T.red} stackId="a" name="Lung Cancer"/><Bar dataKey="child" fill={T.sage} stackId="a" name="Child Asthma"/><Legend/></BarChart></ResponsiveContainer></div>
        <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>PM2.5 vs Health Cost Scatter</div><ResponsiveContainer width="100%" height={280}><ScatterChart><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="x" name="PM2.5" tick={{fontSize:9,fill:T.textSec}}/><YAxis dataKey="y" name="Cost $B" tick={{fontSize:9,fill:T.textSec}}/><Tooltip {...tip}/><Scatter data={filtered.map(c=>({city:c.city,x:c.pm25,y:c.healthCostBn}))} fill={T.red} fillOpacity={0.5}/></ScatterChart></ResponsiveContainer></div>
        <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Deaths per Million Population</div><ResponsiveContainer width="100%" height={280}><BarChart data={[...filtered].sort((a,b)=>(b.prematureDeaths/b.pop)-(a.prematureDeaths/a.pop)).slice(0,12).map(c=>({city:c.city,rate:Math.round(c.prematureDeaths/c.pop)}))} layout="vertical"><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis type="number" tick={{fontSize:9,fill:T.textSec}}/><YAxis type="category" dataKey="city" tick={{fontSize:9,fill:T.textSec}} width={80}/><Tooltip {...tip}/><Bar dataKey="rate" fill={T.red} radius={[0,4,4,0]}/></BarChart></ResponsiveContainer></div>
      </div>
    </div>);
  };

  const renderReg=()=>{
    const regData=[...filtered].sort((a,b)=>b.enforcementScore-a.enforcementScore).slice(0,20);
    return(<div>
      <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16}}>
        <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Enforcement Score vs PM2.5</div><ResponsiveContainer width="100%" height={300}><ScatterChart><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="x" name="Enforcement" tick={{fontSize:9,fill:T.textSec}}/><YAxis dataKey="y" name="PM2.5" tick={{fontSize:9,fill:T.textSec}}/><Tooltip {...tip}/><Scatter data={filtered.map(c=>({city:c.city,x:c.enforcementScore,y:c.pm25}))} fill={T.navy} fillOpacity={0.5}/></ScatterChart></ResponsiveContainer></div>
        <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Top 20 Cities - Enforcement Score</div><ResponsiveContainer width="100%" height={300}><BarChart data={regData}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="city" tick={{fontSize:8,fill:T.textSec}} angle={-30}/><YAxis tick={{fontSize:9,fill:T.textSec}} domain={[0,100]}/><Tooltip {...tip}/><Bar dataKey="enforcementScore" fill={T.navy} radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></div>
        <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Green Space % vs AQI</div><ResponsiveContainer width="100%" height={280}><ScatterChart><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="x" name="Green Space %" tick={{fontSize:9,fill:T.textSec}}/><YAxis dataKey="y" name="AQI" tick={{fontSize:9,fill:T.textSec}}/><Tooltip {...tip}/><Scatter data={filtered.map(c=>({city:c.city,x:c.greenSpacePct,y:c.aqi}))} fill={T.sage} fillOpacity={0.5}/></ScatterChart></ResponsiveContainer></div>
        <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>EV Adoption vs PM2.5</div><ResponsiveContainer width="100%" height={280}><ScatterChart><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="x" name="EV %" tick={{fontSize:9,fill:T.textSec}}/><YAxis dataKey="y" name="PM2.5" tick={{fontSize:9,fill:T.textSec}}/><Tooltip {...tip}/><Scatter data={filtered.map(c=>({city:c.city,x:c.evAdoption,y:c.pm25}))} fill={T.green} fillOpacity={0.5}/></ScatterChart></ResponsiveContainer></div>
        <div style={{...cS,gridColumn:'1/3'}}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Policy Count & Monitor Stations</div>
          <div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr>{['City','Policies','Stations','Enforcement','Nat Std','Green Space','EV Adopt.'].map(h=><th key={h} style={thS}>{h}</th>)}</tr></thead><tbody>{regData.map(r=><tr key={r.id}><td style={tdS}>{r.city}</td><td style={tdS}>{r.policyCount}</td><td style={tdS}>{r.monitorStations}</td><td style={tdS}>{r.enforcementScore}/100</td><td style={tdS}>{r.natStandard} ug/m3</td><td style={tdS}>{r.greenSpacePct}%</td><td style={tdS}>{r.evAdoption}%</td></tr>)}</tbody></table></div>
        </div>
      </div>
    </div>);
  };

  return(<div style={{padding:'24px 32px',fontFamily:T.font,background:T.bg,minHeight:'100vh'}}>
    <div style={{marginBottom:20}}><h1 style={{fontSize:22,fontWeight:700,color:T.navy,margin:0}}>Air Quality & Health Risk Analytics</h1><p style={{fontSize:12,color:T.textSec,margin:'4px 0 0'}}>50 cities | PM2.5, NO2, SO2, O3 monitoring | WHO compliance | Health economics</p></div>
    <div style={{display:'flex',gap:8,marginBottom:20}}>{TABS.map((t,i)=><button key={t} onClick={()=>setTab(i)} style={btnS(tab===i)}>{t}</button>)}</div>
    {tab===0&&renderDash()}{tab===1&&renderPollutant()}{tab===2&&renderHealth()}{tab===3&&renderReg()}
    <SidePanel item={selected} onClose={()=>setSelected(null)}/>
  </div>);
}