import React,{useState,useMemo,useCallback} from 'react';
import {BarChart,Bar,XAxis,YAxis,CartesianGrid,Tooltip,ResponsiveContainer,PieChart,Pie,Cell,AreaChart,Area,ScatterChart,Scatter,ZAxis,Legend,RadarChart,Radar,PolarGrid,PolarAngleAxis,PolarRadiusAxis,LineChart,Line} from 'recharts';
const T={bg:'#f6f4f0',surface:'#ffffff',surfaceH:'#f0ede7',border:'#e5e0d8',borderL:'#d5cfc5',navy:'#1b3a5c',navyL:'#2c5a8c',gold:'#c5a96a',goldL:'#d4be8a',sage:'#5a8a6a',sageL:'#7ba67d',teal:'#5a8a6a',text:'#1b3a5c',textSec:'#5c6b7e',textMut:'#9aa3ae',red:'#dc2626',green:'#16a34a',amber:'#d97706',font:"'DM Sans','SF Pro Display',system-ui,-apple-system,sans-serif",mono:"'JetBrains Mono','SF Mono','Fira Code',monospace"};
const sr=(s)=>{let x=Math.sin(s+1)*10000;return x-Math.floor(x);};const ACCENT='#e11d48';const tip={contentStyle:{background:T.surface,border:`1px solid ${T.border}`,borderRadius:8,fontSize:11,fontFamily:T.font},labelStyle:{color:T.textSec,fontFamily:T.mono,fontSize:10}};
const TABS=['Contagion Dashboard','Asset Class Linkages','Transmission Channels','Stress Scenarios'];const ASSETS_CLS=['All','Equities','Fixed Income','Credit','Commodities','Real Estate','FX','Derivatives'];const PAGE_SIZE=12;const PIECLRS=[T.navy,T.gold,T.sage,T.red,T.amber,T.green,T.navyL,T.goldL,'#8b5cf6'];
const LINKS=(()=>{const pairs=[['Equities','Fixed Income'],['Equities','Credit'],['Equities','Commodities'],['Equities','Real Estate'],['Equities','FX'],['Fixed Income','Credit'],['Fixed Income','Commodities'],['Fixed Income','Real Estate'],['Fixed Income','FX'],['Credit','Commodities'],['Credit','Real Estate'],['Credit','FX'],['Commodities','Real Estate'],['Commodities','FX'],['Real Estate','FX'],['Equities','Derivatives'],['Fixed Income','Derivatives'],['Credit','Derivatives'],['Commodities','Derivatives'],['Real Estate','Derivatives'],['FX','Derivatives'],['Equities - ESG','Credit'],['Equities - ESG','Fixed Income'],['Green Bonds','Equities'],['Green Bonds','Credit'],['Carbon Markets','Equities'],['Carbon Markets','Commodities'],['Carbon Markets','Fixed Income'],['Transition Risk','Equities'],['Transition Risk','Credit'],['Physical Risk','Real Estate'],['Physical Risk','Insurance'],['Stranded Assets','Equities'],['Stranded Assets','Credit'],['Biodiversity','Commodities'],['Biodiversity','Real Estate'],['Water Risk','Agriculture'],['Water Risk','Utilities'],['Social Risk','Equities'],['Regulatory Risk','All Assets']];
  return pairs.map((p,i)=>({id:i+1,from:p[0],to:p[1],correlation:+(sr(i*7)*0.9-0.1).toFixed(2),contagionScore:Math.round(10+sr(i*11)*85),spilloverPct:Math.round(sr(i*13)*60),transmissionSpeed:Math.round(1+sr(i*17)*30),amplification:+(sr(i*19)*3+0.5).toFixed(1),esgDriver:sr(i*23)<0.4?'Climate':sr(i*23)<0.6?'Social':sr(i*23)<0.8?'Governance':'Multi-factor',regime:sr(i*29)<0.3?'Crisis':sr(i*29)<0.6?'Stressed':'Normal',timelag:Math.round(sr(i*31)*14),directionality:sr(i*37)<0.4?'Bidirectional':sr(i*37)<0.7?'From->To':'To->From',strength:sr(i*41)<0.2?'Very Strong':sr(i*41)<0.4?'Strong':sr(i*41)<0.65?'Moderate':'Weak'}));})();
const TREND=Array.from({length:24},(_,i)=>({month:`${2023+Math.floor(i/12)}-${String((i%12)+1).padStart(2,'0')}`,contagionIdx:Math.round(35+sr(i*7)*25+Math.sin(i/4)*10),correlationAvg:+(0.3+sr(i*11)*0.3+Math.sin(i/3)*0.1).toFixed(2),spillover:Math.round(15+sr(i*13)*20+Math.sin(i/5)*8),stressLevel:Math.round(30+sr(i*17)*30)}));
const CHANNELS=[{channel:'Credit Spread Contagion',weight:22,speed:3},{channel:'Equity-Bond Correlation',weight:18,speed:1},{channel:'FX Carry Unwind',weight:14,speed:2},{channel:'Commodity Price Shock',weight:12,speed:5},{channel:'Real Estate Repricing',weight:10,speed:15},{channel:'ESG Sentiment Cascade',weight:8,speed:4},{channel:'Carbon Price Transmission',weight:7,speed:7},{channel:'Regulatory Shock',weight:5,speed:10},{channel:'Liquidity Contagion',weight:4,speed:1}];

export default function CrossAssetContagionPage(){
  const[tab,setTab]=useState(0);const[search,setSearch]=useState('');const[sortCol,setSortCol]=useState('contagionScore');const[sortDir,setSortDir]=useState('desc');const[page,setPage]=useState(1);const[selected,setSelected]=useState(null);
  const filtered=useMemo(()=>{let d=[...LINKS];if(search)d=d.filter(r=>r.from.toLowerCase().includes(search.toLowerCase())||r.to.toLowerCase().includes(search.toLowerCase()));d.sort((a,b)=>sortDir==='asc'?(a[sortCol]>b[sortCol]?1:-1):(a[sortCol]<b[sortCol]?1:-1));return d;},[search,sortCol,sortDir]);
  const paged=useMemo(()=>filtered.slice((page-1)*PAGE_SIZE,page*PAGE_SIZE),[filtered,page]);const totalPages=Math.ceil(filtered.length/PAGE_SIZE);
  const doSort=(col)=>{if(sortCol===col)setSortDir(d=>d==='asc'?'desc':'asc');else{setSortCol(col);setSortDir('desc');}setPage(1);};
  const stats=useMemo(()=>({count:filtered.length,avgContagion:(filtered.reduce((s,r)=>s+r.contagionScore,0)/filtered.length||0).toFixed(0),avgCorr:(filtered.reduce((s,r)=>s+r.correlation,0)/filtered.length||0).toFixed(2),crisis:filtered.filter(r=>r.regime==='Crisis').length,avgSpeed:(filtered.reduce((s,r)=>s+r.transmissionSpeed,0)/filtered.length||0).toFixed(0)}),[filtered]);
  const driverDist=useMemo(()=>{const m={};LINKS.forEach(r=>{m[r.esgDriver]=(m[r.esgDriver]||0)+1;});return Object.entries(m).map(([k,v])=>({name:k,value:v}));},[]);
  const strengthDist=useMemo(()=>{const m={};LINKS.forEach(r=>{m[r.strength]=(m[r.strength]||0)+1;});return Object.entries(m).map(([k,v])=>({name:k,value:v}));},[]);
  const exportCSV=useCallback((data,fn)=>{if(!data.length)return;const keys=Object.keys(data[0]);const csv=[keys.join(','),...data.map(r=>keys.map(k=>`"${r[k]}"`).join(','))].join('\n');const blob=new Blob([csv],{type:'text/csv'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=fn;a.click();URL.revokeObjectURL(url);},[]);
  const si=(col,cur,dir)=>cur===col?(dir==='asc'?' \u25B2':' \u25BC'):' \u25CB';
  const thS={padding:'8px 10px',fontSize:11,fontFamily:T.mono,color:T.textSec,cursor:'pointer',borderBottom:`1px solid ${T.border}`,whiteSpace:'nowrap',userSelect:'none',textAlign:'left',background:T.surfaceH};const tdS={padding:'7px 10px',fontSize:12,fontFamily:T.font,borderBottom:`1px solid ${T.border}`,color:T.text};const inpS={padding:'6px 12px',border:`1px solid ${T.border}`,borderRadius:6,fontSize:12,fontFamily:T.font,background:T.surface,color:T.text,outline:'none',width:220};const btnS=(a)=>({padding:'6px 16px',border:`1px solid ${a?ACCENT:T.border}`,borderRadius:6,fontSize:12,fontFamily:T.font,background:a?ACCENT:T.surface,color:a?'#fff':T.text,cursor:'pointer',fontWeight:a?600:400});const pgB={padding:'4px 10px',border:`1px solid ${T.border}`,borderRadius:4,fontSize:11,cursor:'pointer',background:T.surface,color:T.text};const cS={background:T.surface,border:`1px solid ${T.border}`,borderRadius:10,padding:16};
  const bdg=(val,th)=>{const[lo,mid,hi]=th;const bg=val>=hi?'rgba(220,38,38,0.12)':val>=mid?'rgba(217,119,6,0.12)':val>=lo?'rgba(197,169,106,0.12)':'rgba(22,163,74,0.12)';const c=val>=hi?T.red:val>=mid?T.amber:val>=lo?T.gold:T.green;return{background:bg,color:c,padding:'2px 8px',borderRadius:4,fontSize:11,fontWeight:600,fontFamily:T.mono};};
  const kpi=(l,v)=>(<div style={{background:T.surface,border:`1px solid ${T.border}`,borderRadius:10,padding:'14px 18px',flex:1,minWidth:150}}><div style={{fontSize:10,color:T.textMut,fontFamily:T.mono,textTransform:'uppercase',letterSpacing:1}}>{l}</div><div style={{fontSize:24,fontWeight:700,color:T.navy,marginTop:4}}>{v}</div></div>);
  const SidePanel=({item,onClose})=>{if(!item)return null;return(<div style={{position:'fixed',top:0,right:0,width:440,height:'100vh',background:T.surface,borderLeft:`2px solid ${ACCENT}`,zIndex:1000,overflowY:'auto',boxShadow:'-4px 0 24px rgba(0,0,0,0.10)'}}><div style={{padding:'20px 24px',borderBottom:`1px solid ${T.border}`,display:'flex',justifyContent:'space-between',alignItems:'center'}}><div style={{fontSize:16,fontWeight:700,color:T.navy}}>{item.from} → {item.to}</div><button onClick={onClose} style={{background:'none',border:'none',fontSize:20,cursor:'pointer',color:T.textMut}}>x</button></div><div style={{padding:'16px 24px'}}><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:10}}>{[['Correlation',item.correlation],['Contagion',item.contagionScore+'/100'],['Spillover',item.spilloverPct+'%'],['Speed',item.transmissionSpeed+' days'],['Amplification',item.amplification+'x'],['ESG Driver',item.esgDriver],['Regime',item.regime],['Time Lag',item.timelag+' days'],['Direction',item.directionality],['Strength',item.strength]].map(([k,v],i)=>(<div key={i} style={{background:T.surfaceH,borderRadius:6,padding:'8px 12px'}}><div style={{fontSize:10,color:T.textMut,fontFamily:T.mono}}>{k}</div><div style={{fontSize:14,fontWeight:600,color:T.navy,marginTop:2}}>{v}</div></div>))}</div></div></div>);};

  const renderDash=()=>(<div>
    <div style={{display:'flex',gap:12,marginBottom:20,flexWrap:'wrap'}}>{kpi('Linkages',stats.count)}{kpi('Avg Contagion',stats.avgContagion+'/100')}{kpi('Avg Correlation',stats.avgCorr)}{kpi('Crisis Regime',stats.crisis)}{kpi('Avg Speed',stats.avgSpeed+' days')}</div>
    <div style={{display:'flex',gap:12,marginBottom:16,alignItems:'center'}}><input value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}} placeholder="Search linkages..." style={inpS}/><button onClick={()=>exportCSV(filtered,'cross_asset_contagion.csv')} style={btnS(false)}>Export CSV</button></div>
    <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16,marginBottom:20}}>
      <div style={cS}><div style={{fontSize:11,fontFamily:T.mono,color:T.textSec,marginBottom:8}}>ESG DRIVER DISTRIBUTION</div><ResponsiveContainer width="100%" height={220}><PieChart><Pie data={driverDist} cx="50%" cy="50%" outerRadius={80} dataKey="value" label={({name,percent})=>`${name} ${(percent*100).toFixed(0)}%`}>{driverDist.map((_,i)=><Cell key={i} fill={PIECLRS[i%PIECLRS.length]}/>)}</Pie><Tooltip {...tip}/></PieChart></ResponsiveContainer></div>
      <div style={cS}><div style={{fontSize:11,fontFamily:T.mono,color:T.textSec,marginBottom:8}}>CONTAGION INDEX TREND</div><ResponsiveContainer width="100%" height={220}><AreaChart data={TREND}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="month" tick={{fontSize:8}}/><YAxis tick={{fontSize:10}}/><Tooltip {...tip}/><Area type="monotone" dataKey="contagionIdx" stroke={ACCENT} fill={ACCENT} fillOpacity={0.1} name="Contagion Index"/><Area type="monotone" dataKey="stressLevel" stroke={T.amber} fill={T.amber} fillOpacity={0.08} name="Stress Level"/><Legend/></AreaChart></ResponsiveContainer></div>
    </div>
    <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16,marginBottom:20}}>
      <div style={cS}><div style={{fontSize:11,fontFamily:T.mono,color:T.textSec,marginBottom:8}}>CORRELATION vs SPILLOVER</div><ResponsiveContainer width="100%" height={240}><ScatterChart><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="x" name="Correlation" tick={{fontSize:10}}/><YAxis dataKey="y" name="Spillover %" tick={{fontSize:10}}/><Tooltip {...tip}/><Scatter data={filtered.map(r=>({name:r.from+'->'+r.to,x:r.correlation,y:r.spilloverPct}))} fill={ACCENT} fillOpacity={0.5}/></ScatterChart></ResponsiveContainer></div>
      <div style={cS}><div style={{fontSize:11,fontFamily:T.mono,color:T.textSec,marginBottom:8}}>LINK STRENGTH DISTRIBUTION</div><ResponsiveContainer width="100%" height={240}><BarChart data={strengthDist}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="name" tick={{fontSize:10}}/><YAxis tick={{fontSize:10}}/><Tooltip {...tip}/><Bar dataKey="value" fill={ACCENT} name="Links" radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></div>
    </div>
    <div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr>{[['from','From'],['to','To'],['contagionScore','Contagion'],['correlation','Corr.'],['spilloverPct','Spillover'],['transmissionSpeed','Speed'],['amplification','Amplif.'],['esgDriver','Driver'],['strength','Strength']].map(([col,label])=>(<th key={col} onClick={()=>doSort(col)} style={thS}>{label}{si(col,sortCol,sortDir)}</th>))}</tr></thead><tbody>{paged.map(r=>(<tr key={r.id} onClick={()=>setSelected(r)} style={{cursor:'pointer',background:selected?.id===r.id?T.surfaceH:'transparent'}}><td style={{...tdS,fontWeight:600}}>{r.from}</td><td style={tdS}>{r.to}</td><td style={tdS}><span style={bdg(r.contagionScore,[30,55,75])}>{r.contagionScore}</span></td><td style={tdS}>{r.correlation}</td><td style={tdS}>{r.spilloverPct}%</td><td style={tdS}>{r.transmissionSpeed}d</td><td style={tdS}>{r.amplification}x</td><td style={tdS}>{r.esgDriver}</td><td style={tdS}>{r.strength}</td></tr>))}</tbody></table>
    <div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginTop:12}}><span style={{fontSize:11,color:T.textMut,fontFamily:T.mono}}>{filtered.length} linkages | Page {page}/{totalPages}</span><div style={{display:'flex',gap:4}}><button disabled={page<=1} onClick={()=>setPage(p=>p-1)} style={pgB}>Prev</button><button disabled={page>=totalPages} onClick={()=>setPage(p=>p+1)} style={pgB}>Next</button></div></div></div>
  </div>);

  const renderLinkages=()=>(<div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16,marginBottom:20}}><div style={cS}><div style={{fontSize:11,fontFamily:T.mono,color:T.textSec,marginBottom:8}}>CONTAGION SCORE vs SPEED</div><ResponsiveContainer width="100%" height={280}><ScatterChart><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="x" name="Contagion" tick={{fontSize:10}}/><YAxis dataKey="y" name="Speed (days)" tick={{fontSize:10}}/><ZAxis dataKey="z" range={[20,200]}/><Tooltip {...tip}/><Scatter data={LINKS.map(r=>({name:r.from+'->'+r.to,x:r.contagionScore,y:r.transmissionSpeed,z:r.amplification*30}))} fill={T.red} fillOpacity={0.5}/></ScatterChart></ResponsiveContainer></div><div style={cS}><div style={{fontSize:11,fontFamily:T.mono,color:T.textSec,marginBottom:8}}>CORRELATION EVOLUTION</div><ResponsiveContainer width="100%" height={280}><LineChart data={TREND}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="month" tick={{fontSize:8}}/><YAxis tick={{fontSize:10}}/><Tooltip {...tip}/><Line type="monotone" dataKey="correlationAvg" stroke={ACCENT} strokeWidth={2} name="Avg Correlation"/><Line type="monotone" dataKey="spillover" stroke={T.gold} strokeWidth={2} name="Spillover %"/><Legend/></LineChart></ResponsiveContainer></div></div><div style={cS}><div style={{fontSize:11,fontFamily:T.mono,color:T.textSec,marginBottom:8}}>DIRECTIONALITY BREAKDOWN</div><ResponsiveContainer width="100%" height={220}><PieChart><Pie data={[{name:'Bidirectional',value:LINKS.filter(r=>r.directionality==='Bidirectional').length},{name:'From->To',value:LINKS.filter(r=>r.directionality==='From->To').length},{name:'To->From',value:LINKS.filter(r=>r.directionality==='To->From').length}]} cx="50%" cy="50%" outerRadius={80} dataKey="value" label={({name,percent})=>`${name} ${(percent*100).toFixed(0)}%`}>{[0,1,2].map(i=><Cell key={i} fill={[ACCENT,T.gold,T.navy][i]}/>)}</Pie><Tooltip {...tip}/></PieChart></ResponsiveContainer></div></div>);

  const renderChannels=()=>(<div><div style={cS}><div style={{fontSize:11,fontFamily:T.mono,color:T.textSec,marginBottom:8}}>TRANSMISSION CHANNEL WEIGHTS</div><ResponsiveContainer width="100%" height={300}><BarChart data={CHANNELS} layout="vertical"><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis type="number" tick={{fontSize:10}}/><YAxis dataKey="channel" type="category" tick={{fontSize:9}} width={160}/><Tooltip {...tip}/><Bar dataKey="weight" fill={ACCENT} name="Weight %" radius={[0,4,4,0]}/></BarChart></ResponsiveContainer></div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16,marginTop:16}}><div style={cS}><div style={{fontSize:11,fontFamily:T.mono,color:T.textSec,marginBottom:8}}>CHANNEL SPEED vs WEIGHT</div><ResponsiveContainer width="100%" height={240}><ScatterChart><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="x" name="Weight %" tick={{fontSize:10}}/><YAxis dataKey="y" name="Speed (days)" tick={{fontSize:10}}/><Tooltip {...tip}/><Scatter data={CHANNELS.map(r=>({name:r.channel,x:r.weight,y:r.speed}))} fill={T.gold} fillOpacity={0.6} r={8}/></ScatterChart></ResponsiveContainer></div><div style={cS}><div style={{fontSize:11,fontFamily:T.mono,color:T.textSec,marginBottom:8}}>CHANNEL TABLE</div><table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr>{['Channel','Weight %','Speed (days)'].map(h=>(<th key={h} style={thS}>{h}</th>))}</tr></thead><tbody>{CHANNELS.map((r,i)=>(<tr key={i}><td style={{...tdS,fontWeight:600}}>{r.channel}</td><td style={tdS}>{r.weight}%</td><td style={tdS}>{r.speed}d</td></tr>))}</tbody></table></div></div></div>);

  const renderStress=()=>(<div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16,marginBottom:20}}><div style={cS}><div style={{fontSize:11,fontFamily:T.mono,color:T.textSec,marginBottom:8}}>REGIME DISTRIBUTION</div><ResponsiveContainer width="100%" height={220}><PieChart><Pie data={[{name:'Crisis',value:LINKS.filter(r=>r.regime==='Crisis').length},{name:'Stressed',value:LINKS.filter(r=>r.regime==='Stressed').length},{name:'Normal',value:LINKS.filter(r=>r.regime==='Normal').length}]} cx="50%" cy="50%" outerRadius={80} dataKey="value" label={({name,percent})=>`${name} ${(percent*100).toFixed(0)}%`}>{[0,1,2].map(i=><Cell key={i} fill={[T.red,T.amber,T.green][i]}/>)}</Pie><Tooltip {...tip}/></PieChart></ResponsiveContainer></div><div style={cS}><div style={{fontSize:11,fontFamily:T.mono,color:T.textSec,marginBottom:8}}>STRESS LEVEL EVOLUTION</div><ResponsiveContainer width="100%" height={220}><AreaChart data={TREND}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="month" tick={{fontSize:8}}/><YAxis tick={{fontSize:10}}/><Tooltip {...tip}/><Area type="monotone" dataKey="stressLevel" stroke={T.red} fill={T.red} fillOpacity={0.1} name="Stress Level"/><Legend/></AreaChart></ResponsiveContainer></div></div><div style={cS}><div style={{fontSize:11,fontFamily:T.mono,color:T.textSec,marginBottom:8}}>AMPLIFICATION BY ESG DRIVER</div><ResponsiveContainer width="100%" height={240}><BarChart data={(()=>{const drivers=[...new Set(LINKS.map(r=>r.esgDriver))];return drivers.map(d=>{const l=LINKS.filter(r=>r.esgDriver===d);return{driver:d,avgAmp:+(l.reduce((s,r)=>s+parseFloat(r.amplification),0)/l.length).toFixed(1),count:l.length};});})()}>
    <CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="driver" tick={{fontSize:10}}/><YAxis tick={{fontSize:10}}/><Tooltip {...tip}/><Bar dataKey="avgAmp" fill={ACCENT} name="Avg Amplification" radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></div></div>);

  return(<div style={{fontFamily:T.font,background:T.bg,minHeight:'100vh',padding:'24px 32px',color:T.text}}>
    <div style={{marginBottom:20}}><div style={{fontSize:22,fontWeight:700,color:T.navy}}>Cross-Asset ESG Contagion</div><div style={{fontSize:12,color:T.textSec,marginTop:4,fontFamily:T.mono}}>Cross-asset ESG contagion, transmission channels, spillover analysis across {LINKS.length} linkages</div></div>
    <div style={{display:'flex',gap:4,marginBottom:20,borderBottom:`2px solid ${T.border}`}}>{TABS.map((t,i)=>(<button key={t} onClick={()=>setTab(i)} style={{...btnS(tab===i),borderRadius:'6px 6px 0 0',borderBottom:tab===i?`2px solid ${ACCENT}`:'2px solid transparent'}}>{t}</button>))}</div>
    {tab===0&&renderDash()}{tab===1&&renderLinkages()}{tab===2&&renderChannels()}{tab===3&&renderStress()}
    <SidePanel item={selected} onClose={()=>setSelected(null)}/>
  </div>);
}
