import React,{useState,useMemo,useCallback} from 'react';
import {BarChart,Bar,LineChart,Line,AreaChart,Area,PieChart,Pie,Cell,ScatterChart,Scatter,XAxis,YAxis,CartesianGrid,Tooltip,ResponsiveContainer,Legend,RadarChart,Radar,PolarGrid,PolarAngleAxis,PolarRadiusAxis} from 'recharts';
const T={bg:'#f6f4f0',surface:'#ffffff',surfaceH:'#f0ede7',border:'#e5e0d8',borderL:'#d5cfc5',navy:'#1b3a5c',navyL:'#2c5a8c',gold:'#c5a96a',goldL:'#d4be8a',sage:'#5a8a6a',sageL:'#7ba67d',teal:'#5a8a6a',text:'#1b3a5c',textSec:'#5c6b7e',textMut:'#9aa3ae',red:'#dc2626',green:'#16a34a',amber:'#d97706',font:"'DM Sans','SF Pro Display',system-ui,-apple-system,sans-serif",mono:"'JetBrains Mono','SF Mono','Fira Code',monospace"};
const sr=(s)=>{let x=Math.sin(s+1)*10000;return x-Math.floor(x);};
const ACCENT='#059669';const tip={contentStyle:{background:T.surface,border:`1px solid ${T.border}`,borderRadius:8,fontSize:11,fontFamily:T.font},labelStyle:{color:T.textSec,fontFamily:T.mono,fontSize:10}};const COLORS=[T.navy,T.gold,T.sage,T.red,T.amber,T.green,T.navyL,T.goldL,T.sageL,'#8b5cf6','#ec4899','#06b6d4'];
const fmt=v=>typeof v==='number'?v>=1e9?(v/1e9).toFixed(1)+'B':v>=1e6?(v/1e6).toFixed(1)+'M':v>=1e3?(v/1e3).toFixed(1)+'K':v.toFixed(1):v;
const TABS=['Wage Dashboard','Gap Analysis','Regional Benchmarks','Progress Tracking'];const SECTORS=['All','Consumer','Apparel','Agriculture','Technology','Industrials','Hospitality'];const PAGE=12;
const COS=Array.from({length:50},(_,i)=>{
  const names=['Walmart','Amazon','Nike','H&M','Nestle','Unilever','Starbucks','McDonalds','Coca-Cola','PepsiCo','Costco','Target','Adidas','Inditex','LVMH','P&G','J&J','Tyson Foods','JBS','Cargill','Gap Inc','VF Corp','Levi Strauss','PVH Corp','Hanesbrands','Fast Retailing','Under Armour','Puma','L\'Oreal','Danone','Mondelez','Mars','Reckitt','Colgate','General Mills','Kellogg','Kraft Heinz','Conagra','Hormel','Sysco','Marriott','Hilton','Yum Brands','Darden','Chipotle','Kroger','Albertsons','Ahold Delhaize','Tesco','Carrefour'];
  const secs=['Consumer','Technology','Apparel','Apparel','Consumer','Consumer','Hospitality','Hospitality','Consumer','Consumer','Consumer','Consumer','Apparel','Apparel','Consumer','Consumer','Consumer','Agriculture','Agriculture','Agriculture','Apparel','Apparel','Apparel','Apparel','Apparel','Apparel','Apparel','Apparel','Consumer','Consumer','Consumer','Consumer','Consumer','Consumer','Consumer','Consumer','Consumer','Consumer','Consumer','Consumer','Hospitality','Hospitality','Hospitality','Hospitality','Hospitality','Consumer','Consumer','Consumer','Consumer','Consumer'];
  const workforce=Math.round(sr(i*7)*500+20);const lwGap=Math.round(sr(i*11)*40);const regions=Math.round(sr(i*13)*30+5);const supplyWorkers=Math.round(sr(i*17)*200+10);
  const regBench=Array.from({length:6},(_,r)=>{const rn=['South Asia','Southeast Asia','Sub-Saharan Africa','Latin America','Eastern Europe','East Asia'][r];return{region:rn,lwBench:Math.round(sr(i*100+r*7)*400+200),actualPay:Math.round(sr(i*100+r*11)*500+150),gap:Math.round(sr(i*100+r*13)*30)};});
  const yearly=Array.from({length:5},(_,y)=>({year:2020+y,gap:Math.round(lwGap+5-y*2+sr(i*100+y)*4),coverage:Math.round(50+y*5+sr(i*100+y*3)*8),spend:+(sr(i*100+y*7)*2+0.5).toFixed(1)}));
  return{id:i+1,name:names[i],sector:secs[i],workforceK:workforce,livingWageGap:lwGap,lwCoverage:Math.round(100-lwGap),regionsOp:regions,supplyWorkersK:supplyWorkers,annualWageCostM:Math.round(sr(i*19)*500+50),lwIncreaseCostM:Math.round(sr(i*23)*100+5),commitYear:sr(i*29)<0.3?2025:sr(i*29)<0.6?2027:2030,progress:sr(i*31)<0.3?'On Track':sr(i*31)<0.6?'Behind':'At Risk',methodology:['Anker','WageIndicator','MIT Living Wage','Global Living Wage'][Math.floor(sr(i*37)*4)],verification:sr(i*41)>0.4?'Third-party':'Self-assessed',genderPayGap:Math.round(sr(i*43)*20),supplyChainAudit:sr(i*47)>0.3?'Yes':'No',transparencyScore:Math.round(sr(i*49)*40+50),regBench,yearly};
});
export default function LivingWageTrackerPage(){
  const[tab,setTab]=useState(0);const[search,setSearch]=useState('');const[sectorF,setSectorF]=useState('All');const[sortCol,setSortCol]=useState('livingWageGap');const[sortDir,setSortDir]=useState('desc');const[page,setPage]=useState(1);const[selected,setSelected]=useState(null);
  const filtered=useMemo(()=>{let d=[...COS];if(search)d=d.filter(r=>r.name.toLowerCase().includes(search.toLowerCase()));if(sectorF!=='All')d=d.filter(r=>r.sector===sectorF);d.sort((a,b)=>sortDir==='asc'?(a[sortCol]>b[sortCol]?1:-1):(a[sortCol]<b[sortCol]?1:-1));return d;},[search,sectorF,sortCol,sortDir]);
  const paged=useMemo(()=>filtered.slice((page-1)*PAGE,page*PAGE),[filtered,page]);const totalPages=Math.ceil(filtered.length/PAGE);
  const doSort=col=>{if(sortCol===col)setSortDir(d=>d==='asc'?'desc':'asc');else{setSortCol(col);setSortDir('desc');}setPage(1);};
  const stats=useMemo(()=>({count:filtered.length,avgGap:Math.round(filtered.reduce((s,r)=>s+r.livingWageGap,0)/filtered.length||0),avgCoverage:Math.round(filtered.reduce((s,r)=>s+r.lwCoverage,0)/filtered.length||0),totalWorkers:fmt(filtered.reduce((s,r)=>s+r.workforceK,0)*1000),onTrack:filtered.filter(r=>r.progress==='On Track').length,totalCost:'$'+Math.round(filtered.reduce((s,r)=>s+r.lwIncreaseCostM,0))+'M',verified:filtered.filter(r=>r.verification==='Third-party').length}),[filtered]);
  const sectorGap=useMemo(()=>{const m={};COS.forEach(c=>{if(!m[c.sector])m[c.sector]={s:c.sector,gap:0,cov:0,n:0};m[c.sector].gap+=c.livingWageGap;m[c.sector].cov+=c.lwCoverage;m[c.sector].n++;});return Object.values(m).map(s=>({sector:s.s,gap:Math.round(s.gap/s.n),coverage:Math.round(s.cov/s.n)})).sort((a,b)=>b.gap-a.gap);},[]);
  const exportCSV=useCallback((data,fn)=>{if(!data.length)return;const keys=Object.keys(data[0]).filter(k=>k!=='regBench'&&k!=='yearly');const csv=[keys.join(','),...data.map(r=>keys.map(k=>`"${r[k]}"`).join(','))].join('\n');const b=new Blob([csv],{type:'text/csv'});const u=URL.createObjectURL(b);const a=document.createElement('a');a.href=u;a.download=fn;a.click();URL.revokeObjectURL(u);},[]);
  const si=(col,cur,dir)=>cur===col?(dir==='asc'?' \u25B2':' \u25BC'):' \u25CB';
  const thS={padding:'8px 10px',fontSize:11,fontFamily:T.mono,color:T.textSec,cursor:'pointer',borderBottom:`1px solid ${T.border}`,whiteSpace:'nowrap',userSelect:'none',textAlign:'left',background:T.surfaceH};const tdS={padding:'7px 10px',fontSize:12,fontFamily:T.font,borderBottom:`1px solid ${T.border}`,color:T.text};
  const inpS={padding:'6px 12px',border:`1px solid ${T.border}`,borderRadius:6,fontSize:12,fontFamily:T.font,background:T.surface,color:T.text,outline:'none',width:220};const selS={padding:'6px 10px',border:`1px solid ${T.border}`,borderRadius:6,fontSize:11,fontFamily:T.font,background:T.surface,color:T.text};
  const btnS=a=>({padding:'6px 16px',border:`1px solid ${a?ACCENT:T.border}`,borderRadius:6,fontSize:12,fontFamily:T.font,background:a?ACCENT:T.surface,color:a?'#fff':T.text,cursor:'pointer',fontWeight:a?600:400});const pgB={padding:'4px 10px',border:`1px solid ${T.border}`,borderRadius:4,fontSize:11,cursor:'pointer',background:T.surface,color:T.text};const cS={background:T.surface,border:`1px solid ${T.border}`,borderRadius:10,padding:16};
  const kpi=(l,v,c)=>(<div style={{background:T.surface,border:`1px solid ${T.border}`,borderRadius:10,padding:'14px 18px',flex:1,minWidth:140}}><div style={{fontSize:10,color:T.textMut,fontFamily:T.mono,textTransform:'uppercase',letterSpacing:1}}>{l}</div><div style={{fontSize:22,fontWeight:700,color:c||T.navy,marginTop:4}}>{v}</div></div>);
  const Panel=({item,onClose})=>{if(!item)return null;return(<div style={{position:'fixed',top:0,right:0,width:460,height:'100vh',background:T.surface,borderLeft:`2px solid ${ACCENT}`,zIndex:1000,overflowY:'auto',boxShadow:'-4px 0 24px rgba(0,0,0,0.10)'}}><div style={{padding:'20px 24px',borderBottom:`1px solid ${T.border}`,display:'flex',justifyContent:'space-between',alignItems:'center'}}><div><div style={{fontSize:16,fontWeight:700,color:T.navy}}>{item.name}</div><div style={{fontSize:12,color:T.textSec}}>{item.sector} | Gap: {item.livingWageGap}%</div></div><button onClick={onClose} style={{background:'none',border:'none',fontSize:20,cursor:'pointer',color:T.textMut}}>{'\u2715'}</button></div>
    <div style={{padding:'16px 24px'}}>
      <div style={{display:'grid',gridTemplateColumns:'1fr 1fr 1fr',gap:8,marginBottom:16}}>{[['Workforce',item.workforceK+'K'],['LW Gap',item.livingWageGap+'%'],['Coverage',item.lwCoverage+'%'],['Regions',item.regionsOp],['Supply Workers',item.supplyWorkersK+'K'],['Wage Cost','$'+item.annualWageCostM+'M'],['LW Increase','$'+item.lwIncreaseCostM+'M'],['Commit Year',item.commitYear],['Progress',item.progress],['Gender Gap',item.genderPayGap+'%'],['Verification',item.verification],['Transparency',item.transparencyScore+'/100']].map(([k,v],j)=>(<div key={j} style={{background:T.surfaceH,borderRadius:6,padding:'8px 10px'}}><div style={{fontSize:9,color:T.textMut,fontFamily:T.mono}}>{k}</div><div style={{fontSize:13,fontWeight:600,color:T.navy,marginTop:2}}>{v}</div></div>))}</div>
      <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Regional Wage Benchmark</div><ResponsiveContainer width="100%" height={200}><BarChart data={item.regBench}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="region" tick={{fontSize:7,fill:T.textSec}} angle={-20}/><YAxis tick={{fontSize:9,fill:T.textSec}}/><Tooltip {...tip}/><Bar dataKey="lwBench" fill={T.green} name="LW Benchmark"/><Bar dataKey="actualPay" fill={T.gold} name="Actual Pay"/><Legend/></BarChart></ResponsiveContainer></div>
      <div style={{...cS,marginTop:12}}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>5-Year Gap Trend</div><ResponsiveContainer width="100%" height={180}><LineChart data={item.yearly}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="year" tick={{fontSize:9,fill:T.textSec}}/><YAxis tick={{fontSize:9,fill:T.textSec}}/><Tooltip {...tip}/><Line type="monotone" dataKey="gap" stroke={T.red} name="Gap %" strokeWidth={2}/><Line type="monotone" dataKey="coverage" stroke={T.green} name="Coverage %" strokeWidth={2}/><Legend/></LineChart></ResponsiveContainer></div>
    </div></div>);};

  const renderDash=()=>(<div>
    <div style={{display:'flex',gap:12,marginBottom:20,flexWrap:'wrap'}}>{kpi('Companies',stats.count)}{kpi('Avg Gap',stats.avgGap+'%',T.red)}{kpi('Avg Coverage',stats.avgCoverage+'%',T.green)}{kpi('Total Workers',stats.totalWorkers)}{kpi('On Track',stats.onTrack,T.green)}{kpi('LW Cost',stats.totalCost)}{kpi('Verified',stats.verified)}</div>
    <div style={{display:'flex',gap:12,marginBottom:16,alignItems:'center',flexWrap:'wrap'}}><input value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}} placeholder="Search companies..." style={inpS}/><select value={sectorF} onChange={e=>{setSectorF(e.target.value);setPage(1);}} style={selS}>{SECTORS.map(s=><option key={s}>{s}</option>)}</select><button onClick={()=>exportCSV(filtered,'living_wage.csv')} style={btnS(false)}>Export CSV</button></div>
    <div style={{overflowX:'auto',...cS,padding:0}}><table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr>{[['name','Company'],['sector','Sector'],['livingWageGap','Gap%'],['lwCoverage','Cover%'],['workforceK','Workers K'],['lwIncreaseCostM','Cost $M'],['progress','Progress'],['commitYear','Target']].map(([k,l])=><th key={k} onClick={()=>doSort(k)} style={thS}>{l}{si(k,sortCol,sortDir)}</th>)}</tr></thead>
      <tbody>{paged.map(r=><tr key={r.id} onClick={()=>setSelected(r)} style={{cursor:'pointer',background:selected?.id===r.id?T.surfaceH:'transparent'}}><td style={tdS}><span style={{fontWeight:600}}>{r.name}</span></td><td style={tdS}>{r.sector}</td><td style={tdS}><span style={{color:r.livingWageGap>25?T.red:r.livingWageGap>10?T.amber:T.green,fontWeight:600}}>{r.livingWageGap}%</span></td><td style={tdS}>{r.lwCoverage}%</td><td style={tdS}>{r.workforceK}K</td><td style={tdS}>${r.lwIncreaseCostM}M</td><td style={tdS}><span style={{color:r.progress==='On Track'?T.green:r.progress==='Behind'?T.amber:T.red,fontWeight:600,fontSize:11}}>{r.progress}</span></td><td style={tdS}>{r.commitYear}</td></tr>)}</tbody></table></div>
    {totalPages>1&&<div style={{display:'flex',gap:6,marginTop:12,alignItems:'center',justifyContent:'center'}}><button onClick={()=>setPage(p=>Math.max(1,p-1))} disabled={page===1} style={pgB}>&laquo;</button><span style={{fontSize:11,color:T.textSec,fontFamily:T.mono}}>Page {page}/{totalPages}</span><button onClick={()=>setPage(p=>Math.min(totalPages,p+1))} disabled={page===totalPages} style={pgB}>&raquo;</button></div>}
    <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16,marginTop:20}}>
      <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Living Wage Gap by Sector</div><ResponsiveContainer width="100%" height={260}><BarChart data={sectorGap}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="sector" tick={{fontSize:8,fill:T.textSec}} angle={-20}/><YAxis tick={{fontSize:9,fill:T.textSec}} domain={[0,50]}/><Tooltip {...tip}/><Bar dataKey="gap" fill={T.red} name="Gap %" radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></div>
      <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Gap vs Cost to Close</div><ResponsiveContainer width="100%" height={260}><ScatterChart><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="x" name="Gap %" tick={{fontSize:9,fill:T.textSec}}/><YAxis dataKey="y" name="Cost $M" tick={{fontSize:9,fill:T.textSec}}/><Tooltip {...tip}/><Scatter data={filtered.map(c=>({name:c.name,x:c.livingWageGap,y:c.lwIncreaseCostM}))} fill={ACCENT} fillOpacity={0.5}/></ScatterChart></ResponsiveContainer></div>
    </div>
  </div>);
  const renderGap=()=>(<div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16}}>
    <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Largest Gaps (Top 15)</div><ResponsiveContainer width="100%" height={350}><BarChart data={[...COS].sort((a,b)=>b.livingWageGap-a.livingWageGap).slice(0,15)} layout="vertical"><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis type="number" tick={{fontSize:9,fill:T.textSec}}/><YAxis type="category" dataKey="name" tick={{fontSize:8,fill:T.textSec}} width={80}/><Tooltip {...tip}/><Bar dataKey="livingWageGap" fill={T.red} radius={[0,4,4,0]}/></BarChart></ResponsiveContainer></div>
    <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Gender Pay Gap Distribution</div><ResponsiveContainer width="100%" height={350}><BarChart data={[...filtered].sort((a,b)=>b.genderPayGap-a.genderPayGap).slice(0,15)} layout="vertical"><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis type="number" tick={{fontSize:9,fill:T.textSec}}/><YAxis type="category" dataKey="name" tick={{fontSize:8,fill:T.textSec}} width={80}/><Tooltip {...tip}/><Bar dataKey="genderPayGap" fill={T.amber} radius={[0,4,4,0]}/></BarChart></ResponsiveContainer></div>
  </div></div>);
  const renderRegional=()=>(<div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16}}>
    <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Coverage by Sector</div><ResponsiveContainer width="100%" height={280}><BarChart data={sectorGap}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="sector" tick={{fontSize:8,fill:T.textSec}} angle={-20}/><YAxis tick={{fontSize:9,fill:T.textSec}} domain={[0,100]}/><Tooltip {...tip}/><Bar dataKey="coverage" fill={T.green} radius={[4,4,0,0]} name="Coverage %"/></BarChart></ResponsiveContainer></div>
    <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Progress Distribution</div><ResponsiveContainer width="100%" height={280}><PieChart><Pie data={[{n:'On Track',v:COS.filter(c=>c.progress==='On Track').length},{n:'Behind',v:COS.filter(c=>c.progress==='Behind').length},{n:'At Risk',v:COS.filter(c=>c.progress==='At Risk').length}]} cx="50%" cy="50%" outerRadius={90} dataKey="v" label={({n,v})=>`${n}: ${v}`}>{[T.green,T.amber,T.red].map((c,i)=><Cell key={i} fill={c}/>)}</Pie><Tooltip {...tip}/></PieChart></ResponsiveContainer></div>
  </div></div>);
  const renderProgress=()=>(<div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16}}>
    <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Commitment Timeline</div><ResponsiveContainer width="100%" height={280}><BarChart data={[{y:'2025',c:COS.filter(c=>c.commitYear===2025).length},{y:'2027',c:COS.filter(c=>c.commitYear===2027).length},{y:'2030',c:COS.filter(c=>c.commitYear===2030).length}]}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="y" tick={{fontSize:9,fill:T.textSec}}/><YAxis tick={{fontSize:9,fill:T.textSec}}/><Tooltip {...tip}/><Bar dataKey="c" fill={ACCENT} radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></div>
    <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Transparency Score vs Gap</div><ResponsiveContainer width="100%" height={280}><ScatterChart><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="x" name="Transparency" tick={{fontSize:9,fill:T.textSec}}/><YAxis dataKey="y" name="Gap %" tick={{fontSize:9,fill:T.textSec}}/><Tooltip {...tip}/><Scatter data={filtered.map(c=>({name:c.name,x:c.transparencyScore,y:c.livingWageGap}))} fill={T.navy} fillOpacity={0.5}/></ScatterChart></ResponsiveContainer></div>
  </div></div>);
  return(<div style={{padding:'24px 32px',fontFamily:T.font,background:T.bg,minHeight:'100vh'}}>
    <div style={{marginBottom:20}}><h1 style={{fontSize:22,fontWeight:700,color:T.navy,margin:0}}>Living Wage Tracker</h1><p style={{fontSize:12,color:T.textSec,margin:'4px 0 0'}}>50 companies | Living wage gap, regional benchmarks, progress tracking</p></div>
    <div style={{display:'flex',gap:8,marginBottom:20}}>{TABS.map((t,i)=><button key={t} onClick={()=>setTab(i)} style={btnS(tab===i)}>{t}</button>)}</div>
    {tab===0&&renderDash()}{tab===1&&renderGap()}{tab===2&&renderRegional()}{tab===3&&renderProgress()}
    <Panel item={selected} onClose={()=>setSelected(null)}/>
  </div>);
}