import React,{useState,useMemo,useCallback} from 'react';
import {BarChart,Bar,LineChart,Line,AreaChart,Area,PieChart,Pie,Cell,ScatterChart,Scatter,XAxis,YAxis,CartesianGrid,Tooltip,ResponsiveContainer,Legend,RadarChart,Radar,PolarGrid,PolarAngleAxis,PolarRadiusAxis} from 'recharts';

const T={bg:'#f6f4f0',surface:'#ffffff',surfaceH:'#f0ede7',border:'#e5e0d8',borderL:'#d5cfc5',navy:'#1b3a5c',navyL:'#2c5a8c',gold:'#c5a96a',goldL:'#d4be8a',sage:'#5a8a6a',sageL:'#7ba67d',teal:'#5a8a6a',text:'#1b3a5c',textSec:'#5c6b7e',textMut:'#9aa3ae',red:'#dc2626',green:'#16a34a',amber:'#d97706',font:"'DM Sans','SF Pro Display',system-ui,-apple-system,sans-serif",mono:"'JetBrains Mono','SF Mono','Fira Code',monospace"};
const sr=(s)=>{let x=Math.sin(s+1)*10000;return x-Math.floor(x);};
const ACCENT='#b45309';const tip={contentStyle:{background:T.surface,border:`1px solid ${T.border}`,borderRadius:8,fontSize:11,fontFamily:T.font},labelStyle:{color:T.textSec,fontFamily:T.mono,fontSize:10}};
const COLORS=[T.navy,T.gold,T.sage,T.red,T.amber,T.green,T.navyL,T.goldL,T.sageL,'#8b5cf6','#ec4899','#06b6d4'];
const fmt=v=>typeof v==='number'?v>=1e9?(v/1e9).toFixed(1)+'B':v>=1e6?(v/1e6).toFixed(1)+'M':v>=1e3?(v/1e3).toFixed(1)+'K':v.toFixed(1):v;
const TABS=['Compensation Overview','Pay Ratio Analysis','ESG-Linked Comp','Peer Benchmarking'];
const SECTORS=['All','Technology','Financials','Healthcare','Energy','Consumer','Industrials','Materials'];const PAGE=12;

const COS=Array.from({length:80},(_,i)=>{
  const names=['Apple','Microsoft','Alphabet','Amazon','NVIDIA','Meta','Tesla','JPMorgan','Visa','UnitedHealth','J&J','Walmart','P&G','Mastercard','BofA','Chevron','Home Depot','Coca-Cola','Pfizer','Abbott','Eli Lilly','PepsiCo','Costco','Broadcom','Thermo Fisher','Cisco','Merck','Accenture','McDonalds','Adobe','Linde','Salesforce','AMD','Qualcomm','Intel','Goldman Sachs','Caterpillar','Amgen','Morgan Stanley','Honeywell','Lockheed','Deere','IBM','GE','RTX','Medtronic','AstraZeneca','Shell','BP','TotalEnergies','Nestle','Roche','Novartis','SAP','Siemens','LVMH','Unilever','HSBC','BHP','Rio Tinto','Sony','Toyota','Samsung','Infosys','Reliance','TSMC','Novo Nordisk','Diageo','AbbVie','Starbucks','Netflix','Booking','Intuit','Uber','Airbnb','PayPal','ServiceNow','CrowdStrike','Snowflake','Datadog'];
  const secs=['Technology','Technology','Technology','Technology','Technology','Technology','Technology','Financials','Financials','Healthcare','Healthcare','Consumer','Consumer','Financials','Financials','Energy','Consumer','Consumer','Healthcare','Healthcare','Healthcare','Consumer','Consumer','Technology','Healthcare','Technology','Healthcare','Technology','Consumer','Technology','Materials','Technology','Technology','Technology','Technology','Financials','Industrials','Healthcare','Financials','Industrials','Industrials','Industrials','Technology','Industrials','Industrials','Healthcare','Healthcare','Energy','Energy','Energy','Consumer','Healthcare','Healthcare','Technology','Industrials','Consumer','Consumer','Financials','Materials','Materials','Technology','Industrials','Technology','Technology','Energy','Technology','Healthcare','Consumer','Healthcare','Consumer','Technology','Consumer','Technology','Technology','Technology','Financials','Technology','Technology','Technology','Technology'];
  const ceoPay=+(sr(i*7)*25+5).toFixed(1);const medianPay=Math.round(sr(i*11)*80+40);const payRatio=Math.round(ceoPay*1000/medianPay);const esgLinkedPct=Math.round(sr(i*13)*40);
  const yearly=Array.from({length:5},(_,y)=>({year:2020+y,ceoPay:+(ceoPay-2+y*0.8+sr(i*100+y)*2).toFixed(1),ratio:Math.round(payRatio-50+y*15+sr(i*100+y*3)*30),esgPct:Math.round(esgLinkedPct-5+y*3+sr(i*100+y*7)*5)}));
  return{id:i+1,name:names[i],sector:secs[i],ceoPayM:ceoPay,medianPayK:medianPay,payRatio,esgLinkedPct,stiM:+(ceoPay*0.3+sr(i*17)*3).toFixed(1),ltiM:+(ceoPay*0.5+sr(i*19)*5).toFixed(1),baseSalaryM:+(ceoPay*0.15).toFixed(1),equityPct:Math.round(sr(i*23)*40+30),cashPct:Math.round(sr(i*29)*30+10),clawback:sr(i*31)>0.3?'Yes':'No',holdingReq:sr(i*37)>0.4?'Yes':'No',severanceMultiple:+(sr(i*41)*3+1).toFixed(1),pensionM:+(sr(i*43)*5).toFixed(1),sayOnPayPct:Math.round(sr(i*47)*30+65),tsr1y:+((sr(i*51)-0.3)*40).toFixed(1),tsr3y:+((sr(i*53)-0.25)*60).toFixed(1),yearly};
});

export default function ExecutivePayAnalyticsPage(){
  const[tab,setTab]=useState(0);const[search,setSearch]=useState('');const[sectorF,setSectorF]=useState('All');const[sortCol,setSortCol]=useState('ceoPayM');const[sortDir,setSortDir]=useState('desc');const[page,setPage]=useState(1);const[selected,setSelected]=useState(null);

  const filtered=useMemo(()=>{let d=[...COS];if(search)d=d.filter(r=>r.name.toLowerCase().includes(search.toLowerCase()));if(sectorF!=='All')d=d.filter(r=>r.sector===sectorF);d.sort((a,b)=>sortDir==='asc'?(a[sortCol]>b[sortCol]?1:-1):(a[sortCol]<b[sortCol]?1:-1));return d;},[search,sectorF,sortCol,sortDir]);
  const paged=useMemo(()=>filtered.slice((page-1)*PAGE,page*PAGE),[filtered,page]);const totalPages=Math.ceil(filtered.length/PAGE);
  const doSort=col=>{if(sortCol===col)setSortDir(d=>d==='asc'?'desc':'asc');else{setSortCol(col);setSortDir('desc');}setPage(1);};

  const stats=useMemo(()=>({count:filtered.length,avgCeo:'$'+(filtered.reduce((s,r)=>s+r.ceoPayM,0)/filtered.length||0).toFixed(1)+'M',avgRatio:Math.round(filtered.reduce((s,r)=>s+r.payRatio,0)/filtered.length||0),avgESG:Math.round(filtered.reduce((s,r)=>s+r.esgLinkedPct,0)/filtered.length||0)+'%',avgSoP:Math.round(filtered.reduce((s,r)=>s+r.sayOnPayPct,0)/filtered.length||0)+'%',clawback:filtered.filter(r=>r.clawback==='Yes').length,maxPay:filtered.length?'$'+Math.max(...filtered.map(r=>r.ceoPayM)).toFixed(1)+'M':'$0M'}),[filtered]);

  const sectorPay=useMemo(()=>{const m={};COS.forEach(c=>{if(!m[c.sector])m[c.sector]={s:c.sector,pay:0,ratio:0,esg:0,n:0};m[c.sector].pay+=c.ceoPayM;m[c.sector].ratio+=c.payRatio;m[c.sector].esg+=c.esgLinkedPct;m[c.sector].n++;});return Object.values(m).map(s=>({sector:s.s,avgPay:+(s.pay/s.n).toFixed(1),avgRatio:Math.round(s.ratio/s.n),avgESG:Math.round(s.esg/s.n)}));},[]);

  const exportCSV=useCallback((data,fn)=>{if(!data.length)return;const keys=Object.keys(data[0]).filter(k=>k!=='yearly');const csv=[keys.join(','),...data.map(r=>keys.map(k=>`"${r[k]}"`).join(','))].join('\n');const b=new Blob([csv],{type:'text/csv'});const u=URL.createObjectURL(b);const a=document.createElement('a');a.href=u;a.download=fn;a.click();URL.revokeObjectURL(u);},[]);

  const si=(col,cur,dir)=>cur===col?(dir==='asc'?' \u25B2':' \u25BC'):' \u25CB';
  const thS={padding:'8px 10px',fontSize:11,fontFamily:T.mono,color:T.textSec,cursor:'pointer',borderBottom:`1px solid ${T.border}`,whiteSpace:'nowrap',userSelect:'none',textAlign:'left',background:T.surfaceH};
  const tdS={padding:'7px 10px',fontSize:12,fontFamily:T.font,borderBottom:`1px solid ${T.border}`,color:T.text};
  const inpS={padding:'6px 12px',border:`1px solid ${T.border}`,borderRadius:6,fontSize:12,fontFamily:T.font,background:T.surface,color:T.text,outline:'none',width:220};
  const selS={padding:'6px 10px',border:`1px solid ${T.border}`,borderRadius:6,fontSize:11,fontFamily:T.font,background:T.surface,color:T.text};
  const btnS=a=>({padding:'6px 16px',border:`1px solid ${a?ACCENT:T.border}`,borderRadius:6,fontSize:12,fontFamily:T.font,background:a?ACCENT:T.surface,color:a?'#fff':T.text,cursor:'pointer',fontWeight:a?600:400});
  const pgB={padding:'4px 10px',border:`1px solid ${T.border}`,borderRadius:4,fontSize:11,cursor:'pointer',background:T.surface,color:T.text};
  const cS={background:T.surface,border:`1px solid ${T.border}`,borderRadius:10,padding:16};
  const kpi=(l,v,c)=>(<div style={{background:T.surface,border:`1px solid ${T.border}`,borderRadius:10,padding:'14px 18px',flex:1,minWidth:140}}><div style={{fontSize:10,color:T.textMut,fontFamily:T.mono,textTransform:'uppercase',letterSpacing:1}}>{l}</div><div style={{fontSize:22,fontWeight:700,color:c||T.navy,marginTop:4}}>{v}</div></div>);

  const Panel=({item,onClose})=>{if(!item)return null;return(<div style={{position:'fixed',top:0,right:0,width:460,height:'100vh',background:T.surface,borderLeft:`2px solid ${ACCENT}`,zIndex:1000,overflowY:'auto',boxShadow:'-4px 0 24px rgba(0,0,0,0.10)'}}><div style={{padding:'20px 24px',borderBottom:`1px solid ${T.border}`,display:'flex',justifyContent:'space-between',alignItems:'center'}}><div><div style={{fontSize:16,fontWeight:700,color:T.navy}}>{item.name}</div><div style={{fontSize:12,color:T.textSec}}>{item.sector}</div></div><button onClick={onClose} style={{background:'none',border:'none',fontSize:20,cursor:'pointer',color:T.textMut}}>{'\u2715'}</button></div>
    <div style={{padding:'16px 24px'}}>
      <div style={{display:'grid',gridTemplateColumns:'1fr 1fr 1fr',gap:8,marginBottom:16}}>{[['CEO Pay','$'+item.ceoPayM+'M'],['Median Pay','$'+item.medianPayK+'K'],['Pay Ratio',item.payRatio+':1'],['ESG-Linked',item.esgLinkedPct+'%'],['Base','$'+item.baseSalaryM+'M'],['STI','$'+item.stiM+'M'],['LTI','$'+item.ltiM+'M'],['Equity',item.equityPct+'%'],['Cash',item.cashPct+'%'],['Clawback',item.clawback],['Holding Req',item.holdingReq],['Severance',item.severanceMultiple+'x'],['Pension','$'+item.pensionM+'M'],['Say on Pay',item.sayOnPayPct+'%'],['TSR 1Y',item.tsr1y+'%'],['TSR 3Y',item.tsr3y+'%']].map(([k,v],j)=>(<div key={j} style={{background:T.surfaceH,borderRadius:6,padding:'8px 10px'}}><div style={{fontSize:9,color:T.textMut,fontFamily:T.mono}}>{k}</div><div style={{fontSize:13,fontWeight:600,color:T.navy,marginTop:2}}>{v}</div></div>))}</div>
      <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Compensation Structure</div><ResponsiveContainer width="100%" height={180}><PieChart><Pie data={[{n:'Base',v:+item.baseSalaryM},{n:'STI',v:+item.stiM},{n:'LTI',v:+item.ltiM},{n:'Pension',v:+item.pensionM}]} cx="50%" cy="50%" outerRadius={65} dataKey="v" label={({n,v})=>`${n}: $${v}M`}>{[T.navy,ACCENT,T.gold,T.sage].map((c,i)=><Cell key={i} fill={c}/>)}</Pie><Tooltip {...tip}/></PieChart></ResponsiveContainer></div>
      <div style={{...cS,marginTop:12}}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>5-Year Pay & Ratio Trend</div><ResponsiveContainer width="100%" height={180}><LineChart data={item.yearly}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="year" tick={{fontSize:9,fill:T.textSec}}/><YAxis yAxisId="l" tick={{fontSize:9,fill:T.textSec}}/><YAxis yAxisId="r" orientation="right" tick={{fontSize:9,fill:T.textSec}}/><Tooltip {...tip}/><Line yAxisId="l" type="monotone" dataKey="ceoPay" stroke={ACCENT} name="CEO Pay $M" strokeWidth={2}/><Line yAxisId="r" type="monotone" dataKey="ratio" stroke={T.red} name="Pay Ratio" strokeWidth={2}/><Legend/></LineChart></ResponsiveContainer></div>
    </div></div>);};

  const renderOverview=()=>(<div>
    <div style={{display:'flex',gap:12,marginBottom:20,flexWrap:'wrap'}}>{kpi('Companies',stats.count)}{kpi('Avg CEO Pay',stats.avgCeo)}{kpi('Avg Pay Ratio',stats.avgRatio+':1')}{kpi('Avg ESG-Linked',stats.avgESG)}{kpi('Avg Say on Pay',stats.avgSoP)}{kpi('Clawback',stats.clawback+'/'+stats.count)}{kpi('Max Pay',stats.maxPay)}</div>
    <div style={{display:'flex',gap:12,marginBottom:16,alignItems:'center',flexWrap:'wrap'}}><input value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}} placeholder="Search companies..." style={inpS}/><select value={sectorF} onChange={e=>{setSectorF(e.target.value);setPage(1);}} style={selS}>{SECTORS.map(s=><option key={s}>{s}</option>)}</select><button onClick={()=>exportCSV(filtered,'exec_pay.csv')} style={btnS(false)}>Export CSV</button></div>
    <div style={{overflowX:'auto',...cS,padding:0}}><table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr>{[['name','Company'],['sector','Sector'],['ceoPayM','CEO $M'],['payRatio','Ratio'],['esgLinkedPct','ESG%'],['equityPct','Equity%'],['sayOnPayPct','SoP%'],['tsr1y','TSR 1Y']].map(([k,l])=><th key={k} onClick={()=>doSort(k)} style={thS}>{l}{si(k,sortCol,sortDir)}</th>)}</tr></thead>
      <tbody>{paged.map(r=><tr key={r.id} onClick={()=>setSelected(r)} style={{cursor:'pointer',background:selected?.id===r.id?T.surfaceH:'transparent'}}><td style={tdS}><span style={{fontWeight:600}}>{r.name}</span></td><td style={tdS}>{r.sector}</td><td style={tdS}>${r.ceoPayM}M</td><td style={tdS}>{r.payRatio}:1</td><td style={tdS}>{r.esgLinkedPct}%</td><td style={tdS}>{r.equityPct}%</td><td style={tdS}>{r.sayOnPayPct}%</td><td style={tdS}><span style={{color:r.tsr1y>0?T.green:T.red,fontWeight:600}}>{r.tsr1y>0?'+':''}{r.tsr1y}%</span></td></tr>)}</tbody></table></div>
    {totalPages>1&&<div style={{display:'flex',gap:6,marginTop:12,alignItems:'center',justifyContent:'center'}}><button onClick={()=>setPage(p=>Math.max(1,p-1))} disabled={page===1} style={pgB}>&laquo;</button><span style={{fontSize:11,color:T.textSec,fontFamily:T.mono}}>Page {page}/{totalPages}</span><button onClick={()=>setPage(p=>Math.min(totalPages,p+1))} disabled={page===totalPages} style={pgB}>&raquo;</button></div>}
    <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16,marginTop:20}}>
      <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Avg CEO Pay by Sector</div><ResponsiveContainer width="100%" height={260}><BarChart data={sectorPay}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="sector" tick={{fontSize:8,fill:T.textSec}} angle={-25}/><YAxis tick={{fontSize:9,fill:T.textSec}}/><Tooltip {...tip}/><Bar dataKey="avgPay" fill={ACCENT} radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></div>
      <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>CEO Pay vs TSR</div><ResponsiveContainer width="100%" height={260}><ScatterChart><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="x" name="CEO Pay $M" tick={{fontSize:9,fill:T.textSec}}/><YAxis dataKey="y" name="TSR 1Y %" tick={{fontSize:9,fill:T.textSec}}/><Tooltip {...tip}/><Scatter data={filtered.map(c=>({name:c.name,x:c.ceoPayM,y:c.tsr1y}))} fill={ACCENT} fillOpacity={0.5}/></ScatterChart></ResponsiveContainer></div>
    </div>
  </div>);

  const renderRatio=()=>(<div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16}}>
    <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Pay Ratio by Sector</div><ResponsiveContainer width="100%" height={280}><BarChart data={sectorPay}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="sector" tick={{fontSize:8,fill:T.textSec}} angle={-25}/><YAxis tick={{fontSize:9,fill:T.textSec}}/><Tooltip {...tip}/><Bar dataKey="avgRatio" fill={T.red} radius={[4,4,0,0]} name="Avg Ratio"/></BarChart></ResponsiveContainer></div>
    <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Top 15 Highest Pay Ratios</div><ResponsiveContainer width="100%" height={280}><BarChart data={[...filtered].sort((a,b)=>b.payRatio-a.payRatio).slice(0,15)} layout="vertical"><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis type="number" tick={{fontSize:9,fill:T.textSec}}/><YAxis type="category" dataKey="name" tick={{fontSize:8,fill:T.textSec}} width={80}/><Tooltip {...tip}/><Bar dataKey="payRatio" fill={T.red} radius={[0,4,4,0]}/></BarChart></ResponsiveContainer></div>
    <div style={{...cS,gridColumn:'1/3'}}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Pay Ratio vs Say on Pay Vote</div><ResponsiveContainer width="100%" height={280}><ScatterChart><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="x" name="Pay Ratio" tick={{fontSize:9,fill:T.textSec}}/><YAxis dataKey="y" name="SoP Vote %" tick={{fontSize:9,fill:T.textSec}}/><Tooltip {...tip}/><Scatter data={filtered.map(c=>({name:c.name,x:c.payRatio,y:c.sayOnPayPct}))} fill={T.navy} fillOpacity={0.5}/></ScatterChart></ResponsiveContainer></div>
  </div></div>);

  const renderESG=()=>(<div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16}}>
    <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>ESG-Linked Comp by Sector</div><ResponsiveContainer width="100%" height={280}><BarChart data={sectorPay}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="sector" tick={{fontSize:8,fill:T.textSec}} angle={-25}/><YAxis tick={{fontSize:9,fill:T.textSec}} domain={[0,50]}/><Tooltip {...tip}/><Bar dataKey="avgESG" fill={T.sage} radius={[4,4,0,0]} name="ESG-Linked %"/></BarChart></ResponsiveContainer></div>
    <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>ESG Comp vs Performance</div><ResponsiveContainer width="100%" height={280}><ScatterChart><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="x" name="ESG %" tick={{fontSize:9,fill:T.textSec}}/><YAxis dataKey="y" name="TSR 1Y" tick={{fontSize:9,fill:T.textSec}}/><Tooltip {...tip}/><Scatter data={filtered.map(c=>({name:c.name,x:c.esgLinkedPct,y:c.tsr1y}))} fill={T.sage} fillOpacity={0.5}/></ScatterChart></ResponsiveContainer></div>
    <div style={{...cS,gridColumn:'1/3'}}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>ESG-Linked % Distribution</div><ResponsiveContainer width="100%" height={260}><BarChart data={[{r:'0%',c:filtered.filter(r=>r.esgLinkedPct===0).length},{r:'1-10%',c:filtered.filter(r=>r.esgLinkedPct>0&&r.esgLinkedPct<=10).length},{r:'11-20%',c:filtered.filter(r=>r.esgLinkedPct>10&&r.esgLinkedPct<=20).length},{r:'21-30%',c:filtered.filter(r=>r.esgLinkedPct>20&&r.esgLinkedPct<=30).length},{r:'>30%',c:filtered.filter(r=>r.esgLinkedPct>30).length}]}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="r" tick={{fontSize:9,fill:T.textSec}}/><YAxis tick={{fontSize:9,fill:T.textSec}}/><Tooltip {...tip}/><Bar dataKey="c" fill={ACCENT} radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></div>
  </div></div>);

  const renderPeer=()=>(<div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16}}>
    <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Comp Structure Distribution</div><ResponsiveContainer width="100%" height={280}><PieChart><Pie data={[{n:'Base',v:Math.round(COS.reduce((s,c)=>s+c.baseSalaryM,0))},{n:'STI',v:Math.round(COS.reduce((s,c)=>s+c.stiM,0))},{n:'LTI',v:Math.round(COS.reduce((s,c)=>s+c.ltiM,0))},{n:'Pension',v:Math.round(COS.reduce((s,c)=>s+c.pensionM,0))}]} cx="50%" cy="50%" outerRadius={90} dataKey="v" label={({n,v})=>`${n}: $${v}M`}>{[T.navy,ACCENT,T.gold,T.sage].map((c,i)=><Cell key={i} fill={c}/>)}</Pie><Tooltip {...tip}/></PieChart></ResponsiveContainer></div>
    <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Top 15 by Total CEO Pay</div><ResponsiveContainer width="100%" height={280}><BarChart data={[...filtered].sort((a,b)=>b.ceoPayM-a.ceoPayM).slice(0,15)} layout="vertical"><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis type="number" tick={{fontSize:9,fill:T.textSec}}/><YAxis type="category" dataKey="name" tick={{fontSize:8,fill:T.textSec}} width={80}/><Tooltip {...tip}/><Bar dataKey="ceoPayM" fill={ACCENT} radius={[0,4,4,0]}/></BarChart></ResponsiveContainer></div>
  </div></div>);

  return(<div style={{padding:'24px 32px',fontFamily:T.font,background:T.bg,minHeight:'100vh'}}>
    <div style={{marginBottom:20}}><h1 style={{fontSize:22,fontWeight:700,color:T.navy,margin:0}}>Executive Pay Analytics</h1><p style={{fontSize:12,color:T.textSec,margin:'4px 0 0'}}>80 companies | CEO pay ratio, ESG-linked compensation, peer benchmarking</p></div>
    <div style={{display:'flex',gap:8,marginBottom:20}}>{TABS.map((t,i)=><button key={t} onClick={()=>setTab(i)} style={btnS(tab===i)}>{t}</button>)}</div>
    {tab===0&&renderOverview()}{tab===1&&renderRatio()}{tab===2&&renderESG()}{tab===3&&renderPeer()}
    <Panel item={selected} onClose={()=>setSelected(null)}/>
  </div>);
}