import React,{useState,useMemo,useCallback} from 'react';
import {BarChart,Bar,LineChart,Line,AreaChart,Area,PieChart,Pie,Cell,ScatterChart,Scatter,XAxis,YAxis,CartesianGrid,Tooltip,ResponsiveContainer,Legend,RadarChart,Radar,PolarGrid,PolarAngleAxis,PolarRadiusAxis} from 'recharts';

const T={bg:'#f6f4f0',surface:'#ffffff',surfaceH:'#f0ede7',border:'#e5e0d8',borderL:'#d5cfc5',navy:'#1b3a5c',navyL:'#2c5a8c',gold:'#c5a96a',goldL:'#d4be8a',sage:'#5a8a6a',sageL:'#7ba67d',teal:'#5a8a6a',text:'#1b3a5c',textSec:'#5c6b7e',textMut:'#9aa3ae',red:'#dc2626',green:'#16a34a',amber:'#d97706',font:"'DM Sans','SF Pro Display',system-ui,-apple-system,sans-serif",mono:"'JetBrains Mono','SF Mono','Fira Code',monospace"};
const sr=(s)=>{let x=Math.sin(s+1)*10000;return x-Math.floor(x);};
const ACCENT='#6d28d9';const tip={contentStyle:{background:T.surface,border:`1px solid ${T.border}`,borderRadius:8,fontSize:11,fontFamily:T.font},labelStyle:{color:T.textSec,fontFamily:T.mono,fontSize:10}};
const COLORS=[T.navy,T.gold,T.sage,T.red,T.amber,T.green,T.navyL,T.goldL,T.sageL,'#8b5cf6','#ec4899','#06b6d4'];
const fmt=v=>typeof v==='number'?v>=1e9?(v/1e9).toFixed(1)+'B':v>=1e6?(v/1e6).toFixed(1)+'M':v>=1e3?(v/1e3).toFixed(1)+'K':v.toFixed(1):v;
const TABS=['Factor Dashboard','Alpha Analysis','Risk Decomposition','Backtesting'];
const CATS=['All','Environmental','Social','Governance'];const PAGE=12;

const FACTORS=Array.from({length:50},(_,i)=>{
  const names=['ESG Momentum','Carbon Risk','Green Revenue','Board Quality','Water Stress','Supply Chain ESG','Climate VaR','Transition Risk','Social Capital','Governance Score','Biodiversity','Deforestation','Labor Practice','Data Privacy','Cyber Risk','Exec Compensation','Tax Transparency','Lobbying Exposure','Stranded Assets','Physical Risk','Innovation ESG','Circular Economy','Just Transition','Net Zero Align','SFDR Compliance','EU Taxonomy','TCFD Readiness','SBTi Commitment','Gender Diversity','Pay Equity','Human Rights','Community Impact','Product Safety','Air Quality','Waste Mgmt','Water Efficiency','Land Use','GHG Scope 3','Renewable Energy','EV Exposure','Clean Tech','ESG Controversy','Rating Divergence','Stakeholder Score','Materiality','Double Materiality','Impact Intensity','SDG Alignment','Climate Lobby','Green Bond'];
  const cats=['Environmental','Environmental','Environmental','Governance','Environmental','Social','Environmental','Environmental','Social','Governance','Environmental','Environmental','Social','Social','Governance','Governance','Governance','Governance','Environmental','Environmental','Environmental','Environmental','Social','Environmental','Governance','Environmental','Environmental','Environmental','Social','Social','Social','Social','Social','Environmental','Environmental','Environmental','Environmental','Environmental','Environmental','Environmental','Environmental','Governance','Governance','Social','Environmental','Environmental','Social','Social','Governance','Environmental'];
  const ret1y=+((sr(i*7)-0.4)*15).toFixed(2);const vol=+(sr(i*13)*12+3).toFixed(2);const sharpe=+(ret1y/(vol||1)).toFixed(2);const ir=+((sr(i*17)-0.3)*2).toFixed(2);
  const monthly=Array.from({length:12},(_,m)=>({month:['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'][m],ret:+((sr(i*100+m*7)-0.45)*4).toFixed(2),cum:+((m+1)*ret1y/12+sr(i*100+m*11)*2).toFixed(2)}));
  return{id:i+1,name:names[i],category:cats[i],return1Y:ret1y,return3Y:+((sr(i*11)-0.35)*25).toFixed(2),volatility:vol,sharpe,infoRatio:ir,tStat:+(ir*Math.sqrt(12)).toFixed(2),maxDrawdown:+(-sr(i*19)*20-2).toFixed(1),alpha:+(ret1y*0.6+sr(i*23)*2-1).toFixed(2),beta:+(sr(i*29)*0.8+0.2).toFixed(2),correlation:+(sr(i*31)*0.6-0.1).toFixed(2),turnover:Math.round(sr(i*37)*60+10),holdings:Math.round(sr(i*41)*200+30),exposure:Math.round(sr(i*43)*40+5),tracking:+(sr(i*47)*5+1).toFixed(2),monthly};
});

export default function EsgFactorAttributionPage(){
  const[tab,setTab]=useState(0);const[search,setSearch]=useState('');const[catF,setCatF]=useState('All');const[sortCol,setSortCol]=useState('return1Y');const[sortDir,setSortDir]=useState('desc');const[page,setPage]=useState(1);const[selected,setSelected]=useState(null);

  const filtered=useMemo(()=>{let d=[...FACTORS];if(search)d=d.filter(r=>r.name.toLowerCase().includes(search.toLowerCase()));if(catF!=='All')d=d.filter(r=>r.category===catF);d.sort((a,b)=>sortDir==='asc'?(a[sortCol]>b[sortCol]?1:-1):(a[sortCol]<b[sortCol]?1:-1));return d;},[search,catF,sortCol,sortDir]);
  const paged=useMemo(()=>filtered.slice((page-1)*PAGE,page*PAGE),[filtered,page]);const totalPages=Math.ceil(filtered.length/PAGE);
  const doSort=col=>{if(sortCol===col)setSortDir(d=>d==='asc'?'desc':'asc');else{setSortCol(col);setSortDir('desc');}setPage(1);};

  const stats=useMemo(()=>({count:filtered.length,avgRet:(filtered.reduce((s,r)=>s+r.return1Y,0)/filtered.length||0).toFixed(2),avgSharpe:(filtered.reduce((s,r)=>s+r.sharpe,0)/filtered.length||0).toFixed(2),posAlpha:filtered.filter(r=>r.alpha>0).length,avgIR:(filtered.reduce((s,r)=>s+r.infoRatio,0)/filtered.length||0).toFixed(2),avgVol:(filtered.reduce((s,r)=>s+r.volatility,0)/filtered.length||0).toFixed(1),topFactor:filtered.length?[...filtered].sort((a,b)=>b.return1Y-a.return1Y)[0].name:'-'}),[filtered]);

  const catPerf=useMemo(()=>{const m={};FACTORS.forEach(f=>{if(!m[f.category])m[f.category]={cat:f.category,ret:0,vol:0,sharpe:0,n:0};m[f.category].ret+=f.return1Y;m[f.category].vol+=f.volatility;m[f.category].sharpe+=f.sharpe;m[f.category].n++;});return Object.values(m).map(c=>({category:c.cat,return1Y:+(c.ret/c.n).toFixed(2),volatility:+(c.vol/c.n).toFixed(2),sharpe:+(c.sharpe/c.n).toFixed(2)}));},[]);

  const exportCSV=useCallback((data,fn)=>{if(!data.length)return;const keys=Object.keys(data[0]).filter(k=>k!=='monthly');const csv=[keys.join(','),...data.map(r=>keys.map(k=>`"${r[k]}"`).join(','))].join('\n');const b=new Blob([csv],{type:'text/csv'});const u=URL.createObjectURL(b);const a=document.createElement('a');a.href=u;a.download=fn;a.click();URL.revokeObjectURL(u);},[]);

  const si=(col,cur,dir)=>cur===col?(dir==='asc'?' \u25B2':' \u25BC'):' \u25CB';
  const thS={padding:'8px 10px',fontSize:11,fontFamily:T.mono,color:T.textSec,cursor:'pointer',borderBottom:`1px solid ${T.border}`,whiteSpace:'nowrap',userSelect:'none',textAlign:'left',background:T.surfaceH};
  const tdS={padding:'7px 10px',fontSize:12,fontFamily:T.font,borderBottom:`1px solid ${T.border}`,color:T.text};
  const inpS={padding:'6px 12px',border:`1px solid ${T.border}`,borderRadius:6,fontSize:12,fontFamily:T.font,background:T.surface,color:T.text,outline:'none',width:220};
  const selS={padding:'6px 10px',border:`1px solid ${T.border}`,borderRadius:6,fontSize:11,fontFamily:T.font,background:T.surface,color:T.text};
  const btnS=a=>({padding:'6px 16px',border:`1px solid ${a?ACCENT:T.border}`,borderRadius:6,fontSize:12,fontFamily:T.font,background:a?ACCENT:T.surface,color:a?'#fff':T.text,cursor:'pointer',fontWeight:a?600:400});
  const pgB={padding:'4px 10px',border:`1px solid ${T.border}`,borderRadius:4,fontSize:11,cursor:'pointer',background:T.surface,color:T.text};
  const cS={background:T.surface,border:`1px solid ${T.border}`,borderRadius:10,padding:16};
  const kpi=(l,v,c)=>(<div style={{background:T.surface,border:`1px solid ${T.border}`,borderRadius:10,padding:'14px 18px',flex:1,minWidth:140}}><div style={{fontSize:10,color:T.textMut,fontFamily:T.mono,textTransform:'uppercase',letterSpacing:1}}>{l}</div><div style={{fontSize:22,fontWeight:700,color:c||T.navy,marginTop:4}}>{v}</div></div>);
  const retBdg=v=>({color:v>0?T.green:v<0?T.red:T.textSec,fontWeight:600,fontFamily:T.mono,fontSize:11});

  const Panel=({item,onClose})=>{if(!item)return null;return(<div style={{position:'fixed',top:0,right:0,width:460,height:'100vh',background:T.surface,borderLeft:`2px solid ${ACCENT}`,zIndex:1000,overflowY:'auto',boxShadow:'-4px 0 24px rgba(0,0,0,0.10)'}}><div style={{padding:'20px 24px',borderBottom:`1px solid ${T.border}`,display:'flex',justifyContent:'space-between',alignItems:'center'}}><div><div style={{fontSize:16,fontWeight:700,color:T.navy}}>{item.name}</div><div style={{fontSize:12,color:T.textSec}}>{item.category} Factor</div></div><button onClick={onClose} style={{background:'none',border:'none',fontSize:20,cursor:'pointer',color:T.textMut}}>{'\u2715'}</button></div>
    <div style={{padding:'16px 24px'}}>
      <div style={{display:'grid',gridTemplateColumns:'1fr 1fr 1fr',gap:8,marginBottom:16}}>{[['1Y Return',item.return1Y+'%'],['3Y Return',item.return3Y+'%'],['Volatility',item.volatility+'%'],['Sharpe',item.sharpe],['Info Ratio',item.infoRatio],['t-Stat',item.tStat],['Max DD',item.maxDrawdown+'%'],['Alpha',item.alpha+'%'],['Beta',item.beta],['Correlation',item.correlation],['Turnover',item.turnover+'%'],['Holdings',item.holdings],['Exposure',item.exposure+'%'],['Tracking',item.tracking+'%']].map(([k,v],j)=>(<div key={j} style={{background:T.surfaceH,borderRadius:6,padding:'8px 10px'}}><div style={{fontSize:9,color:T.textMut,fontFamily:T.mono}}>{k}</div><div style={{fontSize:13,fontWeight:600,color:T.navy,marginTop:2}}>{v}</div></div>))}</div>
      <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Monthly Returns</div><ResponsiveContainer width="100%" height={200}><BarChart data={item.monthly}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="month" tick={{fontSize:9,fill:T.textSec}}/><YAxis tick={{fontSize:9,fill:T.textSec}}/><Tooltip {...tip}/><Bar dataKey="ret" fill={ACCENT}>{item.monthly.map((m,j)=><Cell key={j} fill={m.ret>=0?T.green:T.red}/>)}</Bar></BarChart></ResponsiveContainer></div>
      <div style={{...cS,marginTop:12}}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Cumulative Return</div><ResponsiveContainer width="100%" height={180}><AreaChart data={item.monthly}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="month" tick={{fontSize:9,fill:T.textSec}}/><YAxis tick={{fontSize:9,fill:T.textSec}}/><Tooltip {...tip}/><Area type="monotone" dataKey="cum" stroke={ACCENT} fill="rgba(109,40,217,0.15)"/></AreaChart></ResponsiveContainer></div>
    </div></div>);};

  const renderDash=()=>(<div>
    <div style={{display:'flex',gap:12,marginBottom:20,flexWrap:'wrap'}}>{kpi('Factors',stats.count)}{kpi('Avg Return',stats.avgRet+'%')}{kpi('Avg Sharpe',stats.avgSharpe)}{kpi('Pos Alpha',stats.posAlpha+'/'+stats.count,T.green)}{kpi('Avg IR',stats.avgIR)}{kpi('Avg Vol',stats.avgVol+'%')}{kpi('Top Factor',stats.topFactor)}</div>
    <div style={{display:'flex',gap:12,marginBottom:16,alignItems:'center',flexWrap:'wrap'}}><input value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}} placeholder="Search factors..." style={inpS}/><select value={catF} onChange={e=>{setCatF(e.target.value);setPage(1);}} style={selS}>{CATS.map(s=><option key={s}>{s}</option>)}</select><button onClick={()=>exportCSV(filtered,'esg_factors.csv')} style={btnS(false)}>Export CSV</button></div>
    <div style={{overflowX:'auto',...cS,padding:0}}><table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr>{[['name','Factor'],['category','Cat'],['return1Y','1Y Ret'],['volatility','Vol'],['sharpe','Sharpe'],['alpha','Alpha'],['infoRatio','IR'],['tStat','t-Stat'],['maxDrawdown','Max DD']].map(([k,l])=><th key={k} onClick={()=>doSort(k)} style={thS}>{l}{si(k,sortCol,sortDir)}</th>)}</tr></thead>
      <tbody>{paged.map(r=><tr key={r.id} onClick={()=>setSelected(r)} style={{cursor:'pointer',background:selected?.id===r.id?T.surfaceH:'transparent'}}><td style={tdS}><span style={{fontWeight:600}}>{r.name}</span></td><td style={tdS}>{r.category.slice(0,3)}</td><td style={tdS}><span style={retBdg(r.return1Y)}>{r.return1Y>0?'+':''}{r.return1Y}%</span></td><td style={tdS}>{r.volatility}%</td><td style={tdS}>{r.sharpe}</td><td style={tdS}><span style={retBdg(r.alpha)}>{r.alpha>0?'+':''}{r.alpha}%</span></td><td style={tdS}>{r.infoRatio}</td><td style={tdS}>{r.tStat}</td><td style={tdS}><span style={{color:T.red}}>{r.maxDrawdown}%</span></td></tr>)}</tbody></table></div>
    {totalPages>1&&<div style={{display:'flex',gap:6,marginTop:12,alignItems:'center',justifyContent:'center'}}><button onClick={()=>setPage(p=>Math.max(1,p-1))} disabled={page===1} style={pgB}>&laquo;</button><span style={{fontSize:11,color:T.textSec,fontFamily:T.mono}}>Page {page}/{totalPages}</span><button onClick={()=>setPage(p=>Math.min(totalPages,p+1))} disabled={page===totalPages} style={pgB}>&raquo;</button></div>}
    <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16,marginTop:20}}>
      <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Performance by ESG Pillar</div><ResponsiveContainer width="100%" height={260}><BarChart data={catPerf}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="category" tick={{fontSize:9,fill:T.textSec}}/><YAxis tick={{fontSize:9,fill:T.textSec}}/><Tooltip {...tip}/><Bar dataKey="return1Y" fill={ACCENT} name="Avg 1Y Return"/><Bar dataKey="sharpe" fill={T.gold} name="Avg Sharpe"/><Legend/></BarChart></ResponsiveContainer></div>
      <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Return vs Volatility</div><ResponsiveContainer width="100%" height={260}><ScatterChart><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="x" name="Volatility" tick={{fontSize:9,fill:T.textSec}}/><YAxis dataKey="y" name="Return" tick={{fontSize:9,fill:T.textSec}}/><Tooltip {...tip}/><Scatter data={filtered.map(f=>({name:f.name,x:f.volatility,y:f.return1Y}))} fill={ACCENT} fillOpacity={0.5}/></ScatterChart></ResponsiveContainer></div>
    </div>
  </div>);

  const renderAlpha=()=>(<div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16}}>
    <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Top 15 Factors by Alpha</div><ResponsiveContainer width="100%" height={350}><BarChart data={[...FACTORS].sort((a,b)=>b.alpha-a.alpha).slice(0,15)} layout="vertical"><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis type="number" tick={{fontSize:9,fill:T.textSec}}/><YAxis type="category" dataKey="name" tick={{fontSize:8,fill:T.textSec}} width={100}/><Tooltip {...tip}/><Bar dataKey="alpha" fill={ACCENT}>{[...FACTORS].sort((a,b)=>b.alpha-a.alpha).slice(0,15).map((f,j)=><Cell key={j} fill={f.alpha>=0?T.green:T.red}/>)}</Bar></BarChart></ResponsiveContainer></div>
    <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Information Ratio Distribution</div><ResponsiveContainer width="100%" height={350}><BarChart data={[...FACTORS].sort((a,b)=>b.infoRatio-a.infoRatio).slice(0,15)} layout="vertical"><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis type="number" tick={{fontSize:9,fill:T.textSec}}/><YAxis type="category" dataKey="name" tick={{fontSize:8,fill:T.textSec}} width={100}/><Tooltip {...tip}/><Bar dataKey="infoRatio" fill={T.gold} radius={[0,4,4,0]}/></BarChart></ResponsiveContainer></div>
    <div style={{...cS,gridColumn:'1/3'}}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Alpha vs Info Ratio Scatter</div><ResponsiveContainer width="100%" height={280}><ScatterChart><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="x" name="Alpha" tick={{fontSize:9,fill:T.textSec}}/><YAxis dataKey="y" name="IR" tick={{fontSize:9,fill:T.textSec}}/><Tooltip {...tip}/><Scatter data={FACTORS.map(f=>({name:f.name,x:f.alpha,y:f.infoRatio}))} fill={ACCENT} fillOpacity={0.5}/></ScatterChart></ResponsiveContainer></div>
  </div></div>);

  const renderRisk=()=>{
    const catDist=CATS.slice(1).map(c=>({name:c,value:FACTORS.filter(f=>f.category===c).length}));
    return(<div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16}}>
      <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Factor Category Distribution</div><ResponsiveContainer width="100%" height={260}><PieChart><Pie data={catDist} cx="50%" cy="50%" outerRadius={90} dataKey="value" label={({name,value})=>`${name}: ${value}`}>{catDist.map((_,i)=><Cell key={i} fill={COLORS[i]}/>)}</Pie><Tooltip {...tip}/></PieChart></ResponsiveContainer></div>
      <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Volatility by Category</div><ResponsiveContainer width="100%" height={260}><BarChart data={catPerf}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="category" tick={{fontSize:9,fill:T.textSec}}/><YAxis tick={{fontSize:9,fill:T.textSec}}/><Tooltip {...tip}/><Bar dataKey="volatility" fill={T.red} name="Avg Volatility" radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></div>
      <div style={{...cS,gridColumn:'1/3'}}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Max Drawdown Ranking</div><ResponsiveContainer width="100%" height={280}><BarChart data={[...FACTORS].sort((a,b)=>a.maxDrawdown-b.maxDrawdown).slice(0,20)}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="name" tick={{fontSize:7,fill:T.textSec}} angle={-35}/><YAxis tick={{fontSize:9,fill:T.textSec}}/><Tooltip {...tip}/><Bar dataKey="maxDrawdown" fill={T.red} radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></div>
    </div></div>);
  };

  const renderBacktest=()=>{
    const cumData=Array.from({length:24},(_,m)=>({month:'M'+(m+1),esg:+((m+1)*0.4+sr(m*7)*3).toFixed(1),benchmark:+((m+1)*0.3+sr(m*11)*2).toFixed(1)}));
    return(<div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16}}>
      <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>ESG Factor Portfolio vs Benchmark</div><ResponsiveContainer width="100%" height={300}><LineChart data={cumData}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="month" tick={{fontSize:8,fill:T.textSec}}/><YAxis tick={{fontSize:9,fill:T.textSec}}/><Tooltip {...tip}/><Line type="monotone" dataKey="esg" stroke={ACCENT} strokeWidth={2} name="ESG Portfolio" dot={false}/><Line type="monotone" dataKey="benchmark" stroke={T.textMut} strokeWidth={2} name="Benchmark" dot={false}/><Legend/></LineChart></ResponsiveContainer></div>
      <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Rolling 12M Sharpe</div><ResponsiveContainer width="100%" height={300}><AreaChart data={Array.from({length:24},(_,m)=>({month:'M'+(m+1),sharpe:+(0.3+sr(m*13)*0.8).toFixed(2)}))}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="month" tick={{fontSize:8,fill:T.textSec}}/><YAxis tick={{fontSize:9,fill:T.textSec}}/><Tooltip {...tip}/><Area type="monotone" dataKey="sharpe" stroke={T.gold} fill="rgba(197,169,106,0.15)"/></AreaChart></ResponsiveContainer></div>
      <div style={{...cS,gridColumn:'1/3'}}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Factor Correlation Heatmap (Top 10)</div>
        <div style={{overflowX:'auto'}}><table style={{borderCollapse:'collapse'}}><thead><tr><th style={thS}></th>{FACTORS.slice(0,10).map(f=><th key={f.id} style={{...thS,fontSize:8,maxWidth:60}}>{f.name.slice(0,8)}</th>)}</tr></thead><tbody>{FACTORS.slice(0,10).map((f,i)=><tr key={f.id}><td style={{...tdS,fontWeight:600,fontSize:9}}>{f.name.slice(0,10)}</td>{FACTORS.slice(0,10).map((g,j)=>{const v=i===j?1:+(sr(i*100+j*7)*1.6-0.8).toFixed(2);return<td key={g.id} style={{...tdS,textAlign:'center',fontSize:10,fontFamily:T.mono,background:v>0.3?'rgba(22,163,74,0.1)':v<-0.3?'rgba(220,38,38,0.1)':'transparent'}}>{v}</td>;})}</tr>)}</tbody></table></div>
      </div>
    </div></div>);
  };

  return(<div style={{padding:'24px 32px',fontFamily:T.font,background:T.bg,minHeight:'100vh'}}>
    <div style={{marginBottom:20}}><h1 style={{fontSize:22,fontWeight:700,color:T.navy,margin:0}}>ESG Factor Attribution</h1><p style={{fontSize:12,color:T.textSec,margin:'4px 0 0'}}>50 ESG factors | Returns, alpha, risk decomposition & backtesting</p></div>
    <div style={{display:'flex',gap:8,marginBottom:20}}>{TABS.map((t,i)=><button key={t} onClick={()=>setTab(i)} style={btnS(tab===i)}>{t}</button>)}</div>
    {tab===0&&renderDash()}{tab===1&&renderAlpha()}{tab===2&&renderRisk()}{tab===3&&renderBacktest()}
    <Panel item={selected} onClose={()=>setSelected(null)}/>
  </div>);
}