import React,{useState,useMemo,useCallback} from 'react';
import {BarChart,Bar,LineChart,Line,AreaChart,Area,PieChart,Pie,Cell,ScatterChart,Scatter,XAxis,YAxis,CartesianGrid,Tooltip,ResponsiveContainer,Legend,RadarChart,Radar,PolarGrid,PolarAngleAxis,PolarRadiusAxis} from 'recharts';
const T={bg:'#f6f4f0',surface:'#ffffff',surfaceH:'#f0ede7',border:'#e5e0d8',borderL:'#d5cfc5',navy:'#1b3a5c',navyL:'#2c5a8c',gold:'#c5a96a',goldL:'#d4be8a',sage:'#5a8a6a',sageL:'#7ba67d',teal:'#5a8a6a',text:'#1b3a5c',textSec:'#5c6b7e',textMut:'#9aa3ae',red:'#dc2626',green:'#16a34a',amber:'#d97706',font:"'DM Sans','SF Pro Display',system-ui,-apple-system,sans-serif",mono:"'JetBrains Mono','SF Mono','Fira Code',monospace"};
const sr=(s)=>{let x=Math.sin(s+1)*10000;return x-Math.floor(x);};
const ACCENT='#0f766e';const tip={contentStyle:{background:T.surface,border:`1px solid ${T.border}`,borderRadius:8,fontSize:11,fontFamily:T.font},labelStyle:{color:T.textSec,fontFamily:T.mono,fontSize:10}};const COLORS=[T.navy,T.gold,T.sage,T.red,T.amber,T.green,T.navyL,T.goldL,'#8b5cf6','#ec4899'];
const fmt=v=>typeof v==='number'?v>=1e6?(v/1e6).toFixed(1)+'M':v>=1e3?(v/1e3).toFixed(1)+'K':v.toFixed(0):v;
const TABS=['Voting Dashboard','Company AGMs','Resolution Analysis','Voting Trends'];const SECTORS=['All','Technology','Financials','Healthcare','Energy','Consumer','Industrials','Materials','Utilities'];const PAGE=12;
const RESTYPES=['Climate','Board Diversity','Executive Pay','Human Rights','Lobbying Disclosure','Political Spend','Racial Equity','Water Risk','Deforestation','Plastic Pollution','Tax Transparency','Cybersecurity'];
const COS=Array.from({length:80},(_,i)=>{
  const names=['Apple','Microsoft','Alphabet','Amazon','NVIDIA','Meta','Tesla','JPMorgan','Visa','UnitedHealth','J&J','Walmart','P&G','Mastercard','Chevron','Home Depot','Coca-Cola','Pfizer','Abbott','Eli Lilly','PepsiCo','Costco','Broadcom','Cisco','Merck','Accenture','McDonalds','Adobe','Salesforce','AMD','Qualcomm','Intel','Goldman Sachs','Caterpillar','Amgen','Honeywell','Lockheed','Deere','IBM','GE','Medtronic','Shell','BP','TotalEnergies','Nestle','Roche','Novartis','SAP','Siemens','LVMH','Unilever','HSBC','BHP','Rio Tinto','Toyota','Samsung','TSMC','Novo Nordisk','AbbVie','Netflix','Starbucks','Booking','Intuit','Uber','Airbnb','PayPal','ServiceNow','CrowdStrike','Snowflake','Datadog','NextEra','Enel','Iberdrola','Orsted','Duke Energy','Southern Co','Xcel Energy','AES Corp','Dominion','Brookfield'];
  const secs=['Technology','Technology','Technology','Technology','Technology','Technology','Technology','Financials','Financials','Healthcare','Healthcare','Consumer','Consumer','Financials','Energy','Consumer','Consumer','Healthcare','Healthcare','Healthcare','Consumer','Consumer','Technology','Technology','Healthcare','Technology','Consumer','Technology','Technology','Technology','Technology','Technology','Financials','Industrials','Healthcare','Industrials','Industrials','Industrials','Technology','Industrials','Healthcare','Energy','Energy','Energy','Consumer','Healthcare','Healthcare','Technology','Industrials','Consumer','Consumer','Financials','Materials','Materials','Industrials','Technology','Technology','Healthcare','Healthcare','Technology','Consumer','Consumer','Technology','Technology','Technology','Financials','Technology','Technology','Technology','Technology','Utilities','Utilities','Utilities','Utilities','Utilities','Utilities','Utilities','Utilities','Utilities','Utilities'];
  const totalRes=Math.round(sr(i*7)*15+3);const esgRes=Math.round(totalRes*(sr(i*11)*0.4+0.1));const avgSupport=Math.round(sr(i*13)*40+20);const mgmtOpposed=Math.round(esgRes*(sr(i*17)*0.6+0.2));
  const resolutions=Array.from({length:Math.min(esgRes,5)},(_,j)=>({type:RESTYPES[Math.floor(sr(i*100+j*7)*RESTYPES.length)],support:Math.round(sr(i*100+j*11)*50+15),year:2023+Math.floor(sr(i*100+j*13)*2),result:sr(i*100+j*17)>0.7?'Passed':'Failed',filer:['As You Sow','NYSCRF','CalPERS','Follow This','ShareAction','Trillium','ICCR','Mercy Invest'][Math.floor(sr(i*100+j*19)*8)]}));
  return{id:i+1,name:names[i],sector:secs[i],totalResolutions:totalRes,esgResolutions:esgRes,avgSupportPct:avgSupport,mgmtOpposed,shareholderProposals:Math.round(sr(i*19)*8+1),sayOnPayPct:Math.round(sr(i*23)*25+70),directorElectionAvg:Math.round(sr(i*29)*15+80),contestedVotes:Math.round(sr(i*31)*3),abstentionRate:+(sr(i*37)*10+2).toFixed(1),issVote:sr(i*41)>0.4?'Aligned':'Divergent',glassLewis:sr(i*43)>0.45?'Aligned':'Divergent',passedESG:resolutions.filter(r=>r.result==='Passed').length,resolutions,votingPolicy:['Stewardship','Active','Passive'][Math.floor(sr(i*47)*3)]||'Active',engagements:Math.round(sr(i*49)*10+1)};
});
export default function ProxyVotingIntelPage(){
  const[tab,setTab]=useState(0);const[search,setSearch]=useState('');const[sectorF,setSectorF]=useState('All');const[sortCol,setSortCol]=useState('esgResolutions');const[sortDir,setSortDir]=useState('desc');const[page,setPage]=useState(1);const[selected,setSelected]=useState(null);
  const filtered=useMemo(()=>{let d=[...COS];if(search)d=d.filter(r=>r.name.toLowerCase().includes(search.toLowerCase()));if(sectorF!=='All')d=d.filter(r=>r.sector===sectorF);d.sort((a,b)=>sortDir==='asc'?(a[sortCol]>b[sortCol]?1:-1):(a[sortCol]<b[sortCol]?1:-1));return d;},[search,sectorF,sortCol,sortDir]);
  const paged=useMemo(()=>filtered.slice((page-1)*PAGE,page*PAGE),[filtered,page]);const totalPages=Math.ceil(filtered.length/PAGE);
  const doSort=col=>{if(sortCol===col)setSortDir(d=>d==='asc'?'desc':'asc');else{setSortCol(col);setSortDir('desc');}setPage(1);};
  const stats=useMemo(()=>({count:filtered.length,totalESGRes:filtered.reduce((s,r)=>s+r.esgResolutions,0),avgSupport:Math.round(filtered.reduce((s,r)=>s+r.avgSupportPct,0)/filtered.length||0),totalPassed:filtered.reduce((s,r)=>s+r.passedESG,0),avgSoP:Math.round(filtered.reduce((s,r)=>s+r.sayOnPayPct,0)/filtered.length||0),issAligned:filtered.filter(r=>r.issVote==='Aligned').length,contested:filtered.reduce((s,r)=>s+r.contestedVotes,0)}),[filtered]);
  const resTypeDist=useMemo(()=>{const m={};COS.forEach(c=>c.resolutions.forEach(r=>{m[r.type]=(m[r.type]||0)+1;}));return Object.entries(m).map(([k,v])=>({type:k,count:v})).sort((a,b)=>b.count-a.count);},[]);
  const sectorVoting=useMemo(()=>{const m={};COS.forEach(c=>{if(!m[c.sector])m[c.sector]={s:c.sector,support:0,sop:0,n:0};m[c.sector].support+=c.avgSupportPct;m[c.sector].sop+=c.sayOnPayPct;m[c.sector].n++;});return Object.values(m).map(s=>({sector:s.s,avgSupport:Math.round(s.support/s.n),avgSoP:Math.round(s.sop/s.n)}));},[]);
  const exportCSV=useCallback((data,fn)=>{if(!data.length)return;const keys=Object.keys(data[0]).filter(k=>k!=='resolutions');const csv=[keys.join(','),...data.map(r=>keys.map(k=>`"${r[k]}"`).join(','))].join('\n');const b=new Blob([csv],{type:'text/csv'});const u=URL.createObjectURL(b);const a=document.createElement('a');a.href=u;a.download=fn;a.click();URL.revokeObjectURL(u);},[]);
  const si=(col,cur,dir)=>cur===col?(dir==='asc'?' \u25B2':' \u25BC'):' \u25CB';
  const thS={padding:'8px 10px',fontSize:11,fontFamily:T.mono,color:T.textSec,cursor:'pointer',borderBottom:`1px solid ${T.border}`,whiteSpace:'nowrap',userSelect:'none',textAlign:'left',background:T.surfaceH};const tdS={padding:'7px 10px',fontSize:12,fontFamily:T.font,borderBottom:`1px solid ${T.border}`,color:T.text};const inpS={padding:'6px 12px',border:`1px solid ${T.border}`,borderRadius:6,fontSize:12,fontFamily:T.font,background:T.surface,color:T.text,outline:'none',width:220};const selS={padding:'6px 10px',border:`1px solid ${T.border}`,borderRadius:6,fontSize:11,fontFamily:T.font,background:T.surface,color:T.text};
  const btnS=a=>({padding:'6px 16px',border:`1px solid ${a?ACCENT:T.border}`,borderRadius:6,fontSize:12,fontFamily:T.font,background:a?ACCENT:T.surface,color:a?'#fff':T.text,cursor:'pointer',fontWeight:a?600:400});const pgB={padding:'4px 10px',border:`1px solid ${T.border}`,borderRadius:4,fontSize:11,cursor:'pointer',background:T.surface,color:T.text};const cS={background:T.surface,border:`1px solid ${T.border}`,borderRadius:10,padding:16};
  const kpi=(l,v,c)=>(<div style={{background:T.surface,border:`1px solid ${T.border}`,borderRadius:10,padding:'14px 18px',flex:1,minWidth:130}}><div style={{fontSize:10,color:T.textMut,fontFamily:T.mono,textTransform:'uppercase',letterSpacing:1}}>{l}</div><div style={{fontSize:22,fontWeight:700,color:c||T.navy,marginTop:4}}>{v}</div></div>);
  const Panel=({item,onClose})=>{if(!item)return null;return(<div style={{position:'fixed',top:0,right:0,width:460,height:'100vh',background:T.surface,borderLeft:`2px solid ${ACCENT}`,zIndex:1000,overflowY:'auto',boxShadow:'-4px 0 24px rgba(0,0,0,0.10)'}}><div style={{padding:'20px 24px',borderBottom:`1px solid ${T.border}`,display:'flex',justifyContent:'space-between',alignItems:'center'}}><div><div style={{fontSize:16,fontWeight:700,color:T.navy}}>{item.name}</div><div style={{fontSize:12,color:T.textSec}}>{item.sector}</div></div><button onClick={onClose} style={{background:'none',border:'none',fontSize:20,cursor:'pointer',color:T.textMut}}>{'\u2715'}</button></div>
    <div style={{padding:'16px 24px'}}>
      <div style={{display:'grid',gridTemplateColumns:'1fr 1fr 1fr',gap:8,marginBottom:12}}>{[['Total Res.',item.totalResolutions],['ESG Res.',item.esgResolutions],['Avg Support',item.avgSupportPct+'%'],['Mgmt Opposed',item.mgmtOpposed],['Say on Pay',item.sayOnPayPct+'%'],['Dir Election',item.directorElectionAvg+'%'],['Contested',item.contestedVotes],['ISS',item.issVote],['Glass Lewis',item.glassLewis],['Passed ESG',item.passedESG],['Abstention',item.abstentionRate+'%'],['Engagements',item.engagements]].map(([k,v],j)=>(<div key={j} style={{background:T.surfaceH,borderRadius:6,padding:'8px 10px'}}><div style={{fontSize:9,color:T.textMut,fontFamily:T.mono}}>{k}</div><div style={{fontSize:13,fontWeight:600,color:T.navy,marginTop:2}}>{v}</div></div>))}</div>
      {item.resolutions.length>0&&<div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>ESG Resolutions</div><table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr>{['Type','Support%','Year','Result','Filer'].map(h=><th key={h} style={{...thS,fontSize:9}}>{h}</th>)}</tr></thead><tbody>{item.resolutions.map((r,j)=><tr key={j}><td style={tdS}>{r.type}</td><td style={tdS}>{r.support}%</td><td style={tdS}>{r.year}</td><td style={tdS}><span style={{color:r.result==='Passed'?T.green:T.red,fontWeight:600,fontSize:10}}>{r.result}</span></td><td style={{...tdS,fontSize:10}}>{r.filer}</td></tr>)}</tbody></table></div>}
    </div></div>);};
  const renderDash=()=>(<div>
    <div style={{display:'flex',gap:12,marginBottom:20,flexWrap:'wrap'}}>{kpi('Companies',stats.count)}{kpi('ESG Resolutions',stats.totalESGRes)}{kpi('Avg Support',stats.avgSupport+'%')}{kpi('Passed',stats.totalPassed,T.green)}{kpi('Avg Say on Pay',stats.avgSoP+'%')}{kpi('ISS Aligned',stats.issAligned)}{kpi('Contested',stats.contested)}</div>
    <div style={{display:'flex',gap:12,marginBottom:16,alignItems:'center',flexWrap:'wrap'}}><input value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}} placeholder="Search companies..." style={inpS}/><select value={sectorF} onChange={e=>{setSectorF(e.target.value);setPage(1);}} style={selS}>{SECTORS.map(s=><option key={s}>{s}</option>)}</select><button onClick={()=>exportCSV(filtered,'proxy_voting.csv')} style={btnS(false)}>Export CSV</button></div>
    <div style={{overflowX:'auto',...cS,padding:0}}><table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr>{[['name','Company'],['sector','Sector'],['esgResolutions','ESG Res'],['avgSupportPct','Support%'],['sayOnPayPct','SoP%'],['passedESG','Passed'],['issVote','ISS'],['contestedVotes','Contested']].map(([k,l])=><th key={k} onClick={()=>doSort(k)} style={thS}>{l}{si(k,sortCol,sortDir)}</th>)}</tr></thead>
      <tbody>{paged.map(r=><tr key={r.id} onClick={()=>setSelected(r)} style={{cursor:'pointer',background:selected?.id===r.id?T.surfaceH:'transparent'}}><td style={tdS}><span style={{fontWeight:600}}>{r.name}</span></td><td style={tdS}>{r.sector}</td><td style={tdS}>{r.esgResolutions}</td><td style={tdS}>{r.avgSupportPct}%</td><td style={tdS}>{r.sayOnPayPct}%</td><td style={tdS}>{r.passedESG}</td><td style={tdS}><span style={{color:r.issVote==='Aligned'?T.green:T.amber,fontSize:10,fontWeight:600}}>{r.issVote}</span></td><td style={tdS}>{r.contestedVotes}</td></tr>)}</tbody></table></div>
    {totalPages>1&&<div style={{display:'flex',gap:6,marginTop:12,alignItems:'center',justifyContent:'center'}}><button onClick={()=>setPage(p=>Math.max(1,p-1))} disabled={page===1} style={pgB}>&laquo;</button><span style={{fontSize:11,color:T.textSec,fontFamily:T.mono}}>Page {page}/{totalPages}</span><button onClick={()=>setPage(p=>Math.min(totalPages,p+1))} disabled={page===totalPages} style={pgB}>&raquo;</button></div>}
    <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16,marginTop:20}}>
      <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>ESG Resolution Types</div><ResponsiveContainer width="100%" height={280}><BarChart data={resTypeDist.slice(0,10)} layout="vertical"><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis type="number" tick={{fontSize:9,fill:T.textSec}}/><YAxis type="category" dataKey="type" tick={{fontSize:8,fill:T.textSec}} width={100}/><Tooltip {...tip}/><Bar dataKey="count" fill={ACCENT} radius={[0,4,4,0]}/></BarChart></ResponsiveContainer></div>
      <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Support % by Sector</div><ResponsiveContainer width="100%" height={280}><BarChart data={sectorVoting}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="sector" tick={{fontSize:8,fill:T.textSec}} angle={-25}/><YAxis tick={{fontSize:9,fill:T.textSec}} domain={[0,100]}/><Tooltip {...tip}/><Bar dataKey="avgSupport" fill={ACCENT} name="ESG Support %"/><Bar dataKey="avgSoP" fill={T.gold} name="Say on Pay %"/><Legend/></BarChart></ResponsiveContainer></div>
    </div></div>);
  const renderAGM=()=>(<div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16}}>
    <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Highest ESG Resolution Activity</div><ResponsiveContainer width="100%" height={350}><BarChart data={[...COS].sort((a,b)=>b.esgResolutions-a.esgResolutions).slice(0,15)} layout="vertical"><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis type="number" tick={{fontSize:9,fill:T.textSec}}/><YAxis type="category" dataKey="name" tick={{fontSize:8,fill:T.textSec}} width={80}/><Tooltip {...tip}/><Bar dataKey="esgResolutions" fill={ACCENT} radius={[0,4,4,0]}/></BarChart></ResponsiveContainer></div>
    <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Director Election Support</div><ResponsiveContainer width="100%" height={350}><BarChart data={[...filtered].sort((a,b)=>a.directorElectionAvg-b.directorElectionAvg).slice(0,15)} layout="vertical"><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis type="number" tick={{fontSize:9,fill:T.textSec}} domain={[60,100]}/><YAxis type="category" dataKey="name" tick={{fontSize:8,fill:T.textSec}} width={80}/><Tooltip {...tip}/><Bar dataKey="directorElectionAvg" fill={T.navy} radius={[0,4,4,0]}/></BarChart></ResponsiveContainer></div>
  </div></div>);
  const renderResolution=()=>(<div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16}}>
    <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Resolution Outcome Distribution</div><ResponsiveContainer width="100%" height={280}><PieChart><Pie data={[{n:'Passed',v:COS.reduce((s,c)=>s+c.passedESG,0)},{n:'Failed',v:COS.reduce((s,c)=>s+c.esgResolutions-c.passedESG,0)}]} cx="50%" cy="50%" outerRadius={90} dataKey="v" label={({n,v})=>`${n}: ${v}`}>{[T.green,T.red].map((c,i)=><Cell key={i} fill={c}/>)}</Pie><Tooltip {...tip}/></PieChart></ResponsiveContainer></div>
    <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Support vs Abstention</div><ResponsiveContainer width="100%" height={280}><ScatterChart><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="x" name="Avg Support%" tick={{fontSize:9,fill:T.textSec}}/><YAxis dataKey="y" name="Abstention%" tick={{fontSize:9,fill:T.textSec}}/><Tooltip {...tip}/><Scatter data={filtered.map(c=>({name:c.name,x:c.avgSupportPct,y:c.abstentionRate}))} fill={ACCENT} fillOpacity={0.5}/></ScatterChart></ResponsiveContainer></div>
  </div></div>);
  const renderTrends=()=>(<div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16}}>
    <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>ISS Alignment by Sector</div><ResponsiveContainer width="100%" height={280}><BarChart data={SECTORS.slice(1).map(s=>{const cos=COS.filter(c=>c.sector===s);return{sector:s,pct:cos.length?Math.round(cos.filter(c=>c.issVote==='Aligned').length/cos.length*100):0};})}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="sector" tick={{fontSize:8,fill:T.textSec}} angle={-20}/><YAxis tick={{fontSize:9,fill:T.textSec}} domain={[0,100]}/><Tooltip {...tip}/><Bar dataKey="pct" fill={T.sage} radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></div>
    <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Engagements vs Resolutions</div><ResponsiveContainer width="100%" height={280}><ScatterChart><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="x" name="Engagements" tick={{fontSize:9,fill:T.textSec}}/><YAxis dataKey="y" name="ESG Resolutions" tick={{fontSize:9,fill:T.textSec}}/><Tooltip {...tip}/><Scatter data={filtered.map(c=>({name:c.name,x:c.engagements,y:c.esgResolutions}))} fill={T.gold} fillOpacity={0.5}/></ScatterChart></ResponsiveContainer></div>
  </div></div>);
  return(<div style={{padding:'24px 32px',fontFamily:T.font,background:T.bg,minHeight:'100vh'}}>
    <div style={{marginBottom:20}}><h1 style={{fontSize:22,fontWeight:700,color:T.navy,margin:0}}>Proxy Voting Intelligence</h1><p style={{fontSize:12,color:T.textSec,margin:'4px 0 0'}}>80 companies | AGM voting, ESG resolutions, proxy advisory analysis</p></div>
    <div style={{display:'flex',gap:8,marginBottom:20}}>{TABS.map((t,i)=><button key={t} onClick={()=>setTab(i)} style={btnS(tab===i)}>{t}</button>)}</div>
    {tab===0&&renderDash()}{tab===1&&renderAGM()}{tab===2&&renderResolution()}{tab===3&&renderTrends()}
    <Panel item={selected} onClose={()=>setSelected(null)}/>
  </div>);
}