import React,{useState,useMemo,useCallback} from 'react';
import {BarChart,Bar,XAxis,YAxis,CartesianGrid,Tooltip,ResponsiveContainer,PieChart,Pie,Cell,AreaChart,Area,LineChart,Line,RadarChart,Radar,PolarGrid,PolarAngleAxis,PolarRadiusAxis,Legend} from 'recharts';
const T={bg:'#f6f4f0',surface:'#ffffff',surfaceH:'#f0ede7',border:'#e5e0d8',borderL:'#d5cfc5',navy:'#1b3a5c',navyL:'#2c5a8c',gold:'#c5a96a',goldL:'#d4be8a',sage:'#5a8a6a',sageL:'#7ba67d',teal:'#5a8a6a',text:'#1b3a5c',textSec:'#5c6b7e',textMut:'#9aa3ae',red:'#dc2626',green:'#16a34a',amber:'#d97706',font:"'DM Sans','SF Pro Display',system-ui,-apple-system,sans-serif",mono:"'JetBrains Mono','SF Mono','Fira Code',monospace"};
const sr=(s)=>{let x=Math.sin(s+1)*10000;return x-Math.floor(x);};
const ACCENT='#ea580c';const fmt=v=>typeof v==='number'?v>=1e6?(v/1e6).toFixed(1)+'M':v>=1e3?(v/1e3).toFixed(1)+'K':v.toFixed?v.toFixed(2):v:v;
const tip={contentStyle:{background:T.surface,border:`1px solid ${T.border}`,borderRadius:8,fontSize:11,fontFamily:T.font},labelStyle:{color:T.textSec,fontFamily:T.mono,fontSize:10}};
const TABS=['Safety Dashboard','Company Screening','Incident Analysis','Benchmarking'];
const SECTORS=['All','Mining','Construction','Manufacturing','Oil & Gas','Chemicals','Utilities','Transportation','Agriculture','Forestry','Metals'];
const REGIONS=['All','North America','Europe','Asia Pacific','Latin America','Africa','Middle East'];
const RATINGS=['All','Critical','Poor','Below Average','Average','Good','Excellent'];
const PAGE_SIZE=15;const PIECLRS=[T.navy,T.gold,T.sage,T.red,T.amber,T.green,T.navyL,T.goldL,'#8b5cf6','#ec4899'];
const badge=(v,th)=>{const[lo,mid,hi]=th;const bg=v<=lo?'rgba(22,163,74,0.12)':v<=mid?'rgba(197,169,106,0.12)':v<=hi?'rgba(217,119,6,0.12)':'rgba(220,38,38,0.12)';const c=v<=lo?T.green:v<=mid?T.gold:v<=hi?T.amber:T.red;return{background:bg,color:c,padding:'2px 8px',borderRadius:4,fontSize:11,fontWeight:600,fontFamily:T.mono};};
const ratBadge=(r)=>{const m={Critical:{bg:'rgba(220,38,38,0.12)',c:T.red},Poor:{bg:'rgba(220,38,38,0.08)',c:'#b91c1c'},'Below Average':{bg:'rgba(217,119,6,0.12)',c:T.amber},Average:{bg:'rgba(197,169,106,0.15)',c:T.gold},Good:{bg:'rgba(22,163,74,0.12)',c:T.green},Excellent:{bg:'rgba(22,163,74,0.08)',c:'#15803d'}};const s=m[r]||m.Average;return{background:s.bg,color:s.c,padding:'2px 8px',borderRadius:4,fontSize:11,fontWeight:600};};

const COMPANIES=(()=>{const names=['BHP Group','Rio Tinto','Vale SA','Glencore','Anglo American','Freeport McMoRan','Newmont Corp','Barrick Gold','ArcelorMittal','Nucor Corp','US Steel','Caterpillar','Deere & Co','BASF SE','Dow Inc','DuPont','3M Company','Honeywell','General Electric','Siemens AG','ABB Ltd','Schneider Electric','Exxon Mobil','Chevron','Shell plc','BP plc','TotalEnergies','ConocoPhillips','Schlumberger','Halliburton','Baker Hughes','Bechtel Corp','Fluor Corp','AECOM','Jacobs Eng','Skanska AB','Vinci SA','Bouygues','CRH plc','LafargeHolcim','HeidelbergCement','Martin Marietta','Vulcan Materials','Cemex SAB','Saint-Gobain','Suncor Energy','Imperial Oil','Teck Resources','South32 Ltd','Fortescue Metals','Alcoa Corp','Cleveland-Cliffs','Mosaic Co','Nutrien Ltd','CF Industries','Yara Intl','OCI NV','Sasol Ltd','Vedanta Ltd','Hindalco Industries','JSW Steel','Tata Steel','Norsk Hydro','Boliden AB','LKAB','Codelco','Antofagasta','First Quantum','Ivanhoe Mines','Pan American Silver','Kinross Gold','Agnico Eagle','Wheaton Precious','Franco-Nevada','B2Gold Corp','Centerra Gold','Lundin Mining','Hudbay Minerals','Capstone Copper','Ero Copper'];
const secs=['Mining','Mining','Mining','Mining','Mining','Mining','Mining','Mining','Metals','Metals','Metals','Manufacturing','Manufacturing','Chemicals','Chemicals','Chemicals','Manufacturing','Manufacturing','Manufacturing','Manufacturing','Manufacturing','Manufacturing','Oil & Gas','Oil & Gas','Oil & Gas','Oil & Gas','Oil & Gas','Oil & Gas','Oil & Gas','Oil & Gas','Oil & Gas','Construction','Construction','Construction','Construction','Construction','Construction','Construction','Construction','Chemicals','Chemicals','Construction','Construction','Construction','Manufacturing','Oil & Gas','Oil & Gas','Mining','Mining','Mining','Metals','Metals','Chemicals','Chemicals','Chemicals','Chemicals','Chemicals','Oil & Gas','Mining','Metals','Metals','Metals','Metals','Mining','Mining','Mining','Mining','Mining','Mining','Mining','Mining','Mining','Mining','Mining','Mining','Mining','Mining','Mining','Mining','Mining'];
const regs=['Asia Pacific','Europe','Latin America','Europe','Europe','North America','North America','North America','Europe','North America','North America','North America','North America','Europe','North America','North America','North America','North America','North America','Europe','Europe','Europe','North America','North America','Europe','Europe','Europe','North America','North America','North America','North America','North America','North America','North America','North America','Europe','Europe','Europe','Europe','Europe','Europe','North America','North America','Latin America','Europe','North America','North America','North America','Asia Pacific','Asia Pacific','North America','North America','North America','North America','North America','Europe','Europe','Africa','Asia Pacific','Asia Pacific','Asia Pacific','Asia Pacific','Europe','Europe','Europe','Latin America','Europe','Africa','Africa','Latin America','North America','North America','North America','North America','North America','North America','North America','North America','North America','North America'];
return names.map((n,i)=>({id:i+1,name:n,sector:secs[i],region:regs[i],ltir:+(sr(i*7)*4.5+0.2).toFixed(2),trir:+(sr(i*11)*8+0.5).toFixed(2),fatalities:Math.floor(sr(i*13)*5),nearMisses:Math.round(10+sr(i*17)*190),lostDays:Math.round(50+sr(i*19)*2000),employees:Math.round(5000+sr(i*23)*95000),safetySpend:Math.round(sr(i*29)*50),trainingHours:Math.round(8+sr(i*31)*40),inspections:Math.round(50+sr(i*37)*450),violations:Math.round(sr(i*41)*25),safetyScore:Math.round(20+sr(i*43)*75),isoCompliance:sr(i*47)>0.3?'Yes':'No',mentalHealth:Math.round(20+sr(i*53)*70),ergonomics:Math.round(30+sr(i*59)*65),ppeCompliance:Math.round(60+sr(i*61)*38),incidentTrend:sr(i*67)<0.4?'Improving':sr(i*67)<0.7?'Stable':'Worsening',safetyRating:sr(i*7)<0.1?'Critical':sr(i*7)<0.25?'Poor':sr(i*7)<0.45?'Below Average':sr(i*7)<0.65?'Average':sr(i*7)<0.85?'Good':'Excellent',severity:+(sr(i*71)*200+10).toFixed(0),processEvents:Math.round(sr(i*73)*15),contractorRate:+(sr(i*79)*6+0.5).toFixed(2)}));})();

const INCIDENT_TYPES=[{type:'Slips/Falls',count:245,pct:22},{type:'Struck By Object',count:198,pct:18},{type:'Overexertion',count:165,pct:15},{type:'Equipment Contact',count:143,pct:13},{type:'Chemical Exposure',count:110,pct:10},{type:'Vehicle Incident',count:88,pct:8},{type:'Electrical',count:66,pct:6},{type:'Confined Space',count:44,pct:4},{type:'Fire/Explosion',count:33,pct:3},{type:'Other',count:11,pct:1}];
const TREND=Array.from({length:36},(_,i)=>({month:`${2022+Math.floor(i/12)}-${String((i%12)+1).padStart(2,'0')}`,avgLtir:+(2.5-i*0.03+sr(i*7)*0.5).toFixed(2),avgTrir:+(4.5-i*0.05+sr(i*11)*0.8).toFixed(2),fatalities:Math.round(sr(i*13)*4),nearMisses:Math.round(50+sr(i*17)*100)}));
const BENCHMARKS=[{sector:'Mining',ltir:2.8,trir:5.2,fatRate:0.012},{sector:'Construction',ltir:2.1,trir:4.5,fatRate:0.008},{sector:'Manufacturing',ltir:1.5,trir:3.2,fatRate:0.004},{sector:'Oil & Gas',ltir:1.8,trir:3.8,fatRate:0.006},{sector:'Chemicals',ltir:1.2,trir:2.8,fatRate:0.003},{sector:'Metals',ltir:2.4,trir:4.8,fatRate:0.010},{sector:'Utilities',ltir:1.0,trir:2.2,fatRate:0.002},{sector:'Transportation',ltir:2.0,trir:4.0,fatRate:0.007}];

const csvExport=(rows,name)=>{if(!rows.length)return;const h=Object.keys(rows[0]);const csv=[h.join(','),...rows.map(r=>h.map(k=>JSON.stringify(r[k]??'')).join(','))].join('\n');const b=new Blob([csv],{type:'text/csv'});const u=URL.createObjectURL(b);const a=document.createElement('a');a.href=u;a.download=name+'.csv';a.click();URL.revokeObjectURL(u);};
const KPI=({label,value,sub,color})=>(<div style={{background:T.surface,border:`1px solid ${T.border}`,borderRadius:10,padding:'16px 20px',flex:'1 1 180px',minWidth:160}}><div style={{fontSize:11,color:T.textMut,fontFamily:T.mono,textTransform:'uppercase',letterSpacing:0.5}}>{label}</div><div style={{fontSize:26,fontWeight:700,color:color||T.navy,fontFamily:T.mono,marginTop:4}}>{value}</div>{sub&&<div style={{fontSize:11,color:T.textSec,marginTop:2}}>{sub}</div>}</div>);

export default function WorkplaceHealthSafetyPage(){
  const[tab,setTab]=useState(0);const[search,setSearch]=useState('');const[secF,setSecF]=useState('All');const[regF,setRegF]=useState('All');const[ratF,setRatF]=useState('All');
  const[sortCol,setSortCol]=useState('safetyScore');const[sortDir,setSortDir]=useState('desc');const[page,setPage]=useState(1);const[expanded,setExpanded]=useState(null);

  const filtered=useMemo(()=>{let d=[...COMPANIES];if(search)d=d.filter(r=>r.name.toLowerCase().includes(search.toLowerCase()));if(secF!=='All')d=d.filter(r=>r.sector===secF);if(regF!=='All')d=d.filter(r=>r.region===regF);if(ratF!=='All')d=d.filter(r=>r.safetyRating===ratF);d.sort((a,b)=>sortDir==='asc'?(a[sortCol]>b[sortCol]?1:-1):(a[sortCol]<b[sortCol]?1:-1));return d;},[search,secF,regF,ratF,sortCol,sortDir]);
  const paged=filtered.slice((page-1)*PAGE_SIZE,page*PAGE_SIZE);const totalPages=Math.ceil(filtered.length/PAGE_SIZE);
  const doSort=useCallback((col)=>{setSortCol(col);setSortDir(d=>sortCol===col?(d==='asc'?'desc':'asc'):'desc');setPage(1);},[sortCol]);

  const kpis=useMemo(()=>{const avgN=(k)=>+(COMPANIES.reduce((s,c)=>s+c[k],0)/ Math.max(1, COMPANIES.length)).toFixed(2);const totalFat=COMPANIES.reduce((s,c)=>s+c.fatalities,0);const avgScore=Math.round(COMPANIES.reduce((s,c)=>s+c.safetyScore,0)/ Math.max(1, COMPANIES.length));const improving=COMPANIES.filter(c=>c.incidentTrend==='Improving').length;return{avgLtir:avgN('ltir'),avgTrir:avgN('trir'),totalFat,avgScore,improving};},[]);
  const sectorChart=useMemo(()=>{const m={};COMPANIES.forEach(c=>{if(!m[c.sector])m[c.sector]={sector:c.sector,avgLtir:0,avgTrir:0,n:0};m[c.sector].avgLtir+=c.ltir;m[c.sector].avgTrir+=c.trir;m[c.sector].n++;});return Object.values(m).map(s=>({...s,avgLtir:+(s.avgLtir/s.n).toFixed(2),avgTrir:+(s.avgTrir/s.n).toFixed(2)}));},[]);
  const ratingDist=useMemo(()=>{const m={};COMPANIES.forEach(c=>{m[c.safetyRating]=(m[c.safetyRating]||0)+1;});return Object.entries(m).map(([name,value])=>({name,value}));},[]);
  const radarData=useMemo(()=>{const avg=(k)=>Math.round(COMPANIES.reduce((s,c)=>s+c[k],0)/ Math.max(1, COMPANIES.length));return[{dim:'Safety Score',value:avg('safetyScore')},{dim:'Training',value:avg('trainingHours')*2},{dim:'PPE Compliance',value:avg('ppeCompliance')},{dim:'Mental Health',value:avg('mentalHealth')},{dim:'Ergonomics',value:avg('ergonomics')},{dim:'ISO Cert',value:COMPANIES.filter(c=>c.isoCompliance==='Yes').length/ Math.max(1, COMPANIES.length)*100}].map(d=>({...d,fullMark:100}));},[]);

  const ss={wrap:{fontFamily:T.font,background:T.bg,minHeight:'100vh',padding:24,color:T.text},header:{fontSize:22,fontWeight:700,color:T.navy,marginBottom:4},sub:{fontSize:13,color:T.textSec,marginBottom:20},tabs:{display:'flex',gap:4,marginBottom:20,borderBottom:`2px solid ${T.border}`,paddingBottom:0},tab:(a)=>({padding:'10px 20px',fontSize:13,fontWeight:a?700:500,color:a?ACCENT:T.textSec,background:a?'rgba(234,88,12,0.06)':'transparent',border:'none',borderBottom:a?`2px solid ${ACCENT}`:'2px solid transparent',cursor:'pointer',fontFamily:T.font,marginBottom:-2}),card:{background:T.surface,border:`1px solid ${T.border}`,borderRadius:10,padding:20,marginBottom:20},input:{padding:'8px 14px',border:`1px solid ${T.border}`,borderRadius:6,fontSize:13,fontFamily:T.font,background:T.surface,color:T.text,outline:'none',width:220},select:{padding:'8px 12px',border:`1px solid ${T.border}`,borderRadius:6,fontSize:12,fontFamily:T.font,background:T.surface,color:T.text},th:(col,sc,sd)=>({padding:'10px 12px',textAlign:'left',fontSize:11,fontFamily:T.mono,color:sc===col?ACCENT:T.textMut,cursor:'pointer',borderBottom:`2px solid ${T.border}`,userSelect:'none',textTransform:'uppercase',letterSpacing:0.5,whiteSpace:'nowrap'}),td:{padding:'10px 12px',fontSize:12,borderBottom:`1px solid ${T.border}`,fontFamily:T.font},btn:{padding:'6px 16px',fontSize:12,fontWeight:600,color:T.surface,background:ACCENT,border:'none',borderRadius:6,cursor:'pointer',fontFamily:T.font},btnSec:{padding:'6px 16px',fontSize:12,fontWeight:600,color:T.textSec,background:'transparent',border:`1px solid ${T.border}`,borderRadius:6,cursor:'pointer',fontFamily:T.font},pg:{display:'flex',gap:8,alignItems:'center',justifyContent:'center',marginTop:16}};
  const TH=({col,label,sc,sd,fn})=><th style={ss.th(col,sc,sd)} onClick={()=>fn(col)}>{label}{sc===col?(sd==='asc'?' \u25B2':' \u25BC'):''}</th>;

  const renderDash=()=>(<>
    <div style={{display:'flex',gap:16,flexWrap:'wrap',marginBottom:24}}>
      <KPI label="Avg LTIR" value={kpis.avgLtir} sub="per 200K hours" color={ACCENT}/><KPI label="Avg TRIR" value={kpis.avgTrir} sub="per 200K hours" color={T.amber}/>
      <KPI label="Total Fatalities" value={kpis.totalFat} sub="across portfolio" color={T.red}/><KPI label="Safety Score" value={kpis.avgScore+'/100'} sub="avg score" color={T.navy}/>
      <KPI label="Improving" value={kpis.improving} sub="companies" color={T.green}/>
    </div>
    <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:20,marginBottom:24}}>
      <div style={ss.card}><div style={{fontSize:13,fontWeight:700,color:T.navy,marginBottom:12}}>LTIR/TRIR by Sector</div>
        <ResponsiveContainer width="100%" height={260}><BarChart data={sectorChart}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="sector" tick={{fontSize:9,fill:T.textMut}} angle={-25} textAnchor="end" height={60}/><YAxis tick={{fontSize:10,fill:T.textMut}}/><Tooltip {...tip}/><Bar dataKey="avgLtir" fill={ACCENT} radius={[4,4,0,0]} name="Avg LTIR"/><Bar dataKey="avgTrir" fill={T.navy} radius={[4,4,0,0]} name="Avg TRIR"/></BarChart></ResponsiveContainer></div>
      <div style={ss.card}><div style={{fontSize:13,fontWeight:700,color:T.navy,marginBottom:12}}>Safety Rating Distribution</div>
        <ResponsiveContainer width="100%" height={260}><PieChart><Pie data={ratingDist} dataKey="value" nameKey="name" cx="50%" cy="50%" outerRadius={90} innerRadius={45} label={({name,percent})=>`${name} ${(percent*100).toFixed(0)}%`} labelLine={false} fontSize={9}>{ratingDist.map((_,i)=><Cell key={i} fill={PIECLRS[i%PIECLRS.length]}/>)}</Pie><Tooltip {...tip}/></PieChart></ResponsiveContainer></div>
    </div>
    <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:20}}>
      <div style={ss.card}><div style={{fontSize:13,fontWeight:700,color:T.navy,marginBottom:12}}>Safety Trend (36 months)</div>
        <ResponsiveContainer width="100%" height={240}><LineChart data={TREND}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="month" tick={{fontSize:9,fill:T.textMut}} interval={5}/><YAxis tick={{fontSize:10,fill:T.textMut}}/><Tooltip {...tip}/><Line type="monotone" dataKey="avgLtir" stroke={ACCENT} strokeWidth={2} name="Avg LTIR"/><Line type="monotone" dataKey="avgTrir" stroke={T.navy} strokeWidth={2} name="Avg TRIR"/></LineChart></ResponsiveContainer></div>
      <div style={ss.card}><div style={{fontSize:13,fontWeight:700,color:T.navy,marginBottom:12}}>Safety Radar</div>
        <ResponsiveContainer width="100%" height={240}><RadarChart data={radarData} cx="50%" cy="50%" outerRadius={85}><PolarGrid stroke={T.border}/><PolarAngleAxis dataKey="dim" tick={{fontSize:9,fill:T.textSec}}/><PolarRadiusAxis tick={{fontSize:9,fill:T.textMut}} domain={[0,100]}/><Radar name="Avg" dataKey="value" stroke={ACCENT} fill="rgba(234,88,12,0.15)" strokeWidth={2}/></RadarChart></ResponsiveContainer></div>
    </div>
  </>);

  const renderScreen=()=>(<div style={ss.card}>
    <div style={{display:'flex',gap:12,flexWrap:'wrap',marginBottom:16,alignItems:'center'}}>
      <input style={ss.input} placeholder="Search companies..." value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}}/>
      <select style={ss.select} value={secF} onChange={e=>{setSecF(e.target.value);setPage(1);}}>{SECTORS.map(s=><option key={s}>{s}</option>)}</select>
      <select style={ss.select} value={regF} onChange={e=>{setRegF(e.target.value);setPage(1);}}>{REGIONS.map(s=><option key={s}>{s}</option>)}</select>
      <select style={ss.select} value={ratF} onChange={e=>{setRatF(e.target.value);setPage(1);}}>{RATINGS.map(s=><option key={s}>{s}</option>)}</select>
      <div style={{flex:1}}/><span style={{fontSize:11,color:T.textMut,fontFamily:T.mono}}>{filtered.length} companies</span>
      <button style={ss.btn} onClick={()=>csvExport(filtered,'whs_screening')}>Export CSV</button>
    </div>
    <div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr>
      <TH col="name" label="Company" sc={sortCol} sd={sortDir} fn={doSort}/><TH col="sector" label="Sector" sc={sortCol} sd={sortDir} fn={doSort}/>
      <TH col="ltir" label="LTIR" sc={sortCol} sd={sortDir} fn={doSort}/><TH col="trir" label="TRIR" sc={sortCol} sd={sortDir} fn={doSort}/>
      <TH col="fatalities" label="Fatal" sc={sortCol} sd={sortDir} fn={doSort}/><TH col="safetyScore" label="Score" sc={sortCol} sd={sortDir} fn={doSort}/>
      <TH col="incidentTrend" label="Trend" sc={sortCol} sd={sortDir} fn={doSort}/><TH col="safetyRating" label="Rating" sc={sortCol} sd={sortDir} fn={doSort}/>
    </tr></thead><tbody>{paged.map(r=>(<React.Fragment key={r.id}>
      <tr style={{cursor:'pointer',background:expanded===r.id?T.surfaceH:'transparent'}} onClick={()=>setExpanded(expanded===r.id?null:r.id)}>
        <td style={{...ss.td,fontWeight:600}}>{r.name}</td><td style={ss.td}>{r.sector}</td>
        <td style={ss.td}><span style={badge(r.ltir,[1,2,3.5])}>{r.ltir}</span></td>
        <td style={ss.td}><span style={badge(r.trir,[2,4,6])}>{r.trir}</span></td>
        <td style={{...ss.td,fontFamily:T.mono,color:r.fatalities>0?T.red:T.green,fontWeight:600}}>{r.fatalities}</td>
        <td style={ss.td}><span style={{background:r.safetyScore>=70?'rgba(22,163,74,0.12)':r.safetyScore>=50?'rgba(197,169,106,0.12)':'rgba(220,38,38,0.12)',color:r.safetyScore>=70?T.green:r.safetyScore>=50?T.gold:T.red,padding:'2px 8px',borderRadius:4,fontSize:11,fontWeight:600,fontFamily:T.mono}}>{r.safetyScore}</span></td>
        <td style={ss.td}><span style={{color:r.incidentTrend==='Improving'?T.green:r.incidentTrend==='Stable'?T.amber:T.red,fontWeight:600,fontSize:11}}>{r.incidentTrend}</span></td>
        <td style={ss.td}><span style={ratBadge(r.safetyRating)}>{r.safetyRating}</span></td>
      </tr>
      {expanded===r.id&&<tr><td colSpan={8} style={{padding:16,background:T.surfaceH,borderBottom:`1px solid ${T.border}`}}>
        <div style={{display:'grid',gridTemplateColumns:'1fr 1fr 1fr',gap:20}}>
          <div>{[['Near Misses',r.nearMisses],['Lost Days',fmt(r.lostDays)],['Employees',fmt(r.employees)],['Safety Spend ($M)',r.safetySpend],['Training (hrs/yr)',r.trainingHours],['Inspections',r.inspections],['Violations',r.violations],['ISO 45001',r.isoCompliance],['Mental Health',r.mentalHealth],['Ergonomics',r.ergonomics],['PPE Compliance',r.ppeCompliance+'%'],['Severity Rate',r.severity],['Process Events',r.processEvents],['Contractor TRIR',r.contractorRate]].map(([l,v])=>(<div key={l} style={{display:'flex',justifyContent:'space-between',padding:'3px 0',fontSize:11,borderBottom:`1px solid ${T.border}`}}><span style={{color:T.textSec}}>{l}</span><span style={{fontFamily:T.mono,fontWeight:600}}>{v}</span></div>))}</div>
          <ResponsiveContainer width="100%" height={180}><RadarChart data={[{d:'Score',v:r.safetyScore},{d:'Training',v:r.trainingHours*2},{d:'PPE',v:r.ppeCompliance},{d:'Mental',v:r.mentalHealth},{d:'Ergonomics',v:r.ergonomics},{d:'Inspections',v:Math.min(100,r.inspections/5)}]} cx="50%" cy="50%" outerRadius={65}><PolarGrid stroke={T.border}/><PolarAngleAxis dataKey="d" tick={{fontSize:8,fill:T.textSec}}/><PolarRadiusAxis tick={false} domain={[0,100]}/><Radar dataKey="v" stroke={ACCENT} fill="rgba(234,88,12,0.15)" strokeWidth={2}/></RadarChart></ResponsiveContainer>
          <ResponsiveContainer width="100%" height={180}><BarChart data={[{n:'LTIR',v:r.ltir*20},{n:'TRIR',v:r.trir*10},{n:'Near Miss',v:Math.min(100,r.nearMisses/2)},{n:'Violations',v:r.violations*4},{n:'Severity',v:Math.min(100,r.severity/2)}]} layout="vertical"><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis type="number" domain={[0,100]} tick={{fontSize:9,fill:T.textMut}}/><YAxis dataKey="n" type="category" tick={{fontSize:9,fill:T.textSec}} width={65}/><Tooltip {...tip}/><Bar dataKey="v" fill={ACCENT} radius={[0,4,4,0]}/></BarChart></ResponsiveContainer>
        </div>
      </td></tr>}
    </React.Fragment>))}</tbody></table></div>
    <div style={ss.pg}><button style={ss.btnSec} disabled={page<=1} onClick={()=>setPage(p=>p-1)}>Prev</button><span style={{fontSize:12,fontFamily:T.mono,color:T.textSec}}>{page}/{totalPages}</span><button style={ss.btnSec} disabled={page>=totalPages} onClick={()=>setPage(p=>p+1)}>Next</button></div>
  </div>);

  const renderIncident=()=>(<div style={ss.card}>
    <div style={{fontSize:13,fontWeight:700,color:T.navy,marginBottom:16}}>Incident Type Analysis</div>
    <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:20,marginBottom:20}}>
      <ResponsiveContainer width="100%" height={300}><BarChart data={INCIDENT_TYPES}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="type" tick={{fontSize:9,fill:T.textMut}} angle={-25} textAnchor="end" height={70}/><YAxis tick={{fontSize:10,fill:T.textMut}}/><Tooltip {...tip}/><Bar dataKey="count" fill={ACCENT} radius={[4,4,0,0]} name="Count"/></BarChart></ResponsiveContainer>
      <ResponsiveContainer width="100%" height={300}><PieChart><Pie data={INCIDENT_TYPES} dataKey="pct" nameKey="type" cx="50%" cy="50%" outerRadius={110} innerRadius={55} label={({type,pct})=>`${pct}%`} labelLine fontSize={9}>{INCIDENT_TYPES.map((_,i)=><Cell key={i} fill={PIECLRS[i%PIECLRS.length]}/>)}</Pie><Tooltip {...tip}/><Legend wrapperStyle={{fontSize:9}}/></PieChart></ResponsiveContainer>
    </div>
    <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:20,marginBottom:16}}>
      <ResponsiveContainer width="100%" height={240}><AreaChart data={TREND}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="month" tick={{fontSize:9,fill:T.textMut}} interval={5}/><YAxis tick={{fontSize:10,fill:T.textMut}}/><Tooltip {...tip}/><Area type="monotone" dataKey="nearMisses" stroke={T.amber} fill="rgba(217,119,6,0.08)" name="Near Misses"/><Area type="monotone" dataKey="fatalities" stroke={T.red} fill="rgba(220,38,38,0.08)" name="Fatalities"/></AreaChart></ResponsiveContainer>
      <div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr><th style={ss.th('','','')}>Type</th><th style={ss.th('','','')}>Count</th><th style={ss.th('','','')}>Share %</th></tr></thead><tbody>
        {INCIDENT_TYPES.map((r,i)=>(<tr key={i}><td style={{...ss.td,fontWeight:600}}>{r.type}</td><td style={{...ss.td,fontFamily:T.mono}}>{r.count}</td><td style={ss.td}><div style={{display:'flex',alignItems:'center',gap:6}}><div style={{background:T.border,borderRadius:4,height:12,width:80,flex:'0 0 80px'}}><div style={{background:PIECLRS[i],borderRadius:4,height:12,width:r.pct*0.8*10/10*8}}/></div><span style={{fontFamily:T.mono,fontSize:11}}>{r.pct}%</span></div></td></tr>))}
      </tbody></table></div>
    </div>
    <button style={ss.btn} onClick={()=>csvExport(INCIDENT_TYPES,'incident_analysis')}>Export CSV</button>
  </div>);

  const renderBenchmark=()=>(<div style={ss.card}>
    <div style={{fontSize:13,fontWeight:700,color:T.navy,marginBottom:16}}>Industry Benchmarking</div>
    <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:20,marginBottom:20}}>
      <ResponsiveContainer width="100%" height={300}><BarChart data={BENCHMARKS}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="sector" tick={{fontSize:9,fill:T.textMut}} angle={-20} textAnchor="end" height={50}/><YAxis tick={{fontSize:10,fill:T.textMut}}/><Tooltip {...tip}/><Legend/><Bar dataKey="ltir" fill={ACCENT} radius={[4,4,0,0]} name="LTIR Benchmark"/><Bar dataKey="trir" fill={T.navy} radius={[4,4,0,0]} name="TRIR Benchmark"/></BarChart></ResponsiveContainer>
      <ResponsiveContainer width="100%" height={300}><LineChart data={BENCHMARKS}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="sector" tick={{fontSize:9,fill:T.textMut}} angle={-20} textAnchor="end" height={50}/><YAxis tick={{fontSize:10,fill:T.textMut}}/><Tooltip {...tip}/><Line type="monotone" dataKey="fatRate" stroke={T.red} strokeWidth={2} dot={{fill:T.red,r:4}} name="Fatality Rate"/></LineChart></ResponsiveContainer>
    </div>
    <div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr><th style={ss.th('','','')}>Sector</th><th style={ss.th('','','')}>LTIR Benchmark</th><th style={ss.th('','','')}>TRIR Benchmark</th><th style={ss.th('','','')}>Fatality Rate</th></tr></thead><tbody>
      {BENCHMARKS.map((r,i)=>(<tr key={i}><td style={{...ss.td,fontWeight:600}}>{r.sector}</td><td style={{...ss.td,fontFamily:T.mono}}>{r.ltir}</td><td style={{...ss.td,fontFamily:T.mono}}>{r.trir}</td><td style={{...ss.td,fontFamily:T.mono,color:r.fatRate>0.008?T.red:r.fatRate>0.005?T.amber:T.green}}>{r.fatRate}</td></tr>))}
    </tbody></table></div>
    <div style={{marginTop:12}}><button style={ss.btn} onClick={()=>csvExport(BENCHMARKS,'safety_benchmarks')}>Export CSV</button></div>
  </div>);

  return(<div style={ss.wrap}>
    <div style={ss.header}>Workplace Health & Safety Intelligence</div>
    <div style={ss.sub}>LTIR, TRIR, fatality rates, safety scoring across 80 companies</div>
    <div style={ss.tabs}>{TABS.map((t,i)=><button key={t} style={ss.tab(tab===i)} onClick={()=>setTab(i)}>{t}</button>)}</div>
    {tab===0&&renderDash()}{tab===1&&renderScreen()}{tab===2&&renderIncident()}{tab===3&&renderBenchmark()}
  </div>);
}