import React,{useState,useMemo,useCallback} from 'react';
import {BarChart,Bar,XAxis,YAxis,CartesianGrid,Tooltip,ResponsiveContainer,PieChart,Pie,Cell,AreaChart,Area,ScatterChart,Scatter,ZAxis,Legend,RadarChart,Radar,PolarGrid,PolarAngleAxis,PolarRadiusAxis,LineChart,Line} from 'recharts';
const T={bg:'#f6f4f0',surface:'#ffffff',surfaceH:'#f0ede7',border:'#e5e0d8',borderL:'#d5cfc5',navy:'#1b3a5c',navyL:'#2c5a8c',gold:'#c5a96a',goldL:'#d4be8a',sage:'#5a8a6a',sageL:'#7ba67d',teal:'#5a8a6a',text:'#1b3a5c',textSec:'#5c6b7e',textMut:'#9aa3ae',red:'#dc2626',green:'#16a34a',amber:'#d97706',font:"'DM Sans','SF Pro Display',system-ui,-apple-system,sans-serif",mono:"'JetBrains Mono','SF Mono','Fira Code',monospace"};
const sr=(s)=>{let x=Math.sin(s+1)*10000;return x-Math.floor(x);};const ACCENT='#dc2626';const tip={contentStyle:{background:T.surface,border:`1px solid ${T.border}`,borderRadius:8,fontSize:11,fontFamily:T.font},labelStyle:{color:T.textSec,fontFamily:T.mono,fontSize:10}};
const TABS=['Risk Overview','Peril Analysis','Asset Exposure','Scenario Projections'];const SECTORS=['All','Real Estate','Energy','Agriculture','Infrastructure','Insurance','Tourism','Manufacturing','Mining','Utilities'];const PAGE_SIZE=15;const PIECLRS=[T.red,'#b91c1c',T.amber,T.gold,T.green,T.navy,T.navyL,'#8b5cf6','#ec4899'];
const ASSETS=(()=>{const names=['NYC Financial District','London Docklands','Tokyo Waterfront','Miami Beach Complex','Shanghai Pudong','Mumbai Coastal','Jakarta Industrial','Houston Refinery Row','New Orleans Port','Rotterdam Europoort','San Francisco Bay','Hong Kong Central','Singapore CBD','Bangkok Riverside','Venice Historic','Manila Bay Zone','Dhaka Lowlands','Lagos Victoria Island','Karachi Port','Sydney Harbour','Dubai Marina','Rio Copacabana','Cape Town V&A','Istanbul Bosphorus','Kuala Lumpur','Chennai Industrial','Colombo Port','Maldives Resorts','Fiji Tourism Zone','Tuvalu Infrastructure','Amsterdam Canal','Copenhagen Harbour','Venice Lido','Naples Coastal','Barcelona Waterfront','Marseille Port','Lisbon Waterfront','Athens Piraeus','Alexandria Harbor','Casablanca Port','Dakar Industrial','Mombasa Port','Dar es Salaam','Maputo Harbor','Durban Coast','Accra Tema Port','Abidjan Port','Luanda Bay','Beira Corridor','Freetown Coast'];
  const secs=['Real Estate','Real Estate','Real Estate','Real Estate','Real Estate','Real Estate','Manufacturing','Energy','Infrastructure','Infrastructure','Real Estate','Real Estate','Real Estate','Real Estate','Tourism','Real Estate','Agriculture','Real Estate','Infrastructure','Real Estate','Real Estate','Tourism','Tourism','Real Estate','Real Estate','Manufacturing','Infrastructure','Tourism','Tourism','Infrastructure','Real Estate','Infrastructure','Tourism','Real Estate','Tourism','Infrastructure','Tourism','Infrastructure','Infrastructure','Infrastructure','Manufacturing','Infrastructure','Infrastructure','Infrastructure','Real Estate','Infrastructure','Infrastructure','Energy','Infrastructure','Infrastructure'];
  return names.map((n,i)=>({id:i+1,name:n,sector:secs[i],compositeRisk:Math.round(10+sr(i*7)*85),floodRisk:Math.round(sr(i*11)*100),heatStress:Math.round(sr(i*13)*100),cycloneRisk:Math.round(sr(i*17)*90),seaLevelRise:Math.round(sr(i*19)*100),wildfire:Math.round(sr(i*23)*80),drought:Math.round(sr(i*29)*90),precipitation:Math.round(sr(i*31)*80),assetValue:Math.round(50+sr(i*37)*4950),annualLoss:+(sr(i*41)*8+0.1).toFixed(1),insuranceCost:+(sr(i*43)*12+1).toFixed(1),adaptationCost:Math.round(sr(i*47)*200),resilience:Math.round(10+sr(i*53)*80),exposure:Math.round(sr(i*59)*100),vulnerability:Math.round(sr(i*61)*100),rcp26Impact:+(sr(i*67)*5).toFixed(1),rcp85Impact:+(sr(i*71)*15).toFixed(1),riskLevel:sr(i*7)<0.15?'Critical':sr(i*7)<0.35?'High':sr(i*7)<0.55?'Elevated':sr(i*7)<0.8?'Moderate':'Low'}));})();
const PERIL=[{peril:'Coastal Flooding',rcp26:22,rcp45:35,rcp85:62},{peril:'Riverine Flooding',rcp26:18,rcp45:28,rcp85:45},{peril:'Heat Stress',rcp26:25,rcp45:42,rcp85:72},{peril:'Tropical Cyclone',rcp26:15,rcp45:25,rcp85:48},{peril:'Sea Level Rise',rcp26:20,rcp45:38,rcp85:68},{peril:'Wildfire',rcp26:12,rcp45:22,rcp85:42},{peril:'Drought',rcp26:18,rcp45:32,rcp85:55},{peril:'Precipitation',rcp26:10,rcp45:18,rcp85:35}];
const TREND=Array.from({length:10},(_,i)=>({year:2025+i*3,rcp26Loss:+(1.5+i*0.2+sr(i*7)*0.3).toFixed(1),rcp45Loss:+(2+i*0.5+sr(i*11)*0.4).toFixed(1),rcp85Loss:+(2.5+i*1+sr(i*13)*0.6).toFixed(1)}));

export default function ClimatePhysicalRiskPage(){
  const[tab,setTab]=useState(0);const[search,setSearch]=useState('');const[sectorF,setSectorF]=useState('All');const[sortCol,setSortCol]=useState('compositeRisk');const[sortDir,setSortDir]=useState('desc');const[page,setPage]=useState(1);const[selected,setSelected]=useState(null);
  const filtered=useMemo(()=>{let d=[...ASSETS];if(search)d=d.filter(r=>r.name.toLowerCase().includes(search.toLowerCase()));if(sectorF!=='All')d=d.filter(r=>r.sector===sectorF);d.sort((a,b)=>sortDir==='asc'?(a[sortCol]>b[sortCol]?1:-1):(a[sortCol]<b[sortCol]?1:-1));return d;},[search,sectorF,sortCol,sortDir]);
  const paged=useMemo(()=>filtered.slice((page-1)*PAGE_SIZE,page*PAGE_SIZE),[filtered,page]);const totalPages=Math.ceil(filtered.length/PAGE_SIZE);
  const doSort=(col)=>{if(sortCol===col)setSortDir(d=>d==='asc'?'desc':'asc');else{setSortCol(col);setSortDir('desc');}setPage(1);};
  const stats=useMemo(()=>({count:filtered.length,avgRisk:(filtered.reduce((s,r)=>s+r.compositeRisk,0)/filtered.length||0).toFixed(0),critical:filtered.filter(r=>r.riskLevel==='Critical'||r.riskLevel==='High').length,totalValue:filtered.reduce((s,r)=>s+r.assetValue,0),avgLoss:(filtered.reduce((s,r)=>s+r.annualLoss,0)/filtered.length||0).toFixed(1)}),[filtered]);
  const riskDist=useMemo(()=>{const order=['Critical','High','Elevated','Moderate','Low'];const m={};filtered.forEach(r=>{m[r.riskLevel]=(m[r.riskLevel]||0)+1;});return order.filter(k=>m[k]).map(k=>({name:k,value:m[k]}));},[filtered]);
  const sectorRisk=useMemo(()=>{const m={};ASSETS.forEach(r=>{if(!m[r.sector])m[r.sector]={s:r.sector,risk:0,n:0};m[r.sector].risk+=r.compositeRisk;m[r.sector].n++;});return Object.values(m).map(s=>({sector:s.s,risk:Math.round(s.risk/s.n)})).sort((a,b)=>b.risk-a.risk);},[]);
  const exportCSV=useCallback((data,fn)=>{if(!data.length)return;const keys=Object.keys(data[0]);const csv=[keys.join(','),...data.map(r=>keys.map(k=>`"${r[k]}"`).join(','))].join('\n');const blob=new Blob([csv],{type:'text/csv'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=fn;a.click();URL.revokeObjectURL(url);},[]);
  const si=(col,cur,dir)=>cur===col?(dir==='asc'?' \u25B2':' \u25BC'):' \u25CB';
  const thS={padding:'8px 10px',fontSize:11,fontFamily:T.mono,color:T.textSec,cursor:'pointer',borderBottom:`1px solid ${T.border}`,whiteSpace:'nowrap',userSelect:'none',textAlign:'left',background:T.surfaceH};const tdS={padding:'7px 10px',fontSize:12,fontFamily:T.font,borderBottom:`1px solid ${T.border}`,color:T.text};const inpS={padding:'6px 12px',border:`1px solid ${T.border}`,borderRadius:6,fontSize:12,fontFamily:T.font,background:T.surface,color:T.text,outline:'none',width:220};const selS={padding:'6px 10px',border:`1px solid ${T.border}`,borderRadius:6,fontSize:11,fontFamily:T.font,background:T.surface,color:T.text};const btnS=(a)=>({padding:'6px 16px',border:`1px solid ${a?ACCENT:T.border}`,borderRadius:6,fontSize:12,fontFamily:T.font,background:a?ACCENT:T.surface,color:a?'#fff':T.text,cursor:'pointer',fontWeight:a?600:400});const pgB={padding:'4px 10px',border:`1px solid ${T.border}`,borderRadius:4,fontSize:11,cursor:'pointer',background:T.surface,color:T.text};const cS={background:T.surface,border:`1px solid ${T.border}`,borderRadius:10,padding:16};
  const bdg=(val,th)=>{const[lo,mid,hi]=th;const bg=val>=hi?'rgba(220,38,38,0.12)':val>=mid?'rgba(217,119,6,0.12)':val>=lo?'rgba(197,169,106,0.12)':'rgba(22,163,74,0.12)';const c=val>=hi?T.red:val>=mid?T.amber:val>=lo?T.gold:T.green;return{background:bg,color:c,padding:'2px 8px',borderRadius:4,fontSize:11,fontWeight:600,fontFamily:T.mono};};
  const rBdg=(r)=>{const m={Critical:{bg:'rgba(220,38,38,0.12)',c:T.red},High:{bg:'rgba(217,119,6,0.12)',c:T.amber},Elevated:{bg:'rgba(197,169,106,0.15)',c:T.gold},Moderate:{bg:'rgba(22,163,74,0.12)',c:T.green},Low:{bg:'rgba(22,163,74,0.08)',c:'#15803d'}};const s=m[r]||m.Moderate;return{background:s.bg,color:s.c,padding:'2px 8px',borderRadius:4,fontSize:11,fontWeight:600};};
  const kpi=(l,v)=>(<div style={{background:T.surface,border:`1px solid ${T.border}`,borderRadius:10,padding:'14px 18px',flex:1,minWidth:150}}><div style={{fontSize:10,color:T.textMut,fontFamily:T.mono,textTransform:'uppercase',letterSpacing:1}}>{l}</div><div style={{fontSize:24,fontWeight:700,color:T.navy,marginTop:4}}>{v}</div></div>);
  const SidePanel=({item,onClose})=>{if(!item)return null;const rd=[{axis:'Flood',v:item.floodRisk},{axis:'Heat',v:item.heatStress},{axis:'Cyclone',v:item.cycloneRisk},{axis:'Sea Level',v:item.seaLevelRise},{axis:'Wildfire',v:item.wildfire},{axis:'Drought',v:item.drought}];return(<div style={{position:'fixed',top:0,right:0,width:440,height:'100vh',background:T.surface,borderLeft:`2px solid ${ACCENT}`,zIndex:1000,overflowY:'auto',boxShadow:'-4px 0 24px rgba(0,0,0,0.10)'}}><div style={{padding:'20px 24px',borderBottom:`1px solid ${T.border}`,display:'flex',justifyContent:'space-between',alignItems:'center'}}><div style={{fontSize:16,fontWeight:700,color:T.navy}}>{item.name}</div><button onClick={onClose} style={{background:'none',border:'none',fontSize:20,cursor:'pointer',color:T.textMut}}>x</button></div><div style={{padding:'16px 24px'}}><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:10,marginBottom:16}}>{[['Composite Risk',item.compositeRisk+'/100'],['Flood',item.floodRisk],['Heat Stress',item.heatStress],['Cyclone',item.cycloneRisk],['Sea Level',item.seaLevelRise],['Wildfire',item.wildfire],['Asset Value','$'+item.assetValue+'M'],['Annual Loss',item.annualLoss+'%'],['Insurance',item.insuranceCost+'%'],['Adaptation','$'+item.adaptationCost+'M'],['Resilience',item.resilience+'/100'],['RCP 2.6',item.rcp26Impact+'%'],['RCP 8.5',item.rcp85Impact+'%']].map(([k,v],i)=>(<div key={i} style={{background:T.surfaceH,borderRadius:6,padding:'8px 12px'}}><div style={{fontSize:10,color:T.textMut,fontFamily:T.mono}}>{k}</div><div style={{fontSize:14,fontWeight:600,color:T.navy,marginTop:2}}>{v}</div></div>))}</div><div style={{height:220}}><div style={{fontSize:11,fontFamily:T.mono,color:T.textSec,marginBottom:6}}>PERIL RADAR</div><ResponsiveContainer width="100%" height={200}><RadarChart data={rd}><PolarGrid stroke={T.border}/><PolarAngleAxis dataKey="axis" tick={{fontSize:9,fill:T.textSec}}/><PolarRadiusAxis angle={30} domain={[0,100]} tick={{fontSize:9}}/><Radar dataKey="v" stroke={ACCENT} fill={ACCENT} fillOpacity={0.15}/></RadarChart></ResponsiveContainer></div></div></div>);};

  const renderOverview=()=>(<div>
    <div style={{display:'flex',gap:12,marginBottom:20,flexWrap:'wrap'}}>{kpi('Assets',stats.count)}{kpi('Avg Risk',stats.avgRisk+'/100')}{kpi('Critical/High',stats.critical)}{kpi('Total Value','$'+(stats.totalValue/1000).toFixed(0)+'B')}{kpi('Avg Annual Loss',stats.avgLoss+'%')}</div>
    <div style={{display:'flex',gap:12,marginBottom:16,flexWrap:'wrap',alignItems:'center'}}><input value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}} placeholder="Search assets..." style={inpS}/><select value={sectorF} onChange={e=>{setSectorF(e.target.value);setPage(1);}} style={selS}>{SECTORS.map(s=><option key={s}>{s}</option>)}</select><button onClick={()=>exportCSV(filtered,'physical_risk.csv')} style={btnS(false)}>Export CSV</button></div>
    <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16,marginBottom:20}}>
      <div style={cS}><div style={{fontSize:11,fontFamily:T.mono,color:T.textSec,marginBottom:8}}>RISK DISTRIBUTION</div><ResponsiveContainer width="100%" height={220}><PieChart><Pie data={riskDist} cx="50%" cy="50%" outerRadius={80} dataKey="value" label={({name,percent})=>`${name} ${(percent*100).toFixed(0)}%`}>{riskDist.map((_,i)=><Cell key={i} fill={PIECLRS[i%PIECLRS.length]}/>)}</Pie><Tooltip {...tip}/></PieChart></ResponsiveContainer></div>
      <div style={cS}><div style={{fontSize:11,fontFamily:T.mono,color:T.textSec,marginBottom:8}}>PERIL EXPOSURE BY SCENARIO</div><ResponsiveContainer width="100%" height={220}><BarChart data={PERIL}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="peril" tick={{fontSize:8}} angle={-15}/><YAxis tick={{fontSize:10}}/><Tooltip {...tip}/><Bar dataKey="rcp26" fill={T.green} name="RCP 2.6" radius={[2,2,0,0]}/><Bar dataKey="rcp45" fill={T.amber} name="RCP 4.5" radius={[2,2,0,0]}/><Bar dataKey="rcp85" fill={T.red} name="RCP 8.5" radius={[2,2,0,0]}/><Legend/></BarChart></ResponsiveContainer></div>
    </div>
    <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16,marginBottom:20}}>
      <div style={cS}><div style={{fontSize:11,fontFamily:T.mono,color:T.textSec,marginBottom:8}}>SECTOR RISK COMPARISON</div><ResponsiveContainer width="100%" height={240}><BarChart data={sectorRisk}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="sector" tick={{fontSize:8}} angle={-15}/><YAxis tick={{fontSize:10}}/><Tooltip {...tip}/><Bar dataKey="risk" fill={ACCENT} name="Avg Risk" radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></div>
      <div style={cS}><div style={{fontSize:11,fontFamily:T.mono,color:T.textSec,marginBottom:8}}>EXPOSURE vs VULNERABILITY</div><ResponsiveContainer width="100%" height={240}><ScatterChart><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="x" name="Exposure" tick={{fontSize:10}}/><YAxis dataKey="y" name="Vulnerability" tick={{fontSize:10}}/><ZAxis dataKey="z" range={[20,200]}/><Tooltip {...tip}/><Scatter data={filtered.map(r=>({name:r.name,x:r.exposure,y:r.vulnerability,z:r.assetValue/25}))} fill={ACCENT} fillOpacity={0.5}/></ScatterChart></ResponsiveContainer></div>
    </div>
    <div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr>{[['name','Asset'],['sector','Sector'],['compositeRisk','Risk'],['floodRisk','Flood'],['heatStress','Heat'],['seaLevelRise','Sea Lvl'],['assetValue','Value $M'],['annualLoss','Loss %'],['riskLevel','Level']].map(([col,label])=>(<th key={col} onClick={()=>doSort(col)} style={thS}>{label}{si(col,sortCol,sortDir)}</th>))}</tr></thead><tbody>{paged.map(r=>(<tr key={r.id} onClick={()=>setSelected(r)} style={{cursor:'pointer',background:selected?.id===r.id?T.surfaceH:'transparent'}}><td style={{...tdS,fontWeight:600,maxWidth:180,overflow:'hidden',textOverflow:'ellipsis',whiteSpace:'nowrap'}}>{r.name}</td><td style={tdS}>{r.sector}</td><td style={tdS}><span style={bdg(r.compositeRisk,[30,55,75])}>{r.compositeRisk}</span></td><td style={tdS}><span style={bdg(r.floodRisk,[25,50,75])}>{r.floodRisk}</span></td><td style={tdS}><span style={bdg(r.heatStress,[25,50,75])}>{r.heatStress}</span></td><td style={tdS}><span style={bdg(r.seaLevelRise,[25,50,75])}>{r.seaLevelRise}</span></td><td style={tdS}>${r.assetValue}M</td><td style={tdS}>{r.annualLoss}%</td><td style={tdS}><span style={rBdg(r.riskLevel)}>{r.riskLevel}</span></td></tr>))}</tbody></table>
    <div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginTop:12}}><span style={{fontSize:11,color:T.textMut,fontFamily:T.mono}}>{filtered.length} assets | Page {page}/{totalPages}</span><div style={{display:'flex',gap:4}}><button disabled={page<=1} onClick={()=>setPage(p=>p-1)} style={pgB}>Prev</button><button disabled={page>=totalPages} onClick={()=>setPage(p=>p+1)} style={pgB}>Next</button></div></div></div>
  </div>);

  const renderPeril=()=>(<div><div style={cS}><div style={{fontSize:11,fontFamily:T.mono,color:T.textSec,marginBottom:8}}>PERIL COMPARISON ACROSS SCENARIOS</div><ResponsiveContainer width="100%" height={300}><BarChart data={PERIL}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="peril" tick={{fontSize:9}}/><YAxis tick={{fontSize:10}}/><Tooltip {...tip}/><Bar dataKey="rcp26" fill={T.green} name="RCP 2.6" radius={[2,2,0,0]}/><Bar dataKey="rcp45" fill={T.amber} name="RCP 4.5" radius={[2,2,0,0]}/><Bar dataKey="rcp85" fill={T.red} name="RCP 8.5" radius={[2,2,0,0]}/><Legend/></BarChart></ResponsiveContainer></div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16,marginTop:16}}><div style={cS}><div style={{fontSize:11,fontFamily:T.mono,color:T.textSec,marginBottom:8}}>FLOOD vs SEA LEVEL RISE</div><ResponsiveContainer width="100%" height={240}><ScatterChart><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="x" name="Flood" tick={{fontSize:10}}/><YAxis dataKey="y" name="Sea Level" tick={{fontSize:10}}/><Tooltip {...tip}/><Scatter data={ASSETS.map(r=>({name:r.name,x:r.floodRisk,y:r.seaLevelRise}))} fill={ACCENT} fillOpacity={0.4}/></ScatterChart></ResponsiveContainer></div><div style={cS}><div style={{fontSize:11,fontFamily:T.mono,color:T.textSec,marginBottom:8}}>HEAT STRESS vs WILDFIRE</div><ResponsiveContainer width="100%" height={240}><ScatterChart><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="x" name="Heat" tick={{fontSize:10}}/><YAxis dataKey="y" name="Wildfire" tick={{fontSize:10}}/><Tooltip {...tip}/><Scatter data={ASSETS.map(r=>({name:r.name,x:r.heatStress,y:r.wildfire}))} fill={T.amber} fillOpacity={0.4}/></ScatterChart></ResponsiveContainer></div></div></div>);

  const renderExposure=()=>(<div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16,marginBottom:20}}><div style={cS}><div style={{fontSize:11,fontFamily:T.mono,color:T.textSec,marginBottom:8}}>ASSET VALUE AT RISK</div><ResponsiveContainer width="100%" height={300}><BarChart data={[...ASSETS].sort((a,b)=>b.assetValue*b.annualLoss/100-a.assetValue*a.annualLoss/100).slice(0,12)} layout="vertical"><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis type="number" tick={{fontSize:10}}/><YAxis dataKey="name" type="category" tick={{fontSize:8}} width={130}/><Tooltip {...tip}/><Bar dataKey="annualLoss" fill={T.red} name="Annual Loss %" radius={[0,4,4,0]}/></BarChart></ResponsiveContainer></div><div style={cS}><div style={{fontSize:11,fontFamily:T.mono,color:T.textSec,marginBottom:8}}>ADAPTATION COST vs RESILIENCE</div><ResponsiveContainer width="100%" height={300}><ScatterChart><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="x" name="Adaptation $M" tick={{fontSize:10}}/><YAxis dataKey="y" name="Resilience" tick={{fontSize:10}}/><Tooltip {...tip}/><Scatter data={ASSETS.map(r=>({name:r.name,x:r.adaptationCost,y:r.resilience}))} fill={T.green} fillOpacity={0.5}/></ScatterChart></ResponsiveContainer></div></div><div style={cS}><div style={{fontSize:11,fontFamily:T.mono,color:T.textSec,marginBottom:8}}>INSURANCE COST TREND</div><ResponsiveContainer width="100%" height={240}><BarChart data={SECTORS.filter(s=>s!=='All').map(sec=>{const a=ASSETS.filter(r=>r.sector===sec);return{sector:sec,insurance:+(a.reduce((s,r)=>s+r.insuranceCost,0)/a.length).toFixed(1)};})}>
    <CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="sector" tick={{fontSize:8}} angle={-15}/><YAxis tick={{fontSize:10}}/><Tooltip {...tip}/><Bar dataKey="insurance" fill={T.gold} name="Avg Insurance %" radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></div></div>);

  const renderProjections=()=>(<div><div style={cS}><div style={{fontSize:11,fontFamily:T.mono,color:T.textSec,marginBottom:8}}>ANNUAL LOSS PROJECTIONS BY SCENARIO</div><ResponsiveContainer width="100%" height={300}><AreaChart data={TREND}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="year" tick={{fontSize:10}}/><YAxis tick={{fontSize:10}}/><Tooltip {...tip}/><Area type="monotone" dataKey="rcp26Loss" stroke={T.green} fill={T.green} fillOpacity={0.1} name="RCP 2.6"/><Area type="monotone" dataKey="rcp45Loss" stroke={T.amber} fill={T.amber} fillOpacity={0.08} name="RCP 4.5"/><Area type="monotone" dataKey="rcp85Loss" stroke={T.red} fill={T.red} fillOpacity={0.08} name="RCP 8.5"/><Legend/></AreaChart></ResponsiveContainer></div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16,marginTop:16}}><div style={cS}><div style={{fontSize:11,fontFamily:T.mono,color:T.textSec,marginBottom:8}}>RCP 2.6 vs RCP 8.5 IMPACT</div><ResponsiveContainer width="100%" height={240}><ScatterChart><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="x" name="RCP 2.6 %" tick={{fontSize:10}}/><YAxis dataKey="y" name="RCP 8.5 %" tick={{fontSize:10}}/><Tooltip {...tip}/><Scatter data={ASSETS.map(r=>({name:r.name,x:r.rcp26Impact,y:r.rcp85Impact}))} fill={T.navy} fillOpacity={0.5}/></ScatterChart></ResponsiveContainer></div><div style={cS}><div style={{fontSize:11,fontFamily:T.mono,color:T.textSec,marginBottom:8}}>RESILIENCE DISTRIBUTION</div><ResponsiveContainer width="100%" height={240}><BarChart data={[{range:'0-20',count:ASSETS.filter(r=>r.resilience<20).length},{range:'20-40',count:ASSETS.filter(r=>r.resilience>=20&&r.resilience<40).length},{range:'40-60',count:ASSETS.filter(r=>r.resilience>=40&&r.resilience<60).length},{range:'60-80',count:ASSETS.filter(r=>r.resilience>=60&&r.resilience<80).length},{range:'80-100',count:ASSETS.filter(r=>r.resilience>=80).length}]}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="range" tick={{fontSize:10}}/><YAxis tick={{fontSize:10}}/><Tooltip {...tip}/><Bar dataKey="count" fill={ACCENT} name="Assets" radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></div></div></div>);

  return(<div style={{fontFamily:T.font,background:T.bg,minHeight:'100vh',padding:'24px 32px',color:T.text}}>
    <div style={{marginBottom:20}}><div style={{fontSize:22,fontWeight:700,color:T.navy}}>Climate Physical Risk Assessment</div><div style={{fontSize:12,color:T.textSec,marginTop:4,fontFamily:T.mono}}>Multi-peril analysis, RCP scenarios, asset exposure across {ASSETS.length} locations</div></div>
    <div style={{display:'flex',gap:4,marginBottom:20,borderBottom:`2px solid ${T.border}`}}>{TABS.map((t,i)=>(<button key={t} onClick={()=>setTab(i)} style={{...btnS(tab===i),borderRadius:'6px 6px 0 0',borderBottom:tab===i?`2px solid ${ACCENT}`:'2px solid transparent'}}>{t}</button>))}</div>
    {tab===0&&renderOverview()}{tab===1&&renderPeril()}{tab===2&&renderExposure()}{tab===3&&renderProjections()}
    <SidePanel item={selected} onClose={()=>setSelected(null)}/>
  </div>);
}
