import React,{useState,useMemo,useCallback} from 'react';
import {BarChart,Bar,LineChart,Line,AreaChart,Area,PieChart,Pie,Cell,ScatterChart,Scatter,XAxis,YAxis,CartesianGrid,Tooltip,ResponsiveContainer,Legend,RadarChart,Radar,PolarGrid,PolarAngleAxis,PolarRadiusAxis} from 'recharts';

const T={bg:'#f6f4f0',surface:'#ffffff',surfaceH:'#f0ede7',border:'#e5e0d8',borderL:'#d5cfc5',navy:'#1b3a5c',navyL:'#2c5a8c',gold:'#c5a96a',goldL:'#d4be8a',sage:'#5a8a6a',sageL:'#7ba67d',teal:'#5a8a6a',text:'#1b3a5c',textSec:'#5c6b7e',textMut:'#9aa3ae',red:'#dc2626',green:'#16a34a',amber:'#d97706',font:"'DM Sans','SF Pro Display',system-ui,-apple-system,sans-serif",mono:"'JetBrains Mono','SF Mono','Fira Code',monospace"};
const sr=(s)=>{let x=Math.sin(s+1)*10000;return x-Math.floor(x);};
const ACCENT='#7c3aed';const tip={contentStyle:{background:T.surface,border:`1px solid ${T.border}`,borderRadius:8,fontSize:11,fontFamily:T.font},labelStyle:{color:T.textSec,fontFamily:T.mono,fontSize:10}};
const COLORS=[T.navy,T.gold,T.sage,T.red,T.amber,T.green,T.navyL,T.goldL,T.sageL,'#8b5cf6','#ec4899','#06b6d4'];
const fmt=v=>typeof v==='number'?v>=1e9?(v/1e9).toFixed(1)+'B':v>=1e6?(v/1e6).toFixed(1)+'M':v>=1e3?(v/1e3).toFixed(1)+'K':v.toFixed(1):v;
const TABS=['Board Overview','Diversity Analytics','Skills Matrix','Independence'];
const SECTORS=['All','Technology','Financials','Healthcare','Energy','Consumer','Industrials','Materials','Utilities','Real Estate'];const PAGE=12;

const COS=Array.from({length:80},(_,i)=>{
  const names=['Apple','Microsoft','Alphabet','Amazon','NVIDIA','Meta','Tesla','Berkshire','JPMorgan','Visa','UnitedHealth','Johnson & Johnson','Walmart','Procter & Gamble','Mastercard','Bank of America','Chevron','Home Depot','Coca-Cola','Pfizer','Abbott','Eli Lilly','PepsiCo','Costco','Broadcom','Thermo Fisher','Cisco','Merck','Accenture','McDonald\'s','Danaher','Adobe','Linde','Salesforce','AMD','Qualcomm','Intel','Goldman Sachs','Caterpillar','Amgen','Morgan Stanley','Honeywell','Lockheed Martin','Deere','IBM','GE','RTX Corp','Medtronic','AstraZeneca','Shell','BP','TotalEnergies','Nestle','Roche','Novartis','SAP','Siemens','LVMH','Unilever','HSBC','BHP','Rio Tinto','Sony','Toyota','Samsung','Infosys','Reliance','TSMC','Novo Nordisk','Diageo','AbbVie','Starbucks','Netflix','Booking','Intuit','Uber','Airbnb','PayPal','ServiceNow','CrowdStrike'];
  const secs=['Technology','Technology','Technology','Technology','Technology','Technology','Technology','Financials','Financials','Financials','Healthcare','Healthcare','Consumer','Consumer','Financials','Financials','Energy','Consumer','Consumer','Healthcare','Healthcare','Healthcare','Consumer','Consumer','Technology','Healthcare','Technology','Healthcare','Technology','Consumer','Healthcare','Technology','Materials','Technology','Technology','Technology','Technology','Financials','Industrials','Healthcare','Financials','Industrials','Industrials','Industrials','Technology','Industrials','Industrials','Healthcare','Healthcare','Energy','Energy','Energy','Consumer','Healthcare','Healthcare','Technology','Industrials','Consumer','Consumer','Financials','Materials','Materials','Technology','Industrials','Technology','Technology','Energy','Technology','Healthcare','Consumer','Healthcare','Consumer','Technology','Consumer','Technology','Technology','Technology','Financials','Technology','Technology'];
  const boardSize=Math.round(8+sr(i*7)*7);const femPct=Math.round(15+sr(i*11)*35);const indPct=Math.round(50+sr(i*13)*45);const avgAge=Math.round(52+sr(i*17)*16);const avgTenure=+(sr(i*19)*12+2).toFixed(1);
  const skills=['Finance','Technology','Industry','Legal','ESG','International','Marketing','Operations','Risk','HR'];
  const skillMatrix=skills.map(s=>({skill:s,count:Math.round(sr(i*23+skills.indexOf(s)*7)*boardSize*0.8+1)}));
  const ethnicDiv=Math.round(sr(i*29)*40+10);const intlPct=Math.round(sr(i*31)*50+10);const ceoChairSep=sr(i*37)>0.4?'Yes':'No';const leadIndDir=sr(i*41)>0.3?'Yes':'No';
  const overboarding=Math.round(sr(i*43)*3);const refreshRate=+(sr(i*47)*20+5).toFixed(1);const esqExpertise=Math.round(sr(i*49)*boardSize*0.6);
  const yearly=Array.from({length:5},(_,y)=>({year:2020+y,femPct:Math.round(femPct-5+y*2+sr(i*100+y)*3),indPct:Math.round(indPct-3+y*1.5+sr(i*100+y*3)*2),avgAge:Math.round(avgAge-y*0.5+sr(i*100+y*7)*2),boardSize:boardSize+Math.round(sr(i*100+y*11)*2-1)}));
  return{id:i+1,name:names[i],sector:secs[i],boardSize,femalePct:femPct,independentPct:indPct,avgAge,avgTenure,ethnicDiversity:ethnicDiv,intlPct,ceoChairSep,leadIndDir,overboarding,refreshRate,esgExpertise:esqExpertise,skillMatrix,meetingsPerYear:Math.round(sr(i*51)*10+6),attendanceRate:Math.round(sr(i*53)*15+85),committeesAvg:+(sr(i*57)*3+2).toFixed(1),diversityScore:Math.round(femPct*0.3+ethnicDiv*0.3+intlPct*0.2+indPct*0.2),governanceRating:['A+','A','A-','B+','B','B-','C+'][Math.floor(sr(i*59)*7)],yearly};
});

export default function BoardCompositionPage(){
  const[tab,setTab]=useState(0);const[search,setSearch]=useState('');const[sectorF,setSectorF]=useState('All');const[sortCol,setSortCol]=useState('diversityScore');const[sortDir,setSortDir]=useState('desc');const[page,setPage]=useState(1);const[selected,setSelected]=useState(null);

  const filtered=useMemo(()=>{let d=[...COS];if(search)d=d.filter(r=>r.name.toLowerCase().includes(search.toLowerCase()));if(sectorF!=='All')d=d.filter(r=>r.sector===sectorF);d.sort((a,b)=>sortDir==='asc'?(a[sortCol]>b[sortCol]?1:-1):(a[sortCol]<b[sortCol]?1:-1));return d;},[search,sectorF,sortCol,sortDir]);
  const paged=useMemo(()=>filtered.slice((page-1)*PAGE,page*PAGE),[filtered,page]);const totalPages=Math.ceil(filtered.length/PAGE);
  const doSort=col=>{if(sortCol===col)setSortDir(d=>d==='asc'?'desc':'asc');else{setSortCol(col);setSortDir('desc');}setPage(1);};

  const stats=useMemo(()=>({count:filtered.length,avgFem:(filtered.reduce((s,r)=>s+r.femalePct,0)/filtered.length||0).toFixed(0),avgInd:(filtered.reduce((s,r)=>s+r.independentPct,0)/filtered.length||0).toFixed(0),avgAge:(filtered.reduce((s,r)=>s+r.avgAge,0)/filtered.length||0).toFixed(0),avgDiv:(filtered.reduce((s,r)=>s+r.diversityScore,0)/filtered.length||0).toFixed(0),sepChair:filtered.filter(r=>r.ceoChairSep==='Yes').length,avgBoard:(filtered.reduce((s,r)=>s+r.boardSize,0)/filtered.length||0).toFixed(0)}),[filtered]);

  const sectorDiv=useMemo(()=>{const m={};COS.forEach(r=>{if(!m[r.sector])m[r.sector]={s:r.sector,fem:0,ind:0,eth:0,n:0};m[r.sector].fem+=r.femalePct;m[r.sector].ind+=r.independentPct;m[r.sector].eth+=r.ethnicDiversity;m[r.sector].n++;});return Object.values(m).map(s=>({sector:s.s,female:Math.round(s.fem/s.n),independent:Math.round(s.ind/s.n),ethnic:Math.round(s.eth/s.n)}));},[]);
  const femDist=useMemo(()=>{const b=[{r:'<20%',c:0},{r:'20-30%',c:0},{r:'30-40%',c:0},{r:'40-50%',c:0},{r:'>50%',c:0}];filtered.forEach(r=>{if(r.femalePct<20)b[0].c++;else if(r.femalePct<30)b[1].c++;else if(r.femalePct<40)b[2].c++;else if(r.femalePct<50)b[3].c++;else b[4].c++;});return b;},[filtered]);
  const ageDist=useMemo(()=>{const b=[{r:'<55',c:0},{r:'55-60',c:0},{r:'60-65',c:0},{r:'>65',c:0}];filtered.forEach(r=>{if(r.avgAge<55)b[0].c++;else if(r.avgAge<60)b[1].c++;else if(r.avgAge<65)b[2].c++;else b[3].c++;});return b;},[filtered]);

  const exportCSV=useCallback((data,fn)=>{if(!data.length)return;const keys=Object.keys(data[0]).filter(k=>k!=='skillMatrix'&&k!=='yearly');const csv=[keys.join(','),...data.map(r=>keys.map(k=>`"${r[k]}"`).join(','))].join('\n');const b=new Blob([csv],{type:'text/csv'});const u=URL.createObjectURL(b);const a=document.createElement('a');a.href=u;a.download=fn;a.click();URL.revokeObjectURL(u);},[]);

  const si=(col,cur,dir)=>cur===col?(dir==='asc'?' \u25B2':' \u25BC'):' \u25CB';
  const thS={padding:'8px 10px',fontSize:11,fontFamily:T.mono,color:T.textSec,cursor:'pointer',borderBottom:`1px solid ${T.border}`,whiteSpace:'nowrap',userSelect:'none',textAlign:'left',background:T.surfaceH};
  const tdS={padding:'7px 10px',fontSize:12,fontFamily:T.font,borderBottom:`1px solid ${T.border}`,color:T.text};
  const inpS={padding:'6px 12px',border:`1px solid ${T.border}`,borderRadius:6,fontSize:12,fontFamily:T.font,background:T.surface,color:T.text,outline:'none',width:220};
  const selS={padding:'6px 10px',border:`1px solid ${T.border}`,borderRadius:6,fontSize:11,fontFamily:T.font,background:T.surface,color:T.text};
  const btnS=a=>({padding:'6px 16px',border:`1px solid ${a?ACCENT:T.border}`,borderRadius:6,fontSize:12,fontFamily:T.font,background:a?ACCENT:T.surface,color:a?'#fff':T.text,cursor:'pointer',fontWeight:a?600:400});
  const pgB={padding:'4px 10px',border:`1px solid ${T.border}`,borderRadius:4,fontSize:11,cursor:'pointer',background:T.surface,color:T.text};
  const cS={background:T.surface,border:`1px solid ${T.border}`,borderRadius:10,padding:16};
  const kpi=(l,v,c)=>(<div style={{background:T.surface,border:`1px solid ${T.border}`,borderRadius:10,padding:'14px 18px',flex:1,minWidth:140}}><div style={{fontSize:10,color:T.textMut,fontFamily:T.mono,textTransform:'uppercase',letterSpacing:1}}>{l}</div><div style={{fontSize:22,fontWeight:700,color:c||T.navy,marginTop:4}}>{v}</div></div>);

  const Panel=({item,onClose})=>{if(!item)return null;return(<div style={{position:'fixed',top:0,right:0,width:480,height:'100vh',background:T.surface,borderLeft:`2px solid ${ACCENT}`,zIndex:1000,overflowY:'auto',boxShadow:'-4px 0 24px rgba(0,0,0,0.10)'}}><div style={{padding:'20px 24px',borderBottom:`1px solid ${T.border}`,display:'flex',justifyContent:'space-between',alignItems:'center'}}><div><div style={{fontSize:16,fontWeight:700,color:T.navy}}>{item.name}</div><div style={{fontSize:12,color:T.textSec}}>{item.sector} | Rating: {item.governanceRating}</div></div><button onClick={onClose} style={{background:'none',border:'none',fontSize:20,cursor:'pointer',color:T.textMut}}>\u2715</button></div>
    <div style={{padding:'16px 24px'}}>
      <div style={{display:'grid',gridTemplateColumns:'1fr 1fr 1fr',gap:8,marginBottom:16}}>{[['Board Size',item.boardSize],['Female %',item.femalePct+'%'],['Independent %',item.independentPct+'%'],['Avg Age',item.avgAge],['Avg Tenure',item.avgTenure+'yr'],['Ethnic Div.',item.ethnicDiversity+'%'],['Intl %',item.intlPct+'%'],['CEO/Chair Sep',item.ceoChairSep],['Lead Ind Dir',item.leadIndDir],['Overboarding',item.overboarding],['Refresh Rate',item.refreshRate+'%'],['ESG Experts',item.esgExpertise],['Meetings/yr',item.meetingsPerYear],['Attendance',item.attendanceRate+'%'],['Committees',item.committeesAvg],['Diversity Score',item.diversityScore+'/100'],['Gov Rating',item.governanceRating]].map(([k,v],j)=>(<div key={j} style={{background:T.surfaceH,borderRadius:6,padding:'8px 10px'}}><div style={{fontSize:9,color:T.textMut,fontFamily:T.mono}}>{k}</div><div style={{fontSize:13,fontWeight:600,color:T.navy,marginTop:2}}>{v}</div></div>))}</div>
      <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Skills Matrix</div><ResponsiveContainer width="100%" height={220}><RadarChart data={item.skillMatrix}><PolarGrid stroke={T.border}/><PolarAngleAxis dataKey="skill" tick={{fontSize:8,fill:T.textSec}}/><PolarRadiusAxis tick={{fontSize:8}}/><Radar dataKey="count" stroke={ACCENT} fill="rgba(124,58,237,0.2)"/></RadarChart></ResponsiveContainer></div>
      <div style={{...cS,marginTop:12}}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>5-Year Diversity Trend</div><ResponsiveContainer width="100%" height={180}><LineChart data={item.yearly}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="year" tick={{fontSize:9,fill:T.textSec}}/><YAxis tick={{fontSize:9,fill:T.textSec}} domain={[0,100]}/><Tooltip {...tip}/><Line type="monotone" dataKey="femPct" stroke={ACCENT} name="Female %" strokeWidth={2} dot={{r:3}}/><Line type="monotone" dataKey="indPct" stroke={T.gold} name="Independent %" strokeWidth={2} dot={{r:3}}/><Legend/></LineChart></ResponsiveContainer></div>
    </div></div>);};

  const renderOverview=()=>(<div>
    <div style={{display:'flex',gap:12,marginBottom:20,flexWrap:'wrap'}}>{kpi('Companies',stats.count)}{kpi('Avg Female %',stats.avgFem+'%')}{kpi('Avg Independent',stats.avgInd+'%')}{kpi('Avg Age',stats.avgAge)}{kpi('Diversity Score',stats.avgDiv+'/100')}{kpi('CEO/Chair Sep',stats.sepChair+'/'+stats.count)}{kpi('Avg Board Size',stats.avgBoard)}</div>
    <div style={{display:'flex',gap:12,marginBottom:16,alignItems:'center',flexWrap:'wrap'}}><input value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}} placeholder="Search companies..." style={inpS}/><select value={sectorF} onChange={e=>{setSectorF(e.target.value);setPage(1);}} style={selS}>{SECTORS.map(s=><option key={s}>{s}</option>)}</select><button onClick={()=>exportCSV(filtered,'board_composition.csv')} style={btnS(false)}>Export CSV</button></div>
    <div style={{overflowX:'auto',...cS,padding:0}}><table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr>{[['name','Company'],['sector','Sector'],['boardSize','Board'],['femalePct','Female%'],['independentPct','Indep%'],['avgAge','Age'],['diversityScore','Div Score'],['governanceRating','Rating']].map(([k,l])=><th key={k} onClick={()=>doSort(k)} style={thS}>{l}{si(k,sortCol,sortDir)}</th>)}</tr></thead>
      <tbody>{paged.map(r=><tr key={r.id} onClick={()=>setSelected(r)} style={{cursor:'pointer',background:selected?.id===r.id?T.surfaceH:'transparent'}}><td style={tdS}><span style={{fontWeight:600}}>{r.name}</span></td><td style={tdS}>{r.sector}</td><td style={tdS}>{r.boardSize}</td><td style={tdS}><span style={{color:r.femalePct>=30?T.green:r.femalePct>=20?T.amber:T.red,fontWeight:600}}>{r.femalePct}%</span></td><td style={tdS}>{r.independentPct}%</td><td style={tdS}>{r.avgAge}</td><td style={tdS}>{r.diversityScore}</td><td style={{...tdS,fontWeight:600}}>{r.governanceRating}</td></tr>)}</tbody></table></div>
    {totalPages>1&&<div style={{display:'flex',gap:6,marginTop:12,alignItems:'center',justifyContent:'center'}}><button onClick={()=>setPage(p=>Math.max(1,p-1))} disabled={page===1} style={pgB}>&laquo;</button><span style={{fontSize:11,color:T.textSec,fontFamily:T.mono}}>Page {page}/{totalPages}</span><button onClick={()=>setPage(p=>Math.min(totalPages,p+1))} disabled={page===totalPages} style={pgB}>&raquo;</button></div>}
  </div>);

  const renderDiversity=()=>(<div>
    <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16}}>
      <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Diversity Metrics by Sector</div><ResponsiveContainer width="100%" height={280}><BarChart data={sectorDiv}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="sector" tick={{fontSize:8,fill:T.textSec}} angle={-25}/><YAxis tick={{fontSize:9,fill:T.textSec}} domain={[0,100]}/><Tooltip {...tip}/><Bar dataKey="female" fill={ACCENT} name="Female %"/><Bar dataKey="ethnic" fill={T.gold} name="Ethnic %"/><Bar dataKey="independent" fill={T.sage} name="Independent %"/><Legend/></BarChart></ResponsiveContainer></div>
      <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Female Representation Distribution</div><ResponsiveContainer width="100%" height={280}><BarChart data={femDist}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="r" tick={{fontSize:9,fill:T.textSec}}/><YAxis tick={{fontSize:9,fill:T.textSec}}/><Tooltip {...tip}/><Bar dataKey="c" fill={ACCENT} radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></div>
      <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Gender vs Ethnic Diversity</div><ResponsiveContainer width="100%" height={280}><ScatterChart><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="x" name="Female %" tick={{fontSize:9,fill:T.textSec}}/><YAxis dataKey="y" name="Ethnic %" tick={{fontSize:9,fill:T.textSec}}/><Tooltip {...tip}/><Scatter data={filtered.map(c=>({name:c.name,x:c.femalePct,y:c.ethnicDiversity}))} fill={ACCENT} fillOpacity={0.5}/></ScatterChart></ResponsiveContainer></div>
      <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>International Board Members</div><ResponsiveContainer width="100%" height={280}><BarChart data={[...filtered].sort((a,b)=>b.intlPct-a.intlPct).slice(0,15)} layout="vertical"><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis type="number" tick={{fontSize:9,fill:T.textSec}} domain={[0,100]}/><YAxis type="category" dataKey="name" tick={{fontSize:8,fill:T.textSec}} width={80}/><Tooltip {...tip}/><Bar dataKey="intlPct" fill={T.navy} radius={[0,4,4,0]}/></BarChart></ResponsiveContainer></div>
    </div>
  </div>);

  const renderSkills=()=>{
    const aggSkills=['Finance','Technology','Industry','Legal','ESG','International','Marketing','Operations','Risk','HR'].map(s=>{const total=COS.reduce((sum,c)=>{const sk=c.skillMatrix.find(x=>x.skill===s);return sum+(sk?sk.count:0);},0);return{skill:s,total,avg:+(total/COS.length).toFixed(1)};});
    return(<div>
      <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16}}>
        <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Average Skill Coverage Across All Boards</div><ResponsiveContainer width="100%" height={300}><RadarChart data={aggSkills}><PolarGrid stroke={T.border}/><PolarAngleAxis dataKey="skill" tick={{fontSize:9,fill:T.textSec}}/><PolarRadiusAxis tick={{fontSize:8}}/><Radar dataKey="avg" stroke={ACCENT} fill="rgba(124,58,237,0.2)"/></RadarChart></ResponsiveContainer></div>
        <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Total Skill Distribution</div><ResponsiveContainer width="100%" height={300}><BarChart data={aggSkills}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="skill" tick={{fontSize:9,fill:T.textSec}} angle={-20}/><YAxis tick={{fontSize:9,fill:T.textSec}}/><Tooltip {...tip}/><Bar dataKey="total" fill={T.gold} radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></div>
        <div style={{...cS,gridColumn:'1/3'}}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>ESG Expertise by Sector</div><ResponsiveContainer width="100%" height={280}><BarChart data={sectorDiv.map(s=>{const cos=COS.filter(c=>c.sector===s.sector);return{sector:s.sector,esgExperts:Math.round(cos.reduce((sum,c)=>sum+c.esgExpertise,0)/Math.max(1,cos.length)),boardSize:Math.round(cos.reduce((sum,c)=>sum+c.boardSize,0)/Math.max(1,cos.length))};})}>
          <CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="sector" tick={{fontSize:8,fill:T.textSec}} angle={-20}/><YAxis tick={{fontSize:9,fill:T.textSec}}/><Tooltip {...tip}/><Bar dataKey="esgExperts" fill={T.sage} name="ESG Experts (avg)"/><Bar dataKey="boardSize" fill={T.navy} name="Board Size (avg)"/><Legend/></BarChart></ResponsiveContainer></div>
      </div>
    </div>);
  };

  const renderIndependence=()=>(<div>
    <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16}}>
      <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Independence % by Sector</div><ResponsiveContainer width="100%" height={280}><BarChart data={sectorDiv}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="sector" tick={{fontSize:8,fill:T.textSec}} angle={-25}/><YAxis tick={{fontSize:9,fill:T.textSec}} domain={[0,100]}/><Tooltip {...tip}/><Bar dataKey="independent" fill={T.navy} radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></div>
      <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Board Age Distribution</div><ResponsiveContainer width="100%" height={280}><BarChart data={ageDist}><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="r" tick={{fontSize:9,fill:T.textSec}}/><YAxis tick={{fontSize:9,fill:T.textSec}}/><Tooltip {...tip}/><Bar dataKey="c" fill={T.amber} radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></div>
      <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>Tenure vs Independence</div><ResponsiveContainer width="100%" height={280}><ScatterChart><CartesianGrid strokeDasharray="3 3" stroke={T.border}/><XAxis dataKey="x" name="Avg Tenure" tick={{fontSize:9,fill:T.textSec}}/><YAxis dataKey="y" name="Independent %" tick={{fontSize:9,fill:T.textSec}}/><Tooltip {...tip}/><Scatter data={filtered.map(c=>({name:c.name,x:c.avgTenure,y:c.independentPct}))} fill={T.navy} fillOpacity={0.5}/></ScatterChart></ResponsiveContainer></div>
      <div style={cS}><div style={{fontSize:12,fontWeight:600,color:T.navy,marginBottom:8}}>CEO/Chair Separation</div><ResponsiveContainer width="100%" height={280}><PieChart><Pie data={[{name:'Separated',value:filtered.filter(r=>r.ceoChairSep==='Yes').length},{name:'Combined',value:filtered.filter(r=>r.ceoChairSep==='No').length}]} cx="50%" cy="50%" outerRadius={90} dataKey="value" label={({name,value})=>`${name}: ${value}`}>{[T.green,T.red].map((c,i)=><Cell key={i} fill={c}/>)}</Pie><Tooltip {...tip}/></PieChart></ResponsiveContainer></div>
    </div>
  </div>);

  return(<div style={{padding:'24px 32px',fontFamily:T.font,background:T.bg,minHeight:'100vh'}}>
    <div style={{marginBottom:20}}><h1 style={{fontSize:22,fontWeight:700,color:T.navy,margin:0}}>Board Composition Analytics</h1><p style={{fontSize:12,color:T.textSec,margin:'4px 0 0'}}>80 companies | Diversity, skills matrix, independence analysis</p></div>
    <div style={{display:'flex',gap:8,marginBottom:20}}>{TABS.map((t,i)=><button key={t} onClick={()=>setTab(i)} style={btnS(tab===i)}>{t}</button>)}</div>
    {tab===0&&renderOverview()}{tab===1&&renderDiversity()}{tab===2&&renderSkills()}{tab===3&&renderIndependence()}
    <Panel item={selected} onClose={()=>setSelected(null)}/>
  </div>);
}